stages:
    - build
    - test
    - deploy
    - build-docker

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GITLAB_RUNNER_ENV: /home/gitlab-runner/gitlab_test
  TAG_TEST: test
  TAG_PROD: prod # or v1.1
  # Variables Docker
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/sankeyapp:$CI_COMMIT_SHA
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE/sankeyapp:latest
  DOCKER_DRIVER: overlay2

# Cache
cache:
  paths:
    - .cache/pip
    - node_modules/
    - .npm/

# ========================================
# BUILD DOCKER IMAGE
# ========================================

# ===========================
# Étape 1 : Build & Push Docker
# ===========================

build-sankeysuite-docker:
  stage: build-docker
  tags:
    - dev
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - echo "🔧 Build image from Dockerfile"
    - docker build -t "$DOCKER_IMAGE" -t "$DOCKER_IMAGE_LATEST" -f Dockerfile .
    - echo "📤 Push image to GitLab registry"
    - docker push "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE_LATEST"
  rules:
    - changes:
        - Dockerfile
        - client/package.json
        - build_client.sh
        - submodules/**/*
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: manual
    - if: '$BUILD_DOCKER_IMAGE == "true"'
  allow_failure: false

# Build : for all branches, units tests for submodules server side
build:
  stage: build
  tags:
    - dev
  script:
    # Specify env
    - echo $CI_PROJECT_DIR
    - source /home/gitlab-runner/gitlab_dev/bin/activate
    - export EIGEN_INCLUDE=$CI_PROJECT_DIR/submodules/MFAProblem/submodules/eigen
    # Build SankeySuite node module
    - bash build_client.sh -I -L -B -D -S
    # Check flask server
    - bash build_server.sh
  artifacts:
    paths:
      - sankeyapplication/client/build  # c'est le dossier généré par `npm run build`
  except:
    - schedules


# # Test : for all branches, units tests for submodules server side
test:
  stage: test
  tags:
    - dev, test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    TESTS_DIR: /home/ubuntu/dev_opensankey/sankeysuitemanager/Tests
  script:
    - echo $CI_PROJECT_DIR
    - echo $TESTS_DIR
    - echo $GITLAB_RUNNER_ENV/bin/activate
    - source $GITLAB_RUNNER_ENV/bin/activate
    - echo "No test" # TODO add some tests
  dependencies:
    - build

# Deploy : Only for main, on dev url acces
dev_opensankey:
  stage: deploy
  variables:
    NODE_ENV: "production"
    ROOT_FOLDER: /home/ubuntu/dev_opensankey
    REPO_FOLDER: $ROOT_FOLDER/sankeyapplication
    ENV: dev
    APP_NAME: dev_sankeyapp
  only:
    - main
  tags:
    - dev
  environment:
    name: dev
  script:
    # DBG
    - echo $REPO_FOLDER
    # Clean and pull repo
    - git config --global --add safe.directory $REPO_FOLDER
    - cd $REPO_FOLDER
    - git reset --hard
    - git clean -fdx -e env -e server/db.sqlite -e server/db.sqlite.bk -e server/__pycache__ -e doc/__pycache__ -e __pycache__
    - git fetch
    - git pull
    - git config --global --add safe.directory /home/ubuntu/dev_opensankey/sankeyapplication/submodules/LoginComponent
    - git config --global --add safe.directory /home/ubuntu/dev_opensankey/sankeyapplication/submodules/MFAProblem
    - git config --global --add safe.directory /home/ubuntu/dev_opensankey/sankeyapplication/submodules/MFAProblem/submodules/eigen
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey/submodules/SankeyExcelParser
    - git submodule init
    - git submodule foreach --recursive git reset --hard
    - git submodule foreach --recursive git clean -fdx
    - git submodule update --recursive
    # Build client & server
    - source $ROOT_FOLDER/dev_opensankey/bin/activate
    - export EIGEN_INCLUDE=$CI_PROJECT_DIR/submodules/MFAProblem/submodules/eigen
    - bash deploy_SankeyApp.sh
    # Update db
    - cp server/db.sqlite server/db.sqlite.bk/db_`date --iso-8601='seconds'`.sqlite
    - find ./server/db.sqlite.bk -mtime +30 -type f -delete
    - alembic upgrade head
    # Start app
    - bash restart_site.sh $ENV

test_opensankey:
  stage: deploy
  variables:
    NODE_ENV: "production"
    ROOT_FOLDER: /home/ubuntu/test_opensankey
    REPO_FOLDER: $ROOT_FOLDER/sankeyapplication
    ENV: test
    APP_NAME : test_sankeyapp
  tags:
    - test
  environment:
    name: test
  rules:
    - if: $CI_COMMIT_REF_NAME == $TAG_TEST
  script:
    # DBG
    - echo $REPO_FOLDER
    # Clean and pull repo
    - git config --global --add safe.directory $REPO_FOLDER
    - cd $REPO_FOLDER
    - git reset --hard
    - git clean -fdx -e env -e server/db.sqlite -e server/db.sqlite.bk -e server/__pycache__ -e doc/__pycache__ -e __pycache__
    - git fetch
    - git pull
    - git config --global --add safe.directory /home/ubuntu/dev_opensankey/sankeyapplication/submodules/LoginComponent
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey/submodules/SankeyExcelParser
    - git submodule init
    - git submodule foreach --recursive git reset --hard
    - git submodule foreach --recursive git clean -fdx
    - git submodule update --recursive
    # Build client & server
    - source $ROOT_FOLDER/test_opensankey/bin/activate
    - bash deploy_SankeyApp.sh
    # Update db
    - cp server/db.sqlite server/db.sqlite.bk/db_`date --iso-8601='seconds'`.sqlite
    - find ./server/db.sqlite.bk -mtime +180 -type f -delete
    - alembic upgrade head
    # Start app
    - bash restart_site.sh $ENV

prod_opensankey:
  stage: deploy
  variables:
    NODE_ENV: "production"
    ROOT_FOLDER: /home/ubuntu/prod_opensankey
    REPO_FOLDER: $ROOT_FOLDER/sankeyapplication
    ENV: prod
    APP_NAME : prod_sankeyapp
  tags:
    - prod
  environment:
    name: prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $TAG_PROD
  script:
    # DBG
    - echo $REPO_FOLDER
    # Clean and pull repo
    - git config --global --add safe.directory $REPO_FOLDER
    - cd $REPO_FOLDER
    - git reset --hard
    - git clean -fdx -e env -e server/db.sqlite -e server/db.sqlite.bk -e server/__pycache__ -e doc/__pycache__ -e __pycache__
    - git fetch
    - git pull
    - git config --global --add safe.directory /home/ubuntu/dev_opensankey/sankeyapplication/submodules/LoginComponent
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey
    - git config --global --add safe.directory $REPO_FOLDER/submodules/OpenSankey+/submodules/OpenSankey/submodules/SankeyExcelParser
    - git submodule init
    - git submodule foreach --recursive git reset --hard
    - git submodule foreach --recursive git clean -fdx
    - git submodule update --recursive
    # Build client & server
    - source $ROOT_FOLDER/prod_opensankey/bin/activate
    - bash deploy_SankeyApp.sh
    # Update db
    - cp server/db.sqlite server/db.sqlite.bk/db_`date --iso-8601='seconds'`.sqlite
    - find ./server/db.sqlite.bk -mtime +365 -type f -delete
    - alembic upgrade head
    # Start app
    - bash restart_site.sh $ENV

# Étape de build
pages:
  image: node:18
  stage: deploy
  script:
    - |
      if [ -z "$APP_VERSION" ]; then
        echo "[ERREUR] APP_VERSION doit être fourni manuellement dans l’interface GitLab"
        exit 1
      fi
    - echo "[INFO] Version reçue " $APP_VERSION

    # === Chemins ===
    - JS_DIR="$CI_PROJECT_DIR/sankeyapplication/client/build/static/js"
    - CSS_DIR="$CI_PROJECT_DIR/sankeyapplication/client/build/static/css"
    - INDEX_FILE="$CI_PROJECT_DIR/sankeyapplication/client/build/index.html"
    - BUILD_DIR="$CI_PROJECT_DIR/sankeyapplication/client/build"
    - VERSION_DIR="$CI_PROJECT_DIR/sankeyapplication/$APP_VERSION"
    - LATEST_DIR="$CI_PROJECT_DIR/sankeyapplication/latest"

    # === JS ===
    - |
      cd "$JS_DIR"
      for f in main.*.js; do
        cp "$f" "sankeyapplication-v$APP_VERSION.js"
        echo "[INFO] JS renommé : $f → sankeyapplication-v$APP_VERSION.js"
        sed -i "s|$f|sankeyapplication-v$APP_VERSION.js|g" "$INDEX_FILE"
      done

    # === CSS ===
    - |
      cd "$CSS_DIR"
      for f in main.*.css; do
        cp "$f" "sankeyapplication-v$APP_VERSION.css"
        echo "[INFO] CSS renommé : $f → sankeyapplication-v$APP_VERSION.css"
        sed -i "s|$f|sankeyapplication-v$APP_VERSION.css|g" "$INDEX_FILE"
      done

    # === Chemins relatifs pour GitLab Pages
    - sed -i 's|="/static/|="./static/|g' "$INDEX_FILE"

    # === Préparation des dossiers versionnés
    - mkdir -p "$VERSION_DIR"
    - cp -r "$BUILD_DIR"/* "$VERSION_DIR"
    - echo '<meta http-equiv="refresh" content="0; url=/" />' > "$VERSION_DIR/404.html"

    # === (optionnel) Copier aussi vers /latest
    - rm -rf "$LATEST_DIR"
    - cp -r "$VERSION_DIR" "$LATEST_DIR"
    - echo '<meta http-equiv="refresh" content="0; url=/" />' > "$LATEST_DIR/404.html"

  artifacts:
    paths:
      - public
  dependencies:
    - build
  rules:
    - when: manual
      allow_failure: false

# Tag Release:
#   stage: tag-release
#   variables:
#     OAUTH2_TOKEN: glpat-sx8UdDDQ7sLqtWFV4Ywp
#     OAUTH2_EMAIL: vincent.le-doze@terriflux.fr
#     OAUTH2_NAME: Vincent LE DOZE
#   tags:
#     - dev, test, prod
#   except:
#     - tags
#   only:
#     - /^v[0-9]+(?:.[0-9]+)+$/ # regular expression for vX.Y.Z branch
#   script:
#     - VERSION=v"$(php -r "echo json_decode(file_get_contents('$CI_PROJECT_DIR/SankeySuite/client/package.json'), true)['version'];")";
#     - MESSAGE="$(php -r "echo json_encode(['name' => 'Version $VERSION', 'tag_name' => '$VERSION', 'description' => '']);")"; # file_get_contents('$CI_PROJECT_DIR/changelog/$VERSION.md')]);")";
#     - >
#       if [[ `git config --get user.email` =~ $OAUTH2_EMAIL ]]; then
#         echo "Ok user.email"
#       else
#         echo "Config user.email"
#         git config user.email $OAUTH2_EMAIL
#       fi
#     - >
#       if [[ `git config --get user.name` =~ $OAUTH2_NAME ]]; then
#         echo "Ok user.name"
#       else
#         echo "Config user.name"
#         git config user.name $OAUTH2_NAME
#       fi
#     - if [[ `git config --get http.sslVerify` =~ true ]]; then git config http.sslVerify false; fi
#     - >
#       if [[ `git remote` =~ .*api-origin.* ]]; then
#         echo "remote api-origin existant"
#       else
#         echo "remote api-origin ajoute"
#         git remote add api-origin https://oauth2:${OAUTH2_TOKEN}@gitlab.com/su-model/sankeysuitemanager
#       fi
#     - >
#       if [ $(git tag -l "$VERSION") ]; then
#         echo "Version $VERSION already exists"
#       else
#         echo "Version $VERSION cree"
#         git tag -a $VERSION -m "Version $VERSION"
#         git push api-origin $VERSION
#       fi

