stages:
    - build
    - test

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  EIGEN_INCLUDE: /home/ubuntu/dev_opensankey/sankeysuitemanager/eigen
  MFAData: /home/ubuntu/dev_opensankey/MFAData
  SankeyExcelParser: /home/ubuntu/dev_opensankey/SankeyExcelParser

build:
  stage: build
  tags:
    - dev, prod, test
  script:
    - echo $CI_PROJECT_DIR
    - echo $EIGEN_INCLUDE
    - echo $MFAData
    - echo $SankeyExcelParser
    - source /home/gitlab-runner/gitlab_dev/bin/activate
    - pip install $SankeyExcelParser
    - bash build.sh
  except:
    - schedules

test:
  stage: test
  tags:
    - dev, prod, test
  script:
    - echo $CI_PROJECT_DIR
    - echo $EIGEN_INCLUDE
    - echo $MFAData
    - source /home/gitlab-runner/gitlab_dev/bin/activate
    - bash test.sh
  dependencies:
    - build
