stages:
    - deploy
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

deploy_opensankey:
  stage: deploy
  variables:
    NODE_ENV: "production"
    FOLDER: "/home/ubuntu/dev_opensankey"
    ENV   : "dev"
    APP_NAME : "dev_opensankey"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:                              
        FOLDER: "/home/ubuntu/dev_opensankey"
        ENV: "dev" 
        APP_NAME : "dev_opensankey"
    - if: $CI_COMMIT_REF_NAME == "test"
      variables:
        FOLDER: "/home/ubuntu/test_opensankey"
        ENV: "test"
        APP_NAME : "test_opensankey"
    - if: $CI_COMMIT_REF_NAME == "test"
      variables:
        FOLDER: "/home/ubuntu/prod_opensankey"
        ENV: "prod" 
        APP_NAME : "opensankey"
  environment:
    name: $ENV
#  cache: 
#    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
#    paths:
#      - $FOLDER/opensankey/opensankey/client/node_modules/
#    policy: pull
#  before_script:
#    - sudo systemctl stop $APP_NAME || true
  after_script:
    - echo "$FOLDER"
    - cd "$FOLDER"
    - bash restart_site.sh
  script:
    - echo "$FOLDER"
    - cd "$FOLDER"
    - source $ENV_opensankey/bin/activate
    - bash update_build_opensankey.sh

