"""Added OpenSankey+ licence

Revision ID: 0b7755f08fb4
Revises: 3f86fae23367
Create Date: 2023-03-06 11:47:00.419784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7755f08fb4'
down_revision = '3f86fae23367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('license_opensankeyplus', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'license_opensankeyplus')
    # ### end Alembic commands ###
