"""Changed license entry to license_OpenSankey + Added license_MFASankey

Revision ID: 3f86fae23367
Revises:
Create Date: 2023-02-23 19:16:01.024060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f86fae23367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'license', new_column_name='license_opensankey')
    op.add_column('user', sa.Column('license_mfasankey', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'license_opensankey', new_column_name='license')
    op.drop_column('user', 'license_mfasankey')
    # ### end Alembic commands ###
