"""Added secret token for user table

Revision ID: 66e8ea5239d9
Revises: a33403eb7efa
Create Date: 2024-10-16 17:16:54.032416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e8ea5239d9'
down_revision = 'a33403eb7efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret_token', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('secret_expiry', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secret_expiry')
    op.drop_column('user', 'secret_token')
    # ### end Alembic commands ###
