"""Ajout repertoire données preferences utilisateur

Revision ID: 90a4654501ae
Revises: c810ce47ddd8
Create Date: 2025-04-22 15:32:06.120651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a4654501ae'
down_revision = 'c810ce47ddd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dir', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dir')
    # ### end Alembic commands ###
