"""Added stripe ids and infos

Revision ID: a33403eb7efa
Revises: a491b5c772c9
Create Date: 2024-10-10 12:13:50.315372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33403eb7efa'
down_revision = 'a491b5c772c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Redo user tables
    op.create_table(
        'tmp_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=True),
        sa.Column('password', sa.String(length=256), nullable=True),
        sa.Column('firstname', sa.String(length=64), nullable=True),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('license_opensankeyplus', sa.String(length=1024), nullable=True),
        sa.Column('license_sankeysuite', sa.String(length=1024), nullable=True),
        sa.Column('is_developer', sa.Boolean(), nullable=True),
        sa.Column('creation', sa.String(length=128), nullable=True),
        sa.Column('stripe_id', sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('stripe_id'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_user = sa.sql.table(
        'tmp_user',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('email', sa.String(128), nullable=True),
        sa.Column('password', sa.String(256), nullable=True),
        sa.Column('firstname', sa.String(64), nullable=True),
        sa.Column('name', sa.String(64), nullable=True),
        sa.Column('license_opensankeyplus', sa.String(1024), nullable=True),
        sa.Column('license_sankeysuite', sa.String(1024), nullable=True),
        sa.Column('is_developer', sa.Boolean(), nullable=True),
        sa.Column('creation', sa.String(128), nullable=True),
        sa.Column('stripe_id', sa.String(1024), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select \
        id, email, password, firstname, name, \
        license_opensankeyplus, license_sankeysuite, is_developer \
        from user")
    results = res.fetchall()
    tmp_user_data = [{
        'id': r[0],
        'email': r[1],
        'password': r[2],
        'firstname': r[3],
        'name': r[4],
        'license_opensankeyplus':r[5],
        'license_sankeysuite':r[6],
        'is_developer': r[7]
    } for r in results]
    op.bulk_insert(tmp_user, tmp_user_data)
    op.drop_table('user')
    op.rename_table('tmp_user', 'user')
    # Redo license tables
    op.create_table('tmp_license',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('stripe_id', sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('stripe_id'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_license = sa.sql.table(
        'tmp_license',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('name', sa.String(64), nullable=True),
        sa.Column('stripe_id', sa.String(1024), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select id, name from license")
    results = res.fetchall()
    tmp_license_data = [{
        'id': r[0],
        'name': r[1]
    } for r in results]
    op.bulk_insert(tmp_license, tmp_license_data)
    op.drop_table('license')
    op.rename_table('tmp_license', 'license')
    # Redo user-licenses tables
    op.create_table(
        'tmp_user_licenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('license_id', sa.Integer(), nullable=True),
        sa.Column('creation', sa.String(length=128), nullable=True),
        sa.Column('expiry', sa.String(length=128), nullable=True),
        sa.Column('activated', sa.Boolean(), nullable=True),
        sa.Column('stripe_id', sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(['license_id'], ['license.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stripe_id'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_user_license = sa.sql.table(
        'tmp_user_licenses',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('license_id', sa.Integer(), nullable=True),
        sa.Column('creation', sa.String(128), nullable=True),
        sa.Column('expiry', sa.String(128), nullable=True),
        sa.Column('activated', sa.Boolean(), nullable=True),
        sa.Column('stripe_id', sa.String(1024), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select id, user_id, license_id, license_expiry from user_licenses")
    results = res.fetchall()
    tmp_user_licenses_data = [{
        'id': r[0],
        'user_id': r[1],
        'license_id': r[2],
        'expiry': r[3],
    } for r in results]
    op.bulk_insert(tmp_user_license, tmp_user_licenses_data)
    op.drop_table('user_licenses')
    op.rename_table('tmp_user_licenses', 'user_licenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Redo user tables
    op.create_table(
        'tmp_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('password', sa.String(length=100), nullable=True),
        sa.Column('firstname', sa.String(length=1000), nullable=True),
        sa.Column('name', sa.String(length=1000), nullable=True),
        sa.Column('license_opensankeyplus', sa.String(length=2000), nullable=True),
        sa.Column('license_sankeysuite', sa.String(length=2000), nullable=True),
        sa.Column('is_developer', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_user = sa.sql.table(
        'tmp_user',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('email', sa.String(100), nullable=True),
        sa.Column('password', sa.String(100), nullable=True),
        sa.Column('firstname', sa.String(1000), nullable=True),
        sa.Column('name', sa.String(1000), nullable=True),
        sa.Column('license_opensankeyplus', sa.String(2000), nullable=True),
        sa.Column('license_sankeysuite', sa.String(2000), nullable=True),
        sa.Column('is_developer', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select \
        id, email, password, firstname, name, \
        license_opensankeyplus, license_sankeysuite, is_developer \
        from user")
    results = res.fetchall()
    tmp_user_data = [{
        'id': r[0],
        'email': r[1],
        'password': r[2],
        'firstname': r[3],
        'name': r[4],
        'license_opensankeyplus':r[5],
        'license_sankeysuite':r[6],
        'is_developer': r[7]
    } for r in results]
    op.bulk_insert(tmp_user, tmp_user_data)
    op.drop_table('user')
    op.rename_table('tmp_user', 'user')
    # Redo license tables
    op.create_table('tmp_license',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_license = sa.sql.table(
        'tmp_license',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('name', sa.String(50), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select id, name from license")
    results = res.fetchall()
    tmp_license_data = [{
        'id': r[0],
        'name': r[1]
    } for r in results]
    op.bulk_insert(tmp_license, tmp_license_data)
    op.drop_table('license')
    op.rename_table('tmp_license', 'license')
    # Redo user-licenses tables
    op.create_table(
        'tmp_user_licenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('license_id', sa.Integer(), nullable=True),
        sa.Column('license_expiry', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['license_id'], ['license.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('license_expiry'))
    #http://stackoverflow.com/questions/15725859/sqlalchemy-alembic-bulk-insert-fails-str-object-has-no-attribute-autoincre
    tmp_user_license = sa.sql.table(
        'tmp_user_licenses',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('license_id', sa.Integer(), nullable=True),
        sa.Column('license_expiry', sa.String(50), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select id, user_id, license_id, expiry from user_licenses")
    results = res.fetchall()
    tmp_user_licenses_data = [{
        'id': r[0],
        'user_id': r[1],
        'license_id': r[2],
        'license_expiry': r[3],
    } for r in results]
    op.bulk_insert(tmp_user_license, tmp_user_licenses_data)
    op.drop_table('user_licenses')
    op.rename_table('tmp_user_licenses', 'user_licenses')
    # ### end Alembic commands ###
