"""Added metrics table

Revision ID: c810ce47ddd8
Revises: 66e8ea5239d9
Create Date: 2025-02-13 17:44:39.584115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c810ce47ddd8'
down_revision = '66e8ea5239d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('last_visit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
