"""Ajout colonne is_dev

Revision ID: f0d499aa7d66
Revises: fa7772394f50
Create Date: 2023-03-22 12:27:12.397829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d499aa7d66'
down_revision = 'fa7772394f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_developer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_developer')
    # ### end Alembic commands ###
