"""suppression licence OpenSankey de la base de donnée

Revision ID: fa7772394f50
Revises: 0b7755f08fb4
Create Date: 2023-03-09 19:01:36.610333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7772394f50'
down_revision = '0b7755f08fb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'license_opensankey')
    op.alter_column('user', 'license_mfasankey', new_column_name='license_sankeysuite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('license_opensankey', sa.VARCHAR(length=2000), nullable=True))
    op.alter_column('user', 'license_sankeysuite', new_column_name='license_mfasankey')
    # ### end Alembic commands ###
