export const resources_template = {
  //=======================================================
  //EN
  //=======================================================
  en: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz needed',
        gallery_hint: 'Click a template to start from an example',
        sankeytheque_hint: 'Click a study to open it',
        pin: 'Pin the gallery (the drawing resizes to its left, try templates one after another)',
        unpin: 'Unpin the gallery (floats over the drawing, closes as soon as you start working)',
        play: 'Play the gallery (loads each model one after another)',
        pause: 'Pause the slideshow',
        prev: 'Previous model',
        next: 'Next model',
        group_validated: 'Validated study (published on the website)',
        published_link: 'View the published diagram online',
        publication: {
          online: 'Published online',
          open: 'Open the published page',
          load: 'Load into the app',
          version_load: 'Load this version',
          version_open: 'Open this version online',
          history: 'full history (developer)',
          history_error: 'History unavailable',
          history_empty: 'No recorded version yet'
        },
        group_readme_open: 'Read the presentation',
        group_readme_close: 'Hide the presentation',
        group_readme_error: 'Description unavailable',
        library_hint: 'Your versioned projects: click a diagram to open it, a README to read it',
        library: {
          read_md: 'Read this document',
          edit_md: 'Edit this document (deposits a new version)',
          new_readme: 'Create a README (new version of the project)',
          download: 'Download this file',
          versions_error: 'Versions unavailable'
        },
        fr: 'Diagram template in french',
        en: 'Diagram template in english',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Maps',
          web: 'Classics from the web',
          other_formats: 'Other formats',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'My projects',
          // Catégories de la sankeythèque (index MFAData)
          etudes: 'Studies',
          filieres: 'Sectors',
          recherche: 'Research',
          clients: 'Clients'
        }
      },
      // sa#414 — panneau « Explorateur » (projets + classeurs du compte)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorer',
        tooltip: 'Browse your projects and workbooks; a diagram opens in a new sheet',
        hint: 'Your projects and workbooks: click a diagram to open it in a new sheet',
        workbooks: 'Workbooks',
        projects_empty: 'No project in your library yet',
        workbooks_empty: 'No workbook yet',
        workbook_error: 'Workbook unavailable',
        open_sheet: 'Open in a new sheet',
        add_section: 'section',
        add_page: 'page',
        add_slot: 'diagram',
        section_default: 'New section',
        page_default: 'New page',
        delete_node: 'Remove',
        move_up: 'Move up',
        move_down: 'Move down',
        rename_hint: 'Double-click to rename',
        confirm_delete: 'Remove this item and everything under it?',
        save_error: 'Could not save the workbook',
        slot_file: 'Choose a file...',
        slot_add: 'Pin',
        slot_cancel: 'Cancel',
        group_root: 'Folder documents',
        search_placeholder: 'Filter projects...',
        search_no_match: 'No project matches this search',
        menu_entry: 'From my library...',
        delete_project: 'Delete this project',
        confirm_delete_project: 'Delete the project “{{title}}” and ALL its versions? The action cannot be undone.',
        delete_project_error: 'Could not delete the project',
        // sa#495 — starting view of a workbook slot, picked among the REAL
        // views of the pinned diagram (the admin workshop only had free text).
        views_start: 'Starting view',
        views_start_hint: 'the view the published page opens on',
        views_all: 'All views',
        views_group_views: 'Diagram views',
        views_group_labels: 'View labels',
        views_mode_view: 'A specific view',
        views_mode_label: 'Views with a label',
        views_value_placeholder: 'view id or label',
        views_loading: 'Reading the diagram views...',
        views_error: 'Diagram unreadable: free text',
        views_empty: 'This diagram carries no view: free text',
        views_unknown: 'This value is not among the diagram views; it is kept as is',
        views_runtime_warning: 'The published runtime ignores view options: the selection will be recorded, not applied',
        views_not_first: 'Only the selection of the first slot of the page is applied at render time'
      },
    }
  },
  //=======================================================
  //FR
  //=======================================================
  fr: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz necessaire',
        gallery_hint: 'Cliquez sur un modèle pour partir d\'un exemple',
        sankeytheque_hint: 'Cliquez sur une étude pour l\'ouvrir',
        pin: 'Épingler la galerie (le dessin se recadre à gauche, essayez les modèles à la suite)',
        unpin: 'Détacher la galerie (survol du dessin, elle se ferme dès que vous travaillez)',
        play: 'Lancer la galerie (charge chaque modèle l\'un après l\'autre)',
        pause: 'Mettre le diaporama en pause',
        prev: 'Modèle précédent',
        next: 'Modèle suivant',
        group_validated: 'Étude validée (publiée sur le site)',
        published_link: 'Voir le diagramme publié en ligne',
        publication: {
          online: 'Publié en ligne',
          open: 'Ouvrir la page publiée',
          load: 'Charger dans l\'application',
          version_load: 'Charger cette version',
          version_open: 'Ouvrir cette version en ligne',
          history: 'historique complet (développeur)',
          history_error: 'Historique indisponible',
          history_empty: 'Aucune version enregistrée pour l\'instant'
        },
        group_readme_open: 'Lire la présentation',
        group_readme_close: 'Masquer la présentation',
        group_readme_error: 'Description indisponible',
        library_hint: 'Vos projets versionnés : cliquez sur un diagramme pour l\'ouvrir, un README pour le lire',
        library: {
          read_md: 'Lire ce document',
          edit_md: 'Éditer ce document (dépose une nouvelle version)',
          new_readme: 'Créer un README (nouvelle version du projet)',
          download: 'Télécharger ce fichier',
          versions_error: 'Versions indisponibles'
        },
        fr: 'Modèle de diagramme en français',
        en: 'Modèle de diagramme en anglais',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Cartes',
          web: 'Classiques du web',
          other_formats: 'Autres formats',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Mes projets',
          // Catégories de la sankeythèque (index MFAData)
          etudes: 'Études',
          filieres: 'Filières',
          recherche: 'Recherche',
          clients: 'Clients'
        }
      },
      // sa#414 — panneau « Explorateur » (projets + classeurs du compte)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorateur',
        tooltip: 'Parcourez vos projets et classeurs ; un diagramme s\'ouvre dans une nouvelle feuille',
        hint: 'Vos projets et classeurs : cliquez sur un diagramme pour l\'ouvrir dans une nouvelle feuille',
        workbooks: 'Classeurs',
        projects_empty: 'Aucun projet dans votre bibliothèque pour l\'instant',
        workbooks_empty: 'Aucun classeur pour l\'instant',
        workbook_error: 'Classeur indisponible',
        open_sheet: 'Ouvrir dans une nouvelle feuille',
        add_section: 'section',
        add_page: 'page',
        add_slot: 'diagramme',
        section_default: 'Nouvelle section',
        page_default: 'Nouvelle page',
        delete_node: 'Retirer',
        move_up: 'Monter',
        move_down: 'Descendre',
        rename_hint: 'Double-cliquez pour renommer',
        confirm_delete: 'Retirer cet élément et tout ce qu\'il contient ?',
        save_error: 'Échec de l\'enregistrement du classeur',
        slot_file: 'Choisir un fichier...',
        slot_add: 'Épingler',
        slot_cancel: 'Annuler',
        group_root: 'Documents du dossier',
        search_placeholder: 'Filtrer les projets...',
        search_no_match: 'Aucun projet ne correspond',
        menu_entry: 'Depuis ma bibliothèque...',
        delete_project: 'Supprimer ce projet',
        confirm_delete_project: 'Supprimer le projet « {{title}} » et TOUTES ses versions ? L’action est irréversible.',
        delete_project_error: 'Suppression du projet impossible',
        // sa#495 — vue de départ d'un emplacement de classeur, choisie parmi les
        // vues RÉELLES du diagramme épinglé (l'atelier admin n'a que la saisie).
        views_start: 'Vue de départ',
        views_start_hint: 'la vue sur laquelle la page publiée s\'ouvre',
        views_all: 'Toutes les vues',
        views_group_views: 'Vues du diagramme',
        views_group_labels: 'Labels de vues',
        views_mode_view: 'Une vue précise',
        views_mode_label: 'Les vues d\'un label',
        views_value_placeholder: 'id de vue ou label',
        views_loading: 'Lecture des vues du diagramme...',
        views_error: 'Diagramme illisible : saisie libre',
        views_empty: 'Ce diagramme ne porte aucune vue : saisie libre',
        views_unknown: 'Cette valeur ne figure pas dans les vues du diagramme ; elle est conservée telle quelle',
        views_runtime_warning: 'Le rendu publié ignore les options de vues : la sélection sera consignée, pas appliquée',
        views_not_first: 'Seule la sélection du premier emplacement de la page est appliquée au rendu'
      },
    }
  },
  //=======================================================
  //ES
  //=======================================================
  es: {
    translation: {
      templates: {
        need_osp: 'Se necesita MFASankey Dataviz',
        gallery_hint: 'Haga clic en una plantilla para empezar desde un ejemplo',
        sankeytheque_hint: 'Haga clic en un estudio para abrirlo',
        pin: 'Fijar la galería (el dibujo se reajusta a su izquierda, pruebe las plantillas una tras otra)',
        unpin: 'Desacoplar la galería (flota sobre el dibujo, se cierra en cuanto empieza a trabajar)',
        play: 'Reproducir la galería (carga cada modelo uno tras otro)',
        pause: 'Pausar la presentación',
        prev: 'Modelo anterior',
        next: 'Modelo siguiente',
        group_validated: 'Estudio validado (publicado en el sitio web)',
        published_link: 'Ver el diagrama publicado en línea',
        publication: {
          online: 'Publicado en línea',
          open: 'Abrir la página publicada',
          load: 'Cargar en la aplicación',
          version_load: 'Cargar esta versión',
          version_open: 'Abrir esta versión en línea',
          history: 'historial completo (desarrollador)',
          history_error: 'Historial no disponible',
          history_empty: 'Ninguna versión registrada por ahora'
        },
        group_readme_open: 'Leer la presentación',
        group_readme_close: 'Ocultar la presentación',
        group_readme_error: 'Descripción no disponible',
        library_hint: 'Sus proyectos versionados: haga clic en un diagrama para abrirlo, en un README para leerlo',
        library: {
          read_md: 'Leer este documento',
          edit_md: 'Editar este documento (deposita una nueva versión)',
          new_readme: 'Crear un README (nueva versión del proyecto)',
          download: 'Descargar este archivo',
          versions_error: 'Versiones no disponibles'
        },
        fr: 'Plantilla de diagrama en francés',
        en: 'Plantilla de diagrama en inglés',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Mapas',
          web: 'Clásicos de la web',
          other_formats: 'Otros formatos',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Mis proyectos',
          // Categorías de la sankeyteca (índice MFAData)
          etudes: 'Estudios',
          filieres: 'Sectores',
          recherche: 'Investigación',
          clients: 'Clientes'
        }
      },
      // sa#414 — panel « Explorador » (proyectos + libros de la cuenta)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorador',
        tooltip: 'Explore sus proyectos y libros; un diagrama se abre en una hoja nueva',
        hint: 'Sus proyectos y libros: haga clic en un diagrama para abrirlo en una hoja nueva',
        workbooks: 'Libros',
        projects_empty: 'Todavía no hay ningún proyecto en su biblioteca',
        workbooks_empty: 'Todavía no hay ningún libro',
        workbook_error: 'Libro no disponible',
        open_sheet: 'Abrir en una hoja nueva',
        add_section: 'sección',
        add_page: 'página',
        add_slot: 'diagrama',
        section_default: 'Nueva sección',
        page_default: 'Nueva página',
        delete_node: 'Quitar',
        move_up: 'Subir',
        move_down: 'Bajar',
        rename_hint: 'Haga doble clic para renombrar',
        confirm_delete: '¿Quitar este elemento y todo lo que contiene?',
        save_error: 'No se pudo guardar el libro',
        slot_file: 'Elegir un archivo...',
        slot_add: 'Fijar',
        slot_cancel: 'Cancelar',
        group_root: 'Documentos de la carpeta',
        search_placeholder: 'Filtrar proyectos...',
        search_no_match: 'Ningun proyecto coincide',
        menu_entry: 'Desde mi biblioteca...',
        delete_project: 'Eliminar este proyecto',
        confirm_delete_project: '¿Eliminar el proyecto «{{title}}» y TODAS sus versiones? La acción es irreversible.',
        delete_project_error: 'No se ha podido eliminar el proyecto',
        // sa#495
        views_start: 'Vista inicial',
        views_start_hint: 'la vista con la que se abre la página publicada',
        views_all: 'Todas las vistas',
        views_group_views: 'Vistas del diagrama',
        views_group_labels: 'Etiquetas de vistas',
        views_mode_view: 'Una vista concreta',
        views_mode_label: 'Las vistas de una etiqueta',
        views_value_placeholder: 'id de vista o etiqueta',
        views_loading: 'Leyendo las vistas del diagrama...',
        views_error: 'Diagrama ilegible: entrada libre',
        views_empty: 'Este diagrama no tiene ninguna vista: entrada libre',
        views_unknown: 'Este valor no está entre las vistas del diagrama; se conserva tal cual',
        views_runtime_warning: 'El motor publicado ignora las opciones de vistas: la selección se registrará, pero no se aplicará',
        views_not_first: 'Solo se aplica la selección del primer emplazamiento de la página'
      },
    }
  },
  //=======================================================
  //DE
  //=======================================================
  de: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz erforderlich',
        gallery_hint: 'Klicken Sie auf eine Vorlage, um mit einem Beispiel zu starten',
        sankeytheque_hint: 'Klicken Sie auf eine Studie, um sie zu öffnen',
        pin: 'Galerie anheften (die Zeichnung wird links davon neu angepasst, Vorlagen nacheinander ausprobieren)',
        unpin: 'Galerie lösen (schwebt über der Zeichnung, schließt sich, sobald Sie arbeiten)',
        play: 'Galerie abspielen (lädt jedes Modell nacheinander)',
        pause: 'Diashow pausieren',
        prev: 'Vorheriges Modell',
        next: 'Nächstes Modell',
        group_validated: 'Validierte Studie (auf der Website veröffentlicht)',
        published_link: 'Das veröffentlichte Diagramm online ansehen',
        publication: {
          online: 'Online veröffentlicht',
          open: 'Die veröffentlichte Seite öffnen',
          load: 'In die Anwendung laden',
          version_load: 'Diese Version laden',
          version_open: 'Diese Version online öffnen',
          history: 'vollständiger Verlauf (Entwickler)',
          history_error: 'Verlauf nicht verfügbar',
          history_empty: 'Noch keine erfasste Version'
        },
        group_readme_open: 'Beschreibung lesen',
        group_readme_close: 'Beschreibung ausblenden',
        group_readme_error: 'Beschreibung nicht verfügbar',
        library_hint: 'Ihre versionierten Projekte: Klicken Sie auf ein Diagramm, um es zu öffnen, auf ein README, um es zu lesen',
        library: {
          read_md: 'Dieses Dokument lesen',
          edit_md: 'Dieses Dokument bearbeiten (legt eine neue Version an)',
          new_readme: 'Ein README erstellen (neue Version des Projekts)',
          download: 'Diese Datei herunterladen',
          versions_error: 'Versionen nicht verfügbar'
        },
        fr: 'Diagrammvorlage auf Französisch',
        en: 'Diagrammvorlage auf Englisch',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Karten',
          web: 'Klassiker aus dem Web',
          other_formats: 'Andere Formate',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Meine Projekte',
          // Kategorien der Sankey-Bibliothek (MFAData-Index)
          etudes: 'Studien',
          filieres: 'Branchen',
          recherche: 'Forschung',
          clients: 'Kunden'
        }
      },
      // sa#414 — Panel „Explorer" (Projekte + Arbeitsmappen des Kontos)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorer',
        tooltip: 'Durchsuchen Sie Ihre Projekte und Arbeitsmappen; ein Diagramm öffnet sich in einem neuen Blatt',
        hint: 'Ihre Projekte und Arbeitsmappen: Klicken Sie auf ein Diagramm, um es in einem neuen Blatt zu öffnen',
        workbooks: 'Arbeitsmappen',
        projects_empty: 'Noch kein Projekt in Ihrer Bibliothek',
        workbooks_empty: 'Noch keine Arbeitsmappe',
        workbook_error: 'Arbeitsmappe nicht verfügbar',
        open_sheet: 'In einem neuen Blatt öffnen',
        add_section: 'Abschnitt',
        add_page: 'Seite',
        add_slot: 'Diagramm',
        section_default: 'Neuer Abschnitt',
        page_default: 'Neue Seite',
        delete_node: 'Entfernen',
        move_up: 'Nach oben',
        move_down: 'Nach unten',
        rename_hint: 'Doppelklicken zum Umbenennen',
        confirm_delete: 'Dieses Element und alles darunter entfernen?',
        save_error: 'Arbeitsmappe konnte nicht gespeichert werden',
        slot_file: 'Datei wählen...',
        slot_add: 'Anheften',
        slot_cancel: 'Abbrechen',
        group_root: 'Dokumente des Ordners',
        search_placeholder: 'Projekte filtern...',
        search_no_match: 'Kein Projekt entspricht der Suche',
        menu_entry: 'Aus meiner Bibliothek...',
        delete_project: 'Dieses Projekt löschen',
        confirm_delete_project: 'Projekt „{{title}}“ und ALLE seine Versionen löschen? Der Vorgang ist unwiderruflich.',
        delete_project_error: 'Projekt konnte nicht gelöscht werden',
        // sa#495
        views_start: 'Startansicht',
        views_start_hint: 'die Ansicht, mit der die veröffentlichte Seite öffnet',
        views_all: 'Alle Ansichten',
        views_group_views: 'Ansichten des Diagramms',
        views_group_labels: 'Ansichts-Labels',
        views_mode_view: 'Eine bestimmte Ansicht',
        views_mode_label: 'Die Ansichten eines Labels',
        views_value_placeholder: 'Ansichts-ID oder Label',
        views_loading: 'Ansichten des Diagramms werden gelesen...',
        views_error: 'Diagramm nicht lesbar: freie Eingabe',
        views_empty: 'Dieses Diagramm enthält keine Ansicht: freie Eingabe',
        views_unknown: 'Dieser Wert gehört nicht zu den Ansichten des Diagramms; er bleibt unverändert',
        views_runtime_warning: 'Die veröffentlichte Laufzeit ignoriert Ansichtsoptionen: die Auswahl wird vermerkt, aber nicht angewendet',
        views_not_first: 'Beim Rendern wird nur die Auswahl des ersten Platzes der Seite angewendet'
      },
    }
  },
  //=======================================================
  //IT
  //=======================================================
  it: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz necessario',
        gallery_hint: 'Clicca su un modello per partire da un esempio',
        sankeytheque_hint: 'Clicca su uno studio per aprirlo',
        pin: 'Fissa la galleria (il disegno si ridimensiona alla sua sinistra, prova i modelli uno dopo l\'altro)',
        unpin: 'Sgancia la galleria (fluttua sopra il disegno, si chiude appena inizi a lavorare)',
        play: 'Avvia la galleria (carica ogni modello uno dopo l\'altro)',
        pause: 'Metti in pausa la presentazione',
        prev: 'Modello precedente',
        next: 'Modello successivo',
        group_validated: 'Studio validato (pubblicato sul sito)',
        published_link: 'Vedi il diagramma pubblicato online',
        publication: {
          online: 'Pubblicato online',
          open: 'Apri la pagina pubblicata',
          load: 'Carica nell\'applicazione',
          version_load: 'Carica questa versione',
          version_open: 'Apri questa versione online',
          history: 'cronologia completa (sviluppatore)',
          history_error: 'Cronologia non disponibile',
          history_empty: 'Nessuna versione registrata per ora'
        },
        group_readme_open: 'Leggi la presentazione',
        group_readme_close: 'Nascondi la presentazione',
        group_readme_error: 'Descrizione non disponibile',
        library_hint: 'I tuoi progetti versionati: clicca su un diagramma per aprirlo, su un README per leggerlo',
        library: {
          read_md: 'Leggi questo documento',
          edit_md: 'Modifica questo documento (deposita una nuova versione)',
          new_readme: 'Crea un README (nuova versione del progetto)',
          download: 'Scarica questo file',
          versions_error: 'Versioni non disponibili'
        },
        fr: 'Modello di diagramma in francese',
        en: 'Modello di diagramma in inglese',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Mappe',
          web: 'Classici del web',
          other_formats: 'Altri formati',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'I miei progetti',
          // Categorie della sankeyteca (indice MFAData)
          etudes: 'Studi',
          filieres: 'Filiere',
          recherche: 'Ricerca',
          clients: 'Clienti'
        }
      },
      // sa#414 — pannello « Esplora » (progetti + cartelle di lavoro dell'account)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Esplora',
        tooltip: 'Sfoglia i tuoi progetti e le cartelle di lavoro; un diagramma si apre in un nuovo foglio',
        hint: 'I tuoi progetti e le tue cartelle di lavoro: clicca su un diagramma per aprirlo in un nuovo foglio',
        workbooks: 'Cartelle di lavoro',
        projects_empty: 'Nessun progetto nella tua biblioteca per ora',
        workbooks_empty: 'Nessuna cartella di lavoro per ora',
        workbook_error: 'Cartella di lavoro non disponibile',
        open_sheet: 'Apri in un nuovo foglio',
        add_section: 'sezione',
        add_page: 'pagina',
        add_slot: 'diagramma',
        section_default: 'Nuova sezione',
        page_default: 'Nuova pagina',
        delete_node: 'Rimuovi',
        move_up: 'Sposta su',
        move_down: 'Sposta giù',
        rename_hint: 'Doppio clic per rinominare',
        confirm_delete: 'Rimuovere questo elemento e tutto ciò che contiene?',
        save_error: 'Impossibile salvare la cartella di lavoro',
        slot_file: 'Scegli un file...',
        slot_add: 'Aggancia',
        slot_cancel: 'Annulla',
        group_root: 'Documenti della cartella',
        search_placeholder: 'Filtra i progetti...',
        search_no_match: 'Nessun progetto corrisponde',
        menu_entry: 'Dalla mia libreria...',
        delete_project: 'Elimina questo progetto',
        confirm_delete_project: 'Eliminare il progetto «{{title}}» e TUTTE le sue versioni? L’azione è irreversibile.',
        delete_project_error: 'Impossibile eliminare il progetto',
        // sa#495
        views_start: 'Vista iniziale',
        views_start_hint: 'la vista con cui si apre la pagina pubblicata',
        views_all: 'Tutte le viste',
        views_group_views: 'Viste del diagramma',
        views_group_labels: 'Etichette di viste',
        views_mode_view: 'Una vista precisa',
        views_mode_label: 'Le viste di un\'etichetta',
        views_value_placeholder: 'id di vista o etichetta',
        views_loading: 'Lettura delle viste del diagramma...',
        views_error: 'Diagramma illeggibile: inserimento libero',
        views_empty: 'Questo diagramma non contiene alcuna vista: inserimento libero',
        views_unknown: 'Questo valore non è tra le viste del diagramma; viene conservato così com\'è',
        views_runtime_warning: 'Il runtime pubblicato ignora le opzioni di viste: la selezione sarà registrata, non applicata',
        views_not_first: 'Al rendering si applica solo la selezione del primo slot della pagina'
      },
    }
  },
  'zh-CN': {
    translation: {
      templates: {
        need_osp: '需要 MFASankey Dataviz',
        gallery_hint: '点击某个模板即可从示例开始',
        sankeytheque_hint: '点击某项研究即可打开',
        pin: '固定图库（绘图区在其左侧调整大小，可逐个试用模板）',
        unpin: '取消固定图库（浮于绘图之上，一开始操作即关闭）',
        play: '播放图库（逐个加载各个模型）',
        pause: '暂停幻灯片',
        prev: '上一个模型',
        next: '下一个模型',
        group_validated: '已验证的研究（已在网站发布）',
        published_link: '在线查看已发布的图表',
        publication: {
          online: '已在线发布',
          open: '打开已发布页面',
          load: '加载到应用中',
          version_load: '加载此版本',
          version_open: '在线打开此版本',
          history: '完整历史（开发者）',
          history_error: '历史不可用',
          history_empty: '暂无记录的版本'
        },
        group_readme_open: '阅读介绍',
        group_readme_close: '隐藏介绍',
        group_readme_error: '描述不可用',
        library_hint: '您的版本化项目：点击图表打开，点击 README 阅读',
        library: {
          read_md: '阅读此文档',
          edit_md: '编辑此文档（提交新版本）',
          new_readme: '创建 README（项目新版本）',
          download: '下载此文件',
          versions_error: '版本不可用'
        },
        fr: '法语图表模板',
        en: '英语图表模板',
        categories: {
          opensankey: 'OpenSankey',
          maps: '地图',
          web: '网络经典案例',
          other_formats: '其他格式',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: '桑基图库',
          library: '我的项目',
          // Catégories de la sankeythèque (index MFAData)
          etudes: '研究',
          filieres: '部门',
          recherche: '科研',
          clients: '客户'
        }
      },
      // sa#414 — « 资源管理器 » 面板（账户的项目 + 工作簿）
      explorer: {
        theque: 'SankeyThèque',
        title: '资源管理器',
        tooltip: '浏览您的项目和工作簿；图表会在新工作表中打开',
        hint: '您的项目和工作簿：点击图表即可在新工作表中打开',
        workbooks: '工作簿',
        projects_empty: '您的库中还没有项目',
        workbooks_empty: '还没有工作簿',
        workbook_error: '工作簿不可用',
        open_sheet: '在新工作表中打开',
        add_section: '章节',
        add_page: '页面',
        add_slot: '图表',
        section_default: '新章节',
        page_default: '新页面',
        delete_node: '移除',
        move_up: '上移',
        move_down: '下移',
        rename_hint: '双击重命名',
        confirm_delete: '移除此项及其全部内容？',
        save_error: '无法保存工作簿',
        slot_file: '选择文件...',
        slot_add: '固定',
        slot_cancel: '取消',
        group_root: '文件夹文档',
        search_placeholder: '筛选项目…',
        search_no_match: '没有匹配的项目',
        menu_entry: '从我的库中打开…',
        delete_project: '删除此项目',
        confirm_delete_project: '删除项目“{{title}}”及其所有版本？此操作不可撤销。',
        delete_project_error: '无法删除项目',
        // sa#495
        views_start: '起始视图',
        views_start_hint: '发布页面打开时显示的视图',
        views_all: '全部视图',
        views_group_views: '图表视图',
        views_group_labels: '视图标签',
        views_mode_view: '指定某个视图',
        views_mode_label: '某个标签的视图',
        views_value_placeholder: '视图 id 或标签',
        views_loading: '正在读取图表视图...',
        views_error: '图表无法读取：可手动输入',
        views_empty: '该图表没有任何视图：可手动输入',
        views_unknown: '该值不在图表的视图中，将原样保留',
        views_runtime_warning: '发布运行时不支持视图选项：该选择会被记录但不会生效',
        views_not_first: '渲染时仅应用页面第一个位置的选择'
      },
    }
  },
  ja: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz が必要です',
        gallery_hint: 'テンプレートをクリックすると、その例から始められます',
        sankeytheque_hint: '研究事例をクリックすると開きます',
        pin: 'ギャラリーを固定（描画エリアはその左側でサイズ調整され、テンプレートを次々と試せます）',
        unpin: 'ギャラリーの固定を解除（描画の上に浮かび、作業を始めると閉じます）',
        play: 'ギャラリーを再生（各モデルを順に読み込みます）',
        pause: 'スライドショーを一時停止',
        prev: '前のモデル',
        next: '次のモデル',
        group_validated: '検証済みの研究事例（ウェブサイトで公開）',
        published_link: '公開された図をオンラインで見る',
        publication: {
          online: 'オンラインで公開中',
          open: '公開ページを開く',
          load: 'アプリに読み込む',
          version_load: 'このバージョンを読み込む',
          version_open: 'このバージョンをオンラインで開く',
          history: '完全な履歴（開発者）',
          history_error: '履歴を取得できません',
          history_empty: '記録されたバージョンはまだありません'
        },
        group_readme_open: '紹介を読む',
        group_readme_close: '紹介を隠す',
        group_readme_error: '説明を取得できません',
        library_hint: 'バージョン管理されたプロジェクト：図をクリックすると開き、README をクリックすると読めます',
        library: {
          read_md: 'このドキュメントを読む',
          edit_md: 'このドキュメントを編集（新しいバージョンを登録）',
          new_readme: 'README を作成（プロジェクトの新バージョン）',
          download: 'このファイルをダウンロード',
          versions_error: 'バージョンを取得できません'
        },
        fr: 'フランス語の図テンプレート',
        en: '英語の図テンプレート',
        categories: {
          opensankey: 'OpenSankey',
          maps: '地図',
          web: 'ウェブの定番例',
          other_formats: 'その他の形式',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'サンキーライブラリ',
          library: 'マイプロジェクト',
          // Catégories de la sankeythèque (index MFAData)
          etudes: '研究事例',
          filieres: '部門',
          recherche: '研究',
          clients: '顧客'
        }
      },
      // sa#414 — « エクスプローラー » パネル（アカウントのプロジェクト + ワークブック）
      explorer: {
        theque: 'SankeyThèque',
        title: 'エクスプローラー',
        tooltip: 'プロジェクトとワークブックを閲覧できます。図は新しいシートで開きます',
        hint: 'プロジェクトとワークブック：図をクリックすると新しいシートで開きます',
        workbooks: 'ワークブック',
        projects_empty: 'ライブラリにはまだプロジェクトがありません',
        workbooks_empty: 'まだワークブックがありません',
        workbook_error: 'ワークブックを取得できません',
        open_sheet: '新しいシートで開く',
        add_section: 'セクション',
        add_page: 'ページ',
        add_slot: '図',
        section_default: '新しいセクション',
        page_default: '新しいページ',
        delete_node: '削除',
        move_up: '上へ移動',
        move_down: '下へ移動',
        rename_hint: 'ダブルクリックで名前を変更',
        confirm_delete: 'この項目とその配下をすべて削除しますか？',
        save_error: 'ワークブックを保存できませんでした',
        slot_file: 'ファイルを選択...',
        slot_add: 'ピン留め',
        slot_cancel: 'キャンセル',
        group_root: 'フォルダの文書',
        search_placeholder: 'プロジェクトを絞り込む…',
        search_no_match: '一致するプロジェクトはありません',
        menu_entry: 'ライブラリから開く…',
        delete_project: 'このプロジェクトを削除',
        confirm_delete_project: 'プロジェクト「{{title}}」とそのすべてのバージョンを削除しますか？この操作は取り消せません。',
        delete_project_error: 'プロジェクトを削除できませんでした',
        // sa#495
        views_start: '開始ビュー',
        views_start_hint: '公開ページを開いたときに表示するビュー',
        views_all: 'すべてのビュー',
        views_group_views: 'ダイアグラムのビュー',
        views_group_labels: 'ビューのラベル',
        views_mode_view: '特定のビュー',
        views_mode_label: 'ラベルのビュー',
        views_value_placeholder: 'ビュー ID またはラベル',
        views_loading: 'ダイアグラムのビューを読み込み中...',
        views_error: 'ダイアグラムを読み取れません：自由入力',
        views_empty: 'このダイアグラムにはビューがありません：自由入力',
        views_unknown: 'この値はダイアグラムのビューにありません。そのまま保持されます',
        views_runtime_warning: '公開ランタイムはビューオプションに対応していません：選択は記録されますが適用されません',
        views_not_first: 'レンダリング時に適用されるのはページ最初の枠の選択のみです'
      },
    }
  }
}
