export const resources_template = {
  //=======================================================
  //EN
  //=======================================================
  en: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz needed',
        gallery_hint: 'Click a template to start from an example',
        sankeytheque_hint: 'Click a study to open it',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: 'Published studies: click a study to browse its diagrams, then a diagram to open it in a new sheet',
          loading: 'Loading the library…',
          empty: 'No published study yet',
          back: 'All studies',
          open_study: 'Open this study',
          diagrams: '{{count}} diagram(s)',
          versions: 'Published versions'
        },
        pin: 'Pin the gallery (the drawing resizes to its left, try templates one after another)',
        unpin: 'Unpin the gallery (floats over the drawing, closes as soon as you start working)',
        play: 'Play the gallery (loads each model one after another)',
        pause: 'Pause the slideshow',
        prev: 'Previous model',
        next: 'Next model',
        group_validated: 'Validated study (published on the website)',
        published_link: 'View the published diagram online',
        publication: {
          online: 'Published online',
          open: 'Open the published page',
          load: 'Load into the app',
          version_load: 'Load this version',
          version_open: 'Open this version online',
          history: 'full history (developer)',
          history_error: 'History unavailable',
          history_empty: 'No recorded version yet'
        },
        group_readme_open: 'Read the presentation',
        group_readme_close: 'Hide the presentation',
        group_readme_error: 'Description unavailable',
        library_hint: 'Your versioned projects: click a diagram to open it, a README to read it',
        library: {
          read_md: 'Read this document',
          edit_md: 'Edit this document (deposits a new version)',
          new_readme: 'Create a README (new version of the project)',
          download: 'Download this file',
          versions_error: 'Versions unavailable'
        },
        fr: 'Diagram template in french',
        en: 'Diagram template in english',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Maps',
          web: 'Classics from the web',
          other_formats: 'Other formats',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'My projects',
          // Catégories de la sankeythèque (index MFAData)
          etudes: 'Studies',
          filieres: 'Sectors',
          recherche: 'Research',
          clients: 'Clients'
        }
      },
      // sa#414 — panneau « Explorateur » (projets + classeurs du compte)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorer',
        tooltip: 'Browse your projects and workbooks; a diagram opens in a new sheet',
        hint: 'Your projects and workbooks: click a diagram to open it in a new sheet',
        workbooks: 'Workbooks',
        projects_empty: 'No project in your library yet',
        workbooks_empty: 'No workbook yet',
        workbook_error: 'Workbook unavailable',
        open_sheet: 'Open in a new sheet',
        add_section: 'section',
        add_page: 'page',
        add_slot: 'diagram',
        section_default: 'New section',
        page_default: 'New page',
        delete_node: 'Remove',
        move_up: 'Move up',
        move_down: 'Move down',
        rename_hint: 'Double-click to rename',
        confirm_delete: 'Remove this item and everything under it?',
        save_error: 'Could not save the workbook',
        slot_file: 'Choose a file...',
        slot_add: 'Pin',
        slot_cancel: 'Cancel',
        group_root: 'Folder documents',
        search_placeholder: 'Filter projects...',
        search_no_match: 'No project matches this search',
        menu_entry: 'From my library...',
        delete_project: 'Delete this project',
        confirm_delete_project: 'Delete the project “{{title}}” and ALL its versions? The action cannot be undone.',
        delete_project_error: 'Could not delete the project',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: 'settings',
        settings_no_slot: 'Pin a diagram first: the files come from its project',
        settings_loading: 'Loading the project files...',
        settings_header: 'Displayed title',
        settings_header_auto: 'Page title',
        settings_header_custom: 'Custom title',
        settings_header_none: 'No header',
        settings_header_placeholder: 'Title shown in the top bar',
        settings_logo: 'Logo',
        settings_logo_width: 'Logo width',
        settings_footer: 'Footer',
        settings_footer_on: 'Shown',
        settings_footer_off: 'Hidden',
        settings_doc: 'Document',
        settings_doc_auto: 'Automatic',
        settings_doc_none: 'None announced',
        settings_excel: 'Excel workbook',
        settings_excel_locked: 'Designated as the page workbook: always published',
        settings_downloads: 'Downloads',
        settings_downloads_all: 'Every file of the folder',
        settings_downloads_some: 'Selected files',
        settings_downloads_empty: 'No Excel file in the diagram folder',
        settings_none: 'None',
        settings_default: 'Default',
        settings_custom: 'Other path...',
        settings_custom_hint: 'path/in/the/project.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'layout',
        section_flat: 'Placement',
        section_flat_folder: 'Its own folder',
        section_flat_group: 'A group on the home page',
        section_flat_hint: 'Without a folder, the section title becomes a home page heading and its pages stay at the first level',
        section_flat_no_title: 'Without a title the section makes no group: the site will show no heading.',
        section_thumbnail: 'Thumbnail',
        section_thumbnail_hint: 'path/in/a/project.png',
        section_thumbnail_orphan: 'Image missing from the pinned projects: kept as it is.',
        section_thumbnail_no_slot: 'Pin a diagram in a page first: the images come from the projects of the section',
        section_thumbnail_none: 'No image in the projects pinned by the pages',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'text',
        doc_site: 'Site home text',
        doc_node: 'Text',
        doc_lang_default: 'Default',
        doc_filled: 'Text written in the workbook',
        doc_missing: 'No text: the README of the pinned project is used',
        doc_none_hint: 'No text: the home page will show the README of the pinned project.',
        doc_untranslated: 'Without a text, these languages keep the project one: {{langs}}',
        doc_lang_dead: 'Never served: French is the default language, write it under “Default”.',
        doc_language: 'Language',
        doc_panel_label: 'Workbook text editor',
        doc_placeholder: '# Title\n\nHome text, in markdown...',
        doc_hint: 'The workbook text overrides the project README, language by language.',
        doc_fallback_hint: 'A language without a text keeps the one of the pinned project.',
        doc_default_first: 'Start with the default language: the others fall back on it.',
        doc_discard: 'Discard the text being written?',
        doc_saved: 'Text saved',
        doc_cleared: 'Text removed: this language falls back on the pinned project',
        doc_close: 'Close',
        doc_save: 'Save',
        // sa#495 — starting view of a workbook slot, picked among the REAL
        // views of the pinned diagram (the admin workshop only had free text).
        views_start: 'Starting view',
        views_start_hint: 'the view the published page opens on',
        views_all: 'All views',
        views_group_views: 'Diagram views',
        views_group_labels: 'View labels',
        views_mode_view: 'A specific view',
        views_mode_label: 'Views with a label',
        views_value_placeholder: 'view id or label',
        views_loading: 'Reading the diagram views...',
        views_error: 'Diagram unreadable: free text',
        views_empty: 'This diagram carries no view: free text',
        views_unknown: 'This value is not among the diagram views; it is kept as is',
        views_runtime_warning: 'The published runtime ignores view options: the selection will be recorded, not applied',
        views_not_first: 'Only the selection of the first slot of the page is applied at render time',
        // sa#494 — completing a library project from the explorer: a project
        // deposited from the app carried a single `diagramme.json`, where a real
        // study carries fourteen files (workbooks, logo, names.json, READMEs).
        add_files: 'Add files',
        add_files_hint: 'Add files to this project (creates a new version)',
        add_files_in: 'Add files into “{{folder}}”',
        drop_hint: 'Drop a folder or files here',
        deposit_confirm: 'Add {{count}} file(s) to the project “{{title}}”? A new version (v{{number}}) will be created: versions are immutable.',
        deposit_running: 'Depositing into the library...',
        deposit_done: 'v{{number}} created — {{count}} file(s) added',
        deposit_unchanged: 'Same as v{{number}}: nothing new to version',
        deposit_error: 'Deposit failed',
        deposit_refused: {
          empty: 'No file to deposit.',
          gz: 'Compressed file refused: “{{name}}”. A library project only carries plain JSON — uncompress it before depositing.',
          too_many: 'Too many files at once ({{count}}, 200 maximum).',
          too_big: 'File too large: “{{name}}” (100 MB maximum).',
          bad_path: 'Invalid file path: “{{name}}”.'
        },
        // sa#490 — publication state of a workbook, shown on its row
        publish_none: 'not published yet',
        publish_rendered: 'rendered on {{date}}',
        publish_stale: 'modified since',
        publish_open: 'Open the published page',
        // sa#491 — publishing a workbook from the explorer: dry run first, then
        // going online. The address is pre-filled and read-only on purpose.
        publish_action: 'Publish',
        publish_close: 'Close',
        publish_address: 'Online address',
        publish_address_change: 'Change',
        publish_address_computed: 'never published — address derived from the title',
        publish_address_diff: 'Different from “{{slug}}”: a separate site will be created next to it.',
        publish_dry: 'Dry run',
        publish_dry_busy: 'dry run in progress...',
        publish_dry_ok: 'Dry run passed: {{pages}} page(s), {{diagrams}} diagram(s).',
        publish_go: 'Go online',
        publish_go_busy: 'going online...',
        publish_confirm: 'Publish “{{title}}” at address {{slug}}? The previous rendering moves to versions/.',
        publish_done: 'Online: {{url}}',
        publish_failed: 'Refused: {{message}}',
        publish_unsaved: 'Saving in progress — the dry run covers the saved state of the workbook.',
        publish_target: 'Target address: {{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: 'snapshot {{sha}}',
        publish_warnings: 'Warnings ({{n}})',
        publish_long_notice: 'Rendering can take several minutes: pages, diagrams, Excel workbooks and thumbnails are all rebuilt. Keep this tab open.',
        publish_elapsed: '{{seconds}} s',
        publish_phase: 'step: {{phase}}',
        publish_cut: 'Connection lost ({{message}}). Rendering most likely continues on the server: do not start it again and do not close this tab. Reopen this panel in a few minutes to see the result.',
        publish_busy: 'A publication is already running for this address: that is the one followed here.',
        publish_lost: 'Rendering is no longer responding — the server most likely restarted. Nothing was left half online: start the publication again.',
        publish_duration: 'Duration: {{seconds}} s',
        publish_slowest: 'slowest phase: {{phase}} ({{seconds}} s)',
        // sa#502 — creating and deleting a WORKBOOK, the last two gestures that
        // lived only in the administration. The work group follows the server
        // rule (default_group_id): the client never guesses it.
        create_workbook: 'workbook',
        create_workbook_hint: 'Create an empty workbook',
        create_workbook_placeholder: 'Workbook title',
        create_workbook_submit: 'Create',
        create_workbook_error: 'Could not create the workbook',
        delete_workbook: 'Delete this workbook',
        confirm_delete_workbook: 'Delete the workbook “{{title}}”? The action cannot be undone. The pinned bricks are left untouched: they stay in the library, and an already published site stays online.',
        delete_workbook_error: 'Could not delete the workbook'
      },
    }
  },
  //=======================================================
  //FR
  //=======================================================
  fr: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz necessaire',
        gallery_hint: 'Cliquez sur un modèle pour partir d\'un exemple',
        sankeytheque_hint: 'Cliquez sur une étude pour l\'ouvrir',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: 'Études publiées : cliquez sur une étude pour parcourir ses diagrammes, puis sur un diagramme pour l\'ouvrir dans une nouvelle feuille',
          loading: 'Chargement de la thèque…',
          empty: 'Aucune étude publiée pour l\'instant',
          back: 'Toutes les études',
          open_study: 'Ouvrir cette étude',
          diagrams: '{{count}} diagramme(s)',
          versions: 'Versions publiées'
        },
        pin: 'Épingler la galerie (le dessin se recadre à gauche, essayez les modèles à la suite)',
        unpin: 'Détacher la galerie (survol du dessin, elle se ferme dès que vous travaillez)',
        play: 'Lancer la galerie (charge chaque modèle l\'un après l\'autre)',
        pause: 'Mettre le diaporama en pause',
        prev: 'Modèle précédent',
        next: 'Modèle suivant',
        group_validated: 'Étude validée (publiée sur le site)',
        published_link: 'Voir le diagramme publié en ligne',
        publication: {
          online: 'Publié en ligne',
          open: 'Ouvrir la page publiée',
          load: 'Charger dans l\'application',
          version_load: 'Charger cette version',
          version_open: 'Ouvrir cette version en ligne',
          history: 'historique complet (développeur)',
          history_error: 'Historique indisponible',
          history_empty: 'Aucune version enregistrée pour l\'instant'
        },
        group_readme_open: 'Lire la présentation',
        group_readme_close: 'Masquer la présentation',
        group_readme_error: 'Description indisponible',
        library_hint: 'Vos projets versionnés : cliquez sur un diagramme pour l\'ouvrir, un README pour le lire',
        library: {
          read_md: 'Lire ce document',
          edit_md: 'Éditer ce document (dépose une nouvelle version)',
          new_readme: 'Créer un README (nouvelle version du projet)',
          download: 'Télécharger ce fichier',
          versions_error: 'Versions indisponibles'
        },
        fr: 'Modèle de diagramme en français',
        en: 'Modèle de diagramme en anglais',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Cartes',
          web: 'Classiques du web',
          other_formats: 'Autres formats',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Mes projets',
          // Catégories de la sankeythèque (index MFAData)
          etudes: 'Études',
          filieres: 'Filières',
          recherche: 'Recherche',
          clients: 'Clients'
        }
      },
      // sa#414 — panneau « Explorateur » (projets + classeurs du compte)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorateur',
        tooltip: 'Parcourez vos projets et classeurs ; un diagramme s\'ouvre dans une nouvelle feuille',
        hint: 'Vos projets et classeurs : cliquez sur un diagramme pour l\'ouvrir dans une nouvelle feuille',
        workbooks: 'Classeurs',
        projects_empty: 'Aucun projet dans votre bibliothèque pour l\'instant',
        workbooks_empty: 'Aucun classeur pour l\'instant',
        workbook_error: 'Classeur indisponible',
        open_sheet: 'Ouvrir dans une nouvelle feuille',
        add_section: 'section',
        add_page: 'page',
        add_slot: 'diagramme',
        section_default: 'Nouvelle section',
        page_default: 'Nouvelle page',
        delete_node: 'Retirer',
        move_up: 'Monter',
        move_down: 'Descendre',
        rename_hint: 'Double-cliquez pour renommer',
        confirm_delete: 'Retirer cet élément et tout ce qu\'il contient ?',
        save_error: 'Échec de l\'enregistrement du classeur',
        slot_file: 'Choisir un fichier...',
        slot_add: 'Épingler',
        slot_cancel: 'Annuler',
        group_root: 'Documents du dossier',
        search_placeholder: 'Filtrer les projets...',
        search_no_match: 'Aucun projet ne correspond',
        menu_entry: 'Depuis ma bibliothèque...',
        delete_project: 'Supprimer ce projet',
        confirm_delete_project: 'Supprimer le projet « {{title}} » et TOUTES ses versions ? L’action est irréversible.',
        delete_project_error: 'Suppression du projet impossible',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: 'réglages',
        settings_no_slot: 'Épinglez d\'abord un diagramme : les fichiers viennent de son projet',
        settings_loading: 'Chargement des fichiers du projet...',
        settings_header: 'Titre affiché',
        settings_header_auto: 'Titre de la page',
        settings_header_custom: 'Titre choisi',
        settings_header_none: 'Aucun en-tête',
        settings_header_placeholder: 'Titre affiché dans la barre du haut',
        settings_logo: 'Logo',
        settings_logo_width: 'Largeur du logo',
        settings_footer: 'Pied de page',
        settings_footer_on: 'Affiché',
        settings_footer_off: 'Masqué',
        settings_doc: 'Document',
        settings_doc_auto: 'Automatique',
        settings_doc_none: 'Aucun annoncé',
        settings_excel: 'Classeur Excel',
        settings_excel_locked: 'Désigné comme classeur de la page : toujours publié',
        settings_downloads: 'Téléchargements',
        settings_downloads_all: 'Tous les fichiers du dossier',
        settings_downloads_some: 'Fichiers choisis',
        settings_downloads_empty: 'Aucun classeur Excel dans le dossier du diagramme',
        settings_none: 'Aucun',
        settings_default: 'Par défaut',
        settings_custom: 'Autre chemin...',
        settings_custom_hint: 'chemin/dans/le/projet.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'mise en page',
        section_flat: 'Rangement',
        section_flat_folder: 'Un dossier à part',
        section_flat_group: 'Un groupe sur l\'accueil',
        section_flat_hint: 'Sans dossier, le titre de la section devient un intertitre de l\'accueil et ses pages restent au premier niveau',
        section_flat_no_title: 'Sans titre, la section ne fait pas groupe : le site n\'affichera aucun intertitre.',
        section_thumbnail: 'Vignette',
        section_thumbnail_hint: 'chemin/dans/une/brique.png',
        section_thumbnail_orphan: 'Image absente des briques épinglées : conservée telle quelle.',
        section_thumbnail_no_slot: 'Épinglez d\'abord un diagramme dans une page : les images viennent des briques de la section',
        section_thumbnail_none: 'Aucune image dans les briques épinglées par les pages',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'texte',
        doc_site: 'Texte d\'accueil du site',
        doc_node: 'Texte',
        doc_lang_default: 'Par défaut',
        doc_filled: 'Texte écrit dans le classeur',
        doc_missing: 'Aucun texte : le README du projet épinglé est repris',
        doc_none_hint: 'Aucun texte : l\'accueil reprendra le README du projet épinglé.',
        doc_untranslated: 'Sans texte, ces langues gardent celui du projet : {{langs}}',
        doc_lang_dead: 'Variante jamais servie : le français est la langue par défaut, écrivez-le sous « Par défaut ».',
        doc_language: 'Langue',
        doc_panel_label: 'Éditeur du texte du classeur',
        doc_placeholder: '# Titre\n\nTexte d\'accueil, en markdown...',
        doc_hint: 'Le texte du classeur prime sur le README du projet, langue par langue.',
        doc_fallback_hint: 'Une langue sans texte garde celui du projet épinglé.',
        doc_default_first: 'Commencez par la langue par défaut : c\'est le repli des autres.',
        doc_discard: 'Abandonner le texte en cours de saisie ?',
        doc_saved: 'Texte enregistré',
        doc_cleared: 'Texte retiré : cette langue revient au projet épinglé',
        doc_close: 'Fermer',
        doc_save: 'Enregistrer',
        // sa#495 — vue de départ d'un emplacement de classeur, choisie parmi les
        // vues RÉELLES du diagramme épinglé (l'atelier admin n'a que la saisie).
        views_start: 'Vue de départ',
        views_start_hint: 'la vue sur laquelle la page publiée s\'ouvre',
        views_all: 'Toutes les vues',
        views_group_views: 'Vues du diagramme',
        views_group_labels: 'Labels de vues',
        views_mode_view: 'Une vue précise',
        views_mode_label: 'Les vues d\'un label',
        views_value_placeholder: 'id de vue ou label',
        views_loading: 'Lecture des vues du diagramme...',
        views_error: 'Diagramme illisible : saisie libre',
        views_empty: 'Ce diagramme ne porte aucune vue : saisie libre',
        views_unknown: 'Cette valeur ne figure pas dans les vues du diagramme ; elle est conservée telle quelle',
        views_runtime_warning: 'Le rendu publié ignore les options de vues : la sélection sera consignée, pas appliquée',
        views_not_first: 'Seule la sélection du premier emplacement de la page est appliquée au rendu',
        // sa#494 — compléter une brique depuis l'explorateur : une brique déposée
        // par l'application ne portait qu'un `diagramme.json`, quand une filière
        // conforme en porte quatorze (classeurs, logo, names.json, README).
        add_files: 'Ajouter des fichiers',
        add_files_hint: 'Ajouter des fichiers à ce projet (crée une nouvelle version)',
        add_files_in: 'Ajouter des fichiers dans « {{folder}} »',
        drop_hint: 'Glissez ici un dossier ou des fichiers',
        deposit_confirm: 'Ajouter {{count}} fichier(s) au projet « {{title}} » ? Une nouvelle version (v{{number}}) sera créée : les versions sont immuables.',
        deposit_running: 'Dépôt dans la bibliothèque...',
        deposit_done: 'v{{number}} créée — {{count}} fichier(s) ajouté(s)',
        deposit_unchanged: 'Identique à la v{{number}} : rien de neuf à versionner',
        deposit_error: 'Échec du dépôt',
        deposit_refused: {
          empty: 'Aucun fichier à déposer.',
          gz: 'Fichier compressé refusé : « {{name}} ». Une brique ne porte que du JSON en clair — décompressez avant de déposer.',
          too_many: 'Trop de fichiers d\'un coup ({{count}}, 200 au maximum).',
          too_big: 'Fichier trop lourd : « {{name}} » (100 Mo au maximum).',
          bad_path: 'Chemin de fichier invalide : « {{name}} ».'
        },
        // sa#490 — état de publication du classeur, affiché sur sa ligne
        publish_none: 'pas encore publié',
        publish_rendered: 'rendu le {{date}}',
        publish_stale: 'modifié depuis',
        publish_open: 'Ouvrir la page publiée',
        // sa#491 — publier un classeur depuis l'explorateur : essai à blanc
        // d'abord, mise en ligne ensuite. L'adresse est pré-remplie et en
        // lecture seule à dessein (un champ vide créait un site fantôme).
        publish_action: 'Publier',
        publish_close: 'Fermer',
        publish_address: 'Adresse en ligne',
        publish_address_change: 'Changer',
        publish_address_computed: 'jamais publié — adresse calculée depuis le titre',
        publish_address_diff: 'Différente de « {{slug}} » : un site distinct sera créé à côté.',
        publish_dry: 'Essai à blanc',
        publish_dry_busy: 'essai à blanc en cours...',
        publish_dry_ok: 'Essai vert : {{pages}} page(s), {{diagrams}} diagramme(s).',
        publish_go: 'Mettre en ligne',
        publish_go_busy: 'mise en ligne en cours...',
        publish_confirm: 'Publier « {{title}} » à l’adresse {{slug}} ? Le rendu précédent part dans versions/.',
        publish_done: 'En ligne : {{url}}',
        publish_failed: 'Refusé : {{message}}',
        publish_unsaved: 'Enregistrement en cours — l’essai porte sur l’état enregistré du classeur.',
        publish_target: 'Adresse visée : {{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: 'instantané {{sha}}',
        publish_warnings: 'Avertissements ({{n}})',
        publish_long_notice: 'Le rendu peut prendre plusieurs minutes : pages, diagrammes, classeurs Excel et vignettes sont refabriqués. Laissez cet onglet ouvert.',
        publish_elapsed: '{{seconds}} s',
        publish_phase: 'étape : {{phase}}',
        publish_cut: 'Connexion interrompue ({{message}}). Le rendu se poursuit probablement sur le serveur : ne le relancez pas et ne fermez pas cet onglet. Rouvrez ce bloc dans quelques minutes pour voir le résultat.',
        publish_busy: 'Une publication est déjà en cours pour cette adresse : c’est elle qui est suivie ici.',
        publish_lost: 'Le rendu ne donne plus signe de vie — le serveur a probablement redémarré. Rien n’est resté à moitié en ligne : relancez la publication.',
        publish_duration: 'Durée : {{seconds}} s',
        publish_slowest: 'phase la plus longue : {{phase}} ({{seconds}} s)',
        // sa#502 — CRÉER et SUPPRIMER un classeur, les deux derniers gestes qui
        // ne vivaient qu'en administration. Le groupe de travail suit la règle
        // du serveur (default_group_id) : le client ne le devine jamais.
        create_workbook: 'classeur',
        create_workbook_hint: 'Créer un classeur vide',
        create_workbook_placeholder: 'Titre du classeur',
        create_workbook_submit: 'Créer',
        create_workbook_error: 'Création du classeur impossible',
        delete_workbook: 'Supprimer ce classeur',
        confirm_delete_workbook: 'Supprimer le classeur « {{title}} » ? L’action est irréversible. Les briques épinglées ne sont pas touchées : elles restent en bibliothèque, et un site déjà publié reste en ligne.',
        delete_workbook_error: 'Suppression du classeur impossible'
      },
    }
  },
  //=======================================================
  //ES
  //=======================================================
  es: {
    translation: {
      templates: {
        need_osp: 'Se necesita MFASankey Dataviz',
        gallery_hint: 'Haga clic en una plantilla para empezar desde un ejemplo',
        sankeytheque_hint: 'Haga clic en un estudio para abrirlo',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: 'Estudios publicados: haga clic en un estudio para recorrer sus diagramas, luego en un diagrama para abrirlo en una nueva hoja',
          loading: 'Cargando la biblioteca…',
          empty: 'Ningún estudio publicado por ahora',
          back: 'Todos los estudios',
          open_study: 'Abrir este estudio',
          diagrams: '{{count}} diagrama(s)',
          versions: 'Versiones publicadas'
        },
        pin: 'Fijar la galería (el dibujo se reajusta a su izquierda, pruebe las plantillas una tras otra)',
        unpin: 'Desacoplar la galería (flota sobre el dibujo, se cierra en cuanto empieza a trabajar)',
        play: 'Reproducir la galería (carga cada modelo uno tras otro)',
        pause: 'Pausar la presentación',
        prev: 'Modelo anterior',
        next: 'Modelo siguiente',
        group_validated: 'Estudio validado (publicado en el sitio web)',
        published_link: 'Ver el diagrama publicado en línea',
        publication: {
          online: 'Publicado en línea',
          open: 'Abrir la página publicada',
          load: 'Cargar en la aplicación',
          version_load: 'Cargar esta versión',
          version_open: 'Abrir esta versión en línea',
          history: 'historial completo (desarrollador)',
          history_error: 'Historial no disponible',
          history_empty: 'Ninguna versión registrada por ahora'
        },
        group_readme_open: 'Leer la presentación',
        group_readme_close: 'Ocultar la presentación',
        group_readme_error: 'Descripción no disponible',
        library_hint: 'Sus proyectos versionados: haga clic en un diagrama para abrirlo, en un README para leerlo',
        library: {
          read_md: 'Leer este documento',
          edit_md: 'Editar este documento (deposita una nueva versión)',
          new_readme: 'Crear un README (nueva versión del proyecto)',
          download: 'Descargar este archivo',
          versions_error: 'Versiones no disponibles'
        },
        fr: 'Plantilla de diagrama en francés',
        en: 'Plantilla de diagrama en inglés',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Mapas',
          web: 'Clásicos de la web',
          other_formats: 'Otros formatos',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Mis proyectos',
          // Categorías de la sankeyteca (índice MFAData)
          etudes: 'Estudios',
          filieres: 'Sectores',
          recherche: 'Investigación',
          clients: 'Clientes'
        }
      },
      // sa#414 — panel « Explorador » (proyectos + libros de la cuenta)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorador',
        tooltip: 'Explore sus proyectos y libros; un diagrama se abre en una hoja nueva',
        hint: 'Sus proyectos y libros: haga clic en un diagrama para abrirlo en una hoja nueva',
        workbooks: 'Libros',
        projects_empty: 'Todavía no hay ningún proyecto en su biblioteca',
        workbooks_empty: 'Todavía no hay ningún libro',
        workbook_error: 'Libro no disponible',
        open_sheet: 'Abrir en una hoja nueva',
        add_section: 'sección',
        add_page: 'página',
        add_slot: 'diagrama',
        section_default: 'Nueva sección',
        page_default: 'Nueva página',
        delete_node: 'Quitar',
        move_up: 'Subir',
        move_down: 'Bajar',
        rename_hint: 'Haga doble clic para renombrar',
        confirm_delete: '¿Quitar este elemento y todo lo que contiene?',
        save_error: 'No se pudo guardar el libro',
        slot_file: 'Elegir un archivo...',
        slot_add: 'Fijar',
        slot_cancel: 'Cancelar',
        group_root: 'Documentos de la carpeta',
        search_placeholder: 'Filtrar proyectos...',
        search_no_match: 'Ningun proyecto coincide',
        menu_entry: 'Desde mi biblioteca...',
        delete_project: 'Eliminar este proyecto',
        confirm_delete_project: '¿Eliminar el proyecto «{{title}}» y TODAS sus versiones? La acción es irreversible.',
        delete_project_error: 'No se ha podido eliminar el proyecto',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: 'ajustes',
        settings_no_slot: 'Fije primero un diagrama: los archivos vienen de su proyecto',
        settings_loading: 'Cargando los archivos del proyecto...',
        settings_header: 'Título mostrado',
        settings_header_auto: 'Título de la página',
        settings_header_custom: 'Título elegido',
        settings_header_none: 'Sin encabezado',
        settings_header_placeholder: 'Título mostrado en la barra superior',
        settings_logo: 'Logotipo',
        settings_logo_width: 'Ancho del logotipo',
        settings_footer: 'Pie de página',
        settings_footer_on: 'Mostrado',
        settings_footer_off: 'Oculto',
        settings_doc: 'Documento',
        settings_doc_auto: 'Automático',
        settings_doc_none: 'Ninguno anunciado',
        settings_excel: 'Libro de Excel',
        settings_excel_locked: 'Designado como libro de la página: siempre publicado',
        settings_downloads: 'Descargas',
        settings_downloads_all: 'Todos los archivos de la carpeta',
        settings_downloads_some: 'Archivos elegidos',
        settings_downloads_empty: 'Ningún archivo Excel en la carpeta del diagrama',
        settings_none: 'Ninguno',
        settings_default: 'Por defecto',
        settings_custom: 'Otra ruta...',
        settings_custom_hint: 'ruta/en/el/proyecto.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'disposición',
        section_flat: 'Ubicación',
        section_flat_folder: 'Una carpeta propia',
        section_flat_group: 'Un grupo en la portada',
        section_flat_hint: 'Sin carpeta, el título de la sección se convierte en un encabezado de la portada y sus páginas quedan en el primer nivel',
        section_flat_no_title: 'Sin título la sección no forma grupo: el sitio no mostrará ningún encabezado.',
        section_thumbnail: 'Miniatura',
        section_thumbnail_hint: 'ruta/en/un/proyecto.png',
        section_thumbnail_orphan: 'Imagen ausente de los proyectos anclados: se conserva tal cual.',
        section_thumbnail_no_slot: 'Ancle primero un diagrama en una página: las imágenes vienen de los proyectos de la sección',
        section_thumbnail_none: 'Ninguna imagen en los proyectos anclados por las páginas',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'texto',
        doc_site: 'Texto de inicio del sitio',
        doc_node: 'Texto',
        doc_lang_default: 'Por defecto',
        doc_filled: 'Texto escrito en el libro',
        doc_missing: 'Sin texto: se retoma el README del proyecto anclado',
        doc_none_hint: 'Sin texto: la página de inicio mostrará el README del proyecto anclado.',
        doc_untranslated: 'Sin texto, estos idiomas conservan el del proyecto: {{langs}}',
        doc_lang_dead: 'Variante nunca servida: el francés es el idioma por defecto, escríbalo en «Por defecto».',
        doc_language: 'Idioma',
        doc_panel_label: 'Editor del texto del libro',
        doc_placeholder: '# Título\n\nTexto de inicio, en markdown...',
        doc_hint: 'El texto del libro prevalece sobre el README del proyecto, idioma por idioma.',
        doc_fallback_hint: 'Un idioma sin texto conserva el del proyecto anclado.',
        doc_default_first: 'Empiece por el idioma por defecto: los demás recurren a él.',
        doc_discard: '¿Descartar el texto en curso?',
        doc_saved: 'Texto guardado',
        doc_cleared: 'Texto retirado: este idioma vuelve al proyecto anclado',
        doc_close: 'Cerrar',
        doc_save: 'Guardar',
        // sa#495
        views_start: 'Vista inicial',
        views_start_hint: 'la vista con la que se abre la página publicada',
        views_all: 'Todas las vistas',
        views_group_views: 'Vistas del diagrama',
        views_group_labels: 'Etiquetas de vistas',
        views_mode_view: 'Una vista concreta',
        views_mode_label: 'Las vistas de una etiqueta',
        views_value_placeholder: 'id de vista o etiqueta',
        views_loading: 'Leyendo las vistas del diagrama...',
        views_error: 'Diagrama ilegible: entrada libre',
        views_empty: 'Este diagrama no tiene ninguna vista: entrada libre',
        views_unknown: 'Este valor no está entre las vistas del diagrama; se conserva tal cual',
        views_runtime_warning: 'El motor publicado ignora las opciones de vistas: la selección se registrará, pero no se aplicará',
        views_not_first: 'Solo se aplica la selección del primer emplazamiento de la página',
        add_files: 'Añadir archivos',
        add_files_hint: 'Añadir archivos a este proyecto (crea una nueva versión)',
        add_files_in: 'Añadir archivos en «{{folder}}»',
        drop_hint: 'Arrastre aquí una carpeta o archivos',
        deposit_confirm: '¿Añadir {{count}} archivo(s) al proyecto «{{title}}»? Se creará una nueva versión (v{{number}}): las versiones son inmutables.',
        deposit_running: 'Depositando en la biblioteca...',
        deposit_done: 'v{{number}} creada — {{count}} archivo(s) añadidos',
        deposit_unchanged: 'Idéntico a la v{{number}}: nada nuevo que versionar',
        deposit_error: 'Error al depositar',
        deposit_refused: {
          empty: 'Ningún archivo que depositar.',
          gz: 'Archivo comprimido rechazado: «{{name}}». Un proyecto solo admite JSON sin comprimir — descomprímalo antes de depositarlo.',
          too_many: 'Demasiados archivos a la vez ({{count}}, 200 como máximo).',
          too_big: 'Archivo demasiado pesado: «{{name}}» (100 MB como máximo).',
          bad_path: 'Ruta de archivo no válida: «{{name}}».'
        },
        // sa#490 — estado de publicación del cuaderno, en su línea
        publish_none: 'aún no publicado',
        publish_rendered: 'generado el {{date}}',
        publish_stale: 'modificado desde entonces',
        publish_open: 'Abrir la página publicada',
        // sa#491 — publicar un cuaderno desde el explorador: primero la prueba
        // en seco, luego la puesta en línea. La dirección viene rellenada.
        publish_action: 'Publicar',
        publish_close: 'Cerrar',
        publish_address: 'Dirección en línea',
        publish_address_change: 'Cambiar',
        publish_address_computed: 'nunca publicado — dirección derivada del título',
        publish_address_diff: 'Distinta de «{{slug}}»: se creará un sitio aparte junto a él.',
        publish_dry: 'Prueba en seco',
        publish_dry_busy: 'prueba en seco en curso...',
        publish_dry_ok: 'Prueba correcta: {{pages}} página(s), {{diagrams}} diagrama(s).',
        publish_go: 'Poner en línea',
        publish_go_busy: 'puesta en línea en curso...',
        publish_confirm: '¿Publicar «{{title}}» en la dirección {{slug}}? La generación anterior pasa a versions/.',
        publish_done: 'En línea: {{url}}',
        publish_failed: 'Rechazado: {{message}}',
        publish_unsaved: 'Guardado en curso — la prueba cubre el estado guardado del cuaderno.',
        publish_target: 'Dirección prevista: {{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: 'instantánea {{sha}}',
        publish_warnings: 'Advertencias ({{n}})',
        publish_long_notice: 'La renderización puede tardar varios minutos: se rehacen páginas, diagramas, libros de Excel y miniaturas. Deje esta pestaña abierta.',
        publish_elapsed: '{{seconds}} s',
        publish_phase: 'etapa: {{phase}}',
        publish_cut: 'Conexión interrumpida ({{message}}). Es probable que la renderización continúe en el servidor: no la reinicie ni cierre esta pestaña. Vuelva a abrir este panel en unos minutos para ver el resultado.',
        publish_busy: 'Ya hay una publicación en curso para esta dirección: es la que se sigue aquí.',
        publish_lost: 'La renderización ya no da señales de vida — probablemente el servidor se reinició. Nada quedó a medias en línea: vuelva a lanzar la publicación.',
        publish_duration: 'Duración: {{seconds}} s',
        publish_slowest: 'fase más larga: {{phase}} ({{seconds}} s)',
        // sa#502 — crear y eliminar un libro, los dos últimos gestos que solo
        // existían en la administración. El grupo de trabajo sigue la regla del
        // servidor (default_group_id): el cliente nunca lo adivina.
        create_workbook: 'libro',
        create_workbook_hint: 'Crear un libro vacío',
        create_workbook_placeholder: 'Título del libro',
        create_workbook_submit: 'Crear',
        create_workbook_error: 'No se ha podido crear el libro',
        delete_workbook: 'Eliminar este libro',
        confirm_delete_workbook: '¿Eliminar el libro «{{title}}»? La acción es irreversible. Los bloques anclados no se tocan: siguen en la biblioteca, y un sitio ya publicado sigue en línea.',
        delete_workbook_error: 'No se ha podido eliminar el libro'
      },
    }
  },
  //=======================================================
  //DE
  //=======================================================
  de: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz erforderlich',
        gallery_hint: 'Klicken Sie auf eine Vorlage, um mit einem Beispiel zu starten',
        sankeytheque_hint: 'Klicken Sie auf eine Studie, um sie zu öffnen',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: 'Veröffentlichte Studien: Klicken Sie auf eine Studie, um ihre Diagramme zu durchsuchen, dann auf ein Diagramm, um es in einem neuen Blatt zu öffnen',
          loading: 'Bibliothek wird geladen…',
          empty: 'Noch keine veröffentlichte Studie',
          back: 'Alle Studien',
          open_study: 'Diese Studie öffnen',
          diagrams: '{{count}} Diagramm(e)',
          versions: 'Veröffentlichte Versionen'
        },
        pin: 'Galerie anheften (die Zeichnung wird links davon neu angepasst, Vorlagen nacheinander ausprobieren)',
        unpin: 'Galerie lösen (schwebt über der Zeichnung, schließt sich, sobald Sie arbeiten)',
        play: 'Galerie abspielen (lädt jedes Modell nacheinander)',
        pause: 'Diashow pausieren',
        prev: 'Vorheriges Modell',
        next: 'Nächstes Modell',
        group_validated: 'Validierte Studie (auf der Website veröffentlicht)',
        published_link: 'Das veröffentlichte Diagramm online ansehen',
        publication: {
          online: 'Online veröffentlicht',
          open: 'Die veröffentlichte Seite öffnen',
          load: 'In die Anwendung laden',
          version_load: 'Diese Version laden',
          version_open: 'Diese Version online öffnen',
          history: 'vollständiger Verlauf (Entwickler)',
          history_error: 'Verlauf nicht verfügbar',
          history_empty: 'Noch keine erfasste Version'
        },
        group_readme_open: 'Beschreibung lesen',
        group_readme_close: 'Beschreibung ausblenden',
        group_readme_error: 'Beschreibung nicht verfügbar',
        library_hint: 'Ihre versionierten Projekte: Klicken Sie auf ein Diagramm, um es zu öffnen, auf ein README, um es zu lesen',
        library: {
          read_md: 'Dieses Dokument lesen',
          edit_md: 'Dieses Dokument bearbeiten (legt eine neue Version an)',
          new_readme: 'Ein README erstellen (neue Version des Projekts)',
          download: 'Diese Datei herunterladen',
          versions_error: 'Versionen nicht verfügbar'
        },
        fr: 'Diagrammvorlage auf Französisch',
        en: 'Diagrammvorlage auf Englisch',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Karten',
          web: 'Klassiker aus dem Web',
          other_formats: 'Andere Formate',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'Meine Projekte',
          // Kategorien der Sankey-Bibliothek (MFAData-Index)
          etudes: 'Studien',
          filieres: 'Branchen',
          recherche: 'Forschung',
          clients: 'Kunden'
        }
      },
      // sa#414 — Panel „Explorer" (Projekte + Arbeitsmappen des Kontos)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Explorer',
        tooltip: 'Durchsuchen Sie Ihre Projekte und Arbeitsmappen; ein Diagramm öffnet sich in einem neuen Blatt',
        hint: 'Ihre Projekte und Arbeitsmappen: Klicken Sie auf ein Diagramm, um es in einem neuen Blatt zu öffnen',
        workbooks: 'Arbeitsmappen',
        projects_empty: 'Noch kein Projekt in Ihrer Bibliothek',
        workbooks_empty: 'Noch keine Arbeitsmappe',
        workbook_error: 'Arbeitsmappe nicht verfügbar',
        open_sheet: 'In einem neuen Blatt öffnen',
        add_section: 'Abschnitt',
        add_page: 'Seite',
        add_slot: 'Diagramm',
        section_default: 'Neuer Abschnitt',
        page_default: 'Neue Seite',
        delete_node: 'Entfernen',
        move_up: 'Nach oben',
        move_down: 'Nach unten',
        rename_hint: 'Doppelklicken zum Umbenennen',
        confirm_delete: 'Dieses Element und alles darunter entfernen?',
        save_error: 'Arbeitsmappe konnte nicht gespeichert werden',
        slot_file: 'Datei wählen...',
        slot_add: 'Anheften',
        slot_cancel: 'Abbrechen',
        group_root: 'Dokumente des Ordners',
        search_placeholder: 'Projekte filtern...',
        search_no_match: 'Kein Projekt entspricht der Suche',
        menu_entry: 'Aus meiner Bibliothek...',
        delete_project: 'Dieses Projekt löschen',
        confirm_delete_project: 'Projekt „{{title}}“ und ALLE seine Versionen löschen? Der Vorgang ist unwiderruflich.',
        delete_project_error: 'Projekt konnte nicht gelöscht werden',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: 'Einstellungen',
        settings_no_slot: 'Heften Sie zuerst ein Diagramm an: die Dateien stammen aus seinem Projekt',
        settings_loading: 'Projektdateien werden geladen...',
        settings_header: 'Angezeigter Titel',
        settings_header_auto: 'Seitentitel',
        settings_header_custom: 'Eigener Titel',
        settings_header_none: 'Keine Kopfzeile',
        settings_header_placeholder: 'In der oberen Leiste angezeigter Titel',
        settings_logo: 'Logo',
        settings_logo_width: 'Logobreite',
        settings_footer: 'Fußzeile',
        settings_footer_on: 'Angezeigt',
        settings_footer_off: 'Ausgeblendet',
        settings_doc: 'Dokument',
        settings_doc_auto: 'Automatisch',
        settings_doc_none: 'Keines angekündigt',
        settings_excel: 'Excel-Arbeitsmappe',
        settings_excel_locked: 'Als Arbeitsmappe der Seite bestimmt: immer veröffentlicht',
        settings_downloads: 'Downloads',
        settings_downloads_all: 'Alle Dateien des Ordners',
        settings_downloads_some: 'Ausgewählte Dateien',
        settings_downloads_empty: 'Keine Excel-Datei im Diagrammordner',
        settings_none: 'Keines',
        settings_default: 'Standard',
        settings_custom: 'Anderer Pfad...',
        settings_custom_hint: 'pfad/im/projekt.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'Layout',
        section_flat: 'Einordnung',
        section_flat_folder: 'Ein eigener Ordner',
        section_flat_group: 'Eine Gruppe auf der Startseite',
        section_flat_hint: 'Ohne Ordner wird der Titel des Abschnitts zur Zwischenüberschrift der Startseite und seine Seiten bleiben auf der ersten Ebene',
        section_flat_no_title: 'Ohne Titel bildet der Abschnitt keine Gruppe: die Website zeigt keine Zwischenüberschrift.',
        section_thumbnail: 'Vorschaubild',
        section_thumbnail_hint: 'pfad/in/einem/projekt.png',
        section_thumbnail_orphan: 'Bild in den angehefteten Projekten nicht vorhanden: unverändert beibehalten.',
        section_thumbnail_no_slot: 'Heften Sie zuerst ein Diagramm an eine Seite: die Bilder stammen aus den Projekten des Abschnitts',
        section_thumbnail_none: 'Kein Bild in den von den Seiten angehefteten Projekten',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'Text',
        doc_site: 'Startseitentext der Website',
        doc_node: 'Text',
        doc_lang_default: 'Standard',
        doc_filled: 'Im Arbeitsbuch geschriebener Text',
        doc_missing: 'Kein Text: die README des angehefteten Projekts wird übernommen',
        doc_none_hint: 'Kein Text: die Startseite zeigt die README des angehefteten Projekts.',
        doc_untranslated: 'Ohne Text behalten diese Sprachen den des Projekts: {{langs}}',
        doc_lang_dead: 'Nie ausgeliefert: Französisch ist die Standardsprache, schreiben Sie ihn unter „Standard“.',
        doc_language: 'Sprache',
        doc_panel_label: 'Editor für den Text des Arbeitsbuchs',
        doc_placeholder: '# Titel\n\nStartseitentext, in Markdown...',
        doc_hint: 'Der Text des Arbeitsbuchs hat Vorrang vor der README des Projekts, Sprache für Sprache.',
        doc_fallback_hint: 'Eine Sprache ohne Text behält den des angehefteten Projekts.',
        doc_default_first: 'Beginnen Sie mit der Standardsprache: die anderen greifen darauf zurück.',
        doc_discard: 'Den begonnenen Text verwerfen?',
        doc_saved: 'Text gespeichert',
        doc_cleared: 'Text entfernt: diese Sprache fällt auf das angeheftete Projekt zurück',
        doc_close: 'Schließen',
        doc_save: 'Speichern',
        // sa#495
        views_start: 'Startansicht',
        views_start_hint: 'die Ansicht, mit der die veröffentlichte Seite öffnet',
        views_all: 'Alle Ansichten',
        views_group_views: 'Ansichten des Diagramms',
        views_group_labels: 'Ansichts-Labels',
        views_mode_view: 'Eine bestimmte Ansicht',
        views_mode_label: 'Die Ansichten eines Labels',
        views_value_placeholder: 'Ansichts-ID oder Label',
        views_loading: 'Ansichten des Diagramms werden gelesen...',
        views_error: 'Diagramm nicht lesbar: freie Eingabe',
        views_empty: 'Dieses Diagramm enthält keine Ansicht: freie Eingabe',
        views_unknown: 'Dieser Wert gehört nicht zu den Ansichten des Diagramms; er bleibt unverändert',
        views_runtime_warning: 'Die veröffentlichte Laufzeit ignoriert Ansichtsoptionen: die Auswahl wird vermerkt, aber nicht angewendet',
        views_not_first: 'Beim Rendern wird nur die Auswahl des ersten Platzes der Seite angewendet',
        add_files: 'Dateien hinzufügen',
        add_files_hint: 'Dateien zu diesem Projekt hinzufügen (erzeugt eine neue Version)',
        add_files_in: 'Dateien in „{{folder}}“ hinzufügen',
        drop_hint: 'Ordner oder Dateien hierher ziehen',
        deposit_confirm: '{{count}} Datei(en) zum Projekt „{{title}}“ hinzufügen? Es wird eine neue Version (v{{number}}) erstellt: Versionen sind unveränderlich.',
        deposit_running: 'Wird in die Bibliothek abgelegt...',
        deposit_done: 'v{{number}} erstellt — {{count}} Datei(en) hinzugefügt',
        deposit_unchanged: 'Identisch mit v{{number}}: nichts Neues zu versionieren',
        deposit_error: 'Ablegen fehlgeschlagen',
        deposit_refused: {
          empty: 'Keine Datei zum Ablegen.',
          gz: 'Komprimierte Datei abgelehnt: „{{name}}“. Ein Projekt trägt nur unkomprimiertes JSON — bitte vor dem Ablegen entpacken.',
          too_many: 'Zu viele Dateien auf einmal ({{count}}, maximal 200).',
          too_big: 'Datei zu groß: „{{name}}“ (maximal 100 MB).',
          bad_path: 'Ungültiger Dateipfad: „{{name}}“.'
        },
        // sa#490 — Veröffentlichungsstand der Mappe, in ihrer Zeile
        publish_none: 'noch nicht veröffentlicht',
        publish_rendered: 'erzeugt am {{date}}',
        publish_stale: 'seitdem geändert',
        publish_open: 'Veröffentlichte Seite öffnen',
        // sa#491 — eine Mappe aus dem Explorer veröffentlichen: zuerst der
        // Trockenlauf, dann die Onlinestellung. Die Adresse ist vorbelegt.
        publish_action: 'Veröffentlichen',
        publish_close: 'Schließen',
        publish_address: 'Online-Adresse',
        publish_address_change: 'Ändern',
        publish_address_computed: 'nie veröffentlicht — Adresse aus dem Titel abgeleitet',
        publish_address_diff: 'Anders als „{{slug}}“: daneben entsteht eine eigene Website.',
        publish_dry: 'Trockenlauf',
        publish_dry_busy: 'Trockenlauf läuft...',
        publish_dry_ok: 'Trockenlauf bestanden: {{pages}} Seite(n), {{diagrams}} Diagramm(e).',
        publish_go: 'Online stellen',
        publish_go_busy: 'Onlinestellung läuft...',
        publish_confirm: '„{{title}}“ unter der Adresse {{slug}} veröffentlichen? Die vorherige Ausgabe wandert nach versions/.',
        publish_done: 'Online: {{url}}',
        publish_failed: 'Abgelehnt: {{message}}',
        publish_unsaved: 'Speichern läuft — der Trockenlauf betrifft den gespeicherten Stand der Mappe.',
        publish_target: 'Zieladresse: {{url}}',
        publish_runtime: 'Runtime {{key}}',
        publish_snapshot: 'Momentaufnahme {{sha}}',
        publish_warnings: 'Warnungen ({{n}})',
        publish_long_notice: 'Das Rendern kann mehrere Minuten dauern: Seiten, Diagramme, Excel-Mappen und Vorschaubilder werden neu erzeugt. Lassen Sie diesen Tab offen.',
        publish_elapsed: '{{seconds}} s',
        publish_phase: 'Schritt: {{phase}}',
        publish_cut: 'Verbindung abgebrochen ({{message}}). Das Rendern läuft auf dem Server sehr wahrscheinlich weiter: nicht erneut starten und diesen Tab nicht schließen. Öffnen Sie diesen Bereich in einigen Minuten erneut, um das Ergebnis zu sehen.',
        publish_busy: 'Für diese Adresse läuft bereits eine Veröffentlichung: ihr wird hier gefolgt.',
        publish_lost: 'Das Rendern meldet sich nicht mehr — der Server wurde vermutlich neu gestartet. Es ist nichts halb online geblieben: Veröffentlichung erneut starten.',
        publish_duration: 'Dauer: {{seconds}} s',
        publish_slowest: 'längste Phase: {{phase}} ({{seconds}} s)',
        // sa#502 — eine Arbeitsmappe ANLEGEN und LÖSCHEN, die beiden letzten
        // Gesten, die es nur in der Verwaltung gab. Die Arbeitsgruppe folgt der
        // Serverregel (default_group_id): der Client rät sie nie.
        create_workbook: 'Arbeitsmappe',
        create_workbook_hint: 'Eine leere Arbeitsmappe anlegen',
        create_workbook_placeholder: 'Titel der Arbeitsmappe',
        create_workbook_submit: 'Anlegen',
        create_workbook_error: 'Arbeitsmappe konnte nicht angelegt werden',
        delete_workbook: 'Diese Arbeitsmappe löschen',
        confirm_delete_workbook: 'Arbeitsmappe „{{title}}“ löschen? Der Vorgang ist unwiderruflich. Die angehefteten Bausteine bleiben unberührt: Sie bleiben in der Bibliothek, und eine bereits veröffentlichte Website bleibt online.',
        delete_workbook_error: 'Arbeitsmappe konnte nicht gelöscht werden'
      },
    }
  },
  //=======================================================
  //IT
  //=======================================================
  it: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz necessario',
        gallery_hint: 'Clicca su un modello per partire da un esempio',
        sankeytheque_hint: 'Clicca su uno studio per aprirlo',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: 'Studi pubblicati: clicca su uno studio per sfogliarne i diagrammi, poi su un diagramma per aprirlo in un nuovo foglio',
          loading: 'Caricamento della biblioteca…',
          empty: 'Nessuno studio pubblicato per ora',
          back: 'Tutti gli studi',
          open_study: 'Apri questo studio',
          diagrams: '{{count}} diagramma/i',
          versions: 'Versioni pubblicate'
        },
        pin: 'Fissa la galleria (il disegno si ridimensiona alla sua sinistra, prova i modelli uno dopo l\'altro)',
        unpin: 'Sgancia la galleria (fluttua sopra il disegno, si chiude appena inizi a lavorare)',
        play: 'Avvia la galleria (carica ogni modello uno dopo l\'altro)',
        pause: 'Metti in pausa la presentazione',
        prev: 'Modello precedente',
        next: 'Modello successivo',
        group_validated: 'Studio validato (pubblicato sul sito)',
        published_link: 'Vedi il diagramma pubblicato online',
        publication: {
          online: 'Pubblicato online',
          open: 'Apri la pagina pubblicata',
          load: 'Carica nell\'applicazione',
          version_load: 'Carica questa versione',
          version_open: 'Apri questa versione online',
          history: 'cronologia completa (sviluppatore)',
          history_error: 'Cronologia non disponibile',
          history_empty: 'Nessuna versione registrata per ora'
        },
        group_readme_open: 'Leggi la presentazione',
        group_readme_close: 'Nascondi la presentazione',
        group_readme_error: 'Descrizione non disponibile',
        library_hint: 'I tuoi progetti versionati: clicca su un diagramma per aprirlo, su un README per leggerlo',
        library: {
          read_md: 'Leggi questo documento',
          edit_md: 'Modifica questo documento (deposita una nuova versione)',
          new_readme: 'Crea un README (nuova versione del progetto)',
          download: 'Scarica questo file',
          versions_error: 'Versioni non disponibili'
        },
        fr: 'Modello di diagramma in francese',
        en: 'Modello di diagramma in inglese',
        categories: {
          opensankey: 'OpenSankey',
          maps: 'Mappe',
          web: 'Classici del web',
          other_formats: 'Altri formati',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'SankeyThèque',
          library: 'I miei progetti',
          // Categorie della sankeyteca (indice MFAData)
          etudes: 'Studi',
          filieres: 'Filiere',
          recherche: 'Ricerca',
          clients: 'Clienti'
        }
      },
      // sa#414 — pannello « Esplora » (progetti + cartelle di lavoro dell'account)
      explorer: {
        theque: 'SankeyThèque',
        title: 'Esplora',
        tooltip: 'Sfoglia i tuoi progetti e le cartelle di lavoro; un diagramma si apre in un nuovo foglio',
        hint: 'I tuoi progetti e le tue cartelle di lavoro: clicca su un diagramma per aprirlo in un nuovo foglio',
        workbooks: 'Cartelle di lavoro',
        projects_empty: 'Nessun progetto nella tua biblioteca per ora',
        workbooks_empty: 'Nessuna cartella di lavoro per ora',
        workbook_error: 'Cartella di lavoro non disponibile',
        open_sheet: 'Apri in un nuovo foglio',
        add_section: 'sezione',
        add_page: 'pagina',
        add_slot: 'diagramma',
        section_default: 'Nuova sezione',
        page_default: 'Nuova pagina',
        delete_node: 'Rimuovi',
        move_up: 'Sposta su',
        move_down: 'Sposta giù',
        rename_hint: 'Doppio clic per rinominare',
        confirm_delete: 'Rimuovere questo elemento e tutto ciò che contiene?',
        save_error: 'Impossibile salvare la cartella di lavoro',
        slot_file: 'Scegli un file...',
        slot_add: 'Aggancia',
        slot_cancel: 'Annulla',
        group_root: 'Documenti della cartella',
        search_placeholder: 'Filtra i progetti...',
        search_no_match: 'Nessun progetto corrisponde',
        menu_entry: 'Dalla mia libreria...',
        delete_project: 'Elimina questo progetto',
        confirm_delete_project: 'Eliminare il progetto «{{title}}» e TUTTE le sue versioni? L’azione è irreversibile.',
        delete_project_error: 'Impossibile eliminare il progetto',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: 'impostazioni',
        settings_no_slot: 'Aggancia prima un diagramma: i file provengono dal suo progetto',
        settings_loading: 'Caricamento dei file del progetto...',
        settings_header: 'Titolo mostrato',
        settings_header_auto: 'Titolo della pagina',
        settings_header_custom: 'Titolo scelto',
        settings_header_none: 'Nessuna intestazione',
        settings_header_placeholder: 'Titolo mostrato nella barra superiore',
        settings_logo: 'Logo',
        settings_logo_width: 'Larghezza del logo',
        settings_footer: 'Piè di pagina',
        settings_footer_on: 'Mostrato',
        settings_footer_off: 'Nascosto',
        settings_doc: 'Documento',
        settings_doc_auto: 'Automatico',
        settings_doc_none: 'Nessuno annunciato',
        settings_excel: 'Cartella Excel',
        settings_excel_locked: 'Designata come cartella della pagina: sempre pubblicata',
        settings_downloads: 'Download',
        settings_downloads_all: 'Tutti i file della cartella',
        settings_downloads_some: 'File scelti',
        settings_downloads_empty: 'Nessun file Excel nella cartella del diagramma',
        settings_none: 'Nessuno',
        settings_default: 'Predefinito',
        settings_custom: 'Altro percorso...',
        settings_custom_hint: 'percorso/nel/progetto.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'impaginazione',
        section_flat: 'Collocazione',
        section_flat_folder: 'Una cartella a sé',
        section_flat_group: 'Un gruppo nella pagina iniziale',
        section_flat_hint: 'Senza cartella, il titolo della sezione diventa un sottotitolo della pagina iniziale e le sue pagine restano al primo livello',
        section_flat_no_title: 'Senza titolo la sezione non forma un gruppo: il sito non mostrerà alcun sottotitolo.',
        section_thumbnail: 'Miniatura',
        section_thumbnail_hint: 'percorso/in/un/progetto.png',
        section_thumbnail_orphan: 'Immagine assente dai progetti agganciati: conservata com\'è.',
        section_thumbnail_no_slot: 'Aggancia prima un diagramma in una pagina: le immagini vengono dai progetti della sezione',
        section_thumbnail_none: 'Nessuna immagine nei progetti agganciati dalle pagine',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'testo',
        doc_site: 'Testo di apertura del sito',
        doc_node: 'Testo',
        doc_lang_default: 'Predefinita',
        doc_filled: 'Testo scritto nella cartella',
        doc_missing: 'Nessun testo: viene ripreso il README del progetto agganciato',
        doc_none_hint: 'Nessun testo: la pagina iniziale mostrerà il README del progetto agganciato.',
        doc_untranslated: 'Senza testo, queste lingue conservano quello del progetto: {{langs}}',
        doc_lang_dead: 'Variante mai servita: il francese è la lingua predefinita, scrivetelo sotto «Predefinita».',
        doc_language: 'Lingua',
        doc_panel_label: 'Editor del testo della cartella',
        doc_placeholder: '# Titolo\n\nTesto di apertura, in markdown...',
        doc_hint: 'Il testo della cartella prevale sul README del progetto, lingua per lingua.',
        doc_fallback_hint: 'Una lingua senza testo conserva quello del progetto agganciato.',
        doc_default_first: 'Iniziate dalla lingua predefinita: le altre vi fanno riferimento.',
        doc_discard: 'Abbandonare il testo in corso?',
        doc_saved: 'Testo salvato',
        doc_cleared: 'Testo rimosso: questa lingua torna al progetto agganciato',
        doc_close: 'Chiudi',
        doc_save: 'Salva',
        // sa#495
        views_start: 'Vista iniziale',
        views_start_hint: 'la vista con cui si apre la pagina pubblicata',
        views_all: 'Tutte le viste',
        views_group_views: 'Viste del diagramma',
        views_group_labels: 'Etichette di viste',
        views_mode_view: 'Una vista precisa',
        views_mode_label: 'Le viste di un\'etichetta',
        views_value_placeholder: 'id di vista o etichetta',
        views_loading: 'Lettura delle viste del diagramma...',
        views_error: 'Diagramma illeggibile: inserimento libero',
        views_empty: 'Questo diagramma non contiene alcuna vista: inserimento libero',
        views_unknown: 'Questo valore non è tra le viste del diagramma; viene conservato così com\'è',
        views_runtime_warning: 'Il runtime pubblicato ignora le opzioni di viste: la selezione sarà registrata, non applicata',
        views_not_first: 'Al rendering si applica solo la selezione del primo slot della pagina',
        add_files: 'Aggiungi file',
        add_files_hint: 'Aggiungere file a questo progetto (crea una nuova versione)',
        add_files_in: 'Aggiungere file in «{{folder}}»',
        drop_hint: 'Trascina qui una cartella o dei file',
        deposit_confirm: 'Aggiungere {{count}} file al progetto «{{title}}»? Verrà creata una nuova versione (v{{number}}): le versioni sono immutabili.',
        deposit_running: 'Deposito nella biblioteca...',
        deposit_done: 'v{{number}} creata — {{count}} file aggiunti',
        deposit_unchanged: 'Identico alla v{{number}}: nulla di nuovo da versionare',
        deposit_error: 'Deposito non riuscito',
        deposit_refused: {
          empty: 'Nessun file da depositare.',
          gz: 'File compresso rifiutato: «{{name}}». Un progetto contiene solo JSON non compresso — decomprimerlo prima di depositarlo.',
          too_many: 'Troppi file in una volta ({{count}}, massimo 200).',
          too_big: 'File troppo pesante: «{{name}}» (massimo 100 MB).',
          bad_path: 'Percorso di file non valido: «{{name}}».'
        },
        // sa#490 — stato di pubblicazione della cartella, sulla sua riga
        publish_none: 'non ancora pubblicato',
        publish_rendered: 'generato il {{date}}',
        publish_stale: 'modificato da allora',
        publish_open: 'Apri la pagina pubblicata',
        // sa#491 — pubblicare una cartella dall'esploratore: prima la prova a
        // vuoto, poi la messa in linea. L'indirizzo è precompilato.
        publish_action: 'Pubblica',
        publish_close: 'Chiudi',
        publish_address: 'Indirizzo in linea',
        publish_address_change: 'Cambia',
        publish_address_computed: 'mai pubblicato — indirizzo derivato dal titolo',
        publish_address_diff: 'Diverso da «{{slug}}»: verrà creato un sito distinto accanto.',
        publish_dry: 'Prova a vuoto',
        publish_dry_busy: 'prova a vuoto in corso...',
        publish_dry_ok: 'Prova superata: {{pages}} pagina/e, {{diagrams}} diagramma/i.',
        publish_go: 'Metti in linea',
        publish_go_busy: 'messa in linea in corso...',
        publish_confirm: 'Pubblicare «{{title}}» all’indirizzo {{slug}}? La resa precedente passa in versions/.',
        publish_done: 'In linea: {{url}}',
        publish_failed: 'Rifiutato: {{message}}',
        publish_unsaved: 'Salvataggio in corso — la prova riguarda lo stato salvato della cartella.',
        publish_target: 'Indirizzo previsto: {{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: 'istantanea {{sha}}',
        publish_warnings: 'Avvisi ({{n}})',
        publish_long_notice: 'Il rendering può richiedere diversi minuti: pagine, diagrammi, cartelle Excel e miniature vengono rifatti. Lasci aperta questa scheda.',
        publish_elapsed: '{{seconds}} s',
        publish_phase: 'fase: {{phase}}',
        publish_cut: 'Connessione interrotta ({{message}}). Il rendering probabilmente prosegue sul server: non rilanciarlo e non chiudere questa scheda. Riapra questo pannello tra qualche minuto per vedere il risultato.',
        publish_busy: 'Una pubblicazione è già in corso per questo indirizzo: è quella seguita qui.',
        publish_lost: 'Il rendering non dà più segni di vita — probabilmente il server è stato riavviato. Nulla è rimasto a metà in linea: rilanci la pubblicazione.',
        publish_duration: 'Durata: {{seconds}} s',
        publish_slowest: 'fase più lunga: {{phase}} ({{seconds}} s)',
        // sa#502 — creare ed eliminare una cartella di lavoro, gli ultimi due
        // gesti che vivevano solo nell'amministrazione. Il gruppo di lavoro
        // segue la regola del server (default_group_id): il client non la
        // indovina mai.
        create_workbook: 'cartella',
        create_workbook_hint: 'Creare una cartella di lavoro vuota',
        create_workbook_placeholder: 'Titolo della cartella di lavoro',
        create_workbook_submit: 'Crea',
        create_workbook_error: 'Impossibile creare la cartella di lavoro',
        delete_workbook: 'Elimina questa cartella di lavoro',
        confirm_delete_workbook: 'Eliminare la cartella di lavoro «{{title}}»? L’azione è irreversibile. I mattoni appuntati non vengono toccati: restano nella biblioteca e un sito già pubblicato resta online.',
        delete_workbook_error: 'Impossibile eliminare la cartella di lavoro'
      },
    }
  },
  'zh-CN': {
    translation: {
      templates: {
        need_osp: '需要 MFASankey Dataviz',
        gallery_hint: '点击某个模板即可从示例开始',
        sankeytheque_hint: '点击某项研究即可打开',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: '已发布的研究：点击某项研究浏览其图表，再点击图表在新工作表中打开',
          loading: '正在加载图库…',
          empty: '暂无已发布的研究',
          back: '全部研究',
          open_study: '打开此研究',
          diagrams: '{{count}} 个图表',
          versions: '已发布版本'
        },
        pin: '固定图库（绘图区在其左侧调整大小，可逐个试用模板）',
        unpin: '取消固定图库（浮于绘图之上，一开始操作即关闭）',
        play: '播放图库（逐个加载各个模型）',
        pause: '暂停幻灯片',
        prev: '上一个模型',
        next: '下一个模型',
        group_validated: '已验证的研究（已在网站发布）',
        published_link: '在线查看已发布的图表',
        publication: {
          online: '已在线发布',
          open: '打开已发布页面',
          load: '加载到应用中',
          version_load: '加载此版本',
          version_open: '在线打开此版本',
          history: '完整历史（开发者）',
          history_error: '历史不可用',
          history_empty: '暂无记录的版本'
        },
        group_readme_open: '阅读介绍',
        group_readme_close: '隐藏介绍',
        group_readme_error: '描述不可用',
        library_hint: '您的版本化项目：点击图表打开，点击 README 阅读',
        library: {
          read_md: '阅读此文档',
          edit_md: '编辑此文档（提交新版本）',
          new_readme: '创建 README（项目新版本）',
          download: '下载此文件',
          versions_error: '版本不可用'
        },
        fr: '法语图表模板',
        en: '英语图表模板',
        categories: {
          opensankey: 'OpenSankey',
          maps: '地图',
          web: '网络经典案例',
          other_formats: '其他格式',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: '桑基图库',
          library: '我的项目',
          // Catégories de la sankeythèque (index MFAData)
          etudes: '研究',
          filieres: '部门',
          recherche: '科研',
          clients: '客户'
        }
      },
      // sa#414 — « 资源管理器 » 面板（账户的项目 + 工作簿）
      explorer: {
        theque: 'SankeyThèque',
        title: '资源管理器',
        tooltip: '浏览您的项目和工作簿；图表会在新工作表中打开',
        hint: '您的项目和工作簿：点击图表即可在新工作表中打开',
        workbooks: '工作簿',
        projects_empty: '您的库中还没有项目',
        workbooks_empty: '还没有工作簿',
        workbook_error: '工作簿不可用',
        open_sheet: '在新工作表中打开',
        add_section: '章节',
        add_page: '页面',
        add_slot: '图表',
        section_default: '新章节',
        page_default: '新页面',
        delete_node: '移除',
        move_up: '上移',
        move_down: '下移',
        rename_hint: '双击重命名',
        confirm_delete: '移除此项及其全部内容？',
        save_error: '无法保存工作簿',
        slot_file: '选择文件...',
        slot_add: '固定',
        slot_cancel: '取消',
        group_root: '文件夹文档',
        search_placeholder: '筛选项目…',
        search_no_match: '没有匹配的项目',
        menu_entry: '从我的库中打开…',
        delete_project: '删除此项目',
        confirm_delete_project: '删除项目“{{title}}”及其所有版本？此操作不可撤销。',
        delete_project_error: '无法删除项目',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: '设置',
        settings_no_slot: '请先固定一个图表：文件来自其项目',
        settings_loading: '正在加载项目文件…',
        settings_header: '显示标题',
        settings_header_auto: '页面标题',
        settings_header_custom: '自定义标题',
        settings_header_none: '无页眉',
        settings_header_placeholder: '顶栏显示的标题',
        settings_logo: '标识',
        settings_logo_width: '标识宽度',
        settings_footer: '页脚',
        settings_footer_on: '显示',
        settings_footer_off: '隐藏',
        settings_doc: '文档',
        settings_doc_auto: '自动',
        settings_doc_none: '不提供',
        settings_excel: 'Excel 工作簿',
        settings_excel_locked: '已指定为本页工作簿：始终发布',
        settings_downloads: '下载文件',
        settings_downloads_all: '文件夹中的全部文件',
        settings_downloads_some: '所选文件',
        settings_downloads_empty: '图表文件夹中没有 Excel 文件',
        settings_none: '无',
        settings_default: '默认',
        settings_custom: '其他路径…',
        settings_custom_hint: '项目/中的/路径.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: '版式',
        section_flat: '归置',
        section_flat_folder: '单独的文件夹',
        section_flat_group: '首页上的一个分组',
        section_flat_hint: '不建文件夹时，章节标题成为首页的小标题，其页面保留在第一层',
        section_flat_no_title: '没有标题就不成组：站点不会显示任何小标题。',
        section_thumbnail: '缩略图',
        section_thumbnail_hint: '项目/中的/路径.png',
        section_thumbnail_orphan: '该图片不在已固定的项目中：原样保留。',
        section_thumbnail_no_slot: '请先在某个页面固定一个图表：图片来自本章节的项目',
        section_thumbnail_none: '页面固定的项目中没有图片',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: '文本',
        doc_site: '站点首页文本',
        doc_node: '文本',
        doc_lang_default: '默认',
        doc_filled: '已在工作簿中撰写',
        doc_missing: '无文本：将沿用所钉项目的 README',
        doc_none_hint: '无文本：首页将显示所钉项目的 README。',
        doc_untranslated: '没有文本时，这些语言保留项目的内容：{{langs}}',
        doc_lang_dead: '永不使用的变体：法语是默认语言，请写在“默认”下。',
        doc_language: '语言',
        doc_panel_label: '工作簿文本编辑器',
        doc_placeholder: '# 标题\n\n首页文本，markdown 格式...',
        doc_hint: '工作簿文本逐语言优先于项目的 README。',
        doc_fallback_hint: '没有文本的语言保留所钉项目的内容。',
        doc_default_first: '请先写默认语言：其他语言以它为后备。',
        doc_discard: '放弃正在输入的文本？',
        doc_saved: '文本已保存',
        doc_cleared: '文本已删除：该语言回到所钉项目',
        doc_close: '关闭',
        doc_save: '保存',
        // sa#495
        views_start: '起始视图',
        views_start_hint: '发布页面打开时显示的视图',
        views_all: '全部视图',
        views_group_views: '图表视图',
        views_group_labels: '视图标签',
        views_mode_view: '指定某个视图',
        views_mode_label: '某个标签的视图',
        views_value_placeholder: '视图 id 或标签',
        views_loading: '正在读取图表视图...',
        views_error: '图表无法读取：可手动输入',
        views_empty: '该图表没有任何视图：可手动输入',
        views_unknown: '该值不在图表的视图中，将原样保留',
        views_runtime_warning: '发布运行时不支持视图选项：该选择会被记录但不会生效',
        views_not_first: '渲染时仅应用页面第一个位置的选择',
        add_files: '添加文件',
        add_files_hint: '向该项目添加文件（将创建一个新版本）',
        add_files_in: '在“{{folder}}”中添加文件',
        drop_hint: '将文件夹或文件拖放到此处',
        deposit_confirm: '向项目“{{title}}”添加 {{count}} 个文件？将创建新版本（v{{number}}）：版本不可修改。',
        deposit_running: '正在存入资料库...',
        deposit_done: '已创建 v{{number}} — 添加了 {{count}} 个文件',
        deposit_unchanged: '与 v{{number}} 相同：没有新内容需要版本化',
        deposit_error: '存入失败',
        deposit_refused: {
          empty: '没有要存入的文件。',
          gz: '拒绝压缩文件：“{{name}}”。项目只接受未压缩的 JSON — 请先解压再存入。',
          too_many: '一次提交的文件过多（{{count}}，最多 200 个）。',
          too_big: '文件过大：“{{name}}”（最大 100 MB）。',
          bad_path: '文件路径无效：“{{name}}”。'
        },
        // sa#490 — 工作簿的发布状态，显示在其行上
        publish_none: '尚未发布',
        publish_rendered: '生成于 {{date}}',
        publish_stale: '此后已修改',
        publish_open: '打开已发布页面',
        // sa#491 — 从资源管理器发布工作簿：先试运行，再上线。地址已预填。
        publish_action: '发布',
        publish_close: '关闭',
        publish_address: '在线地址',
        publish_address_change: '更改',
        publish_address_computed: '尚未发布 — 地址由标题推导',
        publish_address_diff: '与“{{slug}}”不同：将在其旁新建一个独立站点。',
        publish_dry: '试运行',
        publish_dry_busy: '正在试运行…',
        publish_dry_ok: '试运行通过：{{pages}} 个页面，{{diagrams}} 个图表。',
        publish_go: '上线',
        publish_go_busy: '正在上线…',
        publish_confirm: '将“{{title}}”发布到地址 {{slug}}？先前的生成结果将移入 versions/。',
        publish_done: '已上线：{{url}}',
        publish_failed: '被拒绝：{{message}}',
        publish_unsaved: '正在保存 — 试运行针对工作簿已保存的状态。',
        publish_target: '目标地址：{{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: '快照 {{sha}}',
        publish_warnings: '警告（{{n}}）',
        publish_long_notice: '渲染可能需要数分钟：页面、图表、Excel 工作簿和缩略图都会重新生成。请保持此标签页打开。',
        publish_elapsed: '{{seconds}} 秒',
        publish_phase: '阶段：{{phase}}',
        publish_cut: '连接已中断（{{message}}）。渲染很可能仍在服务器上继续：请勿重新发起，也不要关闭此标签页。几分钟后重新打开此面板即可查看结果。',
        publish_busy: '该地址已有一个发布正在进行：此处跟踪的正是它。',
        publish_lost: '渲染已无响应 — 服务器很可能已重启。没有任何内容半途上线：请重新发起发布。',
        publish_duration: '耗时：{{seconds}} 秒',
        publish_slowest: '最长阶段：{{phase}}（{{seconds}} 秒）',
        // sa#502 — 新建和删除工作簿，这是仅存于管理后台的最后两个操作。
        // 工作组遵循服务端规则（default_group_id）：客户端从不猜测。
        create_workbook: '工作簿',
        create_workbook_hint: '新建一个空工作簿',
        create_workbook_placeholder: '工作簿标题',
        create_workbook_submit: '创建',
        create_workbook_error: '无法创建工作簿',
        delete_workbook: '删除此工作簿',
        confirm_delete_workbook: '删除工作簿“{{title}}”？此操作不可撤销。已固定的构件不受影响：它们仍留在资料库中，已发布的站点也仍然在线。',
        delete_workbook_error: '无法删除工作簿'
      },
    }
  },
  ja: {
    translation: {
      templates: {
        need_osp: 'MFASankey Dataviz が必要です',
        gallery_hint: 'テンプレートをクリックすると、その例から始められます',
        sankeytheque_hint: '研究事例をクリックすると開きます',
        // sa#509 — panneau SankeyThèque à vignettes
        theque: {
          hint: '公開済みの研究事例：研究をクリックして図を一覧し、図をクリックすると新しいシートで開きます',
          loading: 'ライブラリを読み込み中…',
          empty: '公開済みの研究事例はまだありません',
          back: 'すべての研究事例',
          open_study: 'この研究事例を開く',
          diagrams: '{{count}} 件の図',
          versions: '公開済みバージョン'
        },
        pin: 'ギャラリーを固定（描画エリアはその左側でサイズ調整され、テンプレートを次々と試せます）',
        unpin: 'ギャラリーの固定を解除（描画の上に浮かび、作業を始めると閉じます）',
        play: 'ギャラリーを再生（各モデルを順に読み込みます）',
        pause: 'スライドショーを一時停止',
        prev: '前のモデル',
        next: '次のモデル',
        group_validated: '検証済みの研究事例（ウェブサイトで公開）',
        published_link: '公開された図をオンラインで見る',
        publication: {
          online: 'オンラインで公開中',
          open: '公開ページを開く',
          load: 'アプリに読み込む',
          version_load: 'このバージョンを読み込む',
          version_open: 'このバージョンをオンラインで開く',
          history: '完全な履歴（開発者）',
          history_error: '履歴を取得できません',
          history_empty: '記録されたバージョンはまだありません'
        },
        group_readme_open: '紹介を読む',
        group_readme_close: '紹介を隠す',
        group_readme_error: '説明を取得できません',
        library_hint: 'バージョン管理されたプロジェクト：図をクリックすると開き、README をクリックすると読めます',
        library: {
          read_md: 'このドキュメントを読む',
          edit_md: 'このドキュメントを編集（新しいバージョンを登録）',
          new_readme: 'README を作成（プロジェクトの新バージョン）',
          download: 'このファイルをダウンロード',
          versions_error: 'バージョンを取得できません'
        },
        fr: 'フランス語の図テンプレート',
        en: '英語の図テンプレート',
        categories: {
          opensankey: 'OpenSankey',
          maps: '地図',
          web: 'ウェブの定番例',
          other_formats: 'その他の形式',
          sankeymatic: 'SankeyMATIC',
          stan: 'STAN',
          esankey: 'e!Sankey',
          sankeytheque: 'サンキーライブラリ',
          library: 'マイプロジェクト',
          // Catégories de la sankeythèque (index MFAData)
          etudes: '研究事例',
          filieres: '部門',
          recherche: '研究',
          clients: '顧客'
        }
      },
      // sa#414 — « エクスプローラー » パネル（アカウントのプロジェクト + ワークブック）
      explorer: {
        theque: 'SankeyThèque',
        title: 'エクスプローラー',
        tooltip: 'プロジェクトとワークブックを閲覧できます。図は新しいシートで開きます',
        hint: 'プロジェクトとワークブック：図をクリックすると新しいシートで開きます',
        workbooks: 'ワークブック',
        projects_empty: 'ライブラリにはまだプロジェクトがありません',
        workbooks_empty: 'まだワークブックがありません',
        workbook_error: 'ワークブックを取得できません',
        open_sheet: '新しいシートで開く',
        add_section: 'セクション',
        add_page: 'ページ',
        add_slot: '図',
        section_default: '新しいセクション',
        page_default: '新しいページ',
        delete_node: '削除',
        move_up: '上へ移動',
        move_down: '下へ移動',
        rename_hint: 'ダブルクリックで名前を変更',
        confirm_delete: 'この項目とその配下をすべて削除しますか？',
        save_error: 'ワークブックを保存できませんでした',
        slot_file: 'ファイルを選択...',
        slot_add: 'ピン留め',
        slot_cancel: 'キャンセル',
        group_root: 'フォルダの文書',
        search_placeholder: 'プロジェクトを絞り込む…',
        search_no_match: '一致するプロジェクトはありません',
        menu_entry: 'ライブラリから開く…',
        delete_project: 'このプロジェクトを削除',
        confirm_delete_project: 'プロジェクト「{{title}}」とそのすべてのバージョンを削除しますか？この操作は取り消せません。',
        delete_project_error: 'プロジェクトを削除できませんでした',
        // sa#492 — réglages de viewer d'une PAGE, saisis en champs nommés sous
        // sa ligne : logo et fichiers CHOISIS dans la brique épinglée, la
        // saisie libre n'étant qu'un repli.
        settings_toggle: '設定',
        settings_no_slot: 'まず図をピン留めしてください。ファイルはそのプロジェクトから取得されます',
        settings_loading: 'プロジェクトのファイルを読み込み中…',
        settings_header: '表示タイトル',
        settings_header_auto: 'ページのタイトル',
        settings_header_custom: '任意のタイトル',
        settings_header_none: 'ヘッダーなし',
        settings_header_placeholder: '上部バーに表示されるタイトル',
        settings_logo: 'ロゴ',
        settings_logo_width: 'ロゴの幅',
        settings_footer: 'フッター',
        settings_footer_on: '表示',
        settings_footer_off: '非表示',
        settings_doc: 'ドキュメント',
        settings_doc_auto: '自動',
        settings_doc_none: '知らせない',
        settings_excel: 'Excel ブック',
        settings_excel_locked: 'ページのブックに指定済み：常に公開されます',
        settings_downloads: 'ダウンロード',
        settings_downloads_all: 'フォルダー内のすべてのファイル',
        settings_downloads_some: '選んだファイル',
        settings_downloads_empty: '図のフォルダーに Excel ファイルがありません',
        settings_none: 'なし',
        settings_default: '既定',
        settings_custom: '別のパス…',
        settings_custom_hint: 'プロジェクト内/のパス.png',
        // sa#500 — mise en page d'une SECTION : « sans dossier » (sa#433) et
        // vignette, les deux derniers réglages qui n'existaient que dans
        // l'administration. La vignette se CHOISIT dans les briques épinglées
        // par les PAGES de la section — une section n'a pas d'emplacement à
        // elle — la saisie libre restant un repli.
        section_toggle: 'レイアウト',
        section_flat: '配置',
        section_flat_folder: '独立したフォルダ',
        section_flat_group: 'ホームのグループ',
        section_flat_hint: 'フォルダを作らない場合、セクション名はホームの見出しになり、ページは第一階層に残ります',
        section_flat_no_title: 'タイトルがないとグループになりません：サイトに見出しは表示されません。',
        section_thumbnail: 'サムネイル',
        section_thumbnail_hint: 'プロジェクト内/のパス.png',
        section_thumbnail_orphan: 'ピン留めしたプロジェクトにない画像です：そのまま保持します。',
        section_thumbnail_no_slot: 'まずページに図をピン留めしてください：画像はセクションのプロジェクトから取得します',
        section_thumbnail_none: 'ページがピン留めしたプロジェクトに画像がありません',
        // sa#493 — TEXTES du site et des pages, écrits dans le classeur
        // (workbooks.doc, workbook_nodes.doc) : une pastille par langue dans
        // l'explorateur, l'édition dans l'éditeur markdown déjà là. Une langue
        // que le classeur ne dit pas garde le README du projet épinglé.
        doc_toggle: 'テキスト',
        doc_site: 'サイトのトップテキスト',
        doc_node: 'テキスト',
        doc_lang_default: '既定',
        doc_filled: 'ワークブックに記述済み',
        doc_missing: 'テキストなし：ピン留めしたプロジェクトの README を使用',
        doc_none_hint: 'テキストなし：トップページはピン留めしたプロジェクトの README を表示します。',
        doc_untranslated: 'テキストがない言語はプロジェクトのものを保ちます：{{langs}}',
        doc_lang_dead: '配信されない変種：フランス語が既定言語です。「既定」に記述してください。',
        doc_language: '言語',
        doc_panel_label: 'ワークブックのテキストエディタ',
        doc_placeholder: '# タイトル\n\nトップテキスト（markdown）...',
        doc_hint: 'ワークブックのテキストは言語ごとにプロジェクトの README より優先します。',
        doc_fallback_hint: 'テキストのない言語はピン留めしたプロジェクトのものを保ちます。',
        doc_default_first: 'まず既定言語から：他の言語はそれを参照します。',
        doc_discard: '入力中のテキストを破棄しますか？',
        doc_saved: 'テキストを保存しました',
        doc_cleared: 'テキストを削除：この言語はプロジェクトに戻ります',
        doc_close: '閉じる',
        doc_save: '保存',
        // sa#495
        views_start: '開始ビュー',
        views_start_hint: '公開ページを開いたときに表示するビュー',
        views_all: 'すべてのビュー',
        views_group_views: 'ダイアグラムのビュー',
        views_group_labels: 'ビューのラベル',
        views_mode_view: '特定のビュー',
        views_mode_label: 'ラベルのビュー',
        views_value_placeholder: 'ビュー ID またはラベル',
        views_loading: 'ダイアグラムのビューを読み込み中...',
        views_error: 'ダイアグラムを読み取れません：自由入力',
        views_empty: 'このダイアグラムにはビューがありません：自由入力',
        views_unknown: 'この値はダイアグラムのビューにありません。そのまま保持されます',
        views_runtime_warning: '公開ランタイムはビューオプションに対応していません：選択は記録されますが適用されません',
        views_not_first: 'レンダリング時に適用されるのはページ最初の枠の選択のみです',
        add_files: 'ファイルを追加',
        add_files_hint: 'このプロジェクトにファイルを追加します（新しいバージョンが作成されます）',
        add_files_in: '「{{folder}}」にファイルを追加',
        drop_hint: 'フォルダーまたはファイルをここにドロップ',
        deposit_confirm: 'プロジェクト「{{title}}」に {{count}} 個のファイルを追加しますか？新しいバージョン（v{{number}}）が作成されます：バージョンは変更できません。',
        deposit_running: 'ライブラリに保存しています...',
        deposit_done: 'v{{number}} を作成しました — {{count}} 個のファイルを追加',
        deposit_unchanged: 'v{{number}} と同一です：新しく記録するものはありません',
        deposit_error: '保存に失敗しました',
        deposit_refused: {
          empty: '保存するファイルがありません。',
          gz: '圧縮ファイルは受け付けません：「{{name}}」。プロジェクトは非圧縮の JSON のみを扱います — 展開してから保存してください。',
          too_many: '一度に扱えるファイル数を超えています（{{count}}、最大 200）。',
          too_big: 'ファイルが大きすぎます：「{{name}}」（最大 100 MB）。',
          bad_path: 'ファイルパスが不正です：「{{name}}」。'
        },
        // sa#490 — ワークブックの公開状態を行に表示
        publish_none: 'まだ公開されていません',
        publish_rendered: '{{date}} に生成',
        publish_stale: 'それ以降に変更あり',
        publish_open: '公開ページを開く',
        // sa#491 — エクスプローラーからワークブックを公開：まず試行、次に公開。
        // アドレスはあらかじめ入力されている。
        publish_action: '公開',
        publish_close: '閉じる',
        publish_address: '公開アドレス',
        publish_address_change: '変更',
        publish_address_computed: '未公開 — タイトルから算出したアドレス',
        publish_address_diff: '「{{slug}}」とは異なります：隣に別のサイトが作成されます。',
        publish_dry: '試行',
        publish_dry_busy: '試行中…',
        publish_dry_ok: '試行成功：{{pages}} ページ、{{diagrams}} 個の図。',
        publish_go: '公開する',
        publish_go_busy: '公開中…',
        publish_confirm: '「{{title}}」をアドレス {{slug}} に公開しますか？以前の生成結果は versions/ に移ります。',
        publish_done: '公開済み：{{url}}',
        publish_failed: '拒否されました：{{message}}',
        publish_unsaved: '保存中 — 試行はワークブックの保存済みの状態を対象とします。',
        publish_target: '対象アドレス：{{url}}',
        publish_runtime: 'runtime {{key}}',
        publish_snapshot: 'スナップショット {{sha}}',
        publish_warnings: '警告（{{n}}）',
        publish_long_notice: 'レンダリングには数分かかることがあります。ページ、図、Excel ブック、サムネイルがすべて再生成されます。このタブは開いたままにしてください。',
        publish_elapsed: '{{seconds}} 秒',
        publish_phase: '段階：{{phase}}',
        publish_cut: '接続が切断されました（{{message}}）。レンダリングはサーバー側で続いている可能性が高いため、再実行せず、このタブも閉じないでください。数分後にこのパネルを開き直すと結果を確認できます。',
        publish_busy: 'このアドレスでは既に公開処理が進行中です。ここではそれを追跡しています。',
        publish_lost: 'レンダリングが応答しなくなりました。サーバーが再起動した可能性があります。中途半端に公開されたものはありません。公開をやり直してください。',
        publish_duration: '所要時間：{{seconds}} 秒',
        publish_slowest: '最長の段階：{{phase}}（{{seconds}} 秒）',
        // sa#502 — ワークブックの作成と削除。管理画面にしかなかった最後の
        // 二つの操作。ワークグループはサーバーの規則（default_group_id）に
        // 従い、クライアントは決して推測しない。
        create_workbook: 'ワークブック',
        create_workbook_hint: '空のワークブックを作成',
        create_workbook_placeholder: 'ワークブックの名称',
        create_workbook_submit: '作成',
        create_workbook_error: 'ワークブックを作成できませんでした',
        delete_workbook: 'このワークブックを削除',
        confirm_delete_workbook: 'ワークブック「{{title}}」を削除しますか？この操作は取り消せません。ピン留めされた部品はそのままライブラリに残り、公開済みのサイトもオンラインのままです。',
        delete_workbook_error: 'ワークブックを削除できませんでした'
      },
    }
  }
}
