// ==================================================================================================
// The MIT License (MIT) - Copyright (c) 2025 TerriFlux
// ==================================================================================================
// Traductions du tableur Univer (grande zone « Tableur ») : barre d'outils, sélecteurs, modale
// « Ajouter une contrainte », panneau de documentation, noms d'onglets et en-têtes de colonnes du
// classeur. Clé racine i18next : `Spreadsheet`.
// Le classeur (UniverSankeyData) lit ces clés via i18next.t ; les composants React via useTranslation.
// ==================================================================================================

export const resources_spreadsheet = {
  //=======================================================
  // EN
  //=======================================================
  en: {
    translation: {
      Spreadsheet: {
        json: {
          help: 'Native JSON of the diagram, as written when saving (read-only).',
          other: 'Other',
          refresh: 'Reload from diagram',
          copy: 'Copy',
          copied: 'Copied',
        },
        text: {
          title: 'SankeyMATIC editor',
          help: 'One flow per line: "source [value] target" (SankeyMATIC) or 3 columns "source ; target ; value".',
          apply: 'Apply',
          refresh: 'Reload from diagram',
          clear: 'Clear',
          clear_tooltip: 'Empty the editor before pasting a SankeyMATIC diagram, so no leftover setting applies to it.',
          applied: 'Diagram updated',
          error: 'Error',
          flows_recognized: 'flows recognized',
          lines_ignored: 'lines ignored',
          layout: 'Layout:',
          layout_native: 'SankeyMATIC',
          layout_auto: 'Auto',
        },
        sheet: {
          flux: 'Flows',
          analysis: 'Results analysis',
          nodes: 'Nodes',
          nodes_agg: 'Nodes by aggregation',
          tags: 'Tags',
          stock: 'Stocks',
          ratio: 'Flow ratio',
          ratio_stock: 'Stock-flow ratio',
          stock_chaining: 'Stock chaining',
          products: 'Products',
          sectors: 'Sectors',
          exchanges: 'Exchanges',
          tes: 'IOT (IO matrix)',
          ter: 'SUT (supply-use)'
        },
        // --- En-têtes de colonnes ---
        header: {
          level: 'Level',
          level_n: 'Level {{n}}',
          name: 'Name',
          balance: 'Balance',
          balance_io: 'Input-output balance',
          color: 'Color',
          definitions: 'Definitions',
          column_u: 'Column u',
          row_v: 'Row v',
          origin: 'Origin',
          destination: 'Destination',
          value: 'Value',
          min: 'Min',
          max: 'Max',
          computed_value: 'Computed value',
          dest_value: 'Destination value',
          natural_quantity: 'Natural quantity',
          uncertainty_pct: 'Uncertainty %',
          source: 'Source',
          hypothesis: 'Hypothesis',
          computed_min: 'Computed min',
          computed_max: 'Computed max',
          delta_recon: 'Reconciled - unreconciled delta',
          gap_sigma: 'Reconciled gap (σ count)',
          variable_type: 'Variable type',
          node: 'Node',
          stock: 'Stock',
          computed_stock: 'Computed stock',
          delta_stock: 'Δ Stock',
          computed_delta: 'Computed Δ',
          coef: 'Coef',
          origin_ref: 'Origin ref',
          dest_ref: 'Destination ref',
          tag: 'Tag',
          tag_ref: 'Tag ref',
          translation: 'Translation',
          delta_stock_plain: 'Delta stock',
          dimension: 'Dimension',
          tags: 'Tags',
          tag_group_name: 'Tag group name',
          tag_type: 'Tag type',
          colors: 'Colors',
          // En-têtes de matrice
          origin_dest: 'Origin ╲ Destination',
          resources: 'Resources',
          uses: 'Uses'
        },
        // --- Types d'étiquette (colonne Type de l'onglet Etiquettes) ---
        tagtype: {
          node: 'Node',
          level: 'Level',
          flux: 'Flow',
          data: 'Data'
        },
        // --- Classification du type de variable (onglet Analyse) ---
        classif: {
          measured: 'Measured',
          free_interval: 'Free (interval)',
          determined: 'Determined'
        },
        // --- Barre d'outils ---
        toolbar: {
          add_constraint: '+ Constraint',
          add_constraint_tip: 'Create a constraint (flow, stock, node total…) via a guided form',
          parser: 'Parse',
          parser_tip: 'Builds the aggregation hierarchy from the Level column',
          filter: 'Filter',
          filter_tip: 'Toggles column filters (Excel-style) on this sheet',
          columns: 'Columns',
          columns_count: 'Columns ({{shown}}/{{total}})',
          sheets: 'Sheets',
          sheets_count: 'Sheets ({{shown}}/{{total}})',
          search: 'Search',
          select_all: '(Select all)',
          show_all: 'Show all',
          only_visible: 'Visible only',
          display_filter_tip: 'Row display filter for the spreadsheet',
          placement_auto: 'Placement: auto',
          placement_none: 'Placement: none',
          placement_increment: 'Placement: incremental',
          placement_tip: 'How to position a node created by adding a flow: auto (full layout), none (default position), incremental (guesses the spot without moving others)',
          matrix_cross: 'Matrix: cross',
          matrix_value: 'Matrix: value',
          matrix_tip: 'Matrix cell content: cross (the flow exists) or flow value for the selected data_type',
          // os#1405 — la barre s'est vidée : ces clés servent la section du panneau de
          // navigation (panel_title, rows) et le volet de réglages (matrix_label).
          matrix_label: 'Matrix display',
          panel_title: 'Spreadsheet',
          rows: 'Rows'
        },
        // --- Modale « Ajouter une contrainte » ---
        constraint: {
          title: 'Add a constraint',
          term1: 'Term 1',
          term2_ref: 'Term 2 (reference)',
          type_flux: 'Flow',
          type_node_total: 'Node (total)',
          type_stock: 'Stock',
          type_delta_stock: 'Δ stock',
          in: 'inbound',
          out: 'outbound',
          node: 'Node',
          origin: 'Origin',
          destination: 'Destination',
          search: 'Search…',
          no_node: 'No node',
          coef: 'coef',
          translation_label: 'Translation (auto, editable)',
          translation_ph: 'Natural language description',
          regenerate: 'regenerate',
          invalid_combo: 'Invalid term combination.',
          cancel: 'Cancel',
          add: 'Add',
          desc_flux: 'flow {{orig}}→{{dest}}',
          desc_node_in: 'total inbound of {{node}}',
          desc_node_out: 'total outbound of {{node}}',
          desc_stock: 'stock of {{node}}',
          desc_delta: 'Δ stock of {{node}}'
        },
        // --- Panneau de documentation ---
        doc: {
          title: 'Documentation',
          window_title: 'OpenSankey — Documentation',
          pos_sheet_right: 'Right of the spreadsheet',
          pos_sheet_left: 'Left of the spreadsheet',
          pos_sheet_top: 'Above the spreadsheet',
          pos_sheet_bottom: 'Below the spreadsheet',
          pos_diagram_bottom: 'Below the diagram',
          pos_window_bottom: 'Bottom bar',
          pos_right: 'Right',
          pos_left: 'Left',
          pos_top: 'Above',
          pos_bottom: 'Below',
          with_sheet: 'With the spreadsheet',
          under_diagram: 'Below the diagram',
          window_bottom_full: 'Bottom bar (full width)',
          insert: 'Insert',
          insert_image: 'An image…',
          insert_views_outline: 'Title + link for each view',
          insert_view_link: 'Link to a view',
          mode_edit: 'Edit',
          mode_split: 'Side by side',
          mode_preview: 'Preview',
          back_to_diagram_doc: 'Back to the diagram documentation',
          reattach: 'Reattach the documentation into the main window',
          detach: 'Detach the documentation into a separate window',
          editor_placeholder: 'Write this diagram\'s documentation in markdown…\n\n# Title\n\n- point 1\n- point 2'
        },
        // --- Boutons bascule de la grande zone (MenuTop) ---
        zone: {
          diagram: 'Diagram',
          spreadsheet: 'Spreadsheet',
          json: 'JSON',
          doc: 'Doc',
          documentation: 'Documentation',
          unitary: 'Unitary Sankey',
          unit: 'Unit.',
          infos: 'Info',
          move_right: 'Move to the right column',
          move_bottom: 'Move to the bottom band',
          make_main: 'Make it the main pane',
          dock_as_pane: 'Dock as a pane',
          make_floating: 'Make it floating',
          close: 'Close',
          main_window: 'Main pane',
          // Le nom COURT de la fenêtre principale, pour le bouton de la barre du haut : celui-ci
          // écrit la nature puis le nom de la fenêtre ACTIVE, et « Fenêtre principale » en toutes
          // lettres y prendrait à lui seul la place des deux.
          main_window_short: 'Main',
          // Infobulle du bouton unique : le texte long y nomme la fenêtre visée et sa nature (le
          // bouton, lui, tronque), et cette phrase annonce les deux gestes que le menu réunit.
          active_window_menu: 'Change this pane representation, or open a new one',
          new_window: 'New pane',
          on_diagram: 'On the diagram',
          on_selection: 'On the selected element',
          follow: 'Follows the selection',
          pin: 'Pin to this element',
          unpin: 'Follow the selection again',
          no_selection: 'Select a node or a flow',
          no_representation: 'No representation for this element',
          node: 'Node',
          link: 'Flow',
          // os#1420 — le TROISIÈME sujet d'une fenêtre : épinglée à un CRITÈRE (les nœuds portant
          // une étiquette) plutôt qu'à des identifiants. `tag` est le mot du fil d'Ariane
          // (« Étiquette › Importations (4) »), au même titre que `node` et `link` ; `pin_to_tag`
          // nomme le geste, `pin_to_tag_none` l'entrée vide de son sélecteur.
          tag: 'Tag',
          add_subject: 'Add a node or a flow',
          pin_subject: 'Look at a node or a flow',
          pin_to_tag: 'Pin to a tag',
          pin_to_tag_none: 'Choose a tag',
          // os#1421 lot 5 — POSER une figure réglée dans cette fenêtre SUR le nœud du diagramme :
          // le nœud dessine alors cette figure, et la rerégler ici change le nœud (un LIEN, pas
          // une copie). Un nœud n'en porte qu'une : poser sur un nœud qui en porte déjà une autre
          // la remplace, et le libellé reste « Poser » — c'est bien ce que l'auteur demande.
          // `unplace_from_node` est le même bouton quand c'est CETTE figure qui est posée.
          place_on_node: 'Place on the node',
          unplace_from_node: 'Remove from the node',
          remove_subject: 'Remove',
          pin_all: 'Pin the selected elements',
          value_mode: 'Values',
          normalize_on: 'Normalize on',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: 'Diagram representation',
          // os#1386 — une fenêtre peut regarder une AUTRE feuille du document, en lecture.
          // `subject_sheet` nomme le choix (liste déroulante de la barre des sujets, montrée
          // seulement si le document a plusieurs feuilles) ; `sheet_gone` est ce que dit une
          // fenêtre restée épinglée sur une feuille supprimée — elle le DIT, elle ne casse rien.
          subject_sheet: 'Sheet of the subject',
          sheet_gone: 'This sheet no longer exists',
          // os#1389 lot 1 — LE PONT entre la barre d'onglets de feuilles (en bas) et les
          // fenêtres de la grande zone. `open_sheet_in_window` est le geste, au clic droit sur
          // un onglet ; `sheet_window` nomme ce qui s'ouvre (titre de la fenêtre, et libellé de
          // la pastille qui marque un onglet déjà regardé ailleurs) ; `make_sheet_active` est le
          // retour — rapatrier cette feuille dans l'onglet, là où on édite ; `sheet_read_only`
          // dit POURQUOI la fenêtre ne se laisse pas modifier, sans quoi elle passerait pour
          // cassée : une seule feuille est vivante à la fois, c'est celle de l'onglet.
          sheet_window: 'Sheet in a pane',
          make_sheet_active: 'Make this sheet the active one',
          sheet_read_only: 'Read-only — editing happens in the tab',
          open_sheet_in_window: 'Open in a new pane',
          sheet_already_windowed: 'This sheet is already open in another pane',
          // os#1385 (lot 5, D9) — a sheet carries a TYPED document. `no_canvas_for_type` is what
          // a canvas window says when its sheet is of a type that has no canvas (a workbook) ;
          // `no_default_window` is what the gesture says when a sheet has nothing to open at all
          // (an empty workbook, a type this version does not know).
          no_canvas_for_type: 'No canvas for this kind of document',
          no_default_window: 'Nothing to show for this sheet',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'This pane has nothing to show here',
          unknown_representation: 'Pane nature unknown to this version',
          orphan_hint: 'Change its nature, or close it'
        }
      }
    }
  },
  //=======================================================
  // FR
  //=======================================================
  fr: {
    translation: {
      Spreadsheet: {
        json: {
          help: 'JSON natif du diagramme, tel qu\'écrit à l\'enregistrement (lecture seule).',
          other: 'Autres',
          refresh: 'Recharger depuis le diagramme',
          copy: 'Copier',
          copied: 'Copié',
        },
        text: {
          title: 'Éditeur SankeyMATIC',
          help: 'Un flux par ligne : « source [valeur] cible » (SankeyMATIC) ou 3 colonnes « source ; cible ; valeur ».',
          apply: 'Appliquer',
          refresh: 'Recharger depuis le diagramme',
          clear: 'Vider',
          clear_tooltip: 'Videz l\'éditeur avant de coller un diagramme SankeyMATIC, pour qu\'aucun réglage résiduel ne s\'y applique.',
          applied: 'Diagramme mis à jour',
          error: 'Erreur',
          flows_recognized: 'flux reconnus',
          lines_ignored: 'lignes ignorées',
          layout: 'Disposition :',
          layout_native: 'SankeyMATIC',
          layout_auto: 'Auto',
        },
        sheet: {
          flux: 'Flux',
          analysis: 'Analyse des résultats',
          nodes: 'Noeuds',
          nodes_agg: 'Noeuds par agrégation',
          tags: 'Etiquettes',
          stock: 'Stocks',
          ratio: 'Ratio flux',
          ratio_stock: 'Ratio stock flux',
          stock_chaining: 'Chaînage stock',
          products: 'Produits',
          sectors: 'Secteurs',
          exchanges: 'Echanges',
          tes: 'TES (matrice IO)',
          ter: 'TER (emplois-ressources)'
        },
        header: {
          level: 'Niveau',
          level_n: 'Niveau {{n}}',
          name: 'Nom',
          balance: 'Equilibre',
          balance_io: 'Equilibre entrée-sortie',
          color: 'Couleur',
          definitions: 'Définitions',
          column_u: 'Colonne u',
          row_v: 'Ligne v',
          origin: 'Origine',
          destination: 'Destination',
          value: 'Valeur',
          min: 'Min',
          max: 'Max',
          computed_value: 'Valeur calculée',
          dest_value: 'Valeur destination',
          natural_quantity: 'Quantité naturelle',
          uncertainty_pct: 'Incertitude %',
          source: 'Source',
          hypothesis: 'Hypothèse',
          computed_min: 'Min calculée',
          computed_max: 'Max calculée',
          delta_recon: 'Delta réconcilié - non-réconcilié',
          gap_sigma: 'Écart réconcilié (nb σ)',
          variable_type: 'Type de variable',
          node: 'Nœud',
          stock: 'Stock',
          computed_stock: 'Stock calculé',
          delta_stock: 'Δ Stock',
          computed_delta: 'Δ calculée',
          coef: 'Coef',
          origin_ref: 'Origine réf',
          dest_ref: 'Destination réf',
          tag: 'Étiquette',
          tag_ref: 'Étiquette réf',
          translation: 'Traduction',
          delta_stock_plain: 'Delta stock',
          dimension: 'Dimension',
          tags: 'Etiquettes',
          tag_group_name: 'Nom du groupe d\'étiquette',
          tag_type: 'Type d\'étiquette',
          colors: 'Couleurs',
          origin_dest: 'Origine ╲ Destination',
          resources: 'Ressources',
          uses: 'Emplois'
        },
        tagtype: {
          node: 'Noeud',
          level: 'Niveau',
          flux: 'Flux',
          data: 'Donnée'
        },
        classif: {
          measured: 'Mesurée',
          free_interval: 'Libre (intervalle)',
          determined: 'Déterminée'
        },
        toolbar: {
          add_constraint: '+ Contrainte',
          add_constraint_tip: 'Créer une contrainte (flux, stock, total de nœud…) via un formulaire guidé',
          parser: 'Parser',
          parser_tip: 'Construit la hiérarchie d\'agrégation depuis la colonne Niveau',
          filter: 'Filtrer',
          filter_tip: 'Active/désactive les filtres de colonne (style Excel) sur cet onglet',
          columns: 'Colonnes',
          columns_count: 'Colonnes ({{shown}}/{{total}})',
          sheets: 'Onglets',
          sheets_count: 'Onglets ({{shown}}/{{total}})',
          search: 'Rechercher',
          select_all: '(Tout sélectionner)',
          show_all: 'Tout afficher',
          only_visible: 'Visibles uniquement',
          display_filter_tip: 'Filtre d\'affichage des lignes du tableur',
          placement_auto: 'Placement : auto',
          placement_none: 'Placement : aucun',
          placement_increment: 'Placement : incrémental',
          placement_tip: 'Comment positionner un nœud créé en ajoutant un flux : auto (disposition complète), aucun (position par défaut), incrémental (devine la place sans bouger les autres)',
          matrix_cross: 'Matrice : croix',
          matrix_value: 'Matrice : valeur',
          matrix_tip: 'Contenu des cellules de la matrice : croix (le flux existe) ou valeur du flux pour le data_type sélectionné',
          matrix_label: 'Affichage des matrices',
          panel_title: 'Tableur',
          rows: 'Lignes'
        },
        constraint: {
          title: 'Ajouter une contrainte',
          term1: 'Terme 1',
          term2_ref: 'Terme 2 (référence)',
          type_flux: 'Flux',
          type_node_total: 'Nœud (total)',
          type_stock: 'Stock',
          type_delta_stock: 'Δ stock',
          in: 'entrants',
          out: 'sortants',
          node: 'Nœud',
          origin: 'Origine',
          destination: 'Destination',
          search: 'Rechercher…',
          no_node: 'Aucun nœud',
          coef: 'coef',
          translation_label: 'Traduction (auto, modifiable)',
          translation_ph: 'Description en langage naturel',
          regenerate: 'régénérer',
          invalid_combo: 'Combinaison de termes non valide.',
          cancel: 'Annuler',
          add: 'Ajouter',
          desc_flux: 'flux {{orig}}→{{dest}}',
          desc_node_in: 'total des entrants de {{node}}',
          desc_node_out: 'total des sortants de {{node}}',
          desc_stock: 'stock de {{node}}',
          desc_delta: 'Δ stock de {{node}}'
        },
        doc: {
          title: 'Documentation',
          window_title: 'OpenSankey — Documentation',
          pos_sheet_right: 'À droite du tableur',
          pos_sheet_left: 'À gauche du tableur',
          pos_sheet_top: 'Au-dessus du tableur',
          pos_sheet_bottom: 'En-dessous du tableur',
          pos_diagram_bottom: 'Sous le diagramme',
          pos_window_bottom: 'Bandeau bas',
          pos_right: 'À droite',
          pos_left: 'À gauche',
          pos_top: 'Au-dessus',
          pos_bottom: 'En-dessous',
          with_sheet: 'Avec le tableur',
          under_diagram: 'Sous le diagramme',
          window_bottom_full: 'Bandeau bas (pleine largeur)',
          insert: 'Insérer',
          insert_image: 'Une image…',
          insert_views_outline: 'Titre + lien pour chaque vue',
          insert_view_link: 'Lien vers une vue',
          mode_edit: 'Édition',
          mode_split: 'Côte à côte',
          mode_preview: 'Aperçu',
          back_to_diagram_doc: 'Revenir à la documentation du diagramme',
          reattach: 'Ré-attacher la documentation dans la fenêtre principale',
          detach: 'Détacher la documentation dans une fenêtre séparée',
          editor_placeholder: 'Rédigez la documentation de ce diagramme en markdown…\n\n# Titre\n\n- point 1\n- point 2'
        },
        zone: {
          diagram: 'Diagramme',
          spreadsheet: 'Tableur',
          json: 'JSON',
          doc: 'Doc',
          documentation: 'Documentation',
          unitary: 'Sankey unitaire',
          unit: 'Unit.',
          infos: 'Infos',
          move_right: 'Passer dans la colonne de droite',
          move_bottom: 'Passer dans le bandeau du bas',
          make_main: 'En faire le volet principal',
          dock_as_pane: 'Ancrer en volet',
          make_floating: 'Faire flotter',
          close: 'Fermer',
          main_window: 'Volet principal',
          main_window_short: 'Principal',
          active_window_menu: 'Changer la représentation de ce volet, ou en ouvrir un nouveau',
          new_window: 'Nouveau volet',
          on_diagram: 'Sur le diagramme',
          on_selection: 'Sur l’élément sélectionné',
          follow: 'Suit la sélection',
          pin: 'Épingler sur cet élément',
          unpin: 'Suivre à nouveau la sélection',
          no_selection: 'Sélectionnez un nœud ou un flux',
          no_representation: 'Aucune représentation pour cet élément',
          node: 'Nœud',
          link: 'Flux',
          tag: 'Étiquette',
          add_subject: 'Ajouter un nœud ou un flux',
          pin_subject: 'Regarder un nœud ou un flux',
          pin_to_tag: 'Épingler à une étiquette',
          pin_to_tag_none: 'Choisir une étiquette',
          place_on_node: 'Poser sur le nœud',
          unplace_from_node: 'Retirer du nœud',
          remove_subject: 'Retirer',
          pin_all: 'Épingler les éléments sélectionnés',
          value_mode: 'Valeurs',
          normalize_on: 'Normaliser sur',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: 'Représentation du diagramme',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: 'Feuille du sujet',
          sheet_gone: 'Cette feuille n\'existe plus',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés.
          sheet_window: 'Feuille dans un volet',
          make_sheet_active: 'Rendre cette feuille active',
          sheet_read_only: 'Lecture seule — c\'est l\'onglet qui édite',
          open_sheet_in_window: 'Ouvrir dans un nouveau volet',
          sheet_already_windowed: 'Cette feuille est déjà ouverte dans un autre volet',
          no_canvas_for_type: 'Pas de canevas pour ce type de document',
          no_default_window: 'Rien à montrer pour cette feuille',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'Ce volet n\'a pas de contenu à montrer ici',
          unknown_representation: 'Nature de volet inconnue de cette version',
          orphan_hint: 'Changez sa nature, ou fermez-le'
        }
      }
    }
  },
  //=======================================================
  // ES
  //=======================================================
  es: {
    translation: {
      Spreadsheet: {
        json: {
          help: 'JSON nativo del diagrama, tal como se escribe al guardar (solo lectura).',
          other: 'Otros',
          refresh: 'Recargar desde el diagrama',
          copy: 'Copiar',
          copied: 'Copiado',
        },
        text: {
          title: 'Editor SankeyMATIC',
          help: 'Un flujo por línea: «origen [valor] destino» (SankeyMATIC) o 3 columnas «origen ; destino ; valor».',
          apply: 'Aplicar',
          refresh: 'Recargar desde el diagrama',
          clear: 'Vaciar',
          clear_tooltip: 'Vacíe el editor antes de pegar un diagrama SankeyMATIC, para que ningún ajuste residual se le aplique.',
          applied: 'Diagrama actualizado',
          error: 'Error',
          flows_recognized: 'flujos reconocidos',
          lines_ignored: 'líneas ignoradas',
          layout: 'Disposición:',
          layout_native: 'SankeyMATIC',
          layout_auto: 'Auto',
        },
        sheet: {
          flux: 'Flujos',
          analysis: 'Análisis de resultados',
          nodes: 'Nodos',
          nodes_agg: 'Nodos por agregación',
          tags: 'Etiquetas',
          stock: 'Existencias',
          ratio: 'Ratio de flujo',
          ratio_stock: 'Ratio existencia-flujo',
          stock_chaining: 'Encadenamiento de existencias',
          products: 'Productos',
          sectors: 'Sectores',
          exchanges: 'Intercambios',
          tes: 'TIO (matriz IO)',
          ter: 'TOR (empleos-recursos)'
        },
        header: {
          level: 'Nivel',
          level_n: 'Nivel {{n}}',
          name: 'Nombre',
          balance: 'Equilibrio',
          balance_io: 'Equilibrio entrada-salida',
          color: 'Color',
          definitions: 'Definiciones',
          column_u: 'Columna u',
          row_v: 'Fila v',
          origin: 'Origen',
          destination: 'Destino',
          value: 'Valor',
          min: 'Mín',
          max: 'Máx',
          computed_value: 'Valor calculado',
          dest_value: 'Valor destino',
          natural_quantity: 'Cantidad natural',
          uncertainty_pct: 'Incertidumbre %',
          source: 'Fuente',
          hypothesis: 'Hipótesis',
          computed_min: 'Mín calculado',
          computed_max: 'Máx calculado',
          delta_recon: 'Delta reconciliado - no reconciliado',
          gap_sigma: 'Desviación reconciliada (nº σ)',
          variable_type: 'Tipo de variable',
          node: 'Nodo',
          stock: 'Existencia',
          computed_stock: 'Existencia calculada',
          delta_stock: 'Δ Existencia',
          computed_delta: 'Δ calculada',
          coef: 'Coef',
          origin_ref: 'Origen ref',
          dest_ref: 'Destino ref',
          tag: 'Etiqueta',
          tag_ref: 'Etiqueta ref',
          translation: 'Traducción',
          delta_stock_plain: 'Delta existencia',
          dimension: 'Dimensión',
          tags: 'Etiquetas',
          tag_group_name: 'Nombre del grupo de etiquetas',
          tag_type: 'Tipo de etiqueta',
          colors: 'Colores',
          origin_dest: 'Origen ╲ Destino',
          resources: 'Recursos',
          uses: 'Empleos'
        },
        tagtype: {
          node: 'Nodo',
          level: 'Nivel',
          flux: 'Flujo',
          data: 'Dato'
        },
        classif: {
          measured: 'Medida',
          free_interval: 'Libre (intervalo)',
          determined: 'Determinada'
        },
        toolbar: {
          add_constraint: '+ Restricción',
          add_constraint_tip: 'Crear una restricción (flujo, existencia, total de nodo…) mediante un formulario guiado',
          parser: 'Analizar',
          parser_tip: 'Construye la jerarquía de agregación a partir de la columna Nivel',
          filter: 'Filtrar',
          filter_tip: 'Activa/desactiva los filtros de columna (estilo Excel) en esta pestaña',
          columns: 'Columnas',
          columns_count: 'Columnas ({{shown}}/{{total}})',
          sheets: 'Pestañas',
          sheets_count: 'Pestañas ({{shown}}/{{total}})',
          search: 'Buscar',
          select_all: '(Seleccionar todo)',
          show_all: 'Mostrar todo',
          only_visible: 'Solo visibles',
          display_filter_tip: 'Filtro de visualización de las filas de la hoja',
          placement_auto: 'Colocación: auto',
          placement_none: 'Colocación: ninguna',
          placement_increment: 'Colocación: incremental',
          placement_tip: 'Cómo colocar un nodo creado al añadir un flujo: auto (disposición completa), ninguna (posición por defecto), incremental (adivina el sitio sin mover los demás)',
          matrix_cross: 'Matriz: cruz',
          matrix_value: 'Matriz: valor',
          matrix_tip: 'Contenido de las celdas de la matriz: cruz (el flujo existe) o valor del flujo para el data_type seleccionado',
          matrix_label: 'Visualización de las matrices',
          panel_title: 'Hoja de cálculo',
          rows: 'Filas'
        },
        constraint: {
          title: 'Añadir una restricción',
          term1: 'Término 1',
          term2_ref: 'Término 2 (referencia)',
          type_flux: 'Flujo',
          type_node_total: 'Nodo (total)',
          type_stock: 'Existencia',
          type_delta_stock: 'Δ existencia',
          in: 'entrantes',
          out: 'salientes',
          node: 'Nodo',
          origin: 'Origen',
          destination: 'Destino',
          search: 'Buscar…',
          no_node: 'Ningún nodo',
          coef: 'coef',
          translation_label: 'Traducción (auto, editable)',
          translation_ph: 'Descripción en lenguaje natural',
          regenerate: 'regenerar',
          invalid_combo: 'Combinación de términos no válida.',
          cancel: 'Cancelar',
          add: 'Añadir',
          desc_flux: 'flujo {{orig}}→{{dest}}',
          desc_node_in: 'total de entrantes de {{node}}',
          desc_node_out: 'total de salientes de {{node}}',
          desc_stock: 'existencia de {{node}}',
          desc_delta: 'Δ existencia de {{node}}'
        },
        doc: {
          title: 'Documentación',
          window_title: 'OpenSankey — Documentación',
          pos_sheet_right: 'A la derecha de la hoja',
          pos_sheet_left: 'A la izquierda de la hoja',
          pos_sheet_top: 'Encima de la hoja',
          pos_sheet_bottom: 'Debajo de la hoja',
          pos_diagram_bottom: 'Debajo del diagrama',
          pos_window_bottom: 'Banda inferior',
          pos_right: 'A la derecha',
          pos_left: 'A la izquierda',
          pos_top: 'Encima',
          pos_bottom: 'Debajo',
          with_sheet: 'Con la hoja',
          under_diagram: 'Debajo del diagrama',
          window_bottom_full: 'Banda inferior (ancho completo)',
          insert: 'Insertar',
          insert_image: 'Una imagen…',
          insert_views_outline: 'Título + enlace por cada vista',
          insert_view_link: 'Enlace a una vista',
          mode_edit: 'Edición',
          mode_split: 'Lado a lado',
          mode_preview: 'Vista previa',
          back_to_diagram_doc: 'Volver a la documentación del diagrama',
          reattach: 'Volver a anclar la documentación en la ventana principal',
          detach: 'Separar la documentación en una ventana aparte',
          editor_placeholder: 'Redacte la documentación de este diagrama en markdown…\n\n# Título\n\n- punto 1\n- punto 2'
        },
        zone: {
          diagram: 'Diagrama',
          spreadsheet: 'Hoja de cálculo',
          json: 'JSON',
          doc: 'Doc',
          documentation: 'Documentación',
          unitary: 'Sankey unitario',
          unit: 'Unit.',
          infos: 'Info',
          move_right: 'Mover a la columna derecha',
          move_bottom: 'Mover a la banda inferior',
          make_main: 'Convertir en panel principal',
          dock_as_pane: 'Anclar como panel',
          make_floating: 'Hacer flotante',
          close: 'Cerrar',
          main_window: 'Panel principal',
          main_window_short: 'Principal',
          active_window_menu: 'Cambiar la representación de este panel o abrir uno nuevo',
          new_window: 'Nuevo panel',
          on_diagram: 'Sobre el diagrama',
          on_selection: 'Sobre el elemento seleccionado',
          follow: 'Sigue la selección',
          pin: 'Fijar en este elemento',
          unpin: 'Volver a seguir la selección',
          no_selection: 'Seleccione un nodo o un flujo',
          no_representation: 'Ninguna representación para este elemento',
          node: 'Nodo',
          link: 'Flujo',
          tag: 'Etiqueta',
          add_subject: 'Añadir un nodo o un flujo',
          pin_subject: 'Ver un nodo o un flujo',
          pin_to_tag: 'Fijar en una etiqueta',
          pin_to_tag_none: 'Elegir una etiqueta',
          place_on_node: 'Colocar en el nodo',
          unplace_from_node: 'Quitar del nodo',
          remove_subject: 'Quitar',
          pin_all: 'Fijar los elementos seleccionados',
          value_mode: 'Valores',
          normalize_on: 'Normalizar sobre',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: 'Representación del diagrama',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: 'Hoja del sujeto',
          sheet_gone: 'Esta hoja ya no existe',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés.
          sheet_window: 'Hoja en un panel',
          make_sheet_active: 'Activar esta hoja',
          sheet_read_only: 'Solo lectura — la edición se hace en la pestaña',
          open_sheet_in_window: 'Abrir en un panel nuevo',
          sheet_already_windowed: 'Esta hoja ya está abierta en otro panel',
          no_canvas_for_type: 'No hay lienzo para este tipo de documento',
          no_default_window: 'Nada que mostrar para esta hoja',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'Este panel no tiene nada que mostrar aquí',
          unknown_representation: 'Naturaleza de panel desconocida para esta versión',
          orphan_hint: 'Cambie su naturaleza o ciérrelo'
        }
      }
    }
  },
  //=======================================================
  // DE
  //=======================================================
  de: {
    translation: {
      Spreadsheet: {
        json: {
          help: 'Natives JSON des Diagramms, wie beim Speichern geschrieben (schreibgeschützt).',
          other: 'Sonstiges',
          refresh: 'Aus Diagramm neu laden',
          copy: 'Kopieren',
          copied: 'Kopiert',
        },
        text: {
          title: 'SankeyMATIC-Editor',
          help: 'Ein Fluss pro Zeile: „Quelle [Wert] Ziel“ (SankeyMATIC) oder 3 Spalten „Quelle ; Ziel ; Wert“.',
          apply: 'Anwenden',
          refresh: 'Aus Diagramm neu laden',
          clear: 'Leeren',
          clear_tooltip: 'Leeren Sie den Editor, bevor Sie ein SankeyMATIC-Diagramm einfügen, damit keine übrig gebliebene Einstellung darauf angewendet wird.',
          applied: 'Diagramm aktualisiert',
          error: 'Fehler',
          flows_recognized: 'erkannte Flüsse',
          lines_ignored: 'ignorierte Zeilen',
          layout: 'Layout:',
          layout_native: 'SankeyMATIC',
          layout_auto: 'Auto',
        },
        sheet: {
          flux: 'Flüsse',
          analysis: 'Ergebnisanalyse',
          nodes: 'Knoten',
          nodes_agg: 'Knoten nach Aggregation',
          tags: 'Etiketten',
          stock: 'Bestände',
          ratio: 'Flussverhältnis',
          ratio_stock: 'Bestand-Fluss-Verhältnis',
          stock_chaining: 'Bestandsverkettung',
          products: 'Produkte',
          sectors: 'Sektoren',
          exchanges: 'Austausch',
          tes: 'IOT (IO-Matrix)',
          ter: 'AVT (Aufkommen-Verwendung)'
        },
        header: {
          level: 'Ebene',
          level_n: 'Ebene {{n}}',
          name: 'Name',
          balance: 'Gleichgewicht',
          balance_io: 'Eingang-Ausgang-Gleichgewicht',
          color: 'Farbe',
          definitions: 'Definitionen',
          column_u: 'Spalte u',
          row_v: 'Zeile v',
          origin: 'Quelle',
          destination: 'Ziel',
          value: 'Wert',
          min: 'Min',
          max: 'Max',
          computed_value: 'Berechneter Wert',
          dest_value: 'Zielwert',
          natural_quantity: 'Natürliche Menge',
          uncertainty_pct: 'Unsicherheit %',
          source: 'Quelle',
          hypothesis: 'Hypothese',
          computed_min: 'Berechnetes Min',
          computed_max: 'Berechnetes Max',
          delta_recon: 'Abgeglichenes - nicht abgeglichenes Delta',
          gap_sigma: 'Abgeglichene Abweichung (Anz. σ)',
          variable_type: 'Variablentyp',
          node: 'Knoten',
          stock: 'Bestand',
          computed_stock: 'Berechneter Bestand',
          delta_stock: 'Δ Bestand',
          computed_delta: 'Berechnetes Δ',
          coef: 'Koeff.',
          origin_ref: 'Quelle Ref',
          dest_ref: 'Ziel Ref',
          tag: 'Etikett',
          tag_ref: 'Etikett Ref',
          translation: 'Übersetzung',
          delta_stock_plain: 'Delta Bestand',
          dimension: 'Dimension',
          tags: 'Etiketten',
          tag_group_name: 'Name der Etikettengruppe',
          tag_type: 'Etikettentyp',
          colors: 'Farben',
          origin_dest: 'Quelle ╲ Ziel',
          resources: 'Ressourcen',
          uses: 'Verwendungen'
        },
        tagtype: {
          node: 'Knoten',
          level: 'Ebene',
          flux: 'Fluss',
          data: 'Daten'
        },
        classif: {
          measured: 'Gemessen',
          free_interval: 'Frei (Intervall)',
          determined: 'Bestimmt'
        },
        toolbar: {
          add_constraint: '+ Bedingung',
          add_constraint_tip: 'Eine Bedingung (Fluss, Bestand, Knotensumme…) über ein geführtes Formular erstellen',
          parser: 'Parsen',
          parser_tip: 'Erstellt die Aggregationshierarchie aus der Spalte Ebene',
          filter: 'Filtern',
          filter_tip: 'Aktiviert/deaktiviert die Spaltenfilter (Excel-Stil) auf diesem Blatt',
          columns: 'Spalten',
          columns_count: 'Spalten ({{shown}}/{{total}})',
          sheets: 'Blätter',
          sheets_count: 'Blätter ({{shown}}/{{total}})',
          search: 'Suchen',
          select_all: '(Alle auswählen)',
          show_all: 'Alle anzeigen',
          only_visible: 'Nur sichtbare',
          display_filter_tip: 'Anzeigefilter für die Zeilen der Tabelle',
          placement_auto: 'Platzierung: auto',
          placement_none: 'Platzierung: keine',
          placement_increment: 'Platzierung: inkrementell',
          placement_tip: 'Wie ein durch Hinzufügen eines Flusses erstellter Knoten positioniert wird: auto (vollständige Anordnung), keine (Standardposition), inkrementell (errät den Platz, ohne die anderen zu verschieben)',
          matrix_cross: 'Matrix: Kreuz',
          matrix_value: 'Matrix: Wert',
          matrix_tip: 'Inhalt der Matrixzellen: Kreuz (der Fluss existiert) oder Flusswert für den ausgewählten data_type',
          matrix_label: 'Anzeige der Matrizen',
          panel_title: 'Tabelle',
          rows: 'Zeilen'
        },
        constraint: {
          title: 'Eine Bedingung hinzufügen',
          term1: 'Term 1',
          term2_ref: 'Term 2 (Referenz)',
          type_flux: 'Fluss',
          type_node_total: 'Knoten (Summe)',
          type_stock: 'Bestand',
          type_delta_stock: 'Δ Bestand',
          in: 'eingehend',
          out: 'ausgehend',
          node: 'Knoten',
          origin: 'Quelle',
          destination: 'Ziel',
          search: 'Suchen…',
          no_node: 'Kein Knoten',
          coef: 'Koeff.',
          translation_label: 'Übersetzung (auto, bearbeitbar)',
          translation_ph: 'Beschreibung in natürlicher Sprache',
          regenerate: 'neu erzeugen',
          invalid_combo: 'Ungültige Termkombination.',
          cancel: 'Abbrechen',
          add: 'Hinzufügen',
          desc_flux: 'Fluss {{orig}}→{{dest}}',
          desc_node_in: 'Summe eingehend von {{node}}',
          desc_node_out: 'Summe ausgehend von {{node}}',
          desc_stock: 'Bestand von {{node}}',
          desc_delta: 'Δ Bestand von {{node}}'
        },
        doc: {
          title: 'Dokumentation',
          window_title: 'OpenSankey — Dokumentation',
          pos_sheet_right: 'Rechts von der Tabelle',
          pos_sheet_left: 'Links von der Tabelle',
          pos_sheet_top: 'Über der Tabelle',
          pos_sheet_bottom: 'Unter der Tabelle',
          pos_diagram_bottom: 'Unter dem Diagramm',
          pos_window_bottom: 'Untere Leiste',
          pos_right: 'Rechts',
          pos_left: 'Links',
          pos_top: 'Oben',
          pos_bottom: 'Unten',
          with_sheet: 'Mit der Tabelle',
          under_diagram: 'Unter dem Diagramm',
          window_bottom_full: 'Untere Leiste (volle Breite)',
          insert: 'Einfügen',
          insert_image: 'Ein Bild…',
          insert_views_outline: 'Titel + Link für jede Ansicht',
          insert_view_link: 'Link zu einer Ansicht',
          mode_edit: 'Bearbeiten',
          mode_split: 'Nebeneinander',
          mode_preview: 'Vorschau',
          back_to_diagram_doc: 'Zurück zur Diagramm-Dokumentation',
          reattach: 'Dokumentation wieder im Hauptfenster andocken',
          detach: 'Dokumentation in einem separaten Fenster lösen',
          editor_placeholder: 'Verfassen Sie die Dokumentation dieses Diagramms in Markdown…\n\n# Titel\n\n- Punkt 1\n- Punkt 2'
        },
        zone: {
          diagram: 'Diagramm',
          spreadsheet: 'Tabelle',
          json: 'JSON',
          doc: 'Doc',
          documentation: 'Dokumentation',
          unitary: 'Unitäres Sankey',
          unit: 'Einh.',
          infos: 'Infos',
          move_right: 'In die rechte Spalte verschieben',
          move_bottom: 'In das untere Band verschieben',
          make_main: 'Zum Hauptbereich machen',
          dock_as_pane: 'Als Bereich andocken',
          make_floating: 'Schweben lassen',
          close: 'Schließen',
          main_window: 'Hauptbereich',
          main_window_short: 'Haupt',
          active_window_menu: 'Darstellung dieses Bereichs ändern oder einen neuen Bereich öffnen',
          new_window: 'Neuer Bereich',
          on_diagram: 'Auf das Diagramm',
          on_selection: 'Auf das ausgewählte Element',
          follow: 'Folgt der Auswahl',
          pin: 'An dieses Element heften',
          unpin: 'Wieder der Auswahl folgen',
          no_selection: 'Knoten oder Fluss auswählen',
          no_representation: 'Keine Darstellung für dieses Element',
          node: 'Knoten',
          link: 'Fluss',
          tag: 'Etikett',
          add_subject: 'Knoten oder Fluss hinzufügen',
          pin_subject: 'Knoten oder Fluss ansehen',
          pin_to_tag: 'An ein Etikett heften',
          pin_to_tag_none: 'Etikett auswählen',
          place_on_node: 'Auf dem Knoten platzieren',
          unplace_from_node: 'Vom Knoten entfernen',
          remove_subject: 'Entfernen',
          pin_all: 'Ausgewählte Elemente anheften',
          value_mode: 'Werte',
          normalize_on: 'Normieren auf',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: 'Darstellung des Diagramms',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: 'Blatt des Gegenstands',
          sheet_gone: 'Dieses Blatt existiert nicht mehr',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés.
          sheet_window: 'Blatt in einem Bereich',
          make_sheet_active: 'Dieses Blatt aktivieren',
          sheet_read_only: 'Nur Lesen — bearbeitet wird über die Registerkarte',
          open_sheet_in_window: 'In einem neuen Bereich öffnen',
          sheet_already_windowed: 'Dieses Blatt ist bereits in einem anderen Bereich geöffnet',
          no_canvas_for_type: 'Kein Zeichenbereich für diese Art von Dokument',
          no_default_window: 'Für dieses Blatt gibt es nichts zu zeigen',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'Dieser Bereich hat hier nichts zu zeigen',
          unknown_representation: 'Bereichsart in dieser Version unbekannt',
          orphan_hint: 'Ändern Sie seine Art oder schließen Sie ihn'
        }
      }
    }
  },
  //=======================================================
  // IT
  //=======================================================
  it: {
    translation: {
      Spreadsheet: {
        json: {
          help: 'JSON nativo del diagramma, come scritto al salvataggio (sola lettura).',
          other: 'Altro',
          refresh: 'Ricarica dal diagramma',
          copy: 'Copia',
          copied: 'Copiato',
        },
        text: {
          title: 'Editor SankeyMATIC',
          help: 'Un flusso per riga: «origine [valore] destinazione» (SankeyMATIC) o 3 colonne «origine ; destinazione ; valore».',
          apply: 'Applica',
          refresh: 'Ricarica dal diagramma',
          clear: 'Svuota',
          clear_tooltip: 'Svuota l\'editor prima di incollare un diagramma SankeyMATIC, affinché nessuna impostazione residua vi si applichi.',
          applied: 'Diagramma aggiornato',
          error: 'Errore',
          flows_recognized: 'flussi riconosciuti',
          lines_ignored: 'righe ignorate',
          layout: 'Disposizione:',
          layout_native: 'SankeyMATIC',
          layout_auto: 'Auto',
        },
        sheet: {
          flux: 'Flussi',
          analysis: 'Analisi dei risultati',
          nodes: 'Nodi',
          nodes_agg: 'Nodi per aggregazione',
          tags: 'Etichette',
          stock: 'Scorte',
          ratio: 'Rapporto flusso',
          ratio_stock: 'Rapporto scorta-flusso',
          stock_chaining: 'Concatenamento scorte',
          products: 'Prodotti',
          sectors: 'Settori',
          exchanges: 'Scambi',
          tes: 'TIO (matrice IO)',
          ter: 'TOR (impieghi-risorse)'
        },
        header: {
          level: 'Livello',
          level_n: 'Livello {{n}}',
          name: 'Nome',
          balance: 'Equilibrio',
          balance_io: 'Equilibrio entrata-uscita',
          color: 'Colore',
          definitions: 'Definizioni',
          column_u: 'Colonna u',
          row_v: 'Riga v',
          origin: 'Origine',
          destination: 'Destinazione',
          value: 'Valore',
          min: 'Min',
          max: 'Max',
          computed_value: 'Valore calcolato',
          dest_value: 'Valore destinazione',
          natural_quantity: 'Quantità naturale',
          uncertainty_pct: 'Incertezza %',
          source: 'Fonte',
          hypothesis: 'Ipotesi',
          computed_min: 'Min calcolato',
          computed_max: 'Max calcolato',
          delta_recon: 'Delta riconciliato - non riconciliato',
          gap_sigma: 'Scarto riconciliato (n. σ)',
          variable_type: 'Tipo di variabile',
          node: 'Nodo',
          stock: 'Scorta',
          computed_stock: 'Scorta calcolata',
          delta_stock: 'Δ Scorta',
          computed_delta: 'Δ calcolata',
          coef: 'Coef',
          origin_ref: 'Origine rif',
          dest_ref: 'Destinazione rif',
          tag: 'Etichetta',
          tag_ref: 'Etichetta rif',
          translation: 'Traduzione',
          delta_stock_plain: 'Delta scorta',
          dimension: 'Dimensione',
          tags: 'Etichette',
          tag_group_name: 'Nome del gruppo di etichette',
          tag_type: 'Tipo di etichetta',
          colors: 'Colori',
          origin_dest: 'Origine ╲ Destinazione',
          resources: 'Risorse',
          uses: 'Impieghi'
        },
        tagtype: {
          node: 'Nodo',
          level: 'Livello',
          flux: 'Flusso',
          data: 'Dato'
        },
        classif: {
          measured: 'Misurata',
          free_interval: 'Libera (intervallo)',
          determined: 'Determinata'
        },
        toolbar: {
          add_constraint: '+ Vincolo',
          add_constraint_tip: 'Creare un vincolo (flusso, scorta, totale di nodo…) tramite un modulo guidato',
          parser: 'Analizza',
          parser_tip: 'Costruisce la gerarchia di aggregazione dalla colonna Livello',
          filter: 'Filtra',
          filter_tip: 'Attiva/disattiva i filtri di colonna (stile Excel) su questo foglio',
          columns: 'Colonne',
          columns_count: 'Colonne ({{shown}}/{{total}})',
          sheets: 'Fogli',
          sheets_count: 'Fogli ({{shown}}/{{total}})',
          search: 'Cerca',
          select_all: '(Seleziona tutto)',
          show_all: 'Mostra tutto',
          only_visible: 'Solo visibili',
          display_filter_tip: 'Filtro di visualizzazione delle righe del foglio',
          placement_auto: 'Posizionamento: auto',
          placement_none: 'Posizionamento: nessuno',
          placement_increment: 'Posizionamento: incrementale',
          placement_tip: 'Come posizionare un nodo creato aggiungendo un flusso: auto (disposizione completa), nessuno (posizione predefinita), incrementale (indovina il posto senza spostare gli altri)',
          matrix_cross: 'Matrice: croce',
          matrix_value: 'Matrice: valore',
          matrix_tip: 'Contenuto delle celle della matrice: croce (il flusso esiste) o valore del flusso per il data_type selezionato',
          matrix_label: 'Visualizzazione delle matrici',
          panel_title: 'Foglio',
          rows: 'Righe'
        },
        constraint: {
          title: 'Aggiungere un vincolo',
          term1: 'Termine 1',
          term2_ref: 'Termine 2 (riferimento)',
          type_flux: 'Flusso',
          type_node_total: 'Nodo (totale)',
          type_stock: 'Scorta',
          type_delta_stock: 'Δ scorta',
          in: 'entranti',
          out: 'uscenti',
          node: 'Nodo',
          origin: 'Origine',
          destination: 'Destinazione',
          search: 'Cerca…',
          no_node: 'Nessun nodo',
          coef: 'coef',
          translation_label: 'Traduzione (auto, modificabile)',
          translation_ph: 'Descrizione in linguaggio naturale',
          regenerate: 'rigenera',
          invalid_combo: 'Combinazione di termini non valida.',
          cancel: 'Annulla',
          add: 'Aggiungi',
          desc_flux: 'flusso {{orig}}→{{dest}}',
          desc_node_in: 'totale entranti di {{node}}',
          desc_node_out: 'totale uscenti di {{node}}',
          desc_stock: 'scorta di {{node}}',
          desc_delta: 'Δ scorta di {{node}}'
        },
        doc: {
          title: 'Documentazione',
          window_title: 'OpenSankey — Documentazione',
          pos_sheet_right: 'A destra del foglio',
          pos_sheet_left: 'A sinistra del foglio',
          pos_sheet_top: 'Sopra il foglio',
          pos_sheet_bottom: 'Sotto il foglio',
          pos_diagram_bottom: 'Sotto il diagramma',
          pos_window_bottom: 'Banda inferiore',
          pos_right: 'A destra',
          pos_left: 'A sinistra',
          pos_top: 'Sopra',
          pos_bottom: 'Sotto',
          with_sheet: 'Con il foglio',
          under_diagram: 'Sotto il diagramma',
          window_bottom_full: 'Banda inferiore (larghezza piena)',
          insert: 'Inserisci',
          insert_image: 'Un\'immagine…',
          insert_views_outline: 'Titolo + link per ogni vista',
          insert_view_link: 'Link a una vista',
          mode_edit: 'Modifica',
          mode_split: 'Affiancato',
          mode_preview: 'Anteprima',
          back_to_diagram_doc: 'Torna alla documentazione del diagramma',
          reattach: 'Riancorare la documentazione nella finestra principale',
          detach: 'Staccare la documentazione in una finestra separata',
          editor_placeholder: 'Redigi la documentazione di questo diagramma in markdown…\n\n# Titolo\n\n- punto 1\n- punto 2'
        },
        zone: {
          diagram: 'Diagramma',
          spreadsheet: 'Foglio di calcolo',
          json: 'JSON',
          doc: 'Doc',
          documentation: 'Documentazione',
          unitary: 'Sankey unitario',
          unit: 'Unit.',
          infos: 'Info',
          move_right: 'Sposta nella colonna destra',
          move_bottom: 'Sposta nella fascia inferiore',
          make_main: 'Rendilo il riquadro principale',
          dock_as_pane: 'Ancora come riquadro',
          make_floating: 'Rendi flottante',
          close: 'Chiudi',
          main_window: 'Riquadro principale',
          main_window_short: 'Principale',
          active_window_menu: 'Cambiare la rappresentazione di questo riquadro o aprirne uno nuovo',
          new_window: 'Nuovo riquadro',
          on_diagram: 'Sul diagramma',
          on_selection: 'Sull’elemento selezionato',
          follow: 'Segue la selezione',
          pin: 'Fissa su questo elemento',
          unpin: 'Segui di nuovo la selezione',
          no_selection: 'Seleziona un nodo o un flusso',
          no_representation: 'Nessuna rappresentazione per questo elemento',
          node: 'Nodo',
          link: 'Flusso',
          tag: 'Etichetta',
          add_subject: 'Aggiungi un nodo o un flusso',
          pin_subject: 'Guarda un nodo o un flusso',
          pin_to_tag: 'Fissa a un\'etichetta',
          pin_to_tag_none: 'Scegli un\'etichetta',
          place_on_node: 'Posiziona sul nodo',
          unplace_from_node: 'Rimuovi dal nodo',
          remove_subject: 'Rimuovi',
          pin_all: 'Fissa gli elementi selezionati',
          value_mode: 'Valori',
          normalize_on: 'Normalizza su',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: 'Rappresentazione del diagramma',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: 'Foglio del soggetto',
          sheet_gone: 'Questo foglio non esiste più',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés.
          sheet_window: 'Foglio in un riquadro',
          make_sheet_active: 'Rendi attivo questo foglio',
          sheet_read_only: 'Sola lettura — si modifica dalla scheda',
          open_sheet_in_window: 'Apri in un nuovo riquadro',
          sheet_already_windowed: 'Questo foglio è già aperto in un altro riquadro',
          no_canvas_for_type: 'Nessuna area di disegno per questo tipo di documento',
          no_default_window: 'Niente da mostrare per questo foglio',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'Questo riquadro non ha nulla da mostrare qui',
          unknown_representation: 'Natura di riquadro sconosciuta a questa versione',
          orphan_hint: 'Cambiate la sua natura, oppure chiudetelo'
        }
      }
    }
  },
  'zh-CN': {
    translation: {
      Spreadsheet: {
        json: {
          help: '图表的原生 JSON，与保存文件时写出的内容一致（只读）。',
          other: '其他',
          refresh: '从图表重新加载',
          copy: '复制',
          copied: '已复制',
        },
        text: {
          title: 'SankeyMATIC 编辑器',
          help: '每行一条流量："source [value] target"（SankeyMATIC），或三列 "source ; target ; value"。',
          apply: '应用',
          refresh: '从图表重新加载',
          clear: '清空',
          clear_tooltip: '在粘贴 SankeyMATIC 图表之前先清空编辑器，以免残留设置影响它。',
          applied: '图表已更新',
          error: '错误',
          flows_recognized: '条流量已识别',
          lines_ignored: '行被忽略',
          layout: '布局：',
          layout_native: 'SankeyMATIC',
          layout_auto: '自动',
        },
        sheet: {
          flux: '流量',
          analysis: '结果分析',
          nodes: '节点',
          nodes_agg: '按聚合的节点',
          tags: '标签',
          stock: '存量',
          ratio: '流量比例',
          ratio_stock: '存量-流量比例',
          stock_chaining: '存量链接',
          products: '产品',
          sectors: '部门',
          exchanges: '交换',
          tes: 'IOT（投入产出矩阵）',
          ter: 'SUT（供给使用表）'
        },
        // --- En-têtes de colonnes ---
        header: {
          level: '层级',
          level_n: '层级 {{n}}',
          name: '名称',
          balance: '平衡',
          balance_io: '投入产出平衡',
          color: '颜色',
          definitions: '定义',
          column_u: '列 u',
          row_v: '行 v',
          origin: '起点',
          destination: '终点',
          value: '数值',
          min: '最小',
          max: '最大',
          computed_value: '计算值',
          dest_value: '终点数值',
          natural_quantity: '自然量',
          uncertainty_pct: '不确定性 %',
          source: '来源',
          hypothesis: '假设',
          computed_min: '计算最小值',
          computed_max: '计算最大值',
          delta_recon: '调和前后差值',
          gap_sigma: '调和偏差（σ 数）',
          variable_type: '变量类型',
          node: '节点',
          stock: '存量',
          computed_stock: '计算存量',
          delta_stock: 'Δ 存量',
          computed_delta: '计算 Δ',
          coef: '系数',
          origin_ref: '起点参考',
          dest_ref: '终点参考',
          tag: '标签',
          tag_ref: '标签参考',
          translation: '翻译',
          delta_stock_plain: '存量变化',
          dimension: '维度',
          tags: '标签',
          tag_group_name: '标签组名称',
          tag_type: '标签类型',
          colors: '颜色',
          // En-têtes de matrice
          origin_dest: '起点 ╲ 终点',
          resources: '资源',
          uses: '用途'
        },
        // --- Types d'étiquette (colonne Type de l'onglet Etiquettes) ---
        tagtype: {
          node: '节点',
          level: '层级',
          flux: '流量',
          data: '数据'
        },
        // --- Classification du type de variable (onglet Analyse) ---
        classif: {
          measured: '实测',
          free_interval: '自由（区间）',
          determined: '可确定'
        },
        // --- Barre d'outils ---
        toolbar: {
          add_constraint: '+ 约束',
          add_constraint_tip: '通过引导式表单创建约束（流量、存量、节点总量……）',
          parser: '解析',
          parser_tip: '依据 Level 列构建聚合层级',
          filter: '筛选',
          filter_tip: '在该工作表上切换列筛选器（Excel 风格）',
          columns: '列',
          columns_count: '列（{{shown}}/{{total}}）',
          sheets: '工作表',
          sheets_count: '工作表（{{shown}}/{{total}}）',
          search: '搜索',
          select_all: '（全选）',
          show_all: '全部显示',
          only_visible: '仅可见',
          display_filter_tip: '电子表格的行显示筛选',
          placement_auto: '放置：自动',
          placement_none: '放置：无',
          placement_increment: '放置：增量',
          placement_tip: '添加流量时新建节点的定位方式：自动（完整布局）、无（默认位置）、增量（推测位置且不移动其他节点）',
          matrix_cross: '矩阵：叉号',
          matrix_value: '矩阵：数值',
          matrix_tip: '矩阵单元格内容：叉号（表示该流量存在）或所选 data_type 的流量数值',
          matrix_label: '矩阵显示方式',
          panel_title: '电子表格',
          rows: '行'
        },
        // --- Modale « Ajouter une contrainte » ---
        constraint: {
          title: '添加约束',
          term1: '项 1',
          term2_ref: '项 2（参考）',
          type_flux: '流量',
          type_node_total: '节点（总量）',
          type_stock: '存量',
          type_delta_stock: 'Δ 存量',
          in: '进入',
          out: '流出',
          node: '节点',
          origin: '起点',
          destination: '终点',
          search: '搜索……',
          no_node: '无节点',
          coef: '系数',
          translation_label: '释义（自动生成，可编辑）',
          translation_ph: '自然语言描述',
          regenerate: '重新生成',
          invalid_combo: '项的组合无效。',
          cancel: '取消',
          add: '添加',
          desc_flux: '流量 {{orig}}→{{dest}}',
          desc_node_in: '{{node}} 的进入总量',
          desc_node_out: '{{node}} 的流出总量',
          desc_stock: '{{node}} 的存量',
          desc_delta: '{{node}} 的 Δ 存量'
        },
        // --- Panneau de documentation ---
        doc: {
          title: '文档',
          window_title: 'OpenSankey — 文档',
          pos_sheet_right: '电子表格右侧',
          pos_sheet_left: '电子表格左侧',
          pos_sheet_top: '电子表格上方',
          pos_sheet_bottom: '电子表格下方',
          pos_diagram_bottom: '图表下方',
          pos_window_bottom: '底栏',
          pos_right: '右',
          pos_left: '左',
          pos_top: '上方',
          pos_bottom: '下方',
          with_sheet: '与电子表格一起',
          under_diagram: '图表下方',
          window_bottom_full: '底栏（通栏）',
          insert: '插入',
          insert_image: '一张图片……',
          insert_views_outline: '每个视图的标题 + 链接',
          insert_view_link: '指向某个视图的链接',
          mode_edit: '编辑',
          mode_split: '并排',
          mode_preview: '预览',
          back_to_diagram_doc: '返回图表文档',
          reattach: '将文档重新并入主窗口',
          detach: '将文档分离到独立窗口',
          editor_placeholder: '用 markdown 撰写本图表的文档……\n\n# 标题\n\n- 要点 1\n- 要点 2'
        },
        // --- Boutons bascule de la grande zone (MenuTop) ---
        zone: {
          diagram: '图表',
          spreadsheet: '电子表格',
          json: 'JSON',
          doc: '文档',
          documentation: '文档',
          unitary: '单位桑基图',
          unit: '单位图',
          infos: '信息',
          move_right: '移到右栏',
          move_bottom: '移到底栏',
          make_main: '设为主窗格',
          dock_as_pane: '停靠为窗格',
          make_floating: '设为浮动',
          close: '关闭',
          main_window: '主窗格',
          main_window_short: '主',
          active_window_menu: '更改此窗格的表示方式，或打开新窗格',
          new_window: '新建窗格',
          on_diagram: '针对图表',
          on_selection: '针对所选元素',
          follow: '跟随选择',
          pin: '固定到此元素',
          unpin: '重新跟随选择',
          no_selection: '请选择一个节点或流',
          no_representation: '此元素没有可用的表示',
          node: '节点',
          link: '流',
          tag: '标签',
          add_subject: '添加节点或流',
          pin_subject: '查看节点或流',
          pin_to_tag: '固定到标签',
          pin_to_tag_none: '选择一个标签',
          place_on_node: '放置到节点上',
          unplace_from_node: '从节点移除',
          remove_subject: '移除',
          pin_all: '固定所选元素',
          value_mode: '数值',
          normalize_on: '归一化于',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: '图表表示形式',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: '主体所在工作表',
          sheet_gone: '该工作表已不存在',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés. Le tiret
          // cadratin de `sheet_read_only` cède la place aux deux-points, seuls naturels ici.
          sheet_window: '窗格中的工作表',
          make_sheet_active: '将此工作表设为当前工作表',
          sheet_read_only: '只读：编辑请在标签页中进行',
          open_sheet_in_window: '在新窗格中打开',
          sheet_already_windowed: '该工作表已在另一个窗格中打开',
          no_canvas_for_type: '该类型的文档没有画布',
          no_default_window: '该工作表没有可显示的内容',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: '该窗格在此处没有可显示的内容',
          unknown_representation: '此版本无法识别的窗格类型',
          orphan_hint: '请更改其类型，或将其关闭'
        }
      }
    }
  },
  ja: {
    translation: {
      Spreadsheet: {
        json: {
          help: '図のネイティブ JSON。保存時に書き出される内容と同じです（読み取り専用）。',
          other: 'その他',
          refresh: '図から読み込み直す',
          copy: 'コピー',
          copied: 'コピーしました',
        },
        text: {
          title: 'SankeyMATIC エディタ',
          help: '1 行に 1 フロー："source [value] target"（SankeyMATIC）、または 3 列の "source ; target ; value"。',
          apply: '適用',
          refresh: '図から読み込み直す',
          clear: 'クリア',
          clear_tooltip: 'SankeyMATIC の図を貼り付ける前にエディタを空にし、以前の設定が残らないようにします。',
          applied: '図を更新しました',
          error: 'エラー',
          flows_recognized: '件のフローを認識',
          lines_ignored: '行を無視',
          layout: 'レイアウト：',
          layout_native: 'SankeyMATIC',
          layout_auto: '自動',
        },
        sheet: {
          flux: 'フロー',
          analysis: '結果の分析',
          nodes: 'ノード',
          nodes_agg: '集約別のノード',
          tags: 'タグ',
          stock: 'ストック',
          ratio: 'フローの比率',
          ratio_stock: 'ストック・フロー比',
          stock_chaining: 'ストックの連鎖',
          products: '製品',
          sectors: '部門',
          exchanges: '交換',
          tes: 'IOT（投入産出行列）',
          ter: 'SUT（供給使用表）'
        },
        // --- En-têtes de colonnes ---
        header: {
          level: 'レベル',
          level_n: 'レベル {{n}}',
          name: '名前',
          balance: '収支',
          balance_io: '投入産出の収支',
          color: '色',
          definitions: '定義',
          column_u: '列 u',
          row_v: '行 v',
          origin: '始点',
          destination: '終点',
          value: '値',
          min: '最小',
          max: '最大',
          computed_value: '計算値',
          dest_value: '終点側の値',
          natural_quantity: '実数量',
          uncertainty_pct: '不確実性 %',
          source: 'ソース',
          hypothesis: '仮定',
          computed_min: '計算された最小値',
          computed_max: '計算された最大値',
          delta_recon: '調和前後の差',
          gap_sigma: '調和のずれ（σ 単位）',
          variable_type: '変数の種類',
          node: 'ノード',
          stock: 'ストック',
          computed_stock: '計算されたストック',
          delta_stock: 'Δ ストック',
          computed_delta: '計算された Δ',
          coef: '係数',
          origin_ref: '始点の参照',
          dest_ref: '終点の参照',
          tag: 'タグ',
          tag_ref: 'タグの参照',
          translation: '説明文',
          delta_stock_plain: 'ストック変化量',
          dimension: '次元',
          tags: 'タグ',
          tag_group_name: 'タググループ名',
          tag_type: 'タグの種類',
          colors: '色',
          // En-têtes de matrice
          origin_dest: '始点 ╲ 終点',
          resources: '供給',
          uses: '使用'
        },
        // --- Types d'étiquette (colonne Type de l'onglet Etiquettes) ---
        tagtype: {
          node: 'ノード',
          level: 'レベル',
          flux: 'フロー',
          data: 'データ'
        },
        // --- Classification du type de variable (onglet Analyse) ---
        classif: {
          measured: '実測',
          free_interval: '自由（区間）',
          determined: '確定'
        },
        // --- Barre d'outils ---
        toolbar: {
          add_constraint: '+ 制約',
          add_constraint_tip: '案内に沿ったフォームで制約（フロー、ストック、ノード合計など）を作成します',
          parser: '解析',
          parser_tip: 'Level 列から集約の階層を構築します',
          filter: '絞り込み',
          filter_tip: 'このシートで列フィルタ（Excel 形式）を切り替えます',
          columns: '列',
          columns_count: '列（{{shown}}/{{total}}）',
          sheets: 'シート',
          sheets_count: 'シート（{{shown}}/{{total}}）',
          search: '検索',
          select_all: '（すべて選択）',
          show_all: 'すべて表示',
          only_visible: '表示中のみ',
          display_filter_tip: 'スプレッドシートの行の表示フィルタ',
          placement_auto: '配置：自動',
          placement_none: '配置：なし',
          placement_increment: '配置：追加のみ',
          placement_tip: 'フローの追加で作成されたノードをどう配置するか：自動（レイアウト全体を計算）、なし（既定位置）、追加のみ（他を動かさずに位置を推定）',
          matrix_cross: '行列：クロス',
          matrix_value: '行列：値',
          matrix_tip: '行列セルの内容：クロス（そのフローが存在する）、または選択中の data_type におけるフローの値',
          matrix_label: '行列の表示',
          panel_title: 'スプレッドシート',
          rows: '行'
        },
        // --- Modale « Ajouter une contrainte » ---
        constraint: {
          title: '制約を追加',
          term1: '第 1 項',
          term2_ref: '第 2 項（基準）',
          type_flux: 'フロー',
          type_node_total: 'ノード（合計）',
          type_stock: 'ストック',
          type_delta_stock: 'Δ ストック',
          in: '入力',
          out: '出力',
          node: 'ノード',
          origin: '始点',
          destination: '終点',
          search: '検索…',
          no_node: 'ノードなし',
          coef: '係数',
          translation_label: '説明文（自動生成、編集可）',
          translation_ph: '自然言語による説明',
          regenerate: '作り直す',
          invalid_combo: '項の組み合わせが不正です。',
          cancel: 'キャンセル',
          add: '追加',
          desc_flux: 'フロー {{orig}}→{{dest}}',
          desc_node_in: '{{node}} の入力合計',
          desc_node_out: '{{node}} の出力合計',
          desc_stock: '{{node}} のストック',
          desc_delta: '{{node}} の Δ ストック'
        },
        // --- Panneau de documentation ---
        doc: {
          title: '文書',
          window_title: 'OpenSankey — 文書',
          pos_sheet_right: 'スプレッドシートの右',
          pos_sheet_left: 'スプレッドシートの左',
          pos_sheet_top: 'スプレッドシートの上',
          pos_sheet_bottom: 'スプレッドシートの下',
          pos_diagram_bottom: '図の下',
          pos_window_bottom: '下部バー',
          pos_right: '右',
          pos_left: '左',
          pos_top: '上',
          pos_bottom: '下',
          with_sheet: 'スプレッドシートと一緒に',
          under_diagram: '図の下',
          window_bottom_full: '下部バー（全幅）',
          insert: '挿入',
          insert_image: '画像…',
          insert_views_outline: '各ビューの見出し + リンク',
          insert_view_link: 'ビューへのリンク',
          mode_edit: '編集',
          mode_split: '左右に並べる',
          mode_preview: 'プレビュー',
          back_to_diagram_doc: '図の文書に戻る',
          reattach: '文書をメインウィンドウに戻します',
          detach: '文書を別ウィンドウに切り離します',
          editor_placeholder: 'この図の説明を markdown で書きます…\n\n# 見出し\n\n- 項目 1\n- 項目 2'
        },
        // --- Boutons bascule de la grande zone (MenuTop) ---
        zone: {
          diagram: '図',
          spreadsheet: 'スプレッドシート',
          json: 'JSON',
          doc: '文書',
          documentation: '文書',
          unitary: '単位サンキー',
          unit: '単位',
          infos: '情報',
          move_right: '右の列へ移動',
          move_bottom: '下の帯へ移動',
          make_main: 'メインペインにする',
          dock_as_pane: 'ペインとして固定',
          make_floating: 'フローティングにする',
          close: '閉じる',
          main_window: 'メインペイン',
          main_window_short: 'メイン',
          active_window_menu: 'このペインの表示形式を変更、または新しいペインを開く',
          new_window: '新しいペイン',
          on_diagram: '図全体に',
          on_selection: '選択した要素に',
          follow: '選択に追従',
          pin: 'この要素に固定',
          unpin: '再び選択に追従',
          no_selection: 'ノードまたはフローを選択',
          no_representation: 'この要素の表現はありません',
          node: 'ノード',
          link: 'フロー',
          tag: 'タグ',
          add_subject: 'ノードまたはフローを追加',
          pin_subject: 'ノードまたはフローを見る',
          pin_to_tag: 'タグに固定',
          pin_to_tag_none: 'タグを選択',
          place_on_node: 'ノードに配置',
          unplace_from_node: 'ノードから外す',
          remove_subject: '削除',
          pin_all: '選択した要素を固定',
          value_mode: '値',
          normalize_on: '正規化の基準',
          // os#1356 — le GROUPE lui-même, nommé : il change la manière de lire TOUT le
          // diagramme, là où `inspector.element_analysis` porte sur un seul élément.
          diagram_representation: '図の表現形式',
          // os#1386 — cf. le bloc anglais pour le pourquoi de ces deux clés.
          subject_sheet: '対象のシート',
          sheet_gone: 'このシートは存在しません',
          // os#1389 lot 1 — cf. le bloc anglais pour le pourquoi de ces quatre clés. Le tiret
          // cadratin de `sheet_read_only` cède la place aux deux-points, seuls naturels ici.
          sheet_window: 'ペイン内のシート',
          make_sheet_active: 'このシートをアクティブにする',
          sheet_read_only: '読み取り専用：編集はタブで行います',
          open_sheet_in_window: '新しいペインで開く',
          sheet_already_windowed: 'このシートはすでに別のペインで開いています',
          no_canvas_for_type: 'この種類のドキュメントにはキャンバスがありません',
          no_default_window: 'このシートに表示できるものはありません',
          // os#1436 — CE QU'UN VOLET ORPHELIN DIT. Un occupant qu'aucun rendu de la grande
          // zone ne prend etait rendu NULLE PART : case blanche, sans en-tete, donc
          // infermable. Il est desormais rattrape, et ces trois lignes sont ce qu'il ecrit.
          // `orphan_window` parle d'un VOLET et non d'une feuille (a la difference de
          // `no_default_window` juste au-dessus) : l'orphelin est une fenetre de la grille,
          // pas un document. `orphan_hint` donne le geste, sans quoi le message dirait le
          // manque sans dire quoi en faire.
          orphan_window: 'このペインにはここで表示できるものがありません',
          unknown_representation: 'このバージョンでは不明なペインの種類',
          orphan_hint: '種類を変更するか、閉じてください'
        }
      }
    }
  }
}
