export const resources_nodes = {
  en: {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: 'Stylesheet',
        OrderStyle: 'Order of styles associated',
        multi_style: 'Selected nodes have different style',
        editStyle: 'Assign a style',
        AS: 'Reset',
        SelectStyle: 'Select a style',
        Reorg: 'Reorganize incoming/outgoing links',
        Reorg_title: 'Reorganization',
        Slct: 'Selection',
        SlctOutLink: 'Select outgoing links',
        SlctInLink: 'Select incoming links',
        SlctL: 'Sélectionner les flux',
        SlctOL: 'Output',
        SlctIL: 'Input',
        IB: 'Tooltip',
        IS: 'Additional info.',
        align_horiz: 'Horizontally',
        align_horiz_min: 'Relative to the selected node furthest to the left',
        align_horiz_max: 'Relative to the selected node furthest to the right',
        align_vert: 'Vertically',
        align_vert_min: 'Relative to the selected topmost node',
        align_vert_max: 'Relative to the selected node furthest down',
        align_horiz_left: 'Align to its left',
        align_horiz_center: 'Align to its center',
        align_horiz_right: 'Align to its right',
        align_vert_top: 'Align to its top',
        align_vert_bottom: 'Align to its bottom',
        align: 'Align nodes',
        product: 'Product',
        sector: 'Sector',
        exchange: 'Exchange',
        size: 'Size',
        position: 'Position',
        text: 'Text',
        selector: 'Select nodes',
        title_desaggreg: 'Dimension disagregation',
        title_aggreg: 'Dimension agregation',
        text_agreg: 'Will agregate in : ',
        text_desagreg: 'Will disagregate in : ',
        desaggreg: 'Disagregation',
        aggreg: 'Agregation',
        firstPlan: 'Move in the bakground',
        lastPlan: 'Move at the foreground',
        changePlan: 'Change plan of nodes',
        mask_attr: 'Elements display',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: 'Allow to apply a predefined style in the preference menu to the selected node(s)',
          Reorg: 'Allows automatic reorganization of incoming and outgoing links (up/down position)',
          SlctOutLink: 'Allow to select all outgoing links from the node(s)',
          SlctInLink: 'Allow to select all incoming links to the node(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the node. This tooltip pops on graphic space with SHIFT + MOUSE on the node.',
        },
        drawing_area_tooltip: {
          outputs: 'Outputs',
          inputs: 'Inputs',
          dest: 'Outputs',
          val: 'Values',
          data_value: 'Collected data',
          result_value: 'Computed data',
          rat: 'Ratios',
          prov: 'Inputs',
          values_tab: 'Values',
          tags_tab: 'Other informations',
          unitary_tab: 'Unitary Sankey',
          balance: 'Balance',
          balance_diff: 'Difference (In − Out)',
          balance_ok: 'Balanced',
          balance_ko: 'Imbalanced',
          analysis_tab: 'Analysis'
        },
        tabs: {
          apparence: 'Appearence',
          infos: 'Additional info.',
          tags: 'Tags',
          io: 'I/O links positions',
        },
        apparence: {
          apparence: 'Appearence',
          shape_visible: 'Shape',
          shape_color: 'Color',
          shape_color_sustainable: 'Static color',
          shape_type: 'Shape of node',
          Geometry: 'Geometry',
          Cercle: 'Arc',
          Rectangle: 'Rectangle',
          shape_min_width: 'Minimum width',
          shape_min_height: 'Minimum height',
          geometry: 'Positioning',
          geometry_absolute: 'Absolute',
          geometry_parametric: 'Spacing',
          geometry_relative: 'Offset',
          position_u: 'Colonne',
          column_u: 'Column (u)',
          position_v: 'Row',
          row_v: 'Row (v)',
          column_row_uv: 'Column (u) / Row (v)',
          position_dx: 'Ecart horizontal',
          position_dy: 'Ecart vertical',
          anchor_align: 'Link anchors',
          anchor_align_vertical: 'Anchors (vertical sides)',
          anchor_align_horizontal: 'Anchors (horizontal sides)',
          shape_io_reorg_mode: 'Auto-reordering',
          io_reorg_mode_none: 'None',
          io_reorg_mode_simple: 'Opposite node position',
          io_reorg_mode_advanced: 'Curvature, except straight links',
          io_reorg_mode_anchor: 'Curvature, all links',
          shape_link_inset: 'Link distance',
          asn: 'Apply style to nodes',
          override_type_node_shape: 'Override default shape',
          arrow: 'Arrow',
          display_shape: 'Display the node shape',
          hide_shape: 'Hide the node shape',
          display_label: 'Display the label',
          hide_label: 'Hide the label',
          display_value: 'Display the value',
          hide_value: 'Hide the value',
          shape_opacity: 'Opacity',
          tooltips: {
            FormeDisabled: 'Deactivated because the shape is managed by the "Type de noeud" tag group, if you want to be able to change the shape of the selected nodes, go to the "tags" tab and uncheck all the selected tag of the "Type de noeud" group',
            shape_anchor_align_vertical: 'Vertical alignment of link anchors on the left/right sides of the node (top / center / bottom).',
            shape_anchor_align_horizontal: 'Horizontal alignment of link anchors on the top/bottom sides of the node (left / center / right).',
            shape_io_reorg_mode: 'How the incoming/outgoing link order is recomputed when the diagram changes. None: never recomputed (order stays frozen). Opposite node position: sorted by where the opposite node sits (default). Curvature, except straight links: links that run straight stay at the centre of the face, the others fan out. Curvature, all links: no exception — every link is fanned and the one that turns earliest goes to the extremity.',
            shape_link_inset: 'Perpendicular offset of link anchors relative to the node border, in px. Positive pulls the anchors INSIDE the box (incoming/outgoing links meet through the node), negative pushes them outside. The box keeps its size.',
            geometry: 'Méthode pour calculer la position du noeud. Cette position peut être donnée en coordonnées absolues x,y, en coordonnée relative u,v, ou en coordonnée relative à une autre noeud.',
            position_dx: 'Ecart horizontal entre le bord droit du noeud à gauche et le bord gauche du noeud',
            position_dy: 'Ecart vertical entre le bord inférieur du noeud au dessus et le bord supérieur du noeud',
            shape_position_u_locked: 'When locked, autosankey compute keeps this node\'s column index (u) instead of recomputing it.',
            shape_position_v_locked: 'When locked, autosankey compute preserves the relative vertical order (v) of this node within its column instead of recomputing it.',
            override_type_node_shape: 'Override the default forced shape of product and sector type nodes',
          },
          shape_arrow_angle_direction: 'Arrow orientation',
          shape_arrow_angle_factor: 'Arrow slope'
        },
        node_value: {
          anchor: 'Anchor position',
          anchor_dx: 'Horizontal shift',
          anchor_dy: 'Vertical shift',
          tooltips: {
            anchor: 'The anchor of node value can be positioned by combining horizontal position : left, middle and right; and vertically : top, middle and bottom',
            anchor_dx: 'Horizontal shift from label anchor',
            anchor_dy: 'Vertical shift from label anchor',
          }
        },
        labels: {
          labels: 'Name',
          node_value: 'Value',
          name_label_is_visible: 'Label',
          lb: 'White label',
          name_label_background: 'Background',
          name_label_background_color: 'Background color',
          pos: 'Position',
          pos_v: 'Value position',
          tp: 'Font size',
          cl: 'Text box width',
          vdv: 'Value',
          edit_node_label: 'Edit node label',
          anchor: 'Anchor position',
          name_label_text_source: 'Label content',
          name_label_template: 'Template',
          name_label_text: 'Custom label',
          name_label_tag_group: 'Tag group',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatic (first one)',
          text_source: {
            name: 'Node name',
            name_container: 'Element name',
            custom: 'Custom text',
            template: 'Token template',
            tag: 'Tag long name',
            ancestor: 'Ancestor node name',
            name_part: 'Name part (separator)',
          },

          tooltips: {
            name_label_is_visible: 'Displays or not the label(s) attached to the selected node(s)',
            name_label_text_source: 'Choose what the node label shows: the node name, or an independent custom text (edited without renaming the node)',
            name_label_template: 'Text built from tokens replaced at draw time, e.g. "{Name}: {Value} {Unit}"',
            lb: 'Displays the text of the label(s) in white or black (useful if label is positioned on node(s))',
            name_label_background: 'Add a background to the label for a better visibility in case the label is in front of a link',
            top: 'Displays the label(s) above the selected node(s)',
            Milieu_pv: 'Displays the label(s) in the middle (vertically) of the selected node(s)',
            Bas: 'Displays the label(s) below the selected node(s)',
            gauche: 'Displays the label(s) to the left of the selected node(s)',
            Milieu_ph: 'Displays the label(s) in the middle (horizontally) of the selected node(s)',
            droite: 'Displays the label(s) to the right of the selected node(s)',
            cl: 'Width of the text area (in pixels) for the label(s) of the selected node(s)',
            vdv: 'Displays or not the associated value with the selected node(s)',
            anchor: 'L\'ancre du label peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            haut_val: 'Displays the associated value above the selected node(s)',
            Milieu_pv_val: 'Displays the associated value in the middle (vertically) of the selected node(s)',
            Bas_val: 'Displays the associated value below the selected node(s)',
            gauche_val: 'Displays the associated value to the left of the selected node(s)',
            Milieu_ph_val: 'Displays the associated value in the middle (horizontally) of the selected node(s)',
            droite_val: 'Displays the associated value to the right of the selected node(s)',
            haut: 'Place the label above the selected node(s)'
          }
        },
        tags_node: {
          tags: 'Tags',
          Appartenance: 'Affiliations'
        },
        agre: {
          Agré: 'Aggregation',
          DC: 'Cube\'s dimensions',
          Parent: 'Parent',
          CLE: 'Copy childs\' links'
        },
        PF: {
          PF: 'I/O links positions',
          PFM: 'I/O links positions',
          FES: 'Links type',
          ent: 'Input',
          sort: 'Output',
          FRN: 'Relative position / node',
          gauche: 'Left',
          droite: 'Right',
          ades: 'Above',
          edes: 'Below',
          lti: 'Identify the links in the table with their colors',
          col: 'Apply',
          filter_links: 'Links to display',
          visible_links: 'Visible links',
          all_links: 'All links',
          lock: 'Lock',
          delta: 'Spacing',
          tooltips: {
            io: 'Choose either the incoming or outgoing links of the selected node',
            side: 'Choose either the right, left, top or bottom links of the selected node',
            lti: 'Display the lines of the links table with their respective colors to better identify them',
            filter_links: 'Show only visible links or all links including hidden ones',
            lock: 'Lock this anchor side: moving the opposite node will no longer reposition it. Released by any automatic layout pass.',
            delta: 'Extra spacing inserted before this anchor, to space out the links arriving on the node'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Default node style',
        LinkStyle: 'Default link style',
        ContainerStyle: 'Default container style',
        NodeContainerStyle: 'Enclosing node frame',
        NodeLeftExtremityStyle: 'Left extremity node style',
        NodeRightExtremityStyle: 'Right extremity node style',
        NodeProductStyle: 'Product label style',
        NodeSectorStyle: 'Sector label style',
        NodeImportExportCloseStyle: 'Node import-export attached',
        NodeImportCloseStyle: 'Node import attached',
        NodeExportCloseStyle: 'Node export attached',
        NodeImportExportAboveBelowStyle: 'Node import-export above/below',
        NodeImportAboveStyle: 'Node import above',
        NodeExportBelowStyle: 'Node export below',
        LinkImportExportCloseStyle: 'Link import-export attached',
        LinkImportCloseStyle: 'Link import attached',
        LinkExportCloseStyle: 'Link export attached',
        LinkImportExportAboveBelowStyle: 'Link import-export above/below',
        SankeyUnitaryNodeStyle: 'Unitary node',
        SankeyUnitaryNodeInputStyle: 'Unitary node input',
        SankeyUnitaryNodeOutputStyle: 'Unitary node output',
        LinkInUnitaryStyle: 'Unitary input link',
        LinkOutUnitaryStyle: 'Unitary output link',
        family: 'Family',
        family_predefined: 'Application styles',
        family_user: 'User styles'
      }
    }
  },
  fr: {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: 'Feuille de style',
        OrderStyle: 'Ordre des styles associés',
        editStyle: 'Assigner un style',
        multi_style: 'Multiple style sélectionné',
        SelectStyle: 'Sélectionner un style',
        AS: 'Réinitialiser',
        Reorg: 'Réorganiser automatiquement les flux E/S',
        Reorg_title: 'Ordre des flux E/S',
        Slct: 'Sélection',
        SlctOutLink: 'Sélectionner flux sortants',
        SlctInLink: 'Sélectionner flux entrants',
        SlctL: 'Sélectionner les flux',
        SlctOL: 'Sortants',
        SlctIL: 'Entrants',
        IB: 'Info-bulle',
        IS: 'Info sup.',
        align_horiz: 'Horizontalement',
        align_horiz_min: 'Par rapport au noeud sélectionné le + à gauche',
        align_horiz_max: 'Par rapport au noeud sélectionné le + à droite',
        align_vert: 'Verticalement',
        align_vert_min: 'Par rapport au noeud sélectionné le + en haut',
        align_vert_max: 'Par rapport au noeud sélectionné le + en bas',
        align_horiz_left: 'À son côté gauche',
        align_horiz_center: 'À son centre',
        align_horiz_right: 'À son côté droit',
        align_vert_top: 'À son côté du dessus',
        align_vert_bottom: 'À son côté du dessous',
        align: 'Aligner les noeuds',
        product: 'Produit',
        sector: 'Secteur',
        exchange: 'Échange',
        selector: 'Selectionner des noeuds',
        size: 'Taille',
        position: 'Position',
        text: 'Texte',
        title_desaggreg: 'Dimension desagrégation',
        title_aggreg: 'Dimension agrégation',
        text_agreg: 'Sera aggrégé en : ',
        text_desagreg: 'Sera désaggrégé en : ',
        desaggreg: 'Désagrégation',
        aggreg: 'Agrégation',
        firstPlan: 'Mettre au dernier plan',
        lastPlan: 'Mettre au premier plan',
        changePlan: 'Modifier le plan des noeud',
        mask_attr: 'Affichage des éléments',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) noeud(s) selectionné(s)',
          Reorg: 'Permet de réorganiser automatiquement les flux entrant et sortant (position haut / bas)',
          SlctOutLink: 'Permettre de sélectionner tous les flux sortants du/des noeud(s)',
          SlctInLink: 'Permettre de sélectionner tous les flux entrants vers le/les noeud(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du noeud. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le noeud',
        },
        drawing_area_tooltip: {
          outputs: 'Sorties',
          inputs: 'Entrées',
          val: 'Valeurs',
          data_value: 'Donnée collectée',
          result_value: 'Donnée calculée',
          rat: 'Ratios',
          prov: 'Entrées',
          dest: 'Sorties',
          values_tab: 'Valeurs',
          tags_tab: 'Autres informations',
          unitary_tab: 'Sankey unitaire',
          balance: 'Bilan',
          balance_diff: 'Différence (E − S)',
          balance_ok: 'Équilibré',
          balance_ko: 'Déséquilibré',
          analysis_tab: 'Analyse'
        },
        tabs: {
          apparence: 'Apparence',
          infos: 'Info sup.',
          tags: 'Étiquettes',
          io: 'Flux E/S',
        },
        apparence: {
          apparence: 'Apparence',
          Geometry: 'Géométrie',
          Cercle: 'Cercle',
          Rectangle: 'Rectangle',
          geometry: 'Positionnement',
          geometry_absolute: 'Absolu',
          geometry_relative: 'Décalage',
          geometry_parametric: 'Ecartement',
          position_u: 'Colonne',
          column_u: 'Colonne (u)',
          position_v: 'Ligne',
          row_v: 'Ligne (v)',
          column_row_uv: 'Colonne (u) / Ligne (v)',
          position_dx: 'Ecart horizontal',
          position_dy: 'Ecart vertical',
          anchor_align: 'Ancre flux',
          anchor_align_vertical: 'Ancres (côtés verticaux)',
          anchor_align_horizontal: 'Ancres (côtés horizontaux)',
          shape_io_reorg_mode: 'Réorganisation auto',
          io_reorg_mode_none: 'Aucune',
          io_reorg_mode_simple: 'Position des nœuds opposés',
          io_reorg_mode_advanced: 'Courbure, sauf flux droits',
          io_reorg_mode_anchor: 'Courbure, tous les flux',
          shape_link_inset: 'Distance des flux',
          asn: 'Appliquer le style aux noeuds',
          override_type_node_shape: 'Déverrouiller la forme',
          arrow: 'Flèche',
          shape_arrow_angle_factor: 'Inclinaison flèche',
          shape_arrow_angle_direction: 'Orientation flèche',
          display_shape: 'Afficher le noeud',
          hide_shape: 'Masquer le noeud',
          display_label: 'Afficher le nom',
          hide_label: 'Masquer le nom',
          display_value: 'Afficher la valeur',
          hide_value: 'Masquer la valeur',
          tooltips: {
            FormeDisabled: 'Désactivé car la forme est gérée par le groupe d\'étiquette "Type de noeud", si vous voulez pouvoir modifier la forme des noeuds séléctionnés, allez dans l\'onlget Étiquettes et décochez tous les étiquettes sélectionné du groupe "Type de noeud"',
            shape_anchor_align_vertical: 'Alignement vertical des ancres de flux sur les côtés gauche/droite du nœud (haut / centre / bas).',
            shape_anchor_align_horizontal: 'Alignement horizontal des ancres de flux sur les côtés haut/bas du nœud (gauche / centre / droite).',
            shape_io_reorg_mode: 'Comment l\'ordre des flux entrants/sortants est recalculé quand le diagramme change. Aucune : jamais recalculé (l\'ordre reste figé). Position des nœuds opposés : trié par la position du nœud opposé (par défaut). Courbure, sauf flux droits : les flux droits restent au centre du nœud, les autres s\'éventaillent. Courbure, tous les flux : aucune exception — tous les flux s\'éventaillent et celui qui tourne le plus tôt va à l\'extrémité.',
            shape_link_inset: 'Décalage perpendiculaire des ancres de flux par rapport au bord du nœud, en px. Positif fait rentrer les ancres DANS la boîte (les flux entrants/sortants se rejoignent à travers le nœud), négatif les écarte vers l\'extérieur. La boîte garde sa taille.',
            geometry: 'Méthode pour calculer la position du noeud. Cette position peut être donnée en coordonnées absolues x,y, en coordonnée relative u,v, ou en coordonnée relative à une autre noeud.',
            position_dx: 'Ecart horizontal entre le bord droit du noeud à gauche et le bord gauche du noeud',
            position_dy: 'Ecart vertical entre le bord inférieur du noeud au dessus et le bord supérieur du noeud',
            shape_position_u_locked: 'Si verrouillé, le calcul autosankey conserve l\'index de colonne (u) de ce nœud au lieu de le recalculer.',
            shape_position_v_locked: 'Si verrouillé, le calcul autosankey conserve l\'ordre vertical relatif (v) de ce nœud dans sa colonne au lieu de le recalculer.',
            override_type_node_shape: 'Permet de changer la forme forcée par défaut sur les noeuds de types produits et secteur',
          },
          shape_color: 'Couleur',
          shape_color_sustainable: 'Couleur statique',
          shape_min_height: 'Hauteur minimale',
          shape_min_width: 'Largeur minimale',
          shape_opacity: 'Opacité',
          shape_type: 'Forme du nœud',
          shape_visible: 'Forme'
        },
        node_value: {
          anchor: 'Position de l\'ancre',
          anchor_dx: 'Décalage horizontal',
          anchor_dy: 'Décalage vertical',
          tooltips: {
            anchor: 'L\'ancre de la valeur du noeud peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            anchor_dx: 'Décalage horizontal par rapport à l\'ancre de la valeur du noeud',
            anchor_dy: 'Décalage vertical par rapport à l\'ancre e la valeur du noeud',
          }
        },
        labels: {
          labels: 'Nom',
          node_value: 'Valeur',
          name_label_is_visible: 'Libellé',
          lb: 'Blanc',
          name_label_background: 'Fond',
          name_label_background_color: 'Couleur fond',
          pos: 'Position',
          pos_v: 'Position de la valeur',
          tp: 'Taille de police',
          cl: 'Largeur zone de texte',
          vdv: 'Valeur',
          edit_node_label: 'Éditer le nom',
          anchor: 'Position de l\'ancre',
          name_label_text_source: 'Contenu du label',
          name_label_template: 'Gabarit',
          name_label_text: 'Label personnalisé',
          name_label_tag_group: 'Groupe de tags',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatique (la première)',
          text_source: {
            name: 'Nom du nœud',
            name_container: 'Nom de l\'élément',
            custom: 'Texte personnalisé',
            template: 'Gabarit à jetons',
            tag: 'Nom long d\'un tag',
            ancestor: 'Nom du nœud ancêtre',
            name_part: 'Partie du nom (séparateur)',
          },
          tooltips: {
            name_label_text_source: 'Choisir ce qu\'affiche le label du nœud : le nom du nœud, ou un texte personnalisé indépendant (éditable sans renommer le nœud)',
            name_label_template: 'Texte construit avec des jetons remplacés au dessin, ex. « {Name} : {Value} {Unit} »',
            lb: 'Permet d\'afficher le texte du label en blanc ou en noir (utile si label positionné sur noeud(s))',
            haut: 'Positionner le label au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv: 'Positionner le label au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas: 'Positionner le label en dessous du/des noeud(s) sélectionné(s)',
            gauche: 'Positionner le label à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph: 'Positionner le label au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite: 'Positionner le label à droite du/des noeud(s) sélectionné(s)',
            cl: 'Largeur de la zone de texte (en pixel) pour le label du/des noeud(s) sélectionné(s)',
            vdv: 'Active l\'affichage de la valeur associée au(x) noeud(s) sélectionné(s)',
            anchor: 'L\'ancre du label peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            haut_val: 'Positionner l\'affichage de la valeur associée au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv_val: 'Positionner l\'affichage de la valeur associée au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas_val: 'Positionner l\'affichage de la valeur associée en dessous du/des noeud(s) sélectionné(s)',
            gauche_val: 'Positionner l\'affichage de la valeur associée à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph_val: 'Positionner l\'affichage de la valeur associée au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite_val: 'Positionner l\'affichage de la valeur associée à droite du/des noeud(s) sélectionné(s)',
            name_label_background: 'Ajoute un fond au label pour une meilleure lisibilité lorsque le label passe devant un flux',
            name_label_is_visible: 'Affiche ou non le(s) label(s) attaché(s) au(x) nœud(s) sélectionné(s)',
            top: 'Affiche le(s) label(s) au dessus du/des nœud(s) sélectionné(s)',
          }
        },
        tags_node: {
          tags: 'Étiquettes',
          Appartenance: 'Appartenance'
        },
        agre: {
          Agré: 'Agrégations',
          DC: 'Dimension du cube',
          Parent: 'Parent',
          CLE: 'Copier liens enfants'
        },
        PF: {
          PF: 'Flux E/S',
          PFM: 'Organiser flux E/S',
          FES: 'Type de flux',
          ent: 'Entrant',
          sort: 'Sortant',
          FRN: 'Position / noeud',
          gauche: 'Gauche',
          droite: 'Droite',
          ades: 'Au-dessus',
          edes: 'En-dessous',
          lti: 'Identifier les flux du tableau avec leurs couleurs',
          col: 'Appliquer',
          filter_links: 'Flux à afficher',
          visible_links: 'Flux visibles',
          all_links: 'Tous les flux',
          lock: 'Cadenas',
          delta: 'Espacement',
          tooltips: {
            io: 'Choisir les flux entrants ou sortant du noeud selectionné',
            side: 'Choisir les flux de droite, gauche, bas ou haut du noeud selectionné',
            lti: 'Affiche les lignes du tableau des flux avec leur couleurs respectives pour mieux les identifier',
            filter_links: 'Afficher uniquement les flux visibles ou tous les flux y compris les masqués',
            lock: 'Verrouille le côté de cette ancre : déplacer le noeud opposé ne la repositionnera plus. Relâché par tout recalcul automatique.',
            delta: 'Espacement supplémentaire inséré avant cette ancre, pour espacer les flux qui arrivent sur le noeud'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Style de noeud par défaut',
        LinkStyle: 'Style de flux par défaut',
        ContainerStyle: 'Style de container par défaut',
        NodeContainerStyle: 'Cadre englobant de nœuds',
        NodeLeftExtremityStyle: 'Style noeud extrémité gauche',
        NodeRightExtremityStyle: 'Style noeud extrémité droite',
        NodeProductStyle: 'Style étiquette produit',
        NodeSectorStyle: 'Style étiquette secteur',
        NodeImportExportCloseStyle: 'Noeud import export collé',
        NodeImportCloseStyle: 'Noeud import collé',
        NodeExportCloseStyle: 'Noeud export collé',
        NodeImportExportAboveBelowStyle: 'Noeud import export dessus/dessous',
        NodeImportAboveStyle: 'Noeud import au dessus',
        NodeExportBelowStyle: 'Noeud export au dessous',
        LinkImportExportCloseStyle: 'Flux import export collé',
        LinkImportCloseStyle: 'Flux import collé',
        LinkExportCloseStyle: 'Flux export collé',
        LinkImportExportAboveBelowStyle: 'Flux import export haut/bas',
        SankeyUnitaryNodeStyle: 'Unitaire noeud',
        SankeyUnitaryNodeInputStyle: 'Unitaire noeud entrée',
        SankeyUnitaryNodeOutputStyle: 'Unitaire noeud sortie',
        LinkInUnitaryStyle: 'Unitaire flux entrée',
        LinkOutUnitaryStyle: 'Unitaire flux sortie',
        family: 'Famille',
        family_predefined: 'Styles de l\'application',
        family_user: 'Styles utilisateur'
      }
    }
  },
  es: {
    translation: {
      Noeud: {
        Style: 'Hoja de estilo',
        OrderStyle: 'Orden de estilos asociados',
        multi_style: 'Los nodos seleccionados tienen estilos diferentes',
        editStyle: 'Asignar un estilo',
        AS: 'Restablecer',
        SelectStyle: 'Seleccionar un estilo',
        Reorg: 'Reorganizar flujos de entrada/salida',
        Reorg_title: 'Reorganización',
        Slct: 'Selección',
        SlctOutLink: 'Seleccionar flujos salientes',
        SlctInLink: 'Seleccionar flujos entrantes',
        SlctL: 'Seleccionar los flujos',
        SlctOL: 'Salientes',
        SlctIL: 'Entrantes',
        IB: 'Tooltip',
        IS: 'Info. adicional',
        align_horiz: 'Horizontalmente',
        align_horiz_min: 'Respecto al nodo seleccionado más a la izquierda',
        align_horiz_max: 'Respecto al nodo seleccionado más a la derecha',
        align_vert: 'Verticalmente',
        align_vert_min: 'Respecto al nodo seleccionado más arriba',
        align_vert_max: 'Respecto al nodo seleccionado más abajo',
        align_horiz_left: 'Alinear a su izquierda',
        align_horiz_center: 'Alinear a su centro',
        align_horiz_right: 'Alinear a su derecha',
        align_vert_top: 'Alinear a su parte superior',
        align_vert_bottom: 'Alinear a su parte inferior',
        align: 'Alinear nodos',
        product: 'Producto',
        sector: 'Sector',
        exchange: 'Intercambio',
        size: 'Tamaño',
        position: 'Posición',
        text: 'Texto',
        selector: 'Seleccionar nodos',
        title_desaggreg: 'Desagregación de dimensión',
        title_aggreg: 'Agregación de dimensión',
        text_agreg: 'Se agregará en: ',
        text_desagreg: 'Se desagregará en: ',
        desaggreg: 'Desagregación',
        aggreg: 'Agregación',
        firstPlan: 'Enviar al fondo',
        lastPlan: 'Traer al frente',
        changePlan: 'Cambiar plano de los nodos',
        mask_attr: 'Visualización de elementos',
        tooltips: {
          AS: 'Permite aplicar un estilo predefinido del menú de preferencias a los nodos seleccionados',
          Reorg: 'Permite reorganizar automáticamente los flujos entrantes y salientes (posición arriba/abajo)',
          SlctOutLink: 'Permite seleccionar todos los flujos salientes del/de los nodo(s)',
          SlctInLink: 'Permite seleccionar todos los flujos entrantes al/a los nodo(s)',
          IB: 'Tooltip: texto en formato HTML que se muestra con el tooltip del nodo. Este tooltip aparece en el espacio gráfico con SHIFT + RATÓN sobre el nodo.',
        },
        drawing_area_tooltip: {
          outputs: 'Salidas',
          inputs: 'Entradas',
          dest: 'Salidas',
          val: 'Valores',
          data_value: 'Dato recopilado',
          result_value: 'Dato calculado',
          rat: 'Ratios',
          prov: 'Entradas',
          values_tab: 'Valores',
          tags_tab: 'Otras informaciones',
          unitary_tab: 'Sankey unitario',
          balance: 'Balance',
          balance_diff: 'Diferencia (E − S)',
          balance_ok: 'Equilibrado',
          balance_ko: 'Desequilibrado',
          analysis_tab: 'Análisis'
        },
        tabs: {
          apparence: 'Apariencia',
          infos: 'Info. adicional',
          tags: 'Etiquetas',
          io: 'Flujos E/S',
        },
        apparence: {
          apparence: 'Apariencia',
          shape_visible: 'Forma',
          shape_color: 'Color',
          shape_color_sustainable: 'Color estático',
          shape_type: 'Forma del nodo',
          Geometry: 'Geometría',
          Cercle: 'Arco',
          Rectangle: 'Rectángulo',
          shape_min_width: 'Ancho mínimo',
          shape_min_height: 'Alto mínimo',
          geometry: 'Posicionamiento',
          geometry_absolute: 'Absoluto',
          geometry_parametric: 'Espaciado',
          geometry_relative: 'Desplazamiento',
          position_u: 'Columna',
          column_u: 'Columna (u)',
          position_v: 'Fila',
          row_v: 'Fila (v)',
          column_row_uv: 'Columna (u) / Fila (v)',
          position_dx: 'Separación horizontal',
          position_dy: 'Separación vertical',
          anchor_align: 'Anclas de flujo',
          anchor_align_vertical: 'Anclas (lados verticales)',
          anchor_align_horizontal: 'Anclas (lados horizontales)',
          shape_io_reorg_mode: 'Reorganización auto',
          io_reorg_mode_none: 'Ninguna',
          io_reorg_mode_simple: 'Posición de los nodos opuestos',
          io_reorg_mode_advanced: 'Curvatura, salvo flujos rectos',
          io_reorg_mode_anchor: 'Curvatura, todos los flujos',
          shape_link_inset: 'Distancia de flujos',
          asn: 'Aplicar estilo a los nodos',
          override_type_node_shape: 'Desbloquear la forma',
          arrow: 'Flecha',
          display_shape: 'Mostrar el nodo',
          hide_shape: 'Ocultar el nodo',
          display_label: 'Mostrar la etiqueta',
          hide_label: 'Ocultar la etiqueta',
          display_value: 'Mostrar el valor',
          hide_value: 'Ocultar el valor',
          shape_opacity: 'Opacidad',
          tooltips: {
            FormeDisabled: 'Desactivado porque la forma está gestionada por el grupo de etiquetas "Tipo de nodo". Si desea cambiar la forma de los nodos seleccionados, vaya a la pestaña "Etiquetas" y desmarque todas las etiquetas seleccionadas del grupo "Tipo de nodo".',
            shape_anchor_align_vertical: 'Alineación vertical de las anclas de flujo en los lados izquierdo/derecho del nodo (arriba / centro / abajo).',
            shape_anchor_align_horizontal: 'Alineación horizontal de las anclas de flujo en los lados superior/inferior del nodo (izquierda / centro / derecha).',
            shape_io_reorg_mode: 'Cómo se recalcula el orden de los flujos entrantes/salientes cuando cambia el diagrama. Ninguna: nunca se recalcula (el orden queda fijo). Posición de los nodos opuestos: ordenado por la posición del nodo opuesto (por defecto). Curvatura, salvo flujos rectos: los flujos rectos permanecen en el centro del nodo, los demás se abren en abanico. Curvatura, todos los flujos: sin excepción — todos se abren en abanico y el que gira antes va al extremo.',
            shape_link_inset: 'Desplazamiento perpendicular de las anclas de flujo respecto al borde del nodo, en px. Positivo mete las anclas DENTRO de la caja (los flujos entrantes/salientes se unen a través del nodo), negativo las aleja. La caja conserva su tamaño.',
            geometry: 'Método para calcular la posición del nodo. La posición puede darse en coordenadas absolutas x,y, en coordenadas relativas u,v, o en coordenadas relativas a otro nodo.',
            position_dx: 'Separación horizontal entre el borde derecho del nodo a la izquierda y el borde izquierdo del nodo',
            position_dy: 'Separación vertical entre el borde inferior del nodo superior y el borde superior del nodo',
            shape_position_u_locked: 'Si está bloqueado, el cálculo autosankey conserva el índice de columna (u) de este nodo en lugar de recalcularlo.',
            shape_position_v_locked: 'Si está bloqueado, el cálculo autosankey conserva el orden vertical relativo (v) de este nodo en su columna en lugar de recalcularlo.',
            override_type_node_shape: 'Permite cambiar la forma forzada por defecto en los nodos de tipo producto y sector',
          },
          shape_arrow_angle_direction: 'Orientación de la flecha',
          shape_arrow_angle_factor: 'Inclinación de la flecha'
        },
        node_value: {
          anchor: 'Posición del ancla',
          anchor_dx: 'Desplazamiento horizontal',
          anchor_dy: 'Desplazamiento vertical',
          tooltips: {
            anchor: 'El ancla del valor del nodo se puede posicionar de 9 maneras respecto a la forma, combinando horizontalmente borde izquierdo, centro y borde derecho, y verticalmente borde superior, centro y borde inferior',
            anchor_dx: 'Desplazamiento horizontal respecto al ancla del valor del nodo',
            anchor_dy: 'Desplazamiento vertical respecto al ancla del valor del nodo',
          }
        },
        labels: {
          labels: 'Nombre',
          node_value: 'Valor',
          name_label_is_visible: 'Etiqueta',
          lb: 'Etiqueta blanca',
          name_label_background: 'Fondo',
          name_label_background_color: 'Color de fondo',
          pos: 'Posición',
          pos_v: 'Posición del valor',
          tp: 'Tamaño de fuente',
          cl: 'Ancho del área de texto',
          vdv: 'Valor',
          edit_node_label: 'Editar nombre del nodo',
          anchor: 'Posición del ancla',
          name_label_text_source: 'Contenido de la etiqueta',
          name_label_template: 'Plantilla',
          name_label_text: 'Etiqueta personalizada',
          name_label_tag_group: 'Grupo de etiquetas',
          name_label_tag: 'Etiqueta',
          name_label_dimension: 'Dimensión',
          name_label_dimension_auto: 'Automática (la primera)',
          text_source: {
            name: 'Nombre del nodo',
            name_container: 'Nombre del elemento',
            custom: 'Texto personalizado',
            template: 'Plantilla con marcadores',
            tag: 'Nombre largo de una etiqueta',
            ancestor: 'Nombre del nodo ancestro',
            name_part: 'Parte del nombre (separador)',
          },
          tooltips: {
            name_label_text_source: 'Elegir lo que muestra la etiqueta del nodo: el nombre del nodo, o un texto personalizado independiente (editable sin renombrar el nodo)',
            name_label_template: 'Texto construido con marcadores sustituidos al dibujar, p. ej. «{Name}: {Value} {Unit}»',
            name_label_is_visible: 'Muestra u oculta la(s) etiqueta(s) asociada(s) al/a los nodo(s) seleccionado(s)',
            lb: 'Muestra el texto de la(s) etiqueta(s) en blanco o negro (útil si la etiqueta está sobre el/los nodo(s))',
            name_label_background: 'Añade un fondo a la etiqueta para mejor visibilidad cuando está delante de un flujo',
            top: 'Muestra la(s) etiqueta(s) encima del/de los nodo(s) seleccionado(s)',
            Milieu_pv: 'Muestra la(s) etiqueta(s) en el centro (verticalmente) del/de los nodo(s) seleccionado(s)',
            Bas: 'Muestra la(s) etiqueta(s) debajo del/de los nodo(s) seleccionado(s)',
            gauche: 'Muestra la(s) etiqueta(s) a la izquierda del/de los nodo(s) seleccionado(s)',
            Milieu_ph: 'Muestra la(s) etiqueta(s) en el centro (horizontalmente) del/de los nodo(s) seleccionado(s)',
            droite: 'Muestra la(s) etiqueta(s) a la derecha del/de los nodo(s) seleccionado(s)',
            cl: 'Ancho del área de texto (en píxeles) para la(s) etiqueta(s) del/de los nodo(s) seleccionado(s)',
            vdv: 'Muestra u oculta el valor asociado al/a los nodo(s) seleccionado(s)',
            anchor: 'El ancla de la etiqueta se puede posicionar de 9 maneras respecto a la forma, combinando horizontalmente borde izquierdo, centro y borde derecho, y verticalmente borde superior, centro y borde inferior',
            haut_val: 'Muestra el valor asociado encima del/de los nodo(s) seleccionado(s)',
            Milieu_pv_val: 'Muestra el valor asociado en el centro (verticalmente) del/de los nodo(s) seleccionado(s)',
            Bas_val: 'Muestra el valor asociado debajo del/de los nodo(s) seleccionado(s)',
            gauche_val: 'Muestra el valor asociado a la izquierda del/de los nodo(s) seleccionado(s)',
            Milieu_ph_val: 'Muestra el valor asociado en el centro (horizontalmente) del/de los nodo(s) seleccionado(s)',
            droite_val: 'Muestra el valor asociado a la derecha del/de los nodo(s) seleccionado(s)',
            haut: 'Colocar la etiqueta encima del/de los nodo(s) seleccionado(s)'
          }
        },
        tags_node: {
          tags: 'Etiquetas',
          Appartenance: 'Pertenencia'
        },
        agre: {
          Agré: 'Agregación',
          DC: 'Dimensiones del cubo',
          Parent: 'Padre',
          CLE: 'Copiar flujos hijos'
        },
        PF: {
          PF: 'Flujos E/S',
          PFM: 'Organizar flujos E/S',
          FES: 'Tipo de flujo',
          ent: 'Entrada',
          sort: 'Salida',
          FRN: 'Posición relativa / nodo',
          gauche: 'Izquierda',
          droite: 'Derecha',
          ades: 'Encima',
          edes: 'Debajo',
          lti: 'Identificar los flujos de la tabla con sus colores',
          col: 'Aplicar',
          filter_links: 'Flujos a mostrar',
          visible_links: 'Flujos visibles',
          all_links: 'Todos los flujos',
          lock: 'Candado',
          delta: 'Espaciado',
          tooltips: {
            io: 'Elegir los flujos entrantes o salientes del nodo seleccionado',
            side: 'Elegir los flujos de la derecha, izquierda, arriba o abajo del nodo seleccionado',
            lti: 'Mostrar las líneas de la tabla de flujos con sus colores respectivos para identificarlos mejor',
            filter_links: 'Mostrar solo los flujos visibles o todos los flujos incluidos los ocultos',
            lock: 'Bloquea el lado de este anclaje: mover el nodo opuesto ya no lo reposicionará. Se libera con cualquier cálculo automático.',
            delta: 'Espaciado adicional insertado antes de este anclaje, para separar los flujos que llegan al nodo'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Estilo de nodo por defecto',
        LinkStyle: 'Estilo de flujo por defecto',
        ContainerStyle: 'Estilo de contenedor por defecto',
        NodeContainerStyle: 'Marco englobante de nodos',
        NodeLeftExtremityStyle: 'Estilo nodo extremidad izquierda',
        NodeRightExtremityStyle: 'Estilo nodo extremidad derecha',
        NodeProductStyle: 'Estilo etiqueta producto',
        NodeSectorStyle: 'Estilo etiqueta sector',
        NodeImportExportCloseStyle: 'Nodo import-export adjunto',
        NodeImportCloseStyle: 'Nodo import adjunto',
        NodeExportCloseStyle: 'Nodo export adjunto',
        NodeImportExportAboveBelowStyle: 'Nodo import-export arriba/abajo',
        NodeImportAboveStyle: 'Nodo import arriba',
        NodeExportBelowStyle: 'Nodo export abajo',
        LinkImportExportCloseStyle: 'Flujo import-export adjunto',
        LinkImportCloseStyle: 'Flujo import adjunto',
        LinkExportCloseStyle: 'Flujo export adjunto',
        LinkImportExportAboveBelowStyle: 'Flujo import-export arriba/abajo',
        SankeyUnitaryNodeStyle: 'Nodo unitario',
        SankeyUnitaryNodeInputStyle: 'Nodo unitario entrada',
        SankeyUnitaryNodeOutputStyle: 'Nodo unitario salida',
        LinkInUnitaryStyle: 'Flujo unitario entrada',
        LinkOutUnitaryStyle: 'Flujo unitario salida',
        family: 'Familia',
        family_predefined: 'Estilos de la aplicación',
        family_user: 'Estilos de usuario'
      }
    }
  },
  de: {
    translation: {
      Noeud: {
        Style: 'Stilvorlage',
        OrderStyle: 'Reihenfolge der zugeordneten Stile',
        multi_style: 'Ausgewählte Knoten haben unterschiedliche Stile',
        editStyle: 'Stil zuweisen',
        AS: 'Zurücksetzen',
        SelectStyle: 'Stil auswählen',
        Reorg: 'Ein-/Ausgangsflüsse reorganisieren',
        Reorg_title: 'Reorganisation',
        Slct: 'Auswahl',
        SlctOutLink: 'Ausgehende Flüsse auswählen',
        SlctInLink: 'Eingehende Flüsse auswählen',
        SlctL: 'Flüsse auswählen',
        SlctOL: 'Ausgehend',
        SlctIL: 'Eingehend',
        IB: 'Tooltip',
        IS: 'Zusatzinfo',
        align_horiz: 'Horizontal',
        align_horiz_min: 'Relativ zum am weitesten links befindlichen ausgewählten Knoten',
        align_horiz_max: 'Relativ zum am weitesten rechts befindlichen ausgewählten Knoten',
        align_vert: 'Vertikal',
        align_vert_min: 'Relativ zum am weitesten oben befindlichen ausgewählten Knoten',
        align_vert_max: 'Relativ zum am weitesten unten befindlichen ausgewählten Knoten',
        align_horiz_left: 'An seiner linken Seite ausrichten',
        align_horiz_center: 'An seiner Mitte ausrichten',
        align_horiz_right: 'An seiner rechten Seite ausrichten',
        align_vert_top: 'An seiner Oberseite ausrichten',
        align_vert_bottom: 'An seiner Unterseite ausrichten',
        align: 'Knoten ausrichten',
        product: 'Produkt',
        sector: 'Sektor',
        exchange: 'Austausch',
        size: 'Größe',
        position: 'Position',
        text: 'Text',
        selector: 'Knoten auswählen',
        title_desaggreg: 'Dimensionsdisaggregation',
        title_aggreg: 'Dimensionsaggregation',
        text_agreg: 'Wird aggregiert in: ',
        text_desagreg: 'Wird disaggregiert in: ',
        desaggreg: 'Disaggregation',
        aggreg: 'Aggregation',
        firstPlan: 'In den Hintergrund verschieben',
        lastPlan: 'In den Vordergrund verschieben',
        changePlan: 'Ebene der Knoten ändern',
        mask_attr: 'Elementanzeige',
        tooltips: {
          AS: 'Ermöglicht das Anwenden eines vordefinierten Stils aus dem Einstellungsmenü auf die ausgewählten Knoten',
          Reorg: 'Ermöglicht die automatische Reorganisation der ein- und ausgehenden Flüsse (Position oben/unten)',
          SlctOutLink: 'Ermöglicht die Auswahl aller ausgehenden Flüsse des/der Knoten(s)',
          SlctInLink: 'Ermöglicht die Auswahl aller eingehenden Flüsse zum/zu den Knoten',
          IB: 'Tooltip: HTML-formatierter Text, der mit dem Tooltip des Knotens angezeigt wird. Dieser Tooltip erscheint im Grafikbereich mit SHIFT + MAUS auf dem Knoten.',
        },
        drawing_area_tooltip: {
          outputs: 'Ausgänge',
          inputs: 'Eingänge',
          dest: 'Ausgänge',
          val: 'Werte',
          data_value: 'Erhobene Daten',
          result_value: 'Berechnete Daten',
          rat: 'Verhältnisse',
          prov: 'Eingänge',
          values_tab: 'Werte',
          tags_tab: 'Weitere Informationen',
          unitary_tab: 'Einheits-Sankey',
          balance: 'Bilanz',
          balance_diff: 'Differenz (Ein − Aus)',
          balance_ok: 'Ausgeglichen',
          balance_ko: 'Unausgeglichen',
          analysis_tab: 'Analyse'
        },
        tabs: {
          apparence: 'Darstellung',
          infos: 'Zusatzinfo',
          tags: 'Tags',
          io: 'E/A-Flüsse',
        },
        apparence: {
          apparence: 'Darstellung',
          shape_visible: 'Form',
          shape_color: 'Farbe',
          shape_color_sustainable: 'Statische Farbe',
          shape_type: 'Knotenform',
          Geometry: 'Geometrie',
          Cercle: 'Bogen',
          Rectangle: 'Rechteck',
          shape_min_width: 'Mindestbreite',
          shape_min_height: 'Mindesthöhe',
          geometry: 'Positionierung',
          geometry_absolute: 'Absolut',
          geometry_parametric: 'Abstand',
          geometry_relative: 'Versatz',
          position_u: 'Spalte',
          column_u: 'Spalte (u)',
          position_v: 'Zeile',
          row_v: 'Zeile (v)',
          column_row_uv: 'Spalte (u) / Zeile (v)',
          position_dx: 'Horizontaler Abstand',
          position_dy: 'Vertikaler Abstand',
          anchor_align: 'Flussanker',
          anchor_align_vertical: 'Anker (vertikale Seiten)',
          anchor_align_horizontal: 'Anker (horizontale Seiten)',
          shape_io_reorg_mode: 'Auto-Neuordnung',
          io_reorg_mode_none: 'Keine',
          io_reorg_mode_simple: 'Position der Gegenknoten',
          io_reorg_mode_advanced: 'Krümmung, außer geraden Flüssen',
          io_reorg_mode_anchor: 'Krümmung, alle Flüsse',
          shape_link_inset: 'Flussabstand',
          asn: 'Stil auf Knoten anwenden',
          override_type_node_shape: 'Form freischalten',
          arrow: 'Pfeil',
          display_shape: 'Knoten anzeigen',
          hide_shape: 'Knoten ausblenden',
          display_label: 'Beschriftung anzeigen',
          hide_label: 'Beschriftung ausblenden',
          display_value: 'Wert anzeigen',
          hide_value: 'Wert ausblenden',
          shape_opacity: 'Deckkraft',
          tooltips: {
            FormeDisabled: 'Deaktiviert, da die Form von der Tag-Gruppe "Knotentyp" verwaltet wird. Wenn Sie die Form der ausgewählten Knoten ändern möchten, gehen Sie zum Tab "Tags" und deaktivieren Sie alle ausgewählten Tags der Gruppe "Knotentyp".',
            shape_anchor_align_vertical: 'Vertikale Ausrichtung der Flussanker an den linken/rechten Seiten des Knotens (oben / Mitte / unten).',
            shape_anchor_align_horizontal: 'Horizontale Ausrichtung der Flussanker an den oberen/unteren Seiten des Knotens (links / Mitte / rechts).',
            shape_io_reorg_mode: 'Wie die Reihenfolge der ein-/ausgehenden Flüsse bei Änderungen am Diagramm neu berechnet wird. Keine: nie neu berechnet (Reihenfolge bleibt fest). Position der Gegenknoten: nach der Position des gegenüberliegenden Knotens sortiert (Standard). Krümmung, außer geraden Flüssen: gerade Flüsse bleiben in der Knotenmitte, die übrigen fächern auf. Krümmung, alle Flüsse: keine Ausnahme — alle fächern auf, und der zuerst abbiegende Fluss geht ans Ende.',
            shape_link_inset: 'Senkrechter Versatz der Flussanker relativ zum Knotenrand, in px. Positiv zieht die Anker IN die Box (ein-/ausgehende Flüsse treffen sich durch den Knoten), negativ schiebt sie nach außen. Die Box behält ihre Größe.',
            geometry: 'Methode zur Berechnung der Knotenposition. Die Position kann in absoluten Koordinaten x,y, in relativen Koordinaten u,v oder relativ zu einem anderen Knoten angegeben werden.',
            position_dx: 'Horizontaler Abstand zwischen dem rechten Rand des linken Knotens und dem linken Rand des Knotens',
            position_dy: 'Vertikaler Abstand zwischen dem unteren Rand des oberen Knotens und dem oberen Rand des Knotens',
            shape_position_u_locked: 'Wenn gesperrt, behält die Autosankey-Berechnung den Spaltenindex (u) dieses Knotens bei, anstatt ihn neu zu berechnen.',
            shape_position_v_locked: 'Wenn gesperrt, behält die Autosankey-Berechnung die relative vertikale Reihenfolge (v) dieses Knotens in seiner Spalte bei, anstatt sie neu zu berechnen.',
            override_type_node_shape: 'Ermöglicht das Ändern der standardmäßig erzwungenen Form bei Produkt- und Sektorknoten',
          },
          shape_arrow_angle_direction: 'Pfeilausrichtung',
          shape_arrow_angle_factor: 'Pfeilneigung'
        },
        node_value: {
          anchor: 'Ankerposition',
          anchor_dx: 'Horizontaler Versatz',
          anchor_dy: 'Vertikaler Versatz',
          tooltips: {
            anchor: 'Der Anker des Knotenwerts kann auf 9 Arten relativ zur Form positioniert werden, indem horizontal linker Rand, Mitte und rechter Rand und vertikal oberer Rand, Mitte und unterer Rand kombiniert werden',
            anchor_dx: 'Horizontaler Versatz vom Anker des Knotenwerts',
            anchor_dy: 'Vertikaler Versatz vom Anker des Knotenwerts',
          }
        },
        labels: {
          labels: 'Name',
          node_value: 'Wert',
          name_label_is_visible: 'Beschriftung',
          lb: 'Weiße Beschriftung',
          name_label_background: 'Hintergrund',
          name_label_background_color: 'Hintergrundfarbe',
          pos: 'Position',
          pos_v: 'Wertposition',
          tp: 'Schriftgröße',
          cl: 'Textfeldbreite',
          vdv: 'Wert',
          edit_node_label: 'Knotenbezeichnung bearbeiten',
          anchor: 'Ankerposition',
          name_label_text_source: 'Beschriftungsinhalt',
          name_label_template: 'Vorlage',
          name_label_text: 'Benutzerdefinierte Beschriftung',
          name_label_tag_group: 'Tag-Gruppe',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatisch (erste)',
          text_source: {
            name: 'Knotenname',
            name_container: 'Elementname',
            custom: 'Benutzerdefinierter Text',
            template: 'Vorlage mit Platzhaltern',
            tag: 'Langer Tag-Name',
            ancestor: 'Name des Vorfahrknotens',
            name_part: 'Namensteil (Trennzeichen)',
          },
          tooltips: {
            name_label_text_source: 'Wählen, was die Knotenbeschriftung anzeigt: den Knotennamen oder einen unabhängigen benutzerdefinierten Text (bearbeitbar, ohne den Knoten umzubenennen)',
            name_label_template: 'Text aus Platzhaltern, die beim Zeichnen ersetzt werden, z. B. „{Name}: {Value} {Unit}“',
            name_label_is_visible: 'Zeigt oder verbirgt die Beschriftung(en) des/der ausgewählten Knoten(s)',
            lb: 'Zeigt den Text der Beschriftung(en) in Weiß oder Schwarz an (nützlich, wenn die Beschriftung auf dem/den Knoten positioniert ist)',
            name_label_background: 'Fügt einen Hintergrund zur Beschriftung hinzu für bessere Sichtbarkeit, wenn sie vor einem Fluss liegt',
            top: 'Zeigt die Beschriftung(en) oberhalb des/der ausgewählten Knoten(s) an',
            Milieu_pv: 'Zeigt die Beschriftung(en) in der Mitte (vertikal) des/der ausgewählten Knoten(s) an',
            Bas: 'Zeigt die Beschriftung(en) unterhalb des/der ausgewählten Knoten(s) an',
            gauche: 'Zeigt die Beschriftung(en) links vom/von den ausgewählten Knoten an',
            Milieu_ph: 'Zeigt die Beschriftung(en) in der Mitte (horizontal) des/der ausgewählten Knoten(s) an',
            droite: 'Zeigt die Beschriftung(en) rechts vom/von den ausgewählten Knoten an',
            cl: 'Breite des Textbereichs (in Pixeln) für die Beschriftung(en) des/der ausgewählten Knoten(s)',
            vdv: 'Zeigt oder verbirgt den zugehörigen Wert des/der ausgewählten Knoten(s)',
            anchor: 'Der Anker der Beschriftung kann auf 9 Arten relativ zur Form positioniert werden, indem horizontal linker Rand, Mitte und rechter Rand und vertikal oberer Rand, Mitte und unterer Rand kombiniert werden',
            haut_val: 'Zeigt den zugehörigen Wert oberhalb des/der ausgewählten Knoten(s) an',
            Milieu_pv_val: 'Zeigt den zugehörigen Wert in der Mitte (vertikal) des/der ausgewählten Knoten(s) an',
            Bas_val: 'Zeigt den zugehörigen Wert unterhalb des/der ausgewählten Knoten(s) an',
            gauche_val: 'Zeigt den zugehörigen Wert links vom/von den ausgewählten Knoten an',
            Milieu_ph_val: 'Zeigt den zugehörigen Wert in der Mitte (horizontal) des/der ausgewählten Knoten(s) an',
            droite_val: 'Zeigt den zugehörigen Wert rechts vom/von den ausgewählten Knoten an',
            haut: 'Beschriftung oberhalb der ausgewählten Knoten platzieren'
          }
        },
        tags_node: {
          tags: 'Tags',
          Appartenance: 'Zugehörigkeit'
        },
        agre: {
          Agré: 'Aggregation',
          DC: 'Würfeldimensionen',
          Parent: 'Elternknoten',
          CLE: 'Kindflüsse kopieren'
        },
        PF: {
          PF: 'E/A-Flüsse',
          PFM: 'E/A-Flüsse organisieren',
          FES: 'Flusstyp',
          ent: 'Eingang',
          sort: 'Ausgang',
          FRN: 'Relative Position / Knoten',
          gauche: 'Links',
          droite: 'Rechts',
          ades: 'Darüber',
          edes: 'Darunter',
          lti: 'Flüsse in der Tabelle mit ihren Farben kennzeichnen',
          col: 'Anwenden',
          filter_links: 'Anzuzeigende Flüsse',
          visible_links: 'Sichtbare Flüsse',
          all_links: 'Alle Flüsse',
          lock: 'Schloss',
          delta: 'Abstand',
          tooltips: {
            io: 'Eingehende oder ausgehende Flüsse des ausgewählten Knotens auswählen',
            side: 'Rechte, linke, obere oder untere Flüsse des ausgewählten Knotens auswählen',
            lti: 'Zeigt die Zeilen der Flusstabelle mit ihren jeweiligen Farben an, um sie besser zu identifizieren',
            filter_links: 'Nur sichtbare Flüsse oder alle Flüsse einschließlich der verborgenen anzeigen',
            lock: 'Sperrt die Seite dieses Ankers: Das Verschieben des gegenüberliegenden Knotens positioniert ihn nicht mehr neu. Wird durch jede automatische Berechnung aufgehoben.',
            delta: 'Zusätzlicher Abstand vor diesem Anker, um die am Knoten ankommenden Flüsse zu verteilen'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Standard-Knotenstil',
        LinkStyle: 'Standard-Flussstil',
        ContainerStyle: 'Standard-Containerstil',
        NodeContainerStyle: 'Umschließender Knotenrahmen',
        NodeLeftExtremityStyle: 'Knotenstil linkes Ende',
        NodeRightExtremityStyle: 'Knotenstil rechtes Ende',
        NodeProductStyle: 'Produktbezeichnung-Stil',
        NodeSectorStyle: 'Sektorbezeichnung-Stil',
        NodeImportExportCloseStyle: 'Knoten Import-Export angehängt',
        NodeImportCloseStyle: 'Knoten Import angehängt',
        NodeExportCloseStyle: 'Knoten Export angehängt',
        NodeImportExportAboveBelowStyle: 'Knoten Import-Export oben/unten',
        NodeImportAboveStyle: 'Knoten Import oben',
        NodeExportBelowStyle: 'Knoten Export unten',
        LinkImportExportCloseStyle: 'Fluss Import-Export angehängt',
        LinkImportCloseStyle: 'Fluss Import angehängt',
        LinkExportCloseStyle: 'Fluss Export angehängt',
        LinkImportExportAboveBelowStyle: 'Fluss Import-Export oben/unten',
        SankeyUnitaryNodeStyle: 'Einheitsknoten',
        SankeyUnitaryNodeInputStyle: 'Einheitsknoten Eingang',
        SankeyUnitaryNodeOutputStyle: 'Einheitsknoten Ausgang',
        LinkInUnitaryStyle: 'Einheitsfluss Eingang',
        LinkOutUnitaryStyle: 'Einheitsfluss Ausgang',
        family: 'Familie',
        family_predefined: 'Anwendungsstile',
        family_user: 'Benutzerstile'
      }
    }
  },
  it: {
    translation: {
      Noeud: {
        Style: 'Foglio di stile',
        OrderStyle: 'Ordine degli stili associati',
        multi_style: 'I nodi selezionati hanno stili diversi',
        editStyle: 'Assegnare uno stile',
        AS: 'Ripristina',
        SelectStyle: 'Selezionare uno stile',
        Reorg: 'Riorganizzare i flussi in ingresso/uscita',
        Reorg_title: 'Riorganizzazione',
        Slct: 'Selezione',
        SlctOutLink: 'Selezionare flussi in uscita',
        SlctInLink: 'Selezionare flussi in ingresso',
        SlctL: 'Selezionare i flussi',
        SlctOL: 'In uscita',
        SlctIL: 'In ingresso',
        IB: 'Tooltip',
        IS: 'Info aggiuntive',
        align_horiz: 'Orizzontalmente',
        align_horiz_min: 'Rispetto al nodo selezionato più a sinistra',
        align_horiz_max: 'Rispetto al nodo selezionato più a destra',
        align_vert: 'Verticalmente',
        align_vert_min: 'Rispetto al nodo selezionato più in alto',
        align_vert_max: 'Rispetto al nodo selezionato più in basso',
        align_horiz_left: 'Allinea a sinistra',
        align_horiz_center: 'Allinea al centro',
        align_horiz_right: 'Allinea a destra',
        align_vert_top: 'Allinea in alto',
        align_vert_bottom: 'Allinea in basso',
        align: 'Allinea nodi',
        product: 'Prodotto',
        sector: 'Settore',
        exchange: 'Scambio',
        size: 'Dimensione',
        position: 'Posizione',
        text: 'Testo',
        selector: 'Seleziona nodi',
        title_desaggreg: 'Disaggregazione dimensione',
        title_aggreg: 'Aggregazione dimensione',
        text_agreg: 'Verrà aggregato in: ',
        text_desagreg: 'Verrà disaggregato in: ',
        desaggreg: 'Disaggregazione',
        aggreg: 'Aggregazione',
        firstPlan: 'Porta in secondo piano',
        lastPlan: 'Porta in primo piano',
        changePlan: 'Cambia piano dei nodi',
        mask_attr: 'Visualizzazione elementi',
        tooltips: {
          AS: 'Permette di applicare uno stile predefinito dal menu preferenze ai nodi selezionati',
          Reorg: 'Permette di riorganizzare automaticamente i flussi in ingresso e in uscita (posizione su/giù)',
          SlctOutLink: 'Permette di selezionare tutti i flussi in uscita dal/dai nodo/i',
          SlctInLink: 'Permette di selezionare tutti i flussi in ingresso al/ai nodo/i',
          IB: 'Tooltip: testo formattato in HTML visualizzato con il tooltip del nodo. Questo tooltip appare nello spazio grafico con SHIFT + MOUSE sul nodo.',
        },
        drawing_area_tooltip: {
          outputs: 'Uscite',
          inputs: 'Ingressi',
          dest: 'Uscite',
          val: 'Valori',
          data_value: 'Dato raccolto',
          result_value: 'Dato calcolato',
          rat: 'Rapporti',
          prov: 'Ingressi',
          values_tab: 'Valori',
          tags_tab: 'Altre informazioni',
          unitary_tab: 'Sankey unitario',
          balance: 'Bilancio',
          balance_diff: 'Differenza (In − Out)',
          balance_ok: 'Bilanciato',
          balance_ko: 'Sbilanciato',
          analysis_tab: 'Analisi'
        },
        tabs: {
          apparence: 'Aspetto',
          infos: 'Info aggiuntive',
          tags: 'Tag',
          io: 'Flussi I/O',
        },
        apparence: {
          apparence: 'Aspetto',
          shape_visible: 'Forma',
          shape_color: 'Colore',
          shape_color_sustainable: 'Colore statico',
          shape_type: 'Forma del nodo',
          Geometry: 'Geometria',
          Cercle: 'Arco',
          Rectangle: 'Rettangolo',
          shape_min_width: 'Larghezza minima',
          shape_min_height: 'Altezza minima',
          geometry: 'Posizionamento',
          geometry_absolute: 'Assoluto',
          geometry_parametric: 'Spaziatura',
          geometry_relative: 'Offset',
          position_u: 'Colonna',
          column_u: 'Colonna (u)',
          position_v: 'Riga',
          row_v: 'Riga (v)',
          column_row_uv: 'Colonna (u) / Riga (v)',
          position_dx: 'Distanza orizzontale',
          position_dy: 'Distanza verticale',
          anchor_align: 'Ancore di flusso',
          anchor_align_vertical: 'Ancore (lati verticali)',
          anchor_align_horizontal: 'Ancore (lati orizzontali)',
          shape_io_reorg_mode: 'Riordino automatico',
          io_reorg_mode_none: 'Nessuno',
          io_reorg_mode_simple: 'Posizione dei nodi opposti',
          io_reorg_mode_advanced: 'Curvatura, tranne i flussi diritti',
          io_reorg_mode_anchor: 'Curvatura, tutti i flussi',
          shape_link_inset: 'Distanza dei flussi',
          asn: 'Applica stile ai nodi',
          override_type_node_shape: 'Sblocca la forma',
          arrow: 'Freccia',
          display_shape: 'Mostra il nodo',
          hide_shape: 'Nascondi il nodo',
          display_label: 'Mostra l\'etichetta',
          hide_label: 'Nascondi l\'etichetta',
          display_value: 'Mostra il valore',
          hide_value: 'Nascondi il valore',
          shape_opacity: 'Opacità',
          tooltips: {
            FormeDisabled: 'Disattivato perché la forma è gestita dal gruppo di tag "Tipo di nodo". Se si desidera modificare la forma dei nodi selezionati, andare alla scheda "Tag" e deselezionare tutti i tag selezionati del gruppo "Tipo di nodo".',
            shape_anchor_align_vertical: 'Allineamento verticale delle ancore di flusso sui lati sinistro/destro del nodo (alto / centro / basso).',
            shape_anchor_align_horizontal: 'Allineamento orizzontale delle ancore di flusso sui lati superiore/inferiore del nodo (sinistra / centro / destra).',
            shape_io_reorg_mode: 'Come viene ricalcolato l\'ordine dei flussi entranti/uscenti quando il diagramma cambia. Nessuno: mai ricalcolato (l\'ordine resta fisso). Posizione dei nodi opposti: ordinato per la posizione del nodo opposto (predefinito). Curvatura, tranne i flussi diritti: i flussi diritti restano al centro del nodo, gli altri si aprono a ventaglio. Curvatura, tutti i flussi: nessuna eccezione — tutti a ventaglio e quello che curva prima va all\'estremità.',
            shape_link_inset: 'Scostamento perpendicolare delle ancore di flusso rispetto al bordo del nodo, in px. Positivo porta le ancore DENTRO la scatola (i flussi entranti/uscenti si incontrano attraverso il nodo), negativo le allontana. La scatola mantiene la sua dimensione.',
            geometry: 'Metodo per calcolare la posizione del nodo. La posizione può essere data in coordinate assolute x,y, in coordinate relative u,v, o in coordinate relative a un altro nodo.',
            position_dx: 'Distanza orizzontale tra il bordo destro del nodo a sinistra e il bordo sinistro del nodo',
            position_dy: 'Distanza verticale tra il bordo inferiore del nodo superiore e il bordo superiore del nodo',
            shape_position_u_locked: 'Se bloccato, il calcolo autosankey conserva l\'indice di colonna (u) di questo nodo invece di ricalcolarlo.',
            shape_position_v_locked: 'Se bloccato, il calcolo autosankey conserva l\'ordine verticale relativo (v) di questo nodo nella sua colonna invece di ricalcolarlo.',
            override_type_node_shape: 'Permette di cambiare la forma forzata di default sui nodi di tipo prodotto e settore',
          },
          shape_arrow_angle_direction: 'Orientamento della freccia',
          shape_arrow_angle_factor: 'Inclinazione della freccia'
        },
        node_value: {
          anchor: 'Posizione dell\'ancora',
          anchor_dx: 'Spostamento orizzontale',
          anchor_dy: 'Spostamento verticale',
          tooltips: {
            anchor: 'L\'ancora del valore del nodo può essere posizionata in 9 modi rispetto alla forma, combinando orizzontalmente bordo sinistro, centro e bordo destro, e verticalmente bordo superiore, centro e bordo inferiore',
            anchor_dx: 'Spostamento orizzontale dall\'ancora del valore del nodo',
            anchor_dy: 'Spostamento verticale dall\'ancora del valore del nodo',
          }
        },
        labels: {
          labels: 'Nome',
          node_value: 'Valore',
          name_label_is_visible: 'Etichetta',
          lb: 'Etichetta bianca',
          name_label_background: 'Sfondo',
          name_label_background_color: 'Colore sfondo',
          pos: 'Posizione',
          pos_v: 'Posizione del valore',
          tp: 'Dimensione carattere',
          cl: 'Larghezza area testo',
          vdv: 'Valore',
          edit_node_label: 'Modifica nome nodo',
          anchor: 'Posizione dell\'ancora',
          name_label_text_source: 'Contenuto dell\'etichetta',
          name_label_template: 'Modello',
          name_label_text: 'Etichetta personalizzata',
          name_label_tag_group: 'Gruppo di tag',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimensione',
          name_label_dimension_auto: 'Automatica (la prima)',
          text_source: {
            name: 'Nome del nodo',
            name_container: 'Nome dell\'elemento',
            custom: 'Testo personalizzato',
            template: 'Modello con segnaposto',
            tag: 'Nome lungo di un tag',
            ancestor: 'Nome del nodo antenato',
            name_part: 'Parte del nome (separatore)',
          },
          tooltips: {
            name_label_text_source: 'Scegli cosa mostra l\'etichetta del nodo: il nome del nodo, o un testo personalizzato indipendente (modificabile senza rinominare il nodo)',
            name_label_template: 'Testo costruito con segnaposto sostituiti al disegno, es. «{Name}: {Value} {Unit}»',
            name_label_is_visible: 'Mostra o nasconde l\'etichetta/e associata/e al/ai nodo/i selezionato/i',
            lb: 'Mostra il testo dell\'etichetta/e in bianco o nero (utile se l\'etichetta è posizionata sul/sui nodo/i)',
            name_label_background: 'Aggiunge uno sfondo all\'etichetta per una migliore visibilità quando è davanti a un flusso',
            top: 'Mostra l\'etichetta/e sopra il/i nodo/i selezionato/i',
            Milieu_pv: 'Mostra l\'etichetta/e al centro (verticalmente) del/dei nodo/i selezionato/i',
            Bas: 'Mostra l\'etichetta/e sotto il/i nodo/i selezionato/i',
            gauche: 'Mostra l\'etichetta/e a sinistra del/dei nodo/i selezionato/i',
            Milieu_ph: 'Mostra l\'etichetta/e al centro (orizzontalmente) del/dei nodo/i selezionato/i',
            droite: 'Mostra l\'etichetta/e a destra del/dei nodo/i selezionato/i',
            cl: 'Larghezza dell\'area di testo (in pixel) per l\'etichetta/e del/dei nodo/i selezionato/i',
            vdv: 'Mostra o nasconde il valore associato al/ai nodo/i selezionato/i',
            anchor: 'L\'ancora dell\'etichetta può essere posizionata in 9 modi rispetto alla forma, combinando orizzontalmente bordo sinistro, centro e bordo destro, e verticalmente bordo superiore, centro e bordo inferiore',
            haut_val: 'Mostra il valore associato sopra il/i nodo/i selezionato/i',
            Milieu_pv_val: 'Mostra il valore associato al centro (verticalmente) del/dei nodo/i selezionato/i',
            Bas_val: 'Mostra il valore associato sotto il/i nodo/i selezionato/i',
            gauche_val: 'Mostra il valore associato a sinistra del/dei nodo/i selezionato/i',
            Milieu_ph_val: 'Mostra il valore associato al centro (orizzontalmente) del/dei nodo/i selezionato/i',
            droite_val: 'Mostra il valore associato a destra del/dei nodo/i selezionato/i',
            haut: 'Posizionare l\'etichetta sopra il/i nodo(i) selezionato(i)'
          }
        },
        tags_node: {
          tags: 'Tag',
          Appartenance: 'Appartenenza'
        },
        agre: {
          Agré: 'Aggregazione',
          DC: 'Dimensioni del cubo',
          Parent: 'Genitore',
          CLE: 'Copia flussi figli'
        },
        PF: {
          PF: 'Flussi I/O',
          PFM: 'Organizza flussi I/O',
          FES: 'Tipo di flusso',
          ent: 'Ingresso',
          sort: 'Uscita',
          FRN: 'Posizione relativa / nodo',
          gauche: 'Sinistra',
          droite: 'Destra',
          ades: 'Sopra',
          edes: 'Sotto',
          lti: 'Identifica i flussi nella tabella con i loro colori',
          col: 'Applica',
          filter_links: 'Flussi da visualizzare',
          visible_links: 'Flussi visibili',
          all_links: 'Tutti i flussi',
          lock: 'Lucchetto',
          delta: 'Spaziatura',
          tooltips: {
            io: 'Scegliere i flussi in ingresso o in uscita del nodo selezionato',
            side: 'Scegliere i flussi a destra, sinistra, sopra o sotto del nodo selezionato',
            lti: 'Mostra le righe della tabella dei flussi con i rispettivi colori per identificarli meglio',
            filter_links: 'Mostra solo i flussi visibili o tutti i flussi compresi quelli nascosti',
            lock: 'Blocca il lato di questa ancora: spostare il nodo opposto non la riposizionerà più. Rilasciato da qualsiasi calcolo automatico.',
            delta: 'Spaziatura aggiuntiva inserita prima di questa ancora, per distanziare i flussi che arrivano sul nodo'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Stile nodo predefinito',
        LinkStyle: 'Stile flusso predefinito',
        ContainerStyle: 'Stile contenitore predefinito',
        NodeContainerStyle: 'Cornice englobante di nodi',
        NodeLeftExtremityStyle: 'Stile nodo estremità sinistra',
        NodeRightExtremityStyle: 'Stile nodo estremità destra',
        NodeProductStyle: 'Stile etichetta prodotto',
        NodeSectorStyle: 'Stile etichetta settore',
        NodeImportExportCloseStyle: 'Nodo import-export allegato',
        NodeImportCloseStyle: 'Nodo import allegato',
        NodeExportCloseStyle: 'Nodo export allegato',
        NodeImportExportAboveBelowStyle: 'Nodo import-export sopra/sotto',
        NodeImportAboveStyle: 'Nodo import sopra',
        NodeExportBelowStyle: 'Nodo export sotto',
        LinkImportExportCloseStyle: 'Flusso import-export allegato',
        LinkImportCloseStyle: 'Flusso import allegato',
        LinkExportCloseStyle: 'Flusso export allegato',
        LinkImportExportAboveBelowStyle: 'Flusso import-export sopra/sotto',
        SankeyUnitaryNodeStyle: 'Nodo unitario',
        SankeyUnitaryNodeInputStyle: 'Nodo unitario ingresso',
        SankeyUnitaryNodeOutputStyle: 'Nodo unitario uscita',
        LinkInUnitaryStyle: 'Flusso unitario ingresso',
        LinkOutUnitaryStyle: 'Flusso unitario uscita',
        family: 'Famiglia',
        family_predefined: 'Stili dell\'applicazione',
        family_user: 'Stili utente'
      }
    }
  },
  'zh-CN': {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: '样式表',
        OrderStyle: '关联样式的顺序',
        multi_style: '所选节点的样式不同',
        editStyle: '指派样式',
        AS: '重置',
        SelectStyle: '选择一个样式',
        Reorg: '重排进入/流出的流量',
        Reorg_title: '重排',
        Slct: '选择',
        SlctOutLink: '选择流出的流量',
        SlctInLink: '选择进入的流量',
        SlctL: '选择流量',
        SlctOL: '输出',
        SlctIL: '输入',
        IB: '提示框',
        IS: '附加信息',
        align_horiz: '水平方向',
        align_horiz_min: '相对于最左侧的已选节点',
        align_horiz_max: '相对于最右侧的已选节点',
        align_vert: '垂直方向',
        align_vert_min: '相对于最上方的已选节点',
        align_vert_max: '相对于最下方的已选节点',
        align_horiz_left: '对齐到其左侧',
        align_horiz_center: '对齐到其中心',
        align_horiz_right: '对齐到其右侧',
        align_vert_top: '对齐到其顶部',
        align_vert_bottom: '对齐到其底部',
        align: '对齐节点',
        product: '产品',
        sector: '部门',
        exchange: '交换',
        size: '尺寸',
        position: '位置',
        text: '文本',
        selector: '选择节点',
        title_desaggreg: '维度分解',
        title_aggreg: '维度聚合',
        text_agreg: '将聚合为： ',
        text_desagreg: '将分解为： ',
        desaggreg: '分解',
        aggreg: '聚合',
        firstPlan: '移到背景',
        lastPlan: '移到前景',
        changePlan: '更改节点所在图层',
        mask_attr: '元素显示',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: '允许将首选项菜单中预定义的样式应用到所选节点',
          Reorg: '允许自动重排进入与流出的流量（上/下位置）',
          SlctOutLink: '允许选择该节点的所有流出流量',
          SlctInLink: '允许选择进入该节点的所有流量',
          IB: '提示框：以 HTML 编排、随节点提示框一同显示的文本。该提示框在图形区中通过 SHIFT + 鼠标悬停于节点上弹出。',
        },
        drawing_area_tooltip: {
          outputs: '输出',
          inputs: '输入',
          dest: '输出',
          val: '数值',
          data_value: '采集数据',
          result_value: '计算数据',
          rat: '比例',
          prov: '输入',
          values_tab: '数值',
          tags_tab: '其他信息',
          unitary_tab: '单位桑基图',
          balance: '平衡',
          balance_diff: '差额（进 − 出）',
          balance_ok: '已平衡',
          balance_ko: '不平衡',
          analysis_tab: '分析'
        },
        tabs: {
          apparence: '外观',
          infos: '附加信息',
          tags: '标签',
          io: '进出流量位置',
        },
        apparence: {
          apparence: '外观',
          shape_visible: '形状',
          shape_color: '颜色',
          shape_color_sustainable: '固定颜色',
          shape_type: '节点形状',
          Geometry: '几何',
          Cercle: '弧形',
          Rectangle: '矩形',
          shape_min_width: '最小宽度',
          shape_min_height: '最小高度',
          geometry: '定位',
          geometry_absolute: '绝对',
          geometry_parametric: '间距',
          geometry_relative: '偏移',
          position_u: '列',
          column_u: '列 (u)',
          position_v: '行',
          row_v: '行 (v)',
          column_row_uv: '列 (u) / 行 (v)',
          position_dx: '水平间距',
          position_dy: '垂直间距',
          anchor_align: '流量锚点',
          anchor_align_vertical: '锚点（左右两侧）',
          anchor_align_horizontal: '锚点（上下两侧）',
          shape_io_reorg_mode: '自动重排序',
          io_reorg_mode_none: '无',
          io_reorg_mode_simple: '对侧节点位置',
          io_reorg_mode_advanced: '曲率（直线流量除外）',
          io_reorg_mode_anchor: '曲率（全部流量）',
          shape_link_inset: '流量锚点距离',
          asn: '将样式应用到节点',
          override_type_node_shape: '覆盖默认形状',
          arrow: '箭头',
          display_shape: '显示节点形状',
          hide_shape: '隐藏节点形状',
          display_label: '显示标签',
          hide_label: '隐藏标签',
          display_value: '显示数值',
          hide_value: '隐藏数值',
          shape_opacity: '不透明度',
          tooltips: {
            FormeDisabled: '已停用，因为形状由“节点类型”标签组管理；若要能够更改所选节点的形状，请前往“标签”选项卡，并取消勾选“节点类型”组中所有已选的标签',
            shape_anchor_align_vertical: '节点左/右两侧流量锚点的垂直对齐方式（上 / 中 / 下）。',
            shape_anchor_align_horizontal: '节点上/下两侧流量锚点的水平对齐方式（左 / 中 / 右）。',
            shape_io_reorg_mode: '图表变化时如何重新计算进出流量的顺序。无：不再重新计算（顺序保持冻结）。对侧节点位置：按对侧节点位置排序（默认）。曲率（直线流量除外）：直线流量留在节点中部，其余展开成扇形。曲率（全部流量）：没有例外 — 全部展开，最先转弯的流量排到端部。',
            shape_link_inset: '流量锚点相对于节点边框的垂直偏移，单位为 px。正值将锚点拉入方框内部（进出流量在节点内部相接），负值则将其推到方框之外。方框尺寸保持不变。',
            geometry: '计算节点位置的方法。该位置可以用绝对坐标 x,y 给出，也可以用相对坐标 u,v，或相对于另一个节点的坐标给出。',
            position_dx: '左侧节点的右边缘与该节点左边缘之间的水平间距',
            position_dy: '上方节点的下边缘与该节点上边缘之间的垂直间距',
            shape_position_u_locked: '锁定后，自动布局计算将保留该节点的列索引（u），而不再重新计算。',
            shape_position_v_locked: '锁定后，自动布局计算将保留该节点在其列内的相对垂直顺序（v），而不再重新计算。',
            override_type_node_shape: '覆盖产品类型与部门类型节点的默认强制形状',
          },
          shape_arrow_angle_direction: '箭头方向',
          shape_arrow_angle_factor: '箭头斜度'
        },
        node_value: {
          anchor: '锚点位置',
          anchor_dx: '水平偏移',
          anchor_dy: '垂直偏移',
          tooltips: {
            anchor: '节点数值的锚点可通过组合水平位置（左、中、右）与垂直位置（上、中、下）进行定位',
            anchor_dx: '相对于标签锚点的水平偏移',
            anchor_dy: '相对于标签锚点的垂直偏移',
          }
        },
        labels: {
          labels: '名称',
          node_value: '数值',
          name_label_is_visible: '标签',
          lb: '白色标签',
          name_label_background: '背景',
          name_label_background_color: '背景颜色',
          pos: '位置',
          pos_v: '数值位置',
          tp: '字号',
          cl: '文本框宽度',
          vdv: '数值',
          edit_node_label: '编辑节点标签',
          anchor: '锚点位置',
          name_label_text_source: '标签内容',
          name_label_template: '模板',
          name_label_text: '自定义标签',
          name_label_tag_group: '标签组',
          name_label_tag: '标签',
          name_label_dimension: '维度',
          name_label_dimension_auto: '自动（第一个）',
          text_source: {
            name: '节点名称',
            name_container: '元素名称',
            custom: '自定义文本',
            template: '占位符模板',
            tag: '标签全称',
            ancestor: '祖先节点名称',
            name_part: '名称片段（分隔符）',
          },

          tooltips: {
            name_label_is_visible: '是否显示附加在所选节点上的标签',
            name_label_text_source: '选择节点标签显示的内容：节点名称，或独立的自定义文本（编辑时不会重命名节点）',
            name_label_template: '由绘制时替换的占位符组成的文本，例如“{Name}: {Value} {Unit}”',
            lb: '以白色或黑色显示标签文本（当标签位于节点之上时很有用）',
            name_label_background: '为标签添加背景，以便在标签位于流量之前时更清晰可见',
            top: '将标签显示在所选节点的上方',
            Milieu_pv: '将标签显示在所选节点（垂直方向）的中间',
            Bas: '将标签显示在所选节点的下方',
            gauche: '将标签显示在所选节点的左侧',
            Milieu_ph: '将标签显示在所选节点（水平方向）的中间',
            droite: '将标签显示在所选节点的右侧',
            cl: '所选节点标签的文本区宽度（像素）',
            vdv: '是否显示与所选节点关联的数值',
            anchor: '标签的锚点可相对于形状以 9 种方式定位：水平方向组合左边缘、中间、右边缘，垂直方向组合上边缘、中间、下边缘',
            haut_val: '将关联数值显示在所选节点的上方',
            Milieu_pv_val: '将关联数值显示在所选节点（垂直方向）的中间',
            Bas_val: '将关联数值显示在所选节点的下方',
            gauche_val: '将关联数值显示在所选节点的左侧',
            Milieu_ph_val: '将关联数值显示在所选节点（水平方向）的中间',
            droite_val: '将关联数值显示在所选节点的右侧',
            haut: '将标签置于所选节点的上方'
          }
        },
        tags_node: {
          tags: '标签',
          Appartenance: '归属'
        },
        agre: {
          Agré: '聚合',
          DC: '立方体维度',
          Parent: '父节点',
          CLE: '复制子节点的流量'
        },
        PF: {
          PF: '进出流量位置',
          PFM: '进出流量位置',
          FES: '流量类型',
          ent: '输入',
          sort: '输出',
          FRN: '相对节点的位置',
          gauche: '左',
          droite: '右',
          ades: '上方',
          edes: '下方',
          lti: '用颜色在表中标识各条流量',
          col: '应用',
          filter_links: '要显示的流量',
          visible_links: '可见流量',
          all_links: '全部流量',
          lock: '锁定',
          delta: '间距',
          tooltips: {
            io: '选择所选节点的进入流量或流出流量',
            side: '选择所选节点右侧、左侧、上方或下方的流量',
            lti: '以各自的颜色显示流量表的行，以便更好地区分',
            filter_links: '仅显示可见流量，或显示包括隐藏流量在内的全部流量',
            lock: '锁定该锚点一侧：移动对侧节点将不再改变其位置。任何自动布局都会解除锁定。',
            delta: '在该锚点之前插入的额外间距，用于拉开到达该节点的流量'
          }
        }
      },
      ElementStyle: {
        NodeStyle: '默认节点样式',
        LinkStyle: '默认流量样式',
        ContainerStyle: '默认容器样式',
        NodeContainerStyle: '包围节点框体',
        NodeLeftExtremityStyle: '左端节点样式',
        NodeRightExtremityStyle: '右端节点样式',
        NodeProductStyle: '产品标签样式',
        NodeSectorStyle: '部门标签样式',
        NodeImportExportCloseStyle: '进出口节点（就近）',
        NodeImportCloseStyle: '进口节点（就近）',
        NodeExportCloseStyle: '出口节点（就近）',
        NodeImportExportAboveBelowStyle: '进出口节点（上/下）',
        NodeImportAboveStyle: '进口节点（上方）',
        NodeExportBelowStyle: '出口节点（下方）',
        LinkImportExportCloseStyle: '进出口流量（就近）',
        LinkImportCloseStyle: '进口流量（就近）',
        LinkExportCloseStyle: '出口流量（就近）',
        LinkImportExportAboveBelowStyle: '进出口流量（上/下）',
        SankeyUnitaryNodeStyle: '单位节点',
        SankeyUnitaryNodeInputStyle: '单位节点输入',
        SankeyUnitaryNodeOutputStyle: '单位节点输出',
        LinkInUnitaryStyle: '单位输入流量',
        LinkOutUnitaryStyle: '单位输出流量',
        family: '系列',
        family_predefined: '应用样式',
        family_user: '用户样式'
      }
    }
  },
  ja: {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: 'スタイルシート',
        OrderStyle: '紐づくスタイルの順序',
        multi_style: '選択中のノードのスタイルが異なります',
        editStyle: 'スタイルを割り当て',
        AS: 'リセット',
        SelectStyle: 'スタイルを選択',
        Reorg: '入力／出力フローを整理します',
        Reorg_title: '整理',
        Slct: '選択',
        SlctOutLink: '出力フローを選択',
        SlctInLink: '入力フローを選択',
        SlctL: 'フローを選択',
        SlctOL: '出力',
        SlctIL: '入力',
        IB: 'ツールチップ',
        IS: '補足情報',
        align_horiz: '水平方向',
        align_horiz_min: '選択中で最も左にあるノードを基準',
        align_horiz_max: '選択中で最も右にあるノードを基準',
        align_vert: '垂直方向',
        align_vert_min: '選択中で最も上にあるノードを基準',
        align_vert_max: '選択中で最も下にあるノードを基準',
        align_horiz_left: 'その左端に揃える',
        align_horiz_center: 'その中央に揃える',
        align_horiz_right: 'その右端に揃える',
        align_vert_top: 'その上端に揃える',
        align_vert_bottom: 'その下端に揃える',
        align: 'ノードを整列',
        product: '製品',
        sector: '部門',
        exchange: '交換',
        size: 'サイズ',
        position: '位置',
        text: 'テキスト',
        selector: 'ノードを選択',
        title_desaggreg: '次元の分解',
        title_aggreg: '次元の集約',
        text_agreg: '次の単位に集約します： ',
        text_desagreg: '次の単位に分解します： ',
        desaggreg: '分解',
        aggreg: '集約',
        firstPlan: '背面へ移動',
        lastPlan: '前面へ移動',
        changePlan: 'ノードのレイヤーを変更',
        mask_attr: '要素の表示',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: '環境設定メニューで定義したスタイルを、選択したノードに適用できるようにします',
          Reorg: '入力フローと出力フローの自動整理（上下の位置）を行えるようにします',
          SlctOutLink: 'そのノードから出るすべてのフローを選択できるようにします',
          SlctInLink: 'そのノードに入るすべてのフローを選択できるようにします',
          IB: 'ツールチップ：HTML で記述され、ノードのツールチップとして表示されるテキストです。描画エリアでノードの上を SHIFT + マウスでポイントすると表示されます。',
        },
        drawing_area_tooltip: {
          outputs: '出力',
          inputs: '入力',
          dest: '出力',
          val: '値',
          data_value: '収集したデータ',
          result_value: '計算されたデータ',
          rat: '比率',
          prov: '入力',
          values_tab: '値',
          tags_tab: 'その他の情報',
          unitary_tab: '単位サンキー',
          balance: '収支',
          balance_diff: '差（入 − 出）',
          balance_ok: '均衡しています',
          balance_ko: '均衡していません',
          analysis_tab: '分析'
        },
        tabs: {
          apparence: '外観',
          infos: '補足情報',
          tags: 'タグ',
          io: '入出力フローの位置',
        },
        apparence: {
          apparence: '外観',
          shape_visible: '形状',
          shape_color: '色',
          shape_color_sustainable: '固定色',
          shape_type: 'ノードの形状',
          Geometry: '配置',
          Cercle: '円弧',
          Rectangle: '長方形',
          shape_min_width: '最小幅',
          shape_min_height: '最小の高さ',
          geometry: '配置',
          geometry_absolute: '絶対',
          geometry_parametric: '間隔',
          geometry_relative: 'オフセット',
          position_u: '列',
          column_u: '列 (u)',
          position_v: '行',
          row_v: '行 (v)',
          column_row_uv: '列 (u) / 行 (v)',
          position_dx: '水平方向の間隔',
          position_dy: '垂直方向の間隔',
          anchor_align: 'フローのアンカー',
          anchor_align_vertical: 'アンカー（左右の辺）',
          anchor_align_horizontal: 'アンカー（上下の辺）',
          shape_io_reorg_mode: '自動並べ替え',
          io_reorg_mode_none: 'なし',
          io_reorg_mode_simple: '反対側ノードの位置',
          io_reorg_mode_advanced: '曲率（直線フローを除く）',
          io_reorg_mode_anchor: '曲率（すべてのフロー）',
          shape_link_inset: 'フローアンカーの距離',
          asn: 'スタイルをノードに適用',
          override_type_node_shape: '既定の形状を上書き',
          arrow: '矢印',
          display_shape: 'ノードの形状を表示',
          hide_shape: 'ノードの形状を隠す',
          display_label: 'ラベルを表示',
          hide_label: 'ラベルを隠す',
          display_value: '値を表示',
          hide_value: '値を隠す',
          shape_opacity: '不透明度',
          tooltips: {
            FormeDisabled: '形状が「ノード種別」タググループによって管理されているため無効です。選択中のノードの形状を変更できるようにするには、「タグ」タブで「ノード種別」グループの選択中のタグをすべて外してください',
            shape_anchor_align_vertical: 'ノードの左／右の辺におけるフローアンカーの垂直方向の揃え（上／中央／下）。',
            shape_anchor_align_horizontal: 'ノードの上／下の辺におけるフローアンカーの水平方向の揃え（左／中央／右）。',
            shape_io_reorg_mode: '図が変化したときに入出力フローの順序をどう再計算するか。なし：再計算しません（順序は固定されたまま）。反対側ノードの位置：反対側ノードの位置で並べ替え（既定）。曲率（直線フローを除く）：直線フローはノード中央に残り、他は扇状に広がります。曲率（すべてのフロー）：例外なし — すべてが扇状に広がり、最も早く曲がるフローが端に来ます。',
            shape_link_inset: 'ノードの枠に対するフローアンカーの垂直方向のずれ（px）。正の値はアンカーを枠の内側へ引き込み（入出力フローがノードの内部でつながります）、負の値は外側へ押し出します。枠の大きさは変わりません。',
            geometry: 'ノードの位置を計算する方法。位置は絶対座標 x,y、相対座標 u,v、または別のノードからの相対座標で指定できます。',
            position_dx: '左隣のノードの右端と、このノードの左端との水平方向の間隔',
            position_dy: '上のノードの下端と、このノードの上端との垂直方向の間隔',
            shape_position_u_locked: '固定すると、自動レイアウトの計算はこのノードの列インデックス（u）を再計算せずに保持します。',
            shape_position_v_locked: '固定すると、自動レイアウトの計算は列内でのこのノードの相対的な垂直順序（v）を再計算せずに保持します。',
            override_type_node_shape: '製品型・部門型ノードに強制される既定の形状を上書きします',
          },
          shape_arrow_angle_direction: '矢印の向き',
          shape_arrow_angle_factor: '矢印の傾き'
        },
        node_value: {
          anchor: 'アンカーの位置',
          anchor_dx: '水平方向のずれ',
          anchor_dy: '垂直方向のずれ',
          tooltips: {
            anchor: 'ノードの値のアンカーは、水平方向（左・中央・右）と垂直方向（上・中央・下）の組み合わせで配置できます',
            anchor_dx: 'ラベルのアンカーからの水平方向のずれ',
            anchor_dy: 'ラベルのアンカーからの垂直方向のずれ',
          }
        },
        labels: {
          labels: '名前',
          node_value: '値',
          name_label_is_visible: 'ラベル',
          lb: '白いラベル',
          name_label_background: '背景',
          name_label_background_color: '背景色',
          pos: '位置',
          pos_v: '値の位置',
          tp: '文字サイズ',
          cl: 'テキストボックスの幅',
          vdv: '値',
          edit_node_label: 'ノードのラベルを編集',
          anchor: 'アンカーの位置',
          name_label_text_source: 'ラベルの内容',
          name_label_template: 'テンプレート',
          name_label_text: '任意のラベル',
          name_label_tag_group: 'タググループ',
          name_label_tag: 'タグ',
          name_label_dimension: '次元',
          name_label_dimension_auto: '自動（最初のもの）',
          text_source: {
            name: 'ノード名',
            name_container: '要素名',
            custom: '任意テキスト',
            template: 'トークンのテンプレート',
            tag: 'タグの正式名称',
            ancestor: '祖先ノードの名前',
            name_part: '名前の一部（区切り文字）',
          },

          tooltips: {
            name_label_is_visible: '選択したノードに付いているラベルを表示するかどうかを設定します',
            name_label_text_source: 'ノードのラベルに表示する内容を選択：ノード名、またはノード名を変えずに編集できる任意のテキスト',
            name_label_template: '描画時に置き換えられるトークンで組み立てる文字列（例：「{Name}: {Value} {Unit}」）',
            lb: 'ラベルの文字を白または黒で表示します（ラベルをノードの上に配置する場合に便利です）',
            name_label_background: 'ラベルがフローの手前にある場合に見やすくなるよう、ラベルに背景を付けます',
            top: '選択したノードの上にラベルを表示します',
            Milieu_pv: '選択したノードの垂直方向の中央にラベルを表示します',
            Bas: '選択したノードの下にラベルを表示します',
            gauche: '選択したノードの左にラベルを表示します',
            Milieu_ph: '選択したノードの水平方向の中央にラベルを表示します',
            droite: '選択したノードの右にラベルを表示します',
            cl: '選択したノードのラベルのテキスト領域の幅（ピクセル）',
            vdv: '選択したノードに紐づく値を表示するかどうかを設定します',
            anchor: 'ラベルのアンカーは、水平方向（左端・中央・右端）と垂直方向（上端・中央・下端）の組み合わせにより、形状に対して 9 通りに配置できます',
            haut_val: '選択したノードの上に、紐づく値を表示します',
            Milieu_pv_val: '選択したノードの垂直方向の中央に、紐づく値を表示します',
            Bas_val: '選択したノードの下に、紐づく値を表示します',
            gauche_val: '選択したノードの左に、紐づく値を表示します',
            Milieu_ph_val: '選択したノードの水平方向の中央に、紐づく値を表示します',
            droite_val: '選択したノードの右に、紐づく値を表示します',
            haut: '選択したノードの上にラベルを配置します'
          }
        },
        tags_node: {
          tags: 'タグ',
          Appartenance: '所属'
        },
        agre: {
          Agré: '集約',
          DC: 'キューブの次元',
          Parent: '親',
          CLE: '子のフローを複製'
        },
        PF: {
          PF: '入出力フローの位置',
          PFM: '入出力フローの位置',
          FES: 'フローの種類',
          ent: '入力',
          sort: '出力',
          FRN: 'ノードからの相対位置',
          gauche: '左',
          droite: '右',
          ades: '上',
          edes: '下',
          lti: '表の中でフローを色で見分けられるようにします',
          col: '適用',
          filter_links: '表示するフロー',
          visible_links: '表示中のフロー',
          all_links: 'すべてのフロー',
          lock: '固定',
          delta: '間隔',
          tooltips: {
            io: '選択したノードの入力フローか出力フローかを選びます',
            side: '選択したノードの右・左・上・下いずれかのフローを選びます',
            lti: '見分けやすくするため、フローの表の行をそれぞれの色で表示します',
            filter_links: '表示中のフローのみ、または隠れているものも含めたすべてのフローを表示します',
            lock: 'このアンカー側を固定します：反対側のノードを動かしても位置が変わらなくなります。自動レイアウトを実行すると解除されます。',
            delta: 'このアンカーの手前に挿入する追加の間隔。ノードに到達するフロー同士の間隔を空けます'
          }
        }
      },
      ElementStyle: {
        NodeStyle: '既定のノードスタイル',
        LinkStyle: '既定のフロースタイル',
        ContainerStyle: '既定のコンテナスタイル',
        NodeContainerStyle: '内包するノードの枠',
        NodeLeftExtremityStyle: '左端ノードのスタイル',
        NodeRightExtremityStyle: '右端ノードのスタイル',
        NodeProductStyle: '製品ラベルのスタイル',
        NodeSectorStyle: '部門ラベルのスタイル',
        NodeImportExportCloseStyle: '移入・移出ノード（近接）',
        NodeImportCloseStyle: '移入ノード（近接）',
        NodeExportCloseStyle: '移出ノード（近接）',
        NodeImportExportAboveBelowStyle: '移入・移出ノード（上下）',
        NodeImportAboveStyle: '移入ノード（上）',
        NodeExportBelowStyle: '移出ノード（下）',
        LinkImportExportCloseStyle: '移入・移出フロー（近接）',
        LinkImportCloseStyle: '移入フロー（近接）',
        LinkExportCloseStyle: '移出フロー（近接）',
        LinkImportExportAboveBelowStyle: '移入・移出フロー（上下）',
        SankeyUnitaryNodeStyle: '単位ノード',
        SankeyUnitaryNodeInputStyle: '単位ノードの入力',
        SankeyUnitaryNodeOutputStyle: '単位ノードの出力',
        LinkInUnitaryStyle: '単位の入力フロー',
        LinkOutUnitaryStyle: '単位の出力フロー',
        family: '分類',
        family_predefined: 'アプリのスタイル',
        family_user: 'ユーザーのスタイル'
      }
    }
  }
}