// #1243 — Libellés de l'INSPECTEUR piloté par la sélection et des onglets du
// panneau de filtres. Fichier dédié (comme traduction_guided_tour), fusionné
// par deep_assign_resources dans traduction.tsx.
//
// `inspector.*`  : fil d'Ariane, cibles, portée/cascade, onglets, indicateurs.
// `filter_panel.*` : onglets Filtrer / Sélectionner / Éditer du tiroir.

export const resources_inspector = {
  //=======================================================
  //EN
  //=======================================================
  en: {
    translation: {
      inspector: {
        view: 'View',
        back_to_selection: 'Back to selection',
        pin: 'Pin the panel (the drawing resizes to its left)',
        unpin: 'Unpin the panel (floats over the drawing)',
        // Cibles : singulier / pluriel (fil d'Ariane).
        target: {
          view: 'View',
          node: 'Node', nodes: 'nodes',
          link: 'Flow', links: 'flows',
          container: 'Area', containers: 'areas',
          legend: 'Legend', legends: 'legends',
          title: 'Title', titles: 'titles',
          mixed: 'Mixed selection', elements: 'elements'
        },
        nothing_here: 'No settings available for: {{target}}.',
        // Portée & cascade de styles
        selection: 'Selection',
        selection_count: 'Selection ({{count}})',
        styles_count: 'Styles ({{count}})',
        cascade: 'Cascade',
        style_name: 'Style name',
        new_style: '+ New style',
        delete_style: 'Delete',
        delete_style_tooltip: 'Delete this style (elements following it fall back on the rest of their cascade)',
        attach_style: 'Attach a style to the selection (end of cascade, wins)',
        detach_style: 'Detach this style from the selection',
        edited_style_hint: 'Editing the highlighted style: every element following it will change. The last one in the cascade wins; a local override always wins.',
        divergent_cascade: 'Cascade of the 1st element — other selected elements follow a different cascade. ',
        selection_hint: 'Dimmed attributes: inherited from styles (cascade). Purple outline: overridden on the selection. Orange outline: multiple values.',
        tab_overloaded: 'Contains overridden attributes',
        provenance: {
          local: 'Overridden here (on the selection)',
          from_style: 'Inherited from style « {{style}} »',
          factory: 'Factory default value'
        },
        // Onglets
        tab: {
          stock: 'Stock',
          tooltip: 'Tooltip',
          tags: 'Tags',
          analysis: 'Analysis',
          title: 'Title',
          mfa: 'MFA',
          styles: 'Styles'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: 'Origin',
          unresolved: 'this element triggered it, but the file does not say why it exists',
          rules: {
            data_sheet: 'entered on a row of a data sheet',
            matrix_sheet: 'entered in a flow matrix',
            min_max_sheet: 'established by a bound of the “Min Max” sheet',
            constraints_sheet: 'established by an equation of the “Constraints” sheet',
            ratio_flux_sheet: 'established by a row of the “Flow ratio” sheet',
            ratio_stock_flux_sheet: 'established by a row of the “Stock flow ratio” sheet',
            stock_chaining_sheet: 'established by a row of the “Stock chaining” sheet',
            stocks_sheet: 'declared on a row of the “Stocks” sheet',
            stock_parent_aggregate: 'stock aggregate created on the parent node',
            stock_level_mirror: 'stock level mirroring a declared variation',
            nodes_sheet: 'declared in a nodes sheet',
            nodes_agg_sheet: 'declared in an aggregated nodes sheet',
            node_block_parenthood: 'attached to a parent by the block structure of the nodes sheet',
            results_sheet: 'read from the “Results” sheet',
            analysis_sheet: 'read from the “Results analysis” sheet',
            uncertainty_sheet: 'read from the “Uncertainty analysis” sheet',
            flux_from_secondary_sheet: 'created from a secondary sheet (option “Create flows from secondary sheets”)',
            node_from_flux: 'created because a flow refers to it (option “Create nodes from flows”)',
            propagate_to_parent: 'deduced: a child carries this flow, it was raised to the parent',
            propagate_to_children: 'deduced: the parent carries this flow, it was pushed down to the children',
            single_child: 'deduced: the node has a single child, the flow necessarily belongs to it',
            materialize_parent_aggregate: 'deduced: parent aggregate materialised to balance the hierarchy',
            datatag_broadcast: 'deduced: the flow structure was extended to this tag combination',
            manual_draw: 'drawn by hand in the application',
            json_read: 'read from a saved diagram',
            duplicate: 'from a duplication',
            paste: 'from a copy-paste',
            apply_layout: 'from applying a layout',
            merge_diagrams: 'from merging diagrams',
            spreadsheet_edit: 'entered in the spreadsheet tab',
            node_split: 'from splitting a node',
            expansion: 'from expanding a node'
          },
          intro: 'Why the selected element exists, traced back to the entry it comes from.',
          this_element: 'This element',
          because: 'because',
          sheet: 'sheet',
          line: 'line',
          datatags: 'Tag combination',
          unknown: 'This file does not say why this element exists (written before origin tracking, or drawn by hand).',
          select: 'Select a node or a flow.'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: 'Where does this value come from?',
          intro: 'What fixed the value of the selected flow, and the constraints bearing on it.',
          unknown: 'This file does not say what fixed this value (diagram not reconciled, or reconciled by an earlier version).',
          absent: 'This flow does not exist for this tag combination: there is no value to explain.',
          interval: 'Possible range',
          entered_value: 'Entered value',
          reconciled_value: 'Reconciled value',
          flux_involved: '{{n}} flows involved',
          show_flux: 'show the equation',
          hide_flux: 'hide the equation',
          also_in: 'Also appears in {{n}} other constraints',
          show_others: 'show',
          hide_others: 'hide',
          fixed_by: 'Its value is fixed by:',
          takes_part_in: 'No constraint fixes it. It takes part in:',
          no_constraint: 'No constraint of the model bears on this flow.',
          classification: {
            measured: 'entered',
            redundant: 'redundant',
            determined: 'determined',
            free: 'free',
            free_unbounded: 'free, unbounded',
            failed: 'not reconciled'
          },
          meaning: {
            measured: 'The value was entered, and nothing in the model allowed recomputing it: reconciliation left it as it was.',
            redundant: 'The value was entered, and the model could also compute it: reconciliation arbitrated between the two.',
            determined: 'The value was not entered: the constraints of the model are enough to fix it, no other solution is possible.',
            free: 'The constraints are not enough to fix this value; reconciliation picked one within the possible range.',
            free_unbounded: 'The constraints are not enough to fix this value, and nothing bounds it.',
            failed: 'Reconciliation of this tag combination did not succeed: the value shown is the input one.'
          },
          step_by_step: 'Step by step:',
          flat_equation: 'The equation that determines it:',
          combines: 'Combination of:',
          system_one: 'System of {{equations}} equations with 1 unknown:',
          system: 'System of {{equations}} equations with {{unknowns}} unknowns (with {{others}}):',
          coefficient: 'Coefficient',
          computed_from: '{{flux}} is itself computed by…',
          bound_propagated: 'This bound passes from one flux to the other: it comes from a propagation over the whole set of constraints, which no single model equation sums up.',
          holds_min: 'What holds it at {{value}} or above:',
          holds_max: 'What holds it at {{value}} or below:',
          at_least: 'at least',
          at_most: 'at most',
          shape: {
            equal: 'Same as another flux',
            factor: 'A share of another flux',
            children: 'Sum of its {{n}} child flux',
            into: 'Sum of everything entering {{node}}',
            out_of: 'Sum of everything leaving {{node}}',
            sum: 'Sum of {{n}} flux',
            balance_node: 'Balance of node {{node}}',
            balance: '{{added}} flux added, {{removed}} subtracted'
          },
          kinds: {
            mat_balance: 'Material balance of node',
            aggregation: 'Hierarchical relation — aggregation of child flows',
            stock_aggregation: 'Stock aggregation on node',
            equality: 'Entered equation (constraint)',
            bound_min: 'Entered lower bound (constraint)',
            bound_max: 'Entered upper bound (constraint)',
            inconsistency: 'Measurements contradict each other by',
            determined_by: 'Equation determining'
          }
        },
        // #1258 — Onglet MFA (espace AFM unifié).
        mfa: {
          reconciliation: 'Reconciliation',
          open_spreadsheet: 'Open the spreadsheet (constraints)',
          run_reconciliation: 'Reconcile via Excel…',
          value_in_mfa: 'Value type, bounds and uncertainty are edited in the MFA tab.'
        },
        // #1258 — Titres des sections repliables des onglets.
        section: {
          page: 'Page',
          dressing: 'Background & grid',
          scale_sizes: 'Scale & sizes',
          advanced: 'Advanced',
          advanced_geometry: 'Advanced — geometry'
        },
        // #1259 — Section « Groupe » unifiée (ex-« Cadre géométrique » ZDT + nœuds).
        group: {
          title: 'Group',
          tooltip: 'Attaches nodes or text zones to the selected element: the frame positions itself to encompass its members and moves with them'
        },
        visible: 'Visible',
        labels_visible: 'Labels visible',
        stock_enabled: 'Enabled',
        stock_shape: 'Shape',
        stock_shape_tooltip: 'Show the stock shape',
        stock_labels: 'Labels',
        stock_labels_tooltip: 'Show the stock labels',
        stock_shape_visible: 'Stock shape visible',
        stock_select_node: 'Select a node carrying a stock.',
        stock_caption: 'Stock caption',
        stock_delta_caption: 'Δ stock caption',
        advanced_editor: 'Advanced editor…',
        open_editor: 'Open the editor…',
        tags_assign_hint: 'Assignment (groups are edited in Filters)',
        // OS#1278 — section « Analyse » (graphiques couronne / histogramme).
        analysis: {
          decompose_by: 'Decompose by',
          compare_by: 'Compare across',
          compare_by_secondary: 'Then across (series)',
          none: '— none —',
          inputs: 'Incoming flows',
          outputs: 'Outgoing flows',
          inputs_by: 'Incoming flows by {{group}}',
          outputs_by: 'Outgoing flows by {{group}}',
          node_children: 'Child nodes ({{dim}})',
          flux_children: 'Child flows ({{dim}})',
          repr_auto: 'Auto',
          repr_donut: 'Donut',
          repr_bars: 'Bars',
          scale: 'Scale',
          scale_auto: 'Auto',
          scale_shared: 'Shared',
          scale_per_group: 'Per cluster',
          scale_auto_hint: 'Shared scale, unless a cluster becomes unreadable',
          scale_shared_hint: 'One scale for the whole chart',
          scale_per_group_hint: 'One scale per cluster — a cluster is one label of “Compare across”',
          show_in_tooltip: 'Show in tooltip',
          show_on_node: 'Show on the node (donut / histogram)',
          select_subject: 'Select a node or a flow.'
        },
        // OS#1285 — visibilité des blocs d'info-bulle.
        tooltip_blocks: {
          title: 'Visible blocks',
          values: 'Values',
          flux: 'Flow',
          tags: 'Tags',
          series_flux: 'Flow series',
          data: 'Data',
          series_data: 'Data series',
          unitary: 'Unitary Sankey',
          analysis: 'Analysis chart'
        },
        // OS#1286 — registre d'unités du diagramme (grandeurs/unités/défauts).
        units: {
          title: 'Diagram units',
          none: '— none —',
          type_default: 'default',
          open_editor: 'Edit…',
          open_editor_tooltip: 'Edit the diagram units (quantities, units, coefficients, defaults)',
          symbol: 'Symbol',
          display_name: 'Label',
          display_name_tooltip: 'Text actually written on the diagram for this unit. Empty: the canonical symbol is used. Lets a diagram say “tonnes” while still referring to the catalogue unit t — conversions are unaffected.',
          coefficient: 'Coefficient',
          coefficient_tooltip: 'Value of this unit expressed in the base unit of its quantity (base unit = 1). Values are stored in the base unit.',
          display_scale: 'Scale',
          display_scale_tooltip: 'Display scale specific to this quantity (like e!Sankey): base-unit amount shown over 100 px for unit-type bands. Empty: use the diagram scale. Lets you balance different quantities (kWh vs t vs EUR) on the same flow.',
          default: 'Default',
          default_tooltip: 'Default display unit of this quantity (inherited by flows without an explicit unit)',
          add_unit: '+ Unit',
          add_unit_type: '+ Quantity',
          new_unit_name: 'unit',
          new_unit_type_name: 'New quantity',
          empty: 'No quantity in the registry — add one.'
        }
      },
      filter_panel: {
        filter: 'Filter',
        select: 'Select',
        select_tooltip: 'Select elements by type and tag (bulk operations)',
        edit: 'Edit',
        edit_group: 'Edit this group',
        show_hidden: 'Show hidden groups ({{count}})',
        hide_hidden: 'Hide hidden groups',
        select_elements: 'Select elements',
        deselect_all: 'Deselect all',
        selection_summary: 'Selection: {{summary}}',
        short: {
          node: 'Nodes',
          link: 'Flows',
          data: 'Data',
          level: 'Levels',
          views: 'Views'
        }
      }
    }
  },
  //=======================================================
  //FR
  //=======================================================
  fr: {
    translation: {
      inspector: {
        view: 'Vue',
        back_to_selection: 'Retour à la sélection',
        pin: 'Épingler le panneau (le dessin se recadre à gauche)',
        unpin: 'Détacher le panneau (survol du dessin)',
        target: {
          view: 'Vue',
          node: 'Nœud', nodes: 'nœuds',
          link: 'Flux', links: 'flux',
          container: 'Zone', containers: 'zones',
          legend: 'Légende', legends: 'légendes',
          title: 'Titre', titles: 'titres',
          mixed: 'Sélection mixte', elements: 'éléments'
        },
        nothing_here: 'Aucun réglage disponible pour : {{target}}.',
        selection: 'Sélection',
        selection_count: 'Sélection ({{count}})',
        styles_count: 'Styles ({{count}})',
        cascade: 'Cascade',
        style_name: 'Nom du style',
        new_style: '+ Nouveau style',
        delete_style: 'Supprimer',
        delete_style_tooltip: 'Supprimer ce style (les éléments qui le suivaient retombent sur le reste de leur cascade)',
        attach_style: 'Attacher un style à la sélection (fin de cascade, prioritaire)',
        detach_style: 'Détacher ce style de la sélection',
        edited_style_hint: 'Édition du style surligné : tous les éléments qui le suivent seront modifiés. Le dernier de la cascade gagne ; une surcharge locale gagne toujours.',
        divergent_cascade: 'Cascade du 1er élément — d’autres éléments sélectionnés suivent une cascade différente. ',
        selection_hint: 'Attributs en retrait : hérités des styles (cascade). Liseré violet : surchargé sur la sélection. Liseré orange : valeurs multiples.',
        tab_overloaded: 'Contient des attributs surchargés',
        provenance: {
          local: 'Surchargé ici (sur la sélection)',
          from_style: 'Hérité du style « {{style}} »',
          factory: 'Valeur d’usine'
        },
        tab: {
          stock: 'Stock',
          tooltip: 'Infobulle',
          tags: 'Tags',
          analysis: 'Analyse',
          title: 'Titre',
          mfa: 'AFM',
          styles: 'Styles'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: 'Origine',
          unresolved: 'c\'est lui qui l\'a déclenché, mais le fichier ne dit pas pourquoi il existe',
          rules: {
            data_sheet: 'saisi sur une ligne d\'une feuille de données',
            matrix_sheet: 'saisi dans une matrice de flux',
            min_max_sheet: 'établi par une borne de la feuille « Min Max »',
            constraints_sheet: 'établi par une équation de la feuille « Contraintes »',
            ratio_flux_sheet: 'établi par une ligne de la feuille « Ratio Flux »',
            ratio_stock_flux_sheet: 'établi par une ligne de la feuille « Ratio Stock Flux »',
            stock_chaining_sheet: 'établi par une ligne de la feuille « Chaînage Stock »',
            stocks_sheet: 'déclaré sur une ligne de la feuille « Stocks »',
            stock_parent_aggregate: 'agrégat de stock créé d\'office sur le nœud parent',
            stock_level_mirror: 'niveau de stock créé en miroir d\'une variation déclarée',
            nodes_sheet: 'déclaré dans une feuille de nœuds',
            nodes_agg_sheet: 'déclaré dans une feuille de nœuds agrégée',
            node_block_parenthood: 'rattaché à un parent par la structure en blocs de la feuille de nœuds',
            results_sheet: 'lu dans la feuille « Résultats »',
            analysis_sheet: 'lu dans la feuille « Analyses des résultats »',
            uncertainty_sheet: 'lu dans la feuille « Analyses d\'incertitudes »',
            flux_from_secondary_sheet: 'créé depuis un onglet secondaire (option « Créer les flux depuis les onglets secondaires »)',
            node_from_flux: 'créé parce qu\'un flux le désigne (option « Créer les nœuds depuis les flux »)',
            propagate_to_parent: 'déduit : un enfant porte ce flux, il est remonté au parent',
            propagate_to_children: 'déduit : le parent porte ce flux, il est descendu aux enfants',
            single_child: 'déduit : le nœud n\'a qu\'un seul enfant, le flux lui revient nécessairement',
            materialize_parent_aggregate: 'déduit : agrégat parent matérialisé pour équilibrer la hiérarchie',
            datatag_broadcast: 'déduit : la structure du flux a été étendue à cette combinaison d\'étiquettes',
            manual_draw: 'tracé à la main dans l\'application',
            json_read: 'lu depuis un diagramme enregistré',
            duplicate: 'issu d\'une duplication',
            paste: 'issu d\'un copier-coller',
            apply_layout: 'issu de l\'application d\'une mise en page',
            merge_diagrams: 'issu d\'une fusion de diagrammes',
            spreadsheet_edit: 'saisi dans l\'onglet tableur',
            node_split: 'issu de la scission d\'un nœud',
            expansion: 'issu d\'une expansion de nœud'
          },
          intro: 'Pourquoi l\'élément sélectionné existe, remonté jusqu\'à la saisie dont il provient.',
          this_element: 'Cet élément',
          because: 'parce que',
          sheet: 'onglet',
          line: 'ligne',
          datatags: 'Combinaison d\'étiquettes',
          unknown: 'Ce fichier ne dit pas pourquoi cet élément existe (écrit avant la traçabilité, ou tracé à la main).',
          select: 'Sélectionnez un nœud ou un flux.'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: 'D\'où vient cette valeur ?',
          intro: 'Ce qui a fixé la valeur du flux sélectionné, et les contraintes qui portent sur elle.',
          unknown: 'Ce fichier ne dit pas ce qui a fixé cette valeur (diagramme non réconcilié, ou réconcilié par une version antérieure).',
          absent: 'Ce flux n\'existe pas pour cette combinaison d\'étiquettes : il n\'y a pas de valeur à expliquer.',
          interval: 'Intervalle possible',
          entered_value: 'Valeur saisie',
          reconciled_value: 'Valeur réconciliée',
          flux_involved: '{{n}} flux concernés',
          show_flux: 'voir l\'équation',
          hide_flux: 'masquer l\'équation',
          also_in: 'Entre aussi dans {{n}} autres contraintes',
          show_others: 'voir',
          hide_others: 'masquer',
          fixed_by: 'Sa valeur est fixée par :',
          takes_part_in: 'Aucune contrainte ne la fixe. Elle participe à :',
          no_constraint: 'Aucune contrainte du modèle ne porte sur ce flux.',
          classification: {
            measured: 'saisi',
            redundant: 'redondant',
            determined: 'déterminé',
            free: 'libre',
            free_unbounded: 'libre, non borné',
            failed: 'non réconcilié'
          },
          meaning: {
            measured: 'La valeur a été saisie, et rien dans le modèle ne permettait de la recalculer : la réconciliation l\'a laissée telle quelle.',
            redundant: 'La valeur a été saisie, et le modèle permettait aussi de la calculer : la réconciliation a arbitré entre les deux.',
            determined: 'La valeur n\'a pas été saisie : les contraintes du modèle suffisent à la fixer, aucune autre solution n\'est possible.',
            free: 'Les contraintes ne suffisent pas à fixer cette valeur ; la réconciliation en a choisi une dans l\'intervalle possible.',
            free_unbounded: 'Les contraintes ne suffisent pas à fixer cette valeur, et rien ne la borne.',
            failed: 'La réconciliation de cette combinaison d\'étiquettes n\'a pas abouti : la valeur affichée est celle d\'entrée.'
          },
          step_by_step: 'Le cheminement, étape par étape :',
          flat_equation: 'L’équation qui détermine :',
          combines: 'Combinaison de :',
          system_one: 'Système de {{equations}} équations à 1 inconnue :',
          system: 'Système de {{equations}} équations à {{unknowns}} inconnues (avec {{others}}) :',
          coefficient: 'Coefficient',
          computed_from: '{{flux}} est lui-même calculé par…',
          bound_propagated: 'Cette borne se transmet d’un flux à l’autre : elle vient d’une propagation sur l’ensemble des contraintes, qu’aucune équation du modèle ne résume.',
          holds_min: 'Ce qui l’empêche de descendre sous {{value}} :',
          holds_max: 'Ce qui l’empêche de dépasser {{value}} :',
          at_least: 'au moins',
          at_most: 'au plus',
          shape: {
            equal: 'Report d’un autre flux',
            factor: 'Proportion d’un autre flux',
            children: 'Somme de ses {{n}} flux enfants',
            into: 'Somme de tout ce qui entre dans {{node}}',
            out_of: 'Somme de tout ce qui sort de {{node}}',
            sum: 'Somme de {{n}} flux',
            balance_node: 'Bilan du nœud {{node}}',
            balance: '{{added}} flux ajoutés, {{removed}} retranchés'
          },
          kinds: {
            mat_balance: 'Bilan matière du nœud',
            aggregation: 'Relation hiérarchique — agrégation des flux enfants',
            stock_aggregation: 'Agrégation des stocks sur le nœud',
            equality: 'Équation saisie (contrainte)',
            bound_min: 'Borne inférieure saisie (contrainte)',
            bound_max: 'Borne supérieure saisie (contrainte)',
            inconsistency: 'Mesures qui se contredisent de',
            determined_by: 'Équation qui détermine'
          }
        },
        mfa: {
          reconciliation: 'Réconciliation',
          open_spreadsheet: 'Ouvrir le tableur (contraintes)',
          run_reconciliation: 'Réconcilier via Excel…',
          value_in_mfa: 'Type de valeur, bornes et incertitude s’éditent dans l’onglet AFM.'
        },
        section: {
          page: 'Page',
          dressing: 'Habillage',
          scale_sizes: 'Échelle & tailles',
          advanced: 'Avancé',
          advanced_geometry: 'Avancé — géométrie'
        },
        group: {
          title: 'Groupe',
          tooltip: 'Associe des nœuds ou des zones de texte à l’élément sélectionné : le cadre se positionne pour englober ses membres et se déplace avec eux'
        },
        visible: 'Visible',
        labels_visible: 'Libellés visibles',
        stock_enabled: 'Activé',
        stock_shape: 'Forme',
        stock_shape_tooltip: 'Afficher la forme de stock',
        stock_labels: 'Libellés',
        stock_labels_tooltip: 'Afficher les libellés du stock',
        stock_shape_visible: 'Forme de stock visible',
        stock_select_node: 'Sélectionnez un nœud portant un stock.',
        stock_caption: 'Libellé stock',
        stock_delta_caption: 'Libellé Δ stock',
        advanced_editor: 'Éditeur avancé…',
        open_editor: 'Ouvrir l’éditeur…',
        tags_assign_hint: 'Assignation (les groupes s’éditent dans Filtres)',
        // OS#1278 — section « Analyse » (graphiques couronne / histogramme).
        analysis: {
          decompose_by: 'Décomposer par',
          compare_by: 'Comparer selon',
          compare_by_secondary: 'Puis selon (séries)',
          none: '— aucune —',
          inputs: 'Flux entrants',
          outputs: 'Flux sortants',
          inputs_by: 'Flux entrants par {{group}}',
          outputs_by: 'Flux sortants par {{group}}',
          node_children: 'Nœuds enfants ({{dim}})',
          flux_children: 'Flux enfants ({{dim}})',
          repr_auto: 'Auto',
          repr_donut: 'Couronne',
          repr_bars: 'Barres',
          scale: 'Échelle',
          scale_auto: 'Auto',
          scale_shared: 'Partagée',
          scale_per_group: 'Par grappe',
          scale_auto_hint: 'Échelle partagée, sauf si une grappe y devient illisible',
          scale_shared_hint: 'Une seule échelle pour tout le graphique',
          scale_per_group_hint: 'Une échelle par grappe — une grappe = une étiquette de « Comparer selon »',
          show_in_tooltip: 'Afficher dans l’info-bulle',
          show_on_node: 'Afficher sur le nœud (couronne / histogramme)',
          select_subject: 'Sélectionner un nœud ou un flux.'
        },
        // OS#1285 — visibilité des blocs d'info-bulle.
        tooltip_blocks: {
          title: 'Blocs visibles',
          values: 'Valeurs',
          flux: 'Flux',
          tags: 'Tags',
          series_flux: 'Séries flux',
          data: 'Données',
          series_data: 'Séries données',
          unitary: 'Sankey unitaire',
          analysis: 'Graphique d\'analyse'
        },
        // OS#1286 — registre d'unités du diagramme (grandeurs/unités/défauts).
        units: {
          title: 'Unités du diagramme',
          none: '— aucune —',
          type_default: 'défaut',
          open_editor: 'Éditer…',
          open_editor_tooltip: 'Éditer les unités du diagramme (grandeurs, unités, coefficients, défauts)',
          symbol: 'Symbole',
          display_name: 'Libellé',
          display_name_tooltip: 'Texte réellement écrit sur le diagramme pour cette unité. Vide : le symbole canonique est utilisé. Permet à un diagramme de dire « tonnes » tout en référençant l’unité t du catalogue — les conversions sont inchangées.',
          coefficient: 'Coefficient',
          coefficient_tooltip: 'Valeur de cette unité exprimée dans l\'unité de base de sa grandeur (unité de base = 1). Les valeurs sont stockées dans l\'unité de base.',
          display_scale: 'Échelle',
          display_scale_tooltip: 'Échelle d\'affichage propre à la grandeur (façon e!Sankey) : quantité en unité de base affichée sur 100 px pour les bandes « de type unité ». Vide : échelle du dessin. Permet d\'équilibrer des grandeurs différentes (kWh vs t vs €) sur un même flux.',
          default: 'Défaut',
          default_tooltip: 'Unité d\'affichage par défaut de cette grandeur (héritée par les flux sans unité explicite)',
          add_unit: '+ Unité',
          add_unit_type: '+ Grandeur',
          new_unit_name: 'unité',
          new_unit_type_name: 'Nouvelle grandeur',
          empty: 'Aucune grandeur dans le registre — ajoutez-en une.'
        }
      },
      filter_panel: {
        filter: 'Filtrer',
        select: 'Sélectionner',
        select_tooltip: 'Sélectionner des éléments par type et par tag (opérations groupées)',
        edit: 'Éditer',
        edit_group: 'Éditer ce groupe',
        show_hidden: 'Afficher les groupes cachés ({{count}})',
        hide_hidden: 'Masquer les groupes cachés',
        select_elements: 'Sélectionner des éléments',
        deselect_all: 'Tout désélectionner',
        selection_summary: 'Sélection : {{summary}}',
        short: {
          node: 'Nœuds',
          link: 'Flux',
          data: 'Données',
          level: 'Niveaux',
          views: 'Vues'
        }
      }
    }
  },
  //=======================================================
  //ES
  //=======================================================
  es: {
    translation: {
      inspector: {
        view: 'Vista',
        back_to_selection: 'Volver a la selección',
        pin: 'Fijar el panel (el dibujo se reajusta a su izquierda)',
        unpin: 'Desacoplar el panel (flota sobre el dibujo)',
        target: {
          view: 'Vista',
          node: 'Nodo', nodes: 'nodos',
          link: 'Flujo', links: 'flujos',
          container: 'Zona', containers: 'zonas',
          legend: 'Leyenda', legends: 'leyendas',
          title: 'Título', titles: 'títulos',
          mixed: 'Selección mixta', elements: 'elementos'
        },
        nothing_here: 'Ningún ajuste disponible para: {{target}}.',
        selection: 'Selección',
        selection_count: 'Selección ({{count}})',
        styles_count: 'Estilos ({{count}})',
        cascade: 'Cascada',
        style_name: 'Nombre del estilo',
        new_style: '+ Nuevo estilo',
        delete_style: 'Eliminar',
        delete_style_tooltip: 'Eliminar este estilo (los elementos que lo seguían vuelven al resto de su cascada)',
        attach_style: 'Adjuntar un estilo a la selección (final de la cascada, prioritario)',
        detach_style: 'Separar este estilo de la selección',
        edited_style_hint: 'Edición del estilo resaltado: todos los elementos que lo siguen se modificarán. El último de la cascada gana; una anulación local siempre gana.',
        divergent_cascade: 'Cascada del 1.er elemento — otros elementos seleccionados siguen una cascada diferente. ',
        selection_hint: 'Atributos atenuados: heredados de los estilos (cascada). Borde morado: anulado en la selección. Borde naranja: valores múltiples.',
        tab_overloaded: 'Contiene atributos anulados',
        provenance: {
          local: 'Anulado aquí (en la selección)',
          from_style: 'Heredado del estilo « {{style}} »',
          factory: 'Valor de fábrica'
        },
        tab: {
          stock: 'Stock',
          tooltip: 'Información',
          tags: 'Etiquetas',
          analysis: 'Análisis',
          title: 'Título',
          mfa: 'AFM',
          styles: 'Estilos'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: 'Origen',
          unresolved: 'este elemento lo desencadenó, pero el archivo no indica por qué existe',
          rules: {
            data_sheet: 'introducido en una fila de una hoja de datos',
            matrix_sheet: 'introducido en una matriz de flujos',
            min_max_sheet: 'establecido por un límite de la hoja «Min Max»',
            constraints_sheet: 'establecido por una ecuación de la hoja «Restricciones»',
            ratio_flux_sheet: 'establecido por una fila de la hoja «Ratio de flujos»',
            ratio_stock_flux_sheet: 'establecido por una fila de la hoja «Ratio de flujo de stock»',
            stock_chaining_sheet: 'establecido por una fila de la hoja «Encadenamiento de stocks»',
            stocks_sheet: 'declarado en una fila de la hoja «Stocks»',
            stock_parent_aggregate: 'agregado de stock creado en el nodo padre',
            stock_level_mirror: 'nivel de stock creado como reflejo de una variación declarada',
            nodes_sheet: 'declarado en una hoja de nodos',
            nodes_agg_sheet: 'declarado en una hoja de nodos agregados',
            node_block_parenthood: 'vinculado a un padre por la estructura en bloques de la hoja de nodos',
            results_sheet: 'leído de la hoja «Resultados»',
            analysis_sheet: 'leído de la hoja «Análisis de resultados»',
            uncertainty_sheet: 'leído de la hoja «Análisis de incertidumbre»',
            flux_from_secondary_sheet: 'creado desde una hoja secundaria (opción «Crear los flujos desde las hojas secundarias»)',
            node_from_flux: 'creado porque un flujo lo designa (opción «Crear los nodos desde los flujos»)',
            propagate_to_parent: 'deducido: un hijo lleva este flujo, se ha propagado al padre',
            propagate_to_children: 'deducido: el padre lleva este flujo, se ha propagado a los hijos',
            single_child: 'deducido: el nodo solo tiene un hijo, el flujo le corresponde necesariamente',
            materialize_parent_aggregate: 'deducido: agregado padre materializado para equilibrar la jerarquía',
            datatag_broadcast: 'deducido: la estructura del flujo se ha extendido a esta combinación de etiquetas',
            manual_draw: 'dibujado a mano en la aplicación',
            json_read: 'leído de un diagrama guardado',
            duplicate: 'procedente de una duplicación',
            paste: 'procedente de un copiar y pegar',
            apply_layout: 'procedente de la aplicación de un diseño',
            merge_diagrams: 'procedente de la fusión de diagramas',
            spreadsheet_edit: 'introducido en la pestaña de hoja de cálculo',
            node_split: 'procedente de la división de un nodo',
            expansion: 'procedente de la expansión de un nodo'
          },
          intro: 'Por qué existe el elemento seleccionado, remontado hasta la entrada de la que procede.',
          this_element: 'Este elemento',
          because: 'porque',
          sheet: 'hoja',
          line: 'línea',
          datatags: 'Combinación de etiquetas',
          unknown: 'Este archivo no indica por qué existe este elemento (escrito antes del seguimiento de origen, o dibujado a mano).',
          select: 'Seleccione un nodo o un flujo.'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: '¿De dónde viene este valor?',
          intro: 'Lo que fijó el valor del flujo seleccionado, y las restricciones que actúan sobre él.',
          unknown: 'Este archivo no indica qué fijó este valor (diagrama no reconciliado, o reconciliado por una versión anterior).',
          absent: 'Este flujo no existe para esta combinación de etiquetas: no hay valor que explicar.',
          interval: 'Intervalo posible',
          entered_value: 'Valor introducido',
          reconciled_value: 'Valor reconciliado',
          flux_involved: '{{n}} flujos implicados',
          show_flux: 'ver la ecuación',
          hide_flux: 'ocultar la ecuación',
          also_in: 'Aparece también en otras {{n}} restricciones',
          show_others: 'ver',
          hide_others: 'ocultar',
          fixed_by: 'Su valor está fijado por:',
          takes_part_in: 'Ninguna restricción lo fija. Participa en:',
          no_constraint: 'Ninguna restricción del modelo actúa sobre este flujo.',
          classification: {
            measured: 'introducido',
            redundant: 'redundante',
            determined: 'determinado',
            free: 'libre',
            free_unbounded: 'libre, sin cotas',
            failed: 'no reconciliado'
          },
          meaning: {
            measured: 'El valor fue introducido y nada en el modelo permitía recalcularlo: la reconciliación lo dejó tal cual.',
            redundant: 'El valor fue introducido y el modelo también podía calcularlo: la reconciliación arbitró entre ambos.',
            determined: 'El valor no fue introducido: las restricciones del modelo bastan para fijarlo, no hay otra solución posible.',
            free: 'Las restricciones no bastan para fijar este valor; la reconciliación eligió uno dentro del intervalo posible.',
            free_unbounded: 'Las restricciones no bastan para fijar este valor, y nada lo acota.',
            failed: 'La reconciliación de esta combinación de etiquetas no llegó a término: el valor mostrado es el de entrada.'
          },
          step_by_step: 'Paso a paso:',
          flat_equation: 'La ecuación que la determina:',
          combines: 'Combinación de:',
          system_one: 'Sistema de {{equations}} ecuaciones con 1 incógnita:',
          system: 'Sistema de {{equations}} ecuaciones con {{unknowns}} incógnitas (con {{others}}):',
          coefficient: 'Coeficiente',
          computed_from: '{{flux}} se calcula a su vez por…',
          bound_propagated: 'Este límite pasa de un flujo a otro: procede de una propagación sobre el conjunto de las restricciones, que ninguna ecuación del modelo resume.',
          holds_min: 'Lo que impide que baje de {{value}}:',
          holds_max: 'Lo que impide que supere {{value}}:',
          at_least: 'como mínimo',
          at_most: 'como máximo',
          shape: {
            equal: 'Igual a otro flujo',
            factor: 'Proporción de otro flujo',
            children: 'Suma de sus {{n}} flujos hijos',
            into: 'Suma de todo lo que entra en {{node}}',
            out_of: 'Suma de todo lo que sale de {{node}}',
            sum: 'Suma de {{n}} flujos',
            balance_node: 'Balance del nodo {{node}}',
            balance: '{{added}} flujos sumados, {{removed}} restados'
          },
          kinds: {
            mat_balance: 'Balance de materia del nodo',
            aggregation: 'Relación jerárquica — agregación de los flujos hijos',
            stock_aggregation: 'Agregación de existencias en el nodo',
            equality: 'Ecuación introducida (restricción)',
            bound_min: 'Cota inferior introducida (restricción)',
            bound_max: 'Cota superior introducida (restricción)',
            inconsistency: 'Mediciones que se contradicen en',
            determined_by: 'Ecuación que determina'
          }
        },
        mfa: {
          reconciliation: 'Conciliación',
          open_spreadsheet: 'Abrir la hoja de cálculo (restricciones)',
          run_reconciliation: 'Conciliar vía Excel…',
          value_in_mfa: 'El tipo de valor, los límites y la incertidumbre se editan en la pestaña AFM.'
        },
        section: {
          page: 'Página',
          dressing: 'Fondo y cuadrícula',
          scale_sizes: 'Escala y tamaños',
          advanced: 'Avanzado',
          advanced_geometry: 'Avanzado — geometría'
        },
        group: {
          title: 'Grupo',
          tooltip: 'Asocia nodos o zonas de texto al elemento seleccionado: el marco se posiciona para abarcar a sus miembros y se desplaza con ellos'
        },
        visible: 'Visible',
        labels_visible: 'Etiquetas visibles',
        stock_enabled: 'Activado',
        stock_shape: 'Forma',
        stock_shape_tooltip: 'Mostrar la forma de stock',
        stock_labels: 'Etiquetas',
        stock_labels_tooltip: 'Mostrar las etiquetas de stock',
        stock_shape_visible: 'Forma de stock visible',
        stock_select_node: 'Seleccione un nodo que lleve un stock.',
        stock_caption: 'Etiqueta de stock',
        stock_delta_caption: 'Etiqueta Δ stock',
        advanced_editor: 'Editor avanzado…',
        open_editor: 'Abrir el editor…',
        tags_assign_hint: 'Asignación (los grupos se editan en Filtros)',
        // OS#1278 — sección « Análisis » (gráficos anillo / histograma).
        analysis: {
          decompose_by: 'Descomponer por',
          compare_by: 'Comparar según',
          compare_by_secondary: 'Luego según (series)',
          none: '— ninguna —',
          inputs: 'Flujos entrantes',
          outputs: 'Flujos salientes',
          inputs_by: 'Flujos entrantes por {{group}}',
          outputs_by: 'Flujos salientes por {{group}}',
          node_children: 'Nodos hijos ({{dim}})',
          flux_children: 'Flujos hijos ({{dim}})',
          repr_auto: 'Auto',
          repr_donut: 'Anillo',
          repr_bars: 'Barras',
          scale: 'Escala',
          scale_auto: 'Auto',
          scale_shared: 'Compartida',
          scale_per_group: 'Por grupo',
          scale_auto_hint: 'Escala compartida, salvo si un grupo se vuelve ilegible',
          scale_shared_hint: 'Una sola escala para todo el gráfico',
          scale_per_group_hint: 'Una escala por grupo — un grupo es una etiqueta de «Comparar según»',
          show_in_tooltip: 'Mostrar en el tooltip',
          show_on_node: 'Mostrar en el nodo (anillo / histograma)',
          select_subject: 'Seleccione un nodo o un flujo.'
        },
        // OS#1285 — visibilidad de los bloques del tooltip.
        tooltip_blocks: {
          title: 'Bloques visibles',
          values: 'Valores',
          flux: 'Flujo',
          tags: 'Etiquetas',
          series_flux: 'Series de flujo',
          data: 'Datos',
          series_data: 'Series de datos',
          unitary: 'Sankey unitario',
          analysis: 'Gráfico de análisis'
        },
        // OS#1286 — registro de unidades del diagrama.
        units: {
          title: 'Unidades del diagrama',
          none: '— ninguna —',
          type_default: 'por defecto',
          open_editor: 'Editar…',
          open_editor_tooltip: 'Editar las unidades del diagrama (magnitudes, unidades, coeficientes, valores por defecto)',
          symbol: 'Símbolo',
          display_name: 'Etiqueta',
          display_name_tooltip: 'Texto escrito realmente en el diagrama para esta unidad. Vacío: se usa el símbolo canónico. Permite que un diagrama diga « toneladas » sin dejar de referirse a la unidad t del catálogo; las conversiones no cambian.',
          coefficient: 'Coeficiente',
          coefficient_tooltip: 'Valor de esta unidad expresado en la unidad base de su magnitud (unidad base = 1). Los valores se almacenan en la unidad base.',
          display_scale: 'Escala',
          display_scale_tooltip: 'Escala de visualización propia de la magnitud (como e!Sankey): cantidad en unidad base mostrada sobre 100 px para las bandas de tipo unidad. Vacío: escala del diagrama. Permite equilibrar magnitudes diferentes (kWh vs t vs €) en un mismo flujo.',
          default: 'Por defecto',
          default_tooltip: 'Unidad de visualización por defecto de esta magnitud (heredada por los flujos sin unidad explícita)',
          add_unit: '+ Unidad',
          add_unit_type: '+ Magnitud',
          new_unit_name: 'unidad',
          new_unit_type_name: 'Nueva magnitud',
          empty: 'Ninguna magnitud en el registro — añada una.'
        }
      },
      filter_panel: {
        filter: 'Filtrar',
        select: 'Seleccionar',
        select_tooltip: 'Seleccionar elementos por tipo y etiqueta (operaciones en grupo)',
        edit: 'Editar',
        edit_group: 'Editar este grupo',
        show_hidden: 'Mostrar grupos ocultos ({{count}})',
        hide_hidden: 'Ocultar grupos ocultos',
        select_elements: 'Seleccionar elementos',
        deselect_all: 'Deseleccionar todo',
        selection_summary: 'Selección: {{summary}}',
        short: {
          node: 'Nodos',
          link: 'Flujos',
          data: 'Datos',
          level: 'Niveles',
          views: 'Vistas'
        }
      }
    }
  },
  //=======================================================
  //DE
  //=======================================================
  de: {
    translation: {
      inspector: {
        view: 'Ansicht',
        back_to_selection: 'Zurück zur Auswahl',
        pin: 'Panel anheften (die Zeichnung wird links davon neu angepasst)',
        unpin: 'Panel lösen (schwebt über der Zeichnung)',
        target: {
          view: 'Ansicht',
          node: 'Knoten', nodes: 'Knoten',
          link: 'Fluss', links: 'Flüsse',
          container: 'Bereich', containers: 'Bereiche',
          legend: 'Legende', legends: 'Legenden',
          title: 'Titel', titles: 'Titel',
          mixed: 'Gemischte Auswahl', elements: 'Elemente'
        },
        nothing_here: 'Keine Einstellungen verfügbar für: {{target}}.',
        selection: 'Auswahl',
        selection_count: 'Auswahl ({{count}})',
        styles_count: 'Stile ({{count}})',
        cascade: 'Kaskade',
        style_name: 'Name des Stils',
        new_style: '+ Neuer Stil',
        delete_style: 'Löschen',
        delete_style_tooltip: 'Diesen Stil löschen (Elemente, die ihm folgten, fallen auf den Rest ihrer Kaskade zurück)',
        attach_style: 'Einen Stil an die Auswahl anhängen (Ende der Kaskade, hat Vorrang)',
        detach_style: 'Diesen Stil von der Auswahl lösen',
        edited_style_hint: 'Bearbeitung des hervorgehobenen Stils: alle Elemente, die ihm folgen, werden geändert. Der letzte der Kaskade gewinnt; eine lokale Überschreibung gewinnt immer.',
        divergent_cascade: 'Kaskade des 1. Elements — andere ausgewählte Elemente folgen einer anderen Kaskade. ',
        selection_hint: 'Abgeblendete Attribute: von den Stilen geerbt (Kaskade). Violetter Rahmen: in der Auswahl überschrieben. Oranger Rahmen: mehrere Werte.',
        tab_overloaded: 'Enthält überschriebene Attribute',
        provenance: {
          local: 'Hier überschrieben (in der Auswahl)',
          from_style: 'Vom Stil « {{style}} » geerbt',
          factory: 'Werkseinstellung'
        },
        tab: {
          stock: 'Bestand',
          tooltip: 'Tooltip',
          tags: 'Tags',
          analysis: 'Analyse',
          title: 'Titel',
          mfa: 'MFA',
          styles: 'Stile'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: 'Herkunft',
          unresolved: 'dieses Element hat es ausgelöst, aber die Datei sagt nicht, warum es existiert',
          rules: {
            data_sheet: 'in einer Zeile eines Datenblatts eingegeben',
            matrix_sheet: 'in einer Flussmatrix eingegeben',
            min_max_sheet: 'durch eine Grenze des Blatts „Min Max“ festgelegt',
            constraints_sheet: 'durch eine Gleichung des Blatts „Nebenbedingungen“ festgelegt',
            ratio_flux_sheet: 'durch eine Zeile des Blatts „Flussverhältnis“ festgelegt',
            ratio_stock_flux_sheet: 'durch eine Zeile des Blatts „Bestandsflussverhältnis“ festgelegt',
            stock_chaining_sheet: 'durch eine Zeile des Blatts „Bestandsverkettung“ festgelegt',
            stocks_sheet: 'in einer Zeile des Blatts „Bestände“ deklariert',
            stock_parent_aggregate: 'Bestandsaggregat am übergeordneten Knoten erzeugt',
            stock_level_mirror: 'Bestandsniveau als Spiegel einer deklarierten Änderung erzeugt',
            nodes_sheet: 'in einem Knotenblatt deklariert',
            nodes_agg_sheet: 'in einem aggregierten Knotenblatt deklariert',
            node_block_parenthood: 'durch die Blockstruktur des Knotenblatts einem Elternknoten zugeordnet',
            results_sheet: 'aus dem Blatt „Ergebnisse“ gelesen',
            analysis_sheet: 'aus dem Blatt „Ergebnisanalyse“ gelesen',
            uncertainty_sheet: 'aus dem Blatt „Unsicherheitsanalyse“ gelesen',
            flux_from_secondary_sheet: 'aus einem Nebenblatt erzeugt (Option „Flüsse aus Nebenblättern erzeugen“)',
            node_from_flux: 'erzeugt, weil ein Fluss ihn benennt (Option „Knoten aus Flüssen erzeugen“)',
            propagate_to_parent: 'abgeleitet: ein Kind trägt diesen Fluss, er wurde zum Elternknoten hochgezogen',
            propagate_to_children: 'abgeleitet: der Elternknoten trägt diesen Fluss, er wurde an die Kinder weitergegeben',
            single_child: 'abgeleitet: der Knoten hat nur ein Kind, der Fluss gehört notwendigerweise dazu',
            materialize_parent_aggregate: 'abgeleitet: Elternaggregat erzeugt, um die Hierarchie auszugleichen',
            datatag_broadcast: 'abgeleitet: die Flussstruktur wurde auf diese Tag-Kombination ausgeweitet',
            manual_draw: 'von Hand in der Anwendung gezeichnet',
            json_read: 'aus einem gespeicherten Diagramm gelesen',
            duplicate: 'aus einer Duplizierung',
            paste: 'aus einem Kopieren und Einfügen',
            apply_layout: 'aus dem Anwenden eines Layouts',
            merge_diagrams: 'aus dem Zusammenführen von Diagrammen',
            spreadsheet_edit: 'im Tabellenblatt-Reiter eingegeben',
            node_split: 'aus dem Aufteilen eines Knotens',
            expansion: 'aus dem Aufklappen eines Knotens'
          },
          intro: 'Warum das ausgewählte Element existiert, zurückverfolgt bis zur Eingabe, aus der es stammt.',
          this_element: 'Dieses Element',
          because: 'weil',
          sheet: 'Blatt',
          line: 'Zeile',
          datatags: 'Tag-Kombination',
          unknown: 'Diese Datei gibt nicht an, warum dieses Element existiert (vor der Herkunftsverfolgung geschrieben oder von Hand gezeichnet).',
          select: 'Wählen Sie einen Knoten oder einen Fluss aus.'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: 'Woher stammt dieser Wert?',
          intro: 'Was den Wert des ausgewählten Flusses festgelegt hat, und die Nebenbedingungen, die auf ihn wirken.',
          unknown: 'Diese Datei sagt nicht, was diesen Wert festgelegt hat (Diagramm nicht abgeglichen oder von einer älteren Version abgeglichen).',
          absent: 'Dieser Fluss existiert für diese Etikettenkombination nicht: Es gibt keinen Wert zu erklären.',
          interval: 'Möglicher Bereich',
          entered_value: 'Eingegebener Wert',
          reconciled_value: 'Abgeglichener Wert',
          flux_involved: '{{n}} beteiligte Flüsse',
          show_flux: 'Gleichung anzeigen',
          hide_flux: 'Gleichung ausblenden',
          also_in: 'Kommt auch in {{n}} weiteren Nebenbedingungen vor',
          show_others: 'anzeigen',
          hide_others: 'ausblenden',
          fixed_by: 'Sein Wert wird festgelegt durch:',
          takes_part_in: 'Keine Nebenbedingung legt ihn fest. Er wirkt mit in:',
          no_constraint: 'Keine Nebenbedingung des Modells wirkt auf diesen Fluss.',
          classification: {
            measured: 'erfasst',
            redundant: 'redundant',
            determined: 'bestimmt',
            free: 'frei',
            free_unbounded: 'frei, unbeschränkt',
            failed: 'nicht abgeglichen'
          },
          meaning: {
            measured: 'Der Wert wurde eingegeben, und nichts im Modell erlaubte, ihn neu zu berechnen: Der Abgleich hat ihn unverändert gelassen.',
            redundant: 'Der Wert wurde eingegeben, und das Modell konnte ihn ebenfalls berechnen: Der Abgleich hat zwischen beiden entschieden.',
            determined: 'Der Wert wurde nicht eingegeben: Die Nebenbedingungen des Modells genügen, um ihn festzulegen, eine andere Lösung gibt es nicht.',
            free: 'Die Nebenbedingungen genügen nicht, um diesen Wert festzulegen; der Abgleich hat einen aus dem möglichen Bereich gewählt.',
            free_unbounded: 'Die Nebenbedingungen genügen nicht, um diesen Wert festzulegen, und nichts beschränkt ihn.',
            failed: 'Der Abgleich dieser Etikettenkombination ist gescheitert: Der angezeigte Wert ist der Eingabewert.'
          },
          step_by_step: 'Schritt für Schritt:',
          flat_equation: 'Die Gleichung, die ihn bestimmt:',
          combines: 'Kombination aus:',
          system_one: 'System aus {{equations}} Gleichungen mit 1 Unbekannten:',
          system: 'System aus {{equations}} Gleichungen mit {{unknowns}} Unbekannten (mit {{others}}):',
          coefficient: 'Koeffizient',
          computed_from: '{{flux}} wird seinerseits berechnet durch…',
          bound_propagated: 'Diese Schranke wandert von einem Fluss zum anderen: Sie stammt aus einer Propagation über alle Nebenbedingungen, die keine einzelne Gleichung zusammenfasst.',
          holds_min: 'Was verhindert, dass er unter {{value}} fällt:',
          holds_max: 'Was verhindert, dass er {{value}} übersteigt:',
          at_least: 'mindestens',
          at_most: 'höchstens',
          shape: {
            equal: 'Gleich einem anderen Fluss',
            factor: 'Anteil eines anderen Flusses',
            children: 'Summe seiner {{n}} untergeordneten Flüsse',
            into: 'Summe aller Zuflüsse in {{node}}',
            out_of: 'Summe aller Abflüsse aus {{node}}',
            sum: 'Summe aus {{n}} Flüssen',
            balance_node: 'Bilanz des Knotens {{node}}',
            balance: '{{added}} Flüsse addiert, {{removed}} subtrahiert'
          },
          kinds: {
            mat_balance: 'Massenbilanz des Knotens',
            aggregation: 'Hierarchische Beziehung — Aggregation der Kindflüsse',
            stock_aggregation: 'Bestandsaggregation am Knoten',
            equality: 'Eingegebene Gleichung (Nebenbedingung)',
            bound_min: 'Eingegebene Untergrenze (Nebenbedingung)',
            bound_max: 'Eingegebene Obergrenze (Nebenbedingung)',
            inconsistency: 'Messwerte widersprechen sich um',
            determined_by: 'Bestimmende Gleichung für'
          }
        },
        mfa: {
          reconciliation: 'Abgleich',
          open_spreadsheet: 'Tabelle öffnen (Nebenbedingungen)',
          run_reconciliation: 'Abgleich über Excel…',
          value_in_mfa: 'Werttyp, Grenzen und Unsicherheit werden im MFA-Tab bearbeitet.'
        },
        section: {
          page: 'Seite',
          dressing: 'Hintergrund & Raster',
          scale_sizes: 'Maßstab & Größen',
          advanced: 'Erweitert',
          advanced_geometry: 'Erweitert — Geometrie'
        },
        group: {
          title: 'Gruppe',
          tooltip: 'Verknüpft Knoten oder Textzonen mit dem ausgewählten Element: der Rahmen umschließt seine Mitglieder und bewegt sich mit ihnen'
        },
        visible: 'Sichtbar',
        labels_visible: 'Beschriftungen sichtbar',
        stock_enabled: 'Aktiviert',
        stock_shape: 'Form',
        stock_shape_tooltip: 'Die Bestandsform anzeigen',
        stock_labels: 'Beschriftungen',
        stock_labels_tooltip: 'Die Bestandsbeschriftungen anzeigen',
        stock_shape_visible: 'Bestandsform sichtbar',
        stock_select_node: 'Wählen Sie einen Knoten mit Bestand.',
        stock_caption: 'Bestandsbeschriftung',
        stock_delta_caption: 'Δ-Bestandsbeschriftung',
        advanced_editor: 'Erweiterter Editor…',
        open_editor: 'Editor öffnen…',
        tags_assign_hint: 'Zuweisung (Gruppen werden in Filter bearbeitet)',
        // OS#1278 — Abschnitt „Analyse“ (Ring- / Histogramm-Diagramme).
        analysis: {
          decompose_by: 'Zerlegen nach',
          compare_by: 'Vergleichen über',
          compare_by_secondary: 'Dann über (Reihen)',
          none: '— keine —',
          inputs: 'Eingehende Flüsse',
          outputs: 'Ausgehende Flüsse',
          inputs_by: 'Eingehende Flüsse nach {{group}}',
          outputs_by: 'Ausgehende Flüsse nach {{group}}',
          node_children: 'Kindknoten ({{dim}})',
          flux_children: 'Kindflüsse ({{dim}})',
          repr_auto: 'Auto',
          repr_donut: 'Ring',
          repr_bars: 'Balken',
          scale: 'Skala',
          scale_auto: 'Auto',
          scale_shared: 'Gemeinsam',
          scale_per_group: 'Pro Gruppe',
          scale_auto_hint: 'Gemeinsamer Maßstab, außer wenn eine Gruppe unlesbar wird',
          scale_shared_hint: 'Ein einziger Maßstab für das ganze Diagramm',
          scale_per_group_hint: 'Ein Maßstab je Gruppe — eine Gruppe ist ein Label von „Vergleichen über“',
          show_in_tooltip: 'Im Tooltip anzeigen',
          show_on_node: 'Am Knoten anzeigen (Ring / Histogramm)',
          select_subject: 'Wählen Sie einen Knoten oder einen Fluss.'
        },
        // OS#1285 — Sichtbarkeit der Tooltip-Blöcke.
        tooltip_blocks: {
          title: 'Sichtbare Blöcke',
          values: 'Werte',
          flux: 'Fluss',
          tags: 'Tags',
          series_flux: 'Fluss-Serien',
          data: 'Daten',
          series_data: 'Daten-Serien',
          unitary: 'Einheits-Sankey',
          analysis: 'Analysediagramm'
        },
        // OS#1286 — Einheitenregister des Diagramms.
        units: {
          title: 'Einheiten des Diagramms',
          none: '— keine —',
          type_default: 'Standard',
          open_editor: 'Bearbeiten…',
          open_editor_tooltip: 'Einheiten des Diagramms bearbeiten (Größen, Einheiten, Koeffizienten, Standards)',
          symbol: 'Symbol',
          display_name: 'Bezeichnung',
          display_name_tooltip: 'Text, der für diese Einheit tatsächlich im Diagramm steht. Leer: das kanonische Symbol wird verwendet. So kann ein Diagramm „Tonnen“ schreiben und trotzdem die Katalogeinheit t referenzieren — Umrechnungen bleiben unverändert.',
          coefficient: 'Koeffizient',
          coefficient_tooltip: 'Wert dieser Einheit in der Basiseinheit ihrer Größe (Basiseinheit = 1). Werte werden in der Basiseinheit gespeichert.',
          display_scale: 'Skala',
          display_scale_tooltip: 'Anzeigeskala der Größe (wie e!Sankey): Menge in der Basiseinheit auf 100 px für Einheitentyp-Bänder. Leer: Diagrammskala. Erlaubt das Ausbalancieren verschiedener Größen (kWh vs t vs €) auf demselben Fluss.',
          default: 'Standard',
          default_tooltip: 'Standard-Anzeigeeinheit dieser Größe (von Flüssen ohne explizite Einheit geerbt)',
          add_unit: '+ Einheit',
          add_unit_type: '+ Größe',
          new_unit_name: 'Einheit',
          new_unit_type_name: 'Neue Größe',
          empty: 'Keine Größe im Register — fügen Sie eine hinzu.'
        }
      },
      filter_panel: {
        filter: 'Filtern',
        select: 'Auswählen',
        select_tooltip: 'Elemente nach Typ und Tag auswählen (Sammelvorgänge)',
        edit: 'Bearbeiten',
        edit_group: 'Diese Gruppe bearbeiten',
        show_hidden: 'Ausgeblendete Gruppen anzeigen ({{count}})',
        hide_hidden: 'Ausgeblendete Gruppen verbergen',
        select_elements: 'Elemente auswählen',
        deselect_all: 'Auswahl aufheben',
        selection_summary: 'Auswahl: {{summary}}',
        short: {
          node: 'Knoten',
          link: 'Flüsse',
          data: 'Daten',
          level: 'Ebenen',
          views: 'Ansichten'
        }
      }
    }
  },
  //=======================================================
  //IT
  //=======================================================
  it: {
    translation: {
      inspector: {
        view: 'Vista',
        back_to_selection: 'Torna alla selezione',
        pin: 'Fissa il pannello (il disegno si ridimensiona alla sua sinistra)',
        unpin: 'Sgancia il pannello (fluttua sopra il disegno)',
        target: {
          view: 'Vista',
          node: 'Nodo', nodes: 'nodi',
          link: 'Flusso', links: 'flussi',
          container: 'Zona', containers: 'zone',
          legend: 'Legenda', legends: 'legende',
          title: 'Titolo', titles: 'titoli',
          mixed: 'Selezione mista', elements: 'elementi'
        },
        nothing_here: 'Nessuna impostazione disponibile per: {{target}}.',
        selection: 'Selezione',
        selection_count: 'Selezione ({{count}})',
        styles_count: 'Stili ({{count}})',
        cascade: 'Cascata',
        style_name: 'Nome dello stile',
        new_style: '+ Nuovo stile',
        delete_style: 'Elimina',
        delete_style_tooltip: 'Eliminare questo stile (gli elementi che lo seguivano ricadono sul resto della loro cascata)',
        attach_style: 'Allegare uno stile alla selezione (fine della cascata, prioritario)',
        detach_style: 'Staccare questo stile dalla selezione',
        edited_style_hint: 'Modifica dello stile evidenziato: tutti gli elementi che lo seguono saranno modificati. L’ultimo della cascata vince; una sovrascrittura locale vince sempre.',
        divergent_cascade: 'Cascata del 1º elemento — altri elementi selezionati seguono una cascata diversa. ',
        selection_hint: 'Attributi attenuati: ereditati dagli stili (cascata). Bordo viola: sovrascritto sulla selezione. Bordo arancione: valori multipli.',
        tab_overloaded: 'Contiene attributi sovrascritti',
        provenance: {
          local: 'Sovrascritto qui (sulla selezione)',
          from_style: 'Ereditato dallo stile « {{style}} »',
          factory: 'Valore di fabbrica'
        },
        tab: {
          stock: 'Stock',
          tooltip: 'Tooltip',
          tags: 'Tag',
          analysis: 'Analisi',
          title: 'Titolo',
          mfa: 'AFM',
          styles: 'Stili'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: 'Origine',
          unresolved: 'è stato questo elemento a innescarlo, ma il file non dice perché esiste',
          rules: {
            data_sheet: 'inserito in una riga di un foglio dati',
            matrix_sheet: 'inserito in una matrice di flussi',
            min_max_sheet: 'stabilito da un limite del foglio «Min Max»',
            constraints_sheet: 'stabilito da un\'equazione del foglio «Vincoli»',
            ratio_flux_sheet: 'stabilito da una riga del foglio «Rapporto tra flussi»',
            ratio_stock_flux_sheet: 'stabilito da una riga del foglio «Rapporto flusso-stock»',
            stock_chaining_sheet: 'stabilito da una riga del foglio «Concatenamento degli stock»',
            stocks_sheet: 'dichiarato in una riga del foglio «Stock»',
            stock_parent_aggregate: 'aggregato di stock creato sul nodo padre',
            stock_level_mirror: 'livello di stock creato come riflesso di una variazione dichiarata',
            nodes_sheet: 'dichiarato in un foglio di nodi',
            nodes_agg_sheet: 'dichiarato in un foglio di nodi aggregati',
            node_block_parenthood: 'collegato a un padre dalla struttura a blocchi del foglio dei nodi',
            results_sheet: 'letto dal foglio «Risultati»',
            analysis_sheet: 'letto dal foglio «Analisi dei risultati»',
            uncertainty_sheet: 'letto dal foglio «Analisi di incertezza»',
            flux_from_secondary_sheet: 'creato da un foglio secondario (opzione «Creare i flussi dai fogli secondari»)',
            node_from_flux: 'creato perché un flusso lo designa (opzione «Creare i nodi dai flussi»)',
            propagate_to_parent: 'dedotto: un figlio porta questo flusso, è stato risalito al padre',
            propagate_to_children: 'dedotto: il padre porta questo flusso, è stato trasmesso ai figli',
            single_child: 'dedotto: il nodo ha un solo figlio, il flusso gli spetta necessariamente',
            materialize_parent_aggregate: 'dedotto: aggregato padre materializzato per equilibrare la gerarchia',
            datatag_broadcast: 'dedotto: la struttura del flusso è stata estesa a questa combinazione di etichette',
            manual_draw: 'disegnato a mano nell\'applicazione',
            json_read: 'letto da un diagramma salvato',
            duplicate: 'derivato da una duplicazione',
            paste: 'derivato da un copia-incolla',
            apply_layout: 'derivato dall\'applicazione di un layout',
            merge_diagrams: 'derivato dalla fusione di diagrammi',
            spreadsheet_edit: 'inserito nella scheda foglio di calcolo',
            node_split: 'derivato dalla divisione di un nodo',
            expansion: 'derivato dall\'espansione di un nodo'
          },
          intro: 'Perché esiste l\'elemento selezionato, risalendo fino all\'inserimento da cui proviene.',
          this_element: 'Questo elemento',
          because: 'perché',
          sheet: 'foglio',
          line: 'riga',
          datatags: 'Combinazione di etichette',
          unknown: 'Questo file non indica perché questo elemento esiste (scritto prima del tracciamento dell\'origine, o disegnato a mano).',
          select: 'Selezionare un nodo o un flusso.'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: 'Da dove viene questo valore?',
          intro: 'Ciò che ha fissato il valore del flusso selezionato, e i vincoli che agiscono su di esso.',
          unknown: 'Questo file non dice cosa ha fissato questo valore (diagramma non riconciliato, o riconciliato da una versione precedente).',
          absent: 'Questo flusso non esiste per questa combinazione di etichette: non c\'è alcun valore da spiegare.',
          interval: 'Intervallo possibile',
          entered_value: 'Valore inserito',
          reconciled_value: 'Valore riconciliato',
          flux_involved: '{{n}} flussi coinvolti',
          show_flux: 'mostra l\'equazione',
          hide_flux: 'nascondi l\'equazione',
          also_in: 'Compare anche in altri {{n}} vincoli',
          show_others: 'mostra',
          hide_others: 'nascondi',
          fixed_by: 'Il suo valore è fissato da:',
          takes_part_in: 'Nessun vincolo lo fissa. Partecipa a:',
          no_constraint: 'Nessun vincolo del modello agisce su questo flusso.',
          classification: {
            measured: 'inserito',
            redundant: 'ridondante',
            determined: 'determinato',
            free: 'libero',
            free_unbounded: 'libero, non limitato',
            failed: 'non riconciliato'
          },
          meaning: {
            measured: 'Il valore è stato inserito e nulla nel modello permetteva di ricalcolarlo: la riconciliazione lo ha lasciato invariato.',
            redundant: 'Il valore è stato inserito e il modello poteva anche calcolarlo: la riconciliazione ha arbitrato tra i due.',
            determined: 'Il valore non è stato inserito: i vincoli del modello bastano a fissarlo, non esiste altra soluzione possibile.',
            free: 'I vincoli non bastano a fissare questo valore; la riconciliazione ne ha scelto uno nell\'intervallo possibile.',
            free_unbounded: 'I vincoli non bastano a fissare questo valore, e nulla lo limita.',
            failed: 'La riconciliazione di questa combinazione di etichette non è riuscita: il valore mostrato è quello di ingresso.'
          },
          step_by_step: 'Passo dopo passo:',
          flat_equation: 'L’equazione che lo determina:',
          combines: 'Combinazione di:',
          system_one: 'Sistema di {{equations}} equazioni a 1 incognita:',
          system: 'Sistema di {{equations}} equazioni a {{unknowns}} incognite (con {{others}}):',
          coefficient: 'Coefficiente',
          computed_from: '{{flux}} è a sua volta calcolato da…',
          bound_propagated: 'Questo limite passa da un flusso all’altro: viene da una propagazione sull’insieme dei vincoli, che nessuna equazione del modello riassume.',
          holds_min: 'Ciò che impedisce di scendere sotto {{value}}:',
          holds_max: 'Ciò che impedisce di superare {{value}}:',
          at_least: 'almeno',
          at_most: 'al massimo',
          shape: {
            equal: 'Uguale a un altro flusso',
            factor: 'Quota di un altro flusso',
            children: 'Somma dei suoi {{n}} flussi figli',
            into: 'Somma di tutto ciò che entra in {{node}}',
            out_of: 'Somma di tutto ciò che esce da {{node}}',
            sum: 'Somma di {{n}} flussi',
            balance_node: 'Bilancio del nodo {{node}}',
            balance: '{{added}} flussi sommati, {{removed}} sottratti'
          },
          kinds: {
            mat_balance: 'Bilancio di materia del nodo',
            aggregation: 'Relazione gerarchica — aggregazione dei flussi figli',
            stock_aggregation: 'Aggregazione delle scorte sul nodo',
            equality: 'Equazione inserita (vincolo)',
            bound_min: 'Limite inferiore inserito (vincolo)',
            bound_max: 'Limite superiore inserito (vincolo)',
            inconsistency: 'Misure che si contraddicono di',
            determined_by: 'Equazione che determina'
          }
        },
        mfa: {
          reconciliation: 'Riconciliazione',
          open_spreadsheet: 'Aprire il foglio di calcolo (vincoli)',
          run_reconciliation: 'Riconciliare via Excel…',
          value_in_mfa: 'Tipo di valore, limiti e incertezza si modificano nella scheda AFM.'
        },
        section: {
          page: 'Pagina',
          dressing: 'Sfondo e griglia',
          scale_sizes: 'Scala e dimensioni',
          advanced: 'Avanzate',
          advanced_geometry: 'Avanzate — geometria'
        },
        group: {
          title: 'Gruppo',
          tooltip: 'Associa nodi o zone di testo all’elemento selezionato: la cornice si posiziona per racchiudere i suoi membri e si sposta con essi'
        },
        visible: 'Visibile',
        labels_visible: 'Etichette visibili',
        stock_enabled: 'Attivato',
        stock_shape: 'Forma',
        stock_shape_tooltip: 'Mostrare la forma di stock',
        stock_labels: 'Etichette',
        stock_labels_tooltip: 'Mostrare le etichette di stock',
        stock_shape_visible: 'Forma di stock visibile',
        stock_select_node: 'Selezionare un nodo con uno stock.',
        stock_caption: 'Etichetta stock',
        stock_delta_caption: 'Etichetta Δ stock',
        advanced_editor: 'Editor avanzato…',
        open_editor: 'Aprire l’editor…',
        tags_assign_hint: 'Assegnazione (i gruppi si modificano in Filtri)',
        // OS#1278 — sezione « Analisi » (grafici anello / istogramma).
        analysis: {
          decompose_by: 'Scomporre per',
          compare_by: 'Confrontare per',
          compare_by_secondary: 'Poi per (serie)',
          none: '— nessuna —',
          inputs: 'Flussi entranti',
          outputs: 'Flussi uscenti',
          inputs_by: 'Flussi entranti per {{group}}',
          outputs_by: 'Flussi uscenti per {{group}}',
          node_children: 'Nodi figli ({{dim}})',
          flux_children: 'Flussi figli ({{dim}})',
          repr_auto: 'Auto',
          repr_donut: 'Anello',
          repr_bars: 'Barre',
          scale: 'Scala',
          scale_auto: 'Auto',
          scale_shared: 'Condivisa',
          scale_per_group: 'Per gruppo',
          scale_auto_hint: 'Scala condivisa, salvo se un gruppo diventa illeggibile',
          scale_shared_hint: 'Una sola scala per tutto il grafico',
          scale_per_group_hint: 'Una scala per gruppo — un gruppo è un’etichetta di «Confrontare per»',
          show_in_tooltip: 'Mostra nel tooltip',
          show_on_node: 'Mostra sul nodo (anello / istogramma)',
          select_subject: 'Seleziona un nodo o un flusso.'
        },
        // OS#1285 — visibilità dei blocchi del tooltip.
        tooltip_blocks: {
          title: 'Blocchi visibili',
          values: 'Valori',
          flux: 'Flusso',
          tags: 'Tag',
          series_flux: 'Serie di flusso',
          data: 'Dati',
          series_data: 'Serie di dati',
          unitary: 'Sankey unitario',
          analysis: 'Grafico di analisi'
        },
        // OS#1286 — registro delle unità del diagramma.
        units: {
          title: 'Unità del diagramma',
          none: '— nessuna —',
          type_default: 'predefinita',
          open_editor: 'Modifica…',
          open_editor_tooltip: 'Modificare le unità del diagramma (grandezze, unità, coefficienti, predefinite)',
          symbol: 'Simbolo',
          display_name: 'Etichetta',
          display_name_tooltip: 'Testo effettivamente scritto sul diagramma per questa unità. Vuoto: si usa il simbolo canonico. Permette a un diagramma di dire « tonnellate » pur riferendosi all’unità t del catalogo: le conversioni non cambiano.',
          coefficient: 'Coefficiente',
          coefficient_tooltip: 'Valore di questa unità espresso nell\'unità base della sua grandezza (unità base = 1). I valori sono memorizzati nell\'unità base.',
          display_scale: 'Scala',
          display_scale_tooltip: 'Scala di visualizzazione propria della grandezza (come e!Sankey): quantità in unità base mostrata su 100 px per le bande di tipo unità. Vuoto: scala del diagramma. Permette di bilanciare grandezze diverse (kWh vs t vs €) sullo stesso flusso.',
          default: 'Predefinita',
          default_tooltip: 'Unità di visualizzazione predefinita di questa grandezza (ereditata dai flussi senza unità esplicita)',
          add_unit: '+ Unità',
          add_unit_type: '+ Grandezza',
          new_unit_name: 'unità',
          new_unit_type_name: 'Nuova grandezza',
          empty: 'Nessuna grandezza nel registro — aggiungine una.'
        }
      },
      filter_panel: {
        filter: 'Filtrare',
        select: 'Selezionare',
        select_tooltip: 'Selezionare elementi per tipo e tag (operazioni di gruppo)',
        edit: 'Modificare',
        edit_group: 'Modificare questo gruppo',
        show_hidden: 'Mostra gruppi nascosti ({{count}})',
        hide_hidden: 'Nascondi gruppi nascosti',
        select_elements: 'Selezionare elementi',
        deselect_all: 'Deselezionare tutto',
        selection_summary: 'Selezione: {{summary}}',
        short: {
          node: 'Nodi',
          link: 'Flussi',
          data: 'Dati',
          level: 'Livelli',
          views: 'Viste'
        }
      }
    }
  },
  'zh-CN': {
    translation: {
      inspector: {
        view: '视图',
        back_to_selection: '返回所选内容',
        pin: '固定面板（绘图区在其左侧重新调整大小）',
        unpin: '取消固定面板（浮于绘图之上）',
        // Cibles : singulier / pluriel (fil d'Ariane).
        target: {
          view: '视图',
          node: '节点', nodes: '节点',
          link: '流量', links: '流量',
          container: '区域', containers: '区域',
          legend: '图例', legends: '图例',
          title: '标题', titles: '标题',
          mixed: '混合选择', elements: '元素'
        },
        nothing_here: '没有可用于以下对象的设置：{{target}}。',
        // Portée & cascade de styles
        selection: '选择',
        selection_count: '选择（{{count}}）',
        styles_count: '样式（{{count}}）',
        cascade: '层叠',
        style_name: '样式名称',
        new_style: '+ 新建样式',
        delete_style: '删除',
        delete_style_tooltip: '删除该样式（沿用它的元素将回退到其层叠中的其余样式）',
        attach_style: '为所选内容附加一个样式（位于层叠末端，优先生效）',
        detach_style: '将该样式从所选内容中分离',
        edited_style_hint: '正在编辑高亮的样式：所有沿用它的元素都会随之改变。层叠中最后一个优先；局部覆盖始终优先。',
        divergent_cascade: '第 1 个元素的层叠——其他被选中的元素遵循不同的层叠。 ',
        selection_hint: '变暗的属性：继承自样式（层叠）。紫色轮廓：在所选内容上被覆盖。橙色轮廓：存在多个值。',
        tab_overloaded: '包含被覆盖的属性',
        provenance: {
          local: '在此处（所选内容上）被覆盖',
          from_style: '继承自样式 « {{style}} »',
          factory: '出厂默认值'
        },
        // Onglets
        tab: {
          stock: '存量',
          tooltip: '提示框',
          tags: '标签',
          analysis: '分析',
          title: '标题',
          mfa: 'MFA',
          styles: '样式'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: '来源',
          unresolved: '由该元素触发，但文件未说明它为何存在',
          rules: {
            data_sheet: '在数据工作表的某一行中录入',
            matrix_sheet: '在流量矩阵中录入',
            min_max_sheet: '由“最小/最大”工作表的边界确定',
            constraints_sheet: '由“约束”工作表的方程确定',
            ratio_flux_sheet: '由“流量比例”工作表的某一行确定',
            ratio_stock_flux_sheet: '由“库存流量比例”工作表的某一行确定',
            stock_chaining_sheet: '由“库存链接”工作表的某一行确定',
            stocks_sheet: '在“库存”工作表的某一行中声明',
            stock_parent_aggregate: '在父节点上创建的库存汇总',
            stock_level_mirror: '根据已声明的变动创建的库存水平',
            nodes_sheet: '在节点工作表中声明',
            nodes_agg_sheet: '在汇总节点工作表中声明',
            node_block_parenthood: '由节点工作表的分块结构关联到父节点',
            results_sheet: '从“结果”工作表读取',
            analysis_sheet: '从“结果分析”工作表读取',
            uncertainty_sheet: '从“不确定性分析”工作表读取',
            flux_from_secondary_sheet: '从次要工作表创建（选项“从次要工作表创建流量”）',
            node_from_flux: '因某条流量指向它而创建（选项“从流量创建节点”）',
            propagate_to_parent: '推断：某个子节点带有此流量，已上推至父节点',
            propagate_to_children: '推断：父节点带有此流量，已下推至子节点',
            single_child: '推断：该节点只有一个子节点，此流量必然归属于它',
            materialize_parent_aggregate: '推断：为平衡层级而生成的父级汇总',
            datatag_broadcast: '推断：流量结构已扩展到该标签组合',
            manual_draw: '在应用中手动绘制',
            json_read: '从已保存的图表读取',
            duplicate: '来自复制',
            paste: '来自粘贴',
            apply_layout: '来自应用布局',
            merge_diagrams: '来自合并图表',
            spreadsheet_edit: '在表格选项卡中录入',
            node_split: '来自拆分节点',
            expansion: '来自展开节点'
          },
          intro: '所选元素为何存在，可追溯至其来源的录入。',
          this_element: '此元素',
          because: '因为',
          sheet: '工作表',
          line: '行',
          datatags: '标签组合',
          unknown: '此文件未说明该元素为何存在（在来源追踪之前写入，或手动绘制）。',
          select: '请选择一个节点或一条流。'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: '该数值从何而来？',
          intro: '是什么确定了所选流的数值，以及作用于它的约束。',
          unknown: '该文件未说明是什么确定了这个数值（图未经调和，或由较早版本调和）。',
          absent: '该流在此标签组合下不存在：没有可解释的数值。',
          interval: '可能区间',
          entered_value: '录入值',
          reconciled_value: '调和值',
          flux_involved: '涉及 {{n}} 条流',
          show_flux: '查看方程',
          hide_flux: '收起方程',
          also_in: '还出现在其他 {{n}} 个约束中',
          show_others: '显示',
          hide_others: '隐藏',
          fixed_by: '其数值由以下约束确定：',
          takes_part_in: '没有任何约束能确定它。它参与：',
          no_constraint: '模型中没有任何约束作用于该流。',
          classification: {
            measured: '实测',
            redundant: '冗余',
            determined: '已确定',
            free: '自由',
            free_unbounded: '自由且无界',
            failed: '未调和'
          },
          meaning: {
            measured: '该数值为录入值，模型中没有任何方式可重新计算它：调和保持了原值。',
            redundant: '该数值为录入值，模型也能够计算它：调和在两者之间进行了权衡。',
            determined: '该数值并非录入值：模型的约束足以将其确定，不存在其他可能解。',
            free: '约束不足以确定该数值；调和在可能区间内选取了一个。',
            free_unbounded: '约束不足以确定该数值，且没有任何界限。',
            failed: '该标签组合的调和未能完成：显示的是输入值。'
          },
          step_by_step: '逐步推导：',
          flat_equation: '确定它的方程：',
          combines: '以下方程的组合：',
          system_one: '{{equations}} 个方程、1 个未知数的方程组：',
          system: '{{equations}} 个方程、{{unknowns}} 个未知数的方程组（含 {{others}}）：',
          coefficient: '系数',
          computed_from: '{{flux}} 本身由以下方式计算：',
          bound_propagated: '该界限在流之间传递：它来自对全部约束的传播，模型中没有任何单个方程能概括它。',
          holds_min: '使其不低于 {{value}} 的原因：',
          holds_max: '使其不超过 {{value}} 的原因：',
          at_least: '至少',
          at_most: '至多',
          shape: {
            equal: '等于另一条流',
            factor: '另一条流的一部分',
            children: '其 {{n}} 条子流之和',
            into: '进入 {{node}} 的全部之和',
            out_of: '离开 {{node}} 的全部之和',
            sum: '{{n}} 条流之和',
            balance_node: '节点 {{node}} 的平衡',
            balance: '相加 {{added}} 条流，相减 {{removed}} 条'
          },
          kinds: {
            mat_balance: '节点的物质平衡',
            aggregation: '层级关系 — 子流的聚合',
            stock_aggregation: '节点上的存量聚合',
            equality: '录入的方程（约束）',
            bound_min: '录入的下界（约束）',
            bound_max: '录入的上界（约束）',
            inconsistency: '测量值相互矛盾，差值',
            determined_by: '确定该值的方程'
          }
        },
        // #1258 — Onglet MFA (espace AFM unifié).
        mfa: {
          reconciliation: '数据调和',
          open_spreadsheet: '打开电子表格（约束）',
          run_reconciliation: '通过 Excel 调和……',
          value_in_mfa: '数值类型、界限与不确定性在 MFA 选项卡中编辑。'
        },
        // #1258 — Titres des sections repliables des onglets.
        section: {
          page: '页面',
          dressing: '背景与网格',
          scale_sizes: '比例尺与尺寸',
          advanced: '高级',
          advanced_geometry: '高级 — 几何'
        },
        // #1259 — Section « Groupe » unifiée (ex-« Cadre géométrique » ZDT + nœuds).
        group: {
          title: '组',
          tooltip: '将节点或文本区附加到所选元素：框体会自动定位以包围其成员，并随其移动'
        },
        visible: '可见',
        labels_visible: '标签可见',
        stock_enabled: '已启用',
        stock_shape: '形状',
        stock_shape_tooltip: '显示存量形状',
        stock_labels: '标签',
        stock_labels_tooltip: '显示存量标签',
        stock_shape_visible: '存量形状可见',
        stock_select_node: '请选择一个带有存量的节点。',
        stock_caption: '存量说明',
        stock_delta_caption: 'Δ 存量说明',
        advanced_editor: '高级编辑器……',
        open_editor: '打开编辑器……',
        tags_assign_hint: '指派（标签组在“筛选”中编辑）',
        // OS#1278 — section « Analyse » (graphiques couronne / histogramme).
        analysis: {
          decompose_by: '按此分解',
          compare_by: '按此比较',
          compare_by_secondary: '再按此比较（系列）',
          none: '— 无 —',
          inputs: '进入的流量',
          outputs: '流出的流量',
          inputs_by: '按 {{group}} 划分的进入流量',
          outputs_by: '按 {{group}} 划分的流出流量',
          node_children: '子节点（{{dim}}）',
          flux_children: '子流量（{{dim}}）',
          repr_auto: '自动',
          repr_donut: '环形图',
          repr_bars: '条形图',
          scale: '刻度',
          scale_auto: '自动',
          scale_shared: '共享',
          scale_per_group: '按组',
          scale_auto_hint: '共享刻度，除非某一组变得不可读',
          scale_shared_hint: '整个图表使用同一刻度',
          scale_per_group_hint: '每组一个刻度——一组即“按此比较”的一个标签',
          show_in_tooltip: '在提示框中显示',
          show_on_node: '在节点上显示（环形图 / 直方图）',
          select_subject: '请选择一个节点或一条流量。'
        },
        // OS#1285 — visibilité des blocs d'info-bulle.
        tooltip_blocks: {
          title: '可见区块',
          values: '数值',
          flux: '流量',
          tags: '标签',
          series_flux: '流量序列',
          data: '数据',
          series_data: '数据序列',
          unitary: '单位桑基图',
          analysis: '分析图表'
        },
        // OS#1286 — registre d'unités du diagramme (grandeurs/unités/défauts).
        units: {
          title: '图表单位',
          none: '— 无 —',
          type_default: '默认',
          open_editor: '编辑……',
          open_editor_tooltip: '编辑图表的单位（量纲、单位、系数、默认值）',
          symbol: '符号',
          display_name: '显示名称',
          display_name_tooltip: '图中实际书写的单位文本。留空则使用规范符号。可让图表写作“吨”，同时仍引用目录单位 t，换算不受影响。',
          coefficient: '系数',
          coefficient_tooltip: '该单位以其量纲基准单位表示的数值（基准单位 = 1）。数值以基准单位存储。',
          display_scale: '比例尺',
          display_scale_tooltip: '该量纲专用的显示比例尺（类似 e!Sankey）：单位类型分带每 100 px 所代表的基准单位量。留空：使用图表比例尺。可在同一条流量上平衡不同量纲（kWh、t 与 EUR）。',
          default: '默认',
          default_tooltip: '该量纲的默认显示单位（未显式指定单位的流量将继承它）',
          add_unit: '+ 单位',
          add_unit_type: '+ 量纲',
          new_unit_name: '单位',
          new_unit_type_name: '新建量纲',
          empty: '注册表中没有量纲——请添加一个。'
        }
      },
      filter_panel: {
        filter: '筛选',
        select: '选择',
        select_tooltip: '按类型与标签选择元素（批量操作）',
        edit: '编辑',
        edit_group: '编辑该组',
        show_hidden: '显示隐藏的组（{{count}}）',
        hide_hidden: '隐藏“隐藏的组”',
        select_elements: '选择元素',
        deselect_all: '取消全选',
        selection_summary: '所选：{{summary}}',
        short: {
          node: '节点',
          link: '流量',
          data: '数据',
          level: '层级',
          views: '视图'
        }
      }
    }
  },
  ja: {
    translation: {
      inspector: {
        view: 'ビュー',
        back_to_selection: '選択に戻る',
        pin: 'パネルを固定（描画エリアがその左側でサイズ調整されます）',
        unpin: 'パネルの固定を解除（描画の上に浮かびます）',
        // Cibles : singulier / pluriel (fil d'Ariane).
        target: {
          view: 'ビュー',
          node: 'ノード', nodes: 'ノード',
          link: 'フロー', links: 'フロー',
          container: 'エリア', containers: 'エリア',
          legend: '凡例', legends: '凡例',
          title: 'タイトル', titles: 'タイトル',
          mixed: '複数種類の選択', elements: '要素'
        },
        nothing_here: '{{target}} に利用できる設定はありません。',
        // Portée & cascade de styles
        selection: '選択',
        selection_count: '選択（{{count}}）',
        styles_count: 'スタイル（{{count}}）',
        cascade: 'カスケード',
        style_name: 'スタイル名',
        new_style: '+ 新しいスタイル',
        delete_style: '削除',
        delete_style_tooltip: 'このスタイルを削除します（これに従っている要素は、カスケードの残りのスタイルに戻ります）',
        attach_style: '選択中の要素にスタイルを付与します（カスケードの末尾で、最も優先されます）',
        detach_style: 'このスタイルを選択中の要素から外します',
        edited_style_hint: '強調表示されたスタイルを編集しています：これに従うすべての要素が変わります。カスケードの最後が優先され、個別の上書きは常に優先されます。',
        divergent_cascade: '1 番目の要素のカスケード — 選択中の他の要素は別のカスケードに従っています。 ',
        selection_hint: '薄い属性：スタイル（カスケード）から継承。紫の枠：選択中の要素で上書き。オレンジの枠：値が複数あります。',
        tab_overloaded: '上書きされた属性を含みます',
        provenance: {
          local: 'ここで上書き（選択中の要素で）',
          from_style: 'スタイル «{{style}}» から継承',
          factory: '工場出荷時の既定値'
        },
        // Onglets
        tab: {
          stock: 'ストック',
          tooltip: 'ツールチップ',
          tags: 'タグ',
          analysis: '分析',
          title: 'タイトル',
          mfa: 'MFA',
          styles: 'スタイル'
        },
        // #411 — section « Origine » : pourquoi cet element existe.
        origin: {
          title: '由来',
          unresolved: 'この要素が引き金ですが、それがなぜ存在するかはファイルに記録されていません',
          rules: {
            data_sheet: 'データシートの行に入力',
            matrix_sheet: 'フロー行列に入力',
            min_max_sheet: '「Min Max」シートの範囲によって確定',
            constraints_sheet: '「制約」シートの式によって確定',
            ratio_flux_sheet: '「フロー比率」シートの行によって確定',
            ratio_stock_flux_sheet: '「ストックフロー比率」シートの行によって確定',
            stock_chaining_sheet: '「ストック連鎖」シートの行によって確定',
            stocks_sheet: '「ストック」シートの行で宣言',
            stock_parent_aggregate: '親ノードに作成されたストック集計',
            stock_level_mirror: '宣言された変動に対応して作成されたストック水準',
            nodes_sheet: 'ノードシートで宣言',
            nodes_agg_sheet: '集計ノードシートで宣言',
            node_block_parenthood: 'ノードシートのブロック構造により親に紐付け',
            results_sheet: '「結果」シートから読み取り',
            analysis_sheet: '「結果分析」シートから読み取り',
            uncertainty_sheet: '「不確実性分析」シートから読み取り',
            flux_from_secondary_sheet: '副シートから作成（オプション「副シートからフローを作成」）',
            node_from_flux: 'フローが参照しているため作成（オプション「フローからノードを作成」）',
            propagate_to_parent: '推論：子がこのフローを持つため、親に引き上げられた',
            propagate_to_children: '推論：親がこのフローを持つため、子に引き下げられた',
            single_child: '推論：ノードに子が一つしかないため、フローは必然的にそれに属する',
            materialize_parent_aggregate: '推論：階層を整合させるために親集計を生成',
            datatag_broadcast: '推論：フローの構造がこのタグの組み合わせに拡張された',
            manual_draw: 'アプリケーションで手描き',
            json_read: '保存された図から読み取り',
            duplicate: '複製によるもの',
            paste: 'コピー＆ペーストによるもの',
            apply_layout: 'レイアウト適用によるもの',
            merge_diagrams: '図の結合によるもの',
            spreadsheet_edit: '表計算タブで入力',
            node_split: 'ノード分割によるもの',
            expansion: 'ノード展開によるもの'
          },
          intro: '選択した要素が存在する理由を、その入力元まで遡って表示します。',
          this_element: 'この要素',
          because: 'なぜなら',
          sheet: 'シート',
          line: '行',
          datatags: 'タグの組み合わせ',
          unknown: 'このファイルには、この要素が存在する理由が記録されていません（由来の記録より前に書かれたか、手描きです）。',
          select: 'ノードまたはフローを選択してください。'
        },
        // #426 — section « D'où vient cette valeur ? » : ce qui a fixe la valeur.
        determination: {
          title: 'この値はどこから来たのか',
          intro: '選択したフローの値を決めたものと、そこに掛かっている制約。',
          unknown: 'このファイルには、この値を決めたものが記録されていません（未調整の図、または以前のバージョンで調整された図）。',
          absent: 'このタグの組み合わせではこのフローは存在しません。説明すべき値がありません。',
          interval: '取りうる区間',
          entered_value: '入力値',
          reconciled_value: '調整後の値',
          flux_involved: '関係するフロー {{n}} 件',
          show_flux: '式を表示',
          hide_flux: '式を隠す',
          also_in: '他の {{n}} 件の制約にも含まれます',
          show_others: '表示',
          hide_others: '非表示',
          fixed_by: 'この値は次によって決まります:',
          takes_part_in: 'どの制約もこの値を決めていません。次に関与しています:',
          no_constraint: 'モデルのどの制約もこのフローに掛かっていません。',
          classification: {
            measured: '実測',
            redundant: '冗長',
            determined: '決定済み',
            free: '自由',
            free_unbounded: '自由（上下限なし）',
            failed: '未調整'
          },
          meaning: {
            measured: 'この値は入力されたもので、モデルには再計算する手段がありませんでした。調整はそのまま残しました。',
            redundant: 'この値は入力されたもので、モデルでも計算できました。調整が両者を調停しました。',
            determined: 'この値は入力されたものではありません。モデルの制約だけで一意に決まり、他の解はありません。',
            free: '制約だけではこの値は決まりません。調整は取りうる区間の中から一つを選びました。',
            free_unbounded: '制約だけではこの値は決まらず、上下限もありません。',
            failed: 'このタグの組み合わせの調整は完了しませんでした。表示されているのは入力値です。'
          },
          step_by_step: '順を追って：',
          flat_equation: 'この値を決める式：',
          combines: '次の式の組み合わせ：',
          system_one: '{{equations}} 式・1 未知数の連立：',
          system: '{{equations}} 式・{{unknowns}} 未知数の連立（{{others}} を含む）：',
          coefficient: '係数',
          computed_from: '{{flux}} 自体は次によって計算されます：',
          bound_propagated: 'この境界は流れから流れへ伝わります。すべての制約にわたる伝播から生じ、モデルのどの式にもまとめられません。',
          holds_min: '{{value}} を下回らない理由：',
          holds_max: '{{value}} を超えない理由：',
          at_least: '最小',
          at_most: '最大',
          shape: {
            equal: '他のフローと同じ',
            factor: '他のフローの一部',
            children: 'その子フロー {{n}} 件の合計',
            into: '{{node}} に入るすべての合計',
            out_of: '{{node}} から出るすべての合計',
            sum: 'フロー {{n}} 件の合計',
            balance_node: 'ノード {{node}} の収支',
            balance: '{{added}} 件を加算、{{removed}} 件を減算'
          },
          kinds: {
            mat_balance: 'ノードの物質収支',
            aggregation: '階層関係 — 子フローの集計',
            stock_aggregation: 'ノード上のストック集計',
            equality: '入力された式（制約）',
            bound_min: '入力された下限（制約）',
            bound_max: '入力された上限（制約）',
            inconsistency: '測定値の食い違い',
            determined_by: '値を決める式'
          }
        },
        // #1258 — Onglet MFA (espace AFM unifié).
        mfa: {
          reconciliation: 'データ調和',
          open_spreadsheet: 'スプレッドシートを開く（制約）',
          run_reconciliation: 'Excel で調和…',
          value_in_mfa: '値の種類、範囲、不確実性は MFA タブで編集します。'
        },
        // #1258 — Titres des sections repliables des onglets.
        section: {
          page: 'ページ',
          dressing: '背景とグリッド',
          scale_sizes: 'スケールとサイズ',
          advanced: '詳細設定',
          advanced_geometry: '詳細 — 配置'
        },
        // #1259 — Section « Groupe » unifiée (ex-« Cadre géométrique » ZDT + nœuds).
        group: {
          title: 'グループ',
          tooltip: '選択中の要素にノードやテキストエリアを紐づけます：枠はメンバーを囲む位置に配置され、メンバーとともに移動します'
        },
        visible: '表示',
        labels_visible: 'ラベルを表示',
        stock_enabled: '有効',
        stock_shape: '形状',
        stock_shape_tooltip: 'ストックの形状を表示します',
        stock_labels: 'ラベル',
        stock_labels_tooltip: 'ストックのラベルを表示します',
        stock_shape_visible: 'ストックの形状を表示',
        stock_select_node: 'ストックを持つノードを選択してください。',
        stock_caption: 'ストックの説明',
        stock_delta_caption: 'Δ ストックの説明',
        advanced_editor: '詳細エディタ…',
        open_editor: 'エディタを開く…',
        tags_assign_hint: '割り当て（グループは「絞り込み」で編集します）',
        // OS#1278 — section « Analyse » (graphiques couronne / histogramme).
        analysis: {
          decompose_by: '分解の軸',
          compare_by: '比較の軸',
          compare_by_secondary: '第2の比較の軸（系列）',
          none: '— なし —',
          inputs: '入ってくるフロー',
          outputs: '出ていくフロー',
          inputs_by: '{{group}} 別の入ってくるフロー',
          outputs_by: '{{group}} 別の出ていくフロー',
          node_children: '子ノード（{{dim}}）',
          flux_children: '子フロー（{{dim}}）',
          repr_auto: '自動',
          repr_donut: 'ドーナツ',
          repr_bars: '棒',
          scale: 'スケール',
          scale_auto: '自動',
          scale_shared: '共通',
          scale_per_group: 'グループごと',
          scale_auto_hint: '共通スケール、ただしグループが読めなくなる場合を除く',
          scale_shared_hint: 'グラフ全体で 1 つのスケール',
          scale_per_group_hint: 'グループごとに 1 スケール — グループは「比較の軸」の 1 ラベル',
          show_in_tooltip: 'ツールチップに表示',
          show_on_node: 'ノード上に表示（ドーナツ／ヒストグラム）',
          select_subject: 'ノードまたはフローを選択してください。'
        },
        // OS#1285 — visibilité des blocs d'info-bulle.
        tooltip_blocks: {
          title: '表示するブロック',
          values: '値',
          flux: 'フロー',
          tags: 'タグ',
          series_flux: 'フローの系列',
          data: 'データ',
          series_data: 'データの系列',
          unitary: '単位サンキー',
          analysis: '分析チャート'
        },
        // OS#1286 — registre d'unités du diagramme (grandeurs/unités/défauts).
        units: {
          title: '図の単位',
          none: '— なし —',
          type_default: '既定',
          open_editor: '編集…',
          open_editor_tooltip: '図の単位を編集します（物理量、単位、係数、既定値）',
          symbol: '記号',
          display_name: '表示名',
          display_name_tooltip: 'この単位について図上に実際に書かれる文字列。空の場合は正規の記号を使います。目録の単位 t を参照したまま「トン」と表示でき、換算は変わりません。',
          coefficient: '係数',
          coefficient_tooltip: 'この単位を、その物理量の基準単位で表した値（基準単位 = 1）。値は基準単位で保存されます。',
          display_scale: 'スケール',
          display_scale_tooltip: 'この物理量専用の表示スケール（e!Sankey と同様）：単位型の帯について、100 px あたりに相当する基準単位の量です。空欄：図のスケールを使います。同じフロー上で異なる物理量（kWh、t、EUR）のバランスをとれます。',
          default: '既定',
          default_tooltip: 'この物理量の既定の表示単位（単位を明示していないフローが継承します）',
          add_unit: '+ 単位',
          add_unit_type: '+ 物理量',
          new_unit_name: '単位',
          new_unit_type_name: '新しい物理量',
          empty: 'レジストリに物理量がありません — 追加してください。'
        }
      },
      filter_panel: {
        filter: '絞り込み',
        select: '選択',
        select_tooltip: '種類とタグで要素を選択します（一括操作）',
        edit: '編集',
        edit_group: 'このグループを編集',
        show_hidden: '非表示のグループを表示（{{count}}）',
        hide_hidden: '非表示のグループを隠す',
        select_elements: '要素を選択',
        deselect_all: '選択をすべて解除',
        selection_summary: '選択：{{summary}}',
        short: {
          node: 'ノード',
          link: 'フロー',
          data: 'データ',
          level: 'レベル',
          views: 'ビュー'
        }
      }
    }
  }
}
