export const resources_nodes = {
  en: {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: 'Stylesheet',
        OrderStyle: 'Order of styles associated',
        multi_style: 'Selected nodes have different style',
        editStyle: 'Assign a style',
        AS: 'Reset',
        SelectStyle: 'Select a style',
        Reorg: 'Reorganize incoming/outgoing links',
        Reorg_title: 'Reorganization',
        Slct: 'Selection',
        SlctOutLink: 'Select outgoing links',
        SlctInLink: 'Select incoming links',
        SlctL: 'Sélectionner les flux',
        SlctOL: 'Output',
        SlctIL: 'Input',
        IB: 'Tooltip',
        IS: 'Additional info.',
        align_horiz: 'Horizontally',
        align_horiz_min: 'Relative to the selected node furthest to the left',
        align_horiz_max: 'Relative to the selected node furthest to the right',
        align_vert: 'Vertically',
        align_vert_min: 'Relative to the selected topmost node',
        align_vert_max: 'Relative to the selected node furthest down',
        align_horiz_left: 'Align to its left',
        align_horiz_center: 'Align to its center',
        align_horiz_right: 'Align to its right',
        align_vert_top: 'Align to its top',
        align_vert_bottom: 'Align to its bottom',
        align: 'Align nodes',
        product: 'Product',
        sector: 'Sector',
        exchange: 'Exchange',
        size: 'Size',
        position: 'Position',
        text: 'Text',
        selector: 'Select nodes',
        title_desaggreg: 'Dimension disagregation',
        title_aggreg: 'Dimension agregation',
        text_agreg: 'Will agregate in : ',
        text_desagreg: 'Will disagregate in : ',
        desaggreg: 'Disagregation',
        aggreg: 'Agregation',
        firstPlan: 'Move in the bakground',
        lastPlan: 'Move at the foreground',
        changePlan: 'Change plan of nodes',
        mask_attr: 'Elements display',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: 'Allow to apply a predefined style in the preference menu to the selected node(s)',
          Reorg: 'Allows automatic reorganization of incoming and outgoing links (up/down position)',
          SlctOutLink: 'Allow to select all outgoing links from the node(s)',
          SlctInLink: 'Allow to select all incoming links to the node(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the node. This tooltip pops on graphic space with SHIFT + MOUSE on the node.',
        },
        drawing_area_tooltip: {
          outputs: 'Outputs',
          inputs: 'Inputs',
          dest: 'Outputs',
          val: 'Values',
          data_value: 'Collected data',
          result_value: 'Computed data',
          rat: 'Ratios',
          prov: 'Inputs',
          values_tab: 'Values',
          tags_tab: 'Other informations'
        },
        tabs: {
          apparence: 'Appearence',
          infos: 'Additional info.',
          tags: 'Tags',
          io: 'I/O links positions',
        },
        apparence: {
          apparence: 'Appearence',
          shape_visible: 'Shape',
          shape_color: 'Color',
          shape_color_sustainable: 'Static color',
          shape_type: 'Shape of node',
          Geometry: 'Geometry',
          Cercle: 'Arc',
          Rectangle: 'Rectangle',
          shape_min_width: 'Minimum width',
          shape_min_height: 'Minimum height',
          geometry: 'Positioning',
          geometry_absolute: 'Absolute',
          geometry_parametric: 'Spacing',
          geometry_relative: 'Offset',
          position_u: 'Colonne',
          column_u: 'Column (u)',
          position_v: 'Row',
          row_v: 'Row (v)',
          position_dx: 'Ecart horizontal',
          position_dy: 'Ecart vertical',
          anchor_align_vertical: 'Anchors (vertical sides)',
          anchor_align_horizontal: 'Anchors (horizontal sides)',
          asn: 'Apply style to nodes',
          override_type_node_shape: 'Override default shape',
          arrow: 'Arrow',
          display_shape: 'Display the node shape',
          hide_shape: 'Hide the node shape',
          display_label: 'Display the label',
          hide_label: 'Hide the label',
          display_value: 'Display the value',
          hide_value: 'Hide the value',
          shape_opacity: 'Opacity',
          tooltips: {
            FormeDisabled: 'Deactivated because the shape is managed by the "Type de noeud" tag group, if you want to be able to change the shape of the selected nodes, go to the "tags" tab and uncheck all the selected tag of the "Type de noeud" group',
            shape_anchor_align_vertical: 'Vertical alignment of link anchors on the left/right sides of the node (top / center / bottom).',
            shape_anchor_align_horizontal: 'Horizontal alignment of link anchors on the top/bottom sides of the node (left / center / right).',
            geometry: 'Méthode pour calculer la position du noeud. Cette position peut être donnée en coordonnées absolues x,y, en coordonnée relative u,v, ou en coordonnée relative à une autre noeud.',
            position_dx: 'Ecart horizontal entre le bord droit du noeud à gauche et le bord gauche du noeud',
            position_dy: 'Ecart vertical entre le bord inférieur du noeud au dessus et le bord supérieur du noeud',
            shape_position_u_locked: 'When locked, autosankey compute keeps this node\'s column index (u) instead of recomputing it.',
            shape_position_v_locked: 'When locked, autosankey compute preserves the relative vertical order (v) of this node within its column instead of recomputing it.',
            override_type_node_shape: 'Override the default forced shape of product and sector type nodes',
          }
        },
        node_value: {
          anchor: 'Anchor position',
          anchor_dx: 'Horizontal shift',
          anchor_dy: 'Vertical shift',
          tooltips: {
            anchor: 'The anchor of node value can be positioned by combining horizontal position : left, middle and right; and vertically : top, middle and bottom',
            anchor_dx: 'Horizontal shift from label anchor',
            anchor_dy: 'Vertical shift from label anchor',
          }
        },
        labels: {
          labels: 'Name',
          node_value: 'Value',
          name_label_is_visible: 'Label',
          lb: 'White label',
          name_label_background: 'Background',
          name_label_background_color: 'Background color',
          pos: 'Position',
          pos_v: 'Value position',
          tp: 'Font size',
          cl: 'Text box width',
          vdv: 'Value',
          edit_node_label: 'Edit node label',
          anchor: 'Anchor position',
          name_label_text_source: 'Label content',
          name_label_text: 'Custom label',
          name_label_tag_group: 'Tag group',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatic (first one)',
          text_source: {
            name: 'Node name',
            name_container: 'Element name',
            custom: 'Custom text',
            tag: 'Tag long name',
            ancestor: 'Ancestor node name',
          },

          tooltips: {
            name_label_is_visible: 'Displays or not the label(s) attached to the selected node(s)',
            name_label_text_source: 'Choose what the node label shows: the node name, or an independent custom text (edited without renaming the node)',
            lb: 'Displays the text of the label(s) in white or black (useful if label is positioned on node(s))',
            name_label_background: 'Add a background to the label for a better visibility in case the label is in front of a link',
            top: 'Displays the label(s) above the selected node(s)',
            Milieu_pv: 'Displays the label(s) in the middle (vertically) of the selected node(s)',
            Bas: 'Displays the label(s) below the selected node(s)',
            gauche: 'Displays the label(s) to the left of the selected node(s)',
            Milieu_ph: 'Displays the label(s) in the middle (horizontally) of the selected node(s)',
            droite: 'Displays the label(s) to the right of the selected node(s)',
            cl: 'Width of the text area (in pixels) for the label(s) of the selected node(s)',
            vdv: 'Displays or not the associated value with the selected node(s)',
            anchor: 'L\'ancre du label peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            haut_val: 'Displays the associated value above the selected node(s)',
            Milieu_pv_val: 'Displays the associated value in the middle (vertically) of the selected node(s)',
            Bas_val: 'Displays the associated value below the selected node(s)',
            gauche_val: 'Displays the associated value to the left of the selected node(s)',
            Milieu_ph_val: 'Displays the associated value in the middle (horizontally) of the selected node(s)',
            droite_val: 'Displays the associated value to the right of the selected node(s)',
          }
        },
        tags_node: {
          tags: 'Tags',
          Appartenance: 'Affiliations'
        },
        agre: {
          Agré: 'Aggregation',
          DC: 'Cube\'s dimensions',
          Parent: 'Parent',
          CLE: 'Copy childs\' links'
        },
        PF: {
          PF: 'I/O links positions',
          PFM: 'I/O links positions',
          FES: 'Links type',
          ent: 'Input',
          sort: 'Output',
          FRN: 'Relative position / node',
          gauche: 'Left',
          droite: 'Right',
          ades: 'Above',
          edes: 'Below',
          lti: 'Identify the links in the table with their colors',
          col: 'Apply',
          filter_links: 'Links to display',
          visible_links: 'Visible links',
          all_links: 'All links',
          lock: 'Lock',
          delta: 'Spacing',
          tooltips: {
            io: 'Choose either the incoming or outgoing links of the selected node',
            side: 'Choose either the right, left, top or bottom links of the selected node',
            lti: 'Display the lines of the links table with their respective colors to better identify them',
            filter_links: 'Show only visible links or all links including hidden ones',
            lock: 'Lock this anchor side: moving the opposite node will no longer reposition it. Released by any automatic layout pass.',
            delta: 'Extra spacing inserted before this anchor, to space out the links arriving on the node'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Default node style',
        LinkStyle: 'Default link style',
        ContainerStyle: 'Default container style',
        NodeContainerStyle: 'Enclosing node frame',
        NodeLeftExtremityStyle: 'Left extremity node style',
        NodeRightExtremityStyle: 'Right extremity node style',
        NodeProductStyle: 'Product label style',
        NodeSectorStyle: 'Sector label style',
        NodeImportExportCloseStyle: 'Node import-export attached',
        NodeImportCloseStyle: 'Node import attached',
        NodeExportCloseStyle: 'Node export attached',
        NodeImportExportAboveBelowStyle: 'Node import-export above/below',
        NodeImportAboveStyle: 'Node import above',
        NodeExportBelowStyle: 'Node export below',
        LinkImportExportCloseStyle: 'Link import-export attached',
        LinkImportCloseStyle: 'Link import attached',
        LinkExportCloseStyle: 'Link export attached',
        LinkImportExportAboveBelowStyle: 'Link import-export above/below',
        SankeyUnitaryNodeStyle: 'Unitary node',
        SankeyUnitaryNodeInputStyle: 'Unitary node input',
        SankeyUnitaryNodeOutputStyle: 'Unitary node output',
        LinkInUnitaryStyle: 'Unitary input link',
        LinkOutUnitaryStyle: 'Unitary output link',
        family: 'Family',
        family_predefined: 'Application styles',
        family_user: 'User styles'
      }
    }
  },
  fr: {
    translation: {
      Noeud: {
        // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : TS (maintenant dans ELEMENTS_SELECTION_CONFIG)
        // ❌ SUPPRIMÉ : NS (maintenant dans ELEMENTS_SELECTION_CONFIG)

        Style: 'Feuille de style',
        OrderStyle: 'Ordre des styles associés',
        editStyle: 'Assigner un style',
        multi_style: 'Multiple style sélectionné',
        SelectStyle: 'Sélectionner un style',
        AS: 'Réinitialiser',
        Reorg: 'Réorganiser automatiquement les flux E/S',
        Reorg_title: 'Ordre des flux E/S',
        Slct: 'Sélection',
        SlctOutLink: 'Sélectionner flux sortants',
        SlctInLink: 'Sélectionner flux entrants',
        SlctL: 'Sélectionner les flux',
        SlctOL: 'Sortants',
        SlctIL: 'Entrants',
        IB: 'Info-bulle',
        IS: 'Info sup.',
        align_horiz: 'Horizontalement',
        align_horiz_min: 'Par rapport au noeud sélectionné le + à gauche',
        align_horiz_max: 'Par rapport au noeud sélectionné le + à droite',
        align_vert: 'Verticalement',
        align_vert_min: 'Par rapport au noeud sélectionné le + en haut',
        align_vert_max: 'Par rapport au noeud sélectionné le + en bas',
        align_horiz_left: 'À son côté gauche',
        align_horiz_center: 'À son centre',
        align_horiz_right: 'À son côté droit',
        align_vert_top: 'À son côté du dessus',
        align_vert_bottom: 'À son côté du dessous',
        align: 'Aligner les noeuds',
        product: 'Produit',
        sector: 'Secteur',
        exchange: 'Échange',
        selector: 'Selectionner des noeuds',
        size: 'Taille',
        position: 'Position',
        text: 'Texte',
        title_desaggreg: 'Dimension desagrégation',
        title_aggreg: 'Dimension agrégation',
        text_agreg: 'Sera aggrégé en : ',
        text_desagreg: 'Sera désaggrégé en : ',
        desaggreg: 'Désagrégation',
        aggreg: 'Agrégation',
        firstPlan: 'Mettre au dernier plan',
        lastPlan: 'Mettre au premier plan',
        changePlan: 'Modifier le plan des noeud',
        mask_attr: 'Affichage des éléments',
        tooltips: {
          // ❌ SUPPRIMÉ : Nom (maintenant dans ELEMENTS_SELECTION_CONFIG as tooltips.Nom)
          AS: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) noeud(s) selectionné(s)',
          Reorg: 'Permet de réorganiser automatiquement les flux entrant et sortant (position haut / bas)',
          SlctOutLink: 'Permettre de sélectionner tous les flux sortants du/des noeud(s)',
          SlctInLink: 'Permettre de sélectionner tous les flux entrants vers le/les noeud(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du noeud. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le noeud',
        },
        drawing_area_tooltip: {
          outputs: 'Sorties',
          inputs: 'Entrées',
          val: 'Valeurs',
          data_value: 'Donnée collectée',
          result_value: 'Donnée calculée',
          rat: 'Ratios',
          prov: 'Entrées',
          dest: 'Sorties',
          values_tab: 'Valeurs',
          tags_tab: 'Autres informations'
        },
        tabs: {
          apparence: 'Apparence',
          infos: 'Info sup.',
          tags: 'Étiquettes',
          io: 'Flux E/S',
        },
        apparence: {
          apparence: 'Apparence',
          Geometry: 'Géométrie',
          Cercle: 'Cercle',
          Rectangle: 'Rectangle',
          geometry: 'Positionnement',
          geometry_absolute: 'Absolu',
          geometry_relative: 'Décalage',
          geometry_parametric: 'Ecartement',
          position_u: 'Colonne',
          column_u: 'Colonne (u)',
          position_v: 'Ligne',
          row_v: 'Ligne (v)',
          position_dx: 'Ecart horizontal',
          position_dy: 'Ecart vertical',
          anchor_align: 'Ancre flux',
          anchor_align_vertical: 'Ancres (côtés verticaux)',
          anchor_align_horizontal: 'Ancres (côtés horizontaux)',
          asn: 'Appliquer le style aux noeuds',
          override_type_node_shape: 'Déverrouiller la forme',
          arrow: 'Flèche',
          shape_arrow_angle_factor: 'Inclinaison flèche',
          shape_arrow_angle_direction: 'Orientation flèche',
          display_shape: 'Afficher le noeud',
          hide_shape: 'Masquer le noeud',
          display_label: 'Afficher le nom',
          hide_label: 'Masquer le nom',
          display_value: 'Afficher la valeur',
          hide_value: 'Masquer la valeur',
          tooltips: {
            FormeDisabled: 'Désactivé car la forme est gérée par le groupe d\'étiquette "Type de noeud", si vous voulez pouvoir modifier la forme des noeuds séléctionnés, allez dans l\'onlget Étiquettes et décochez tous les étiquettes sélectionné du groupe "Type de noeud"',
            shape_anchor_align_vertical: 'Alignement vertical des ancres de flux sur les côtés gauche/droite du nœud (haut / centre / bas).',
            shape_anchor_align_horizontal: 'Alignement horizontal des ancres de flux sur les côtés haut/bas du nœud (gauche / centre / droite).',
            geometry: 'Méthode pour calculer la position du noeud. Cette position peut être donnée en coordonnées absolues x,y, en coordonnée relative u,v, ou en coordonnée relative à une autre noeud.',
            position_dx: 'Ecart horizontal entre le bord droit du noeud à gauche et le bord gauche du noeud',
            position_dy: 'Ecart vertical entre le bord inférieur du noeud au dessus et le bord supérieur du noeud',
            shape_position_u_locked: 'Si verrouillé, le calcul autosankey conserve l\'index de colonne (u) de ce nœud au lieu de le recalculer.',
            shape_position_v_locked: 'Si verrouillé, le calcul autosankey conserve l\'ordre vertical relatif (v) de ce nœud dans sa colonne au lieu de le recalculer.',
            override_type_node_shape: 'Permet de changer la forme forcée par défaut sur les noeuds de types produits et secteur',
          }
        },
        node_value: {
          anchor: 'Position de l\'ancre',
          anchor_dx: 'Décalage horizontal',
          anchor_dy: 'Décalage vertical',
          tooltips: {
            anchor: 'L\'ancre de la valeur du noeud peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            anchor_dx: 'Décalage horizontal par rapport à l\'ancre de la valeur du noeud',
            anchor_dy: 'Décalage vertical par rapport à l\'ancre e la valeur du noeud',
          }
        },
        labels: {
          labels: 'Nom',
          node_value: 'Valeur',
          name_label_is_visible: 'Libellé',
          lb: 'Blanc',
          name_label_background: 'Fond',
          name_label_background_color: 'Couleur fond',
          pos: 'Position',
          pos_v: 'Position de la valeur',
          tp: 'Taille de police',
          cl: 'Largeur zone de texte',
          vdv: 'Valeur',
          edit_node_label: 'Éditer le nom',
          anchor: 'Position de l\'ancre',
          name_label_text_source: 'Contenu du label',
          name_label_text: 'Label personnalisé',
          name_label_tag_group: 'Groupe de tags',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatique (la première)',
          text_source: {
            name: 'Nom du nœud',
            name_container: 'Nom de l\'élément',
            custom: 'Texte personnalisé',
            tag: 'Nom long d\'un tag',
            ancestor: 'Nom du nœud ancêtre',
          },
          tooltips: {
            name_label_text_source: 'Choisir ce qu\'affiche le label du nœud : le nom du nœud, ou un texte personnalisé indépendant (éditable sans renommer le nœud)',
            lb: 'Permet d\'afficher le texte du label en blanc ou en noir (utile si label positionné sur noeud(s))',
            haut: 'Positionner le label au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv: 'Positionner le label au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas: 'Positionner le label en dessous du/des noeud(s) sélectionné(s)',
            gauche: 'Positionner le label à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph: 'Positionner le label au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite: 'Positionner le label à droite du/des noeud(s) sélectionné(s)',
            cl: 'Largeur de la zone de texte (en pixel) pour le label du/des noeud(s) sélectionné(s)',
            vdv: 'Active l\'affichage de la valeur associée au(x) noeud(s) sélectionné(s)',
            anchor: 'L\'ancre du label peut être positionné de 9 manières par rapport à la forme combinant horizontalement bord gauche, milieu bord droit et verticalement bord supérieur milieu bord inférieur',
            haut_val: 'Positionner l\'affichage de la valeur associée au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv_val: 'Positionner l\'affichage de la valeur associée au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas_val: 'Positionner l\'affichage de la valeur associée en dessous du/des noeud(s) sélectionné(s)',
            gauche_val: 'Positionner l\'affichage de la valeur associée à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph_val: 'Positionner l\'affichage de la valeur associée au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite_val: 'Positionner l\'affichage de la valeur associée à droite du/des noeud(s) sélectionné(s)',
          }
        },
        tags_node: {
          tags: 'Étiquettes',
          Appartenance: 'Appartenance'
        },
        agre: {
          Agré: 'Agrégations',
          DC: 'Dimension du cube',
          Parent: 'Parent',
          CLE: 'Copier liens enfants'
        },
        PF: {
          PF: 'Flux E/S',
          PFM: 'Organiser flux E/S',
          FES: 'Type de flux',
          ent: 'Entrant',
          sort: 'Sortant',
          FRN: 'Position / noeud',
          gauche: 'Gauche',
          droite: 'Droite',
          ades: 'Au-dessus',
          edes: 'En-dessous',
          lti: 'Identifier les flux du tableau avec leurs couleurs',
          col: 'Appliquer',
          filter_links: 'Flux à afficher',
          visible_links: 'Flux visibles',
          all_links: 'Tous les flux',
          lock: 'Cadenas',
          delta: 'Espacement',
          tooltips: {
            io: 'Choisir les flux entrants ou sortant du noeud selectionné',
            side: 'Choisir les flux de droite, gauche, bas ou haut du noeud selectionné',
            lti: 'Affiche les lignes du tableau des flux avec leur couleurs respectives pour mieux les identifier',
            filter_links: 'Afficher uniquement les flux visibles ou tous les flux y compris les masqués',
            lock: 'Verrouille le côté de cette ancre : déplacer le noeud opposé ne la repositionnera plus. Relâché par tout recalcul automatique.',
            delta: 'Espacement supplémentaire inséré avant cette ancre, pour espacer les flux qui arrivent sur le noeud'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Style de noeud par défaut',
        LinkStyle: 'Style de flux par défaut',
        ContainerStyle: 'Style de container par défaut',
        NodeContainerStyle: 'Cadre englobant de nœuds',
        NodeLeftExtremityStyle: 'Style noeud extrémité gauche',
        NodeRightExtremityStyle: 'Style noeud extrémité droite',
        NodeProductStyle: 'Style étiquette produit',
        NodeSectorStyle: 'Style étiquette secteur',
        NodeImportExportCloseStyle: 'Noeud import export collé',
        NodeImportCloseStyle: 'Noeud import collé',
        NodeExportCloseStyle: 'Noeud export collé',
        NodeImportExportAboveBelowStyle: 'Noeud import export dessus/dessous',
        NodeImportAboveStyle: 'Noeud import au dessus',
        NodeExportBelowStyle: 'Noeud export au dessous',
        LinkImportExportCloseStyle: 'Flux import export collé',
        LinkImportCloseStyle: 'Flux import collé',
        LinkExportCloseStyle: 'Flux export collé',
        LinkImportExportAboveBelowStyle: 'Flux import export haut/bas',
        SankeyUnitaryNodeStyle: 'Unitaire noeud',
        SankeyUnitaryNodeInputStyle: 'Unitaire noeud entrée',
        SankeyUnitaryNodeOutputStyle: 'Unitaire noeud sortie',
        LinkInUnitaryStyle: 'Unitaire flux entrée',
        LinkOutUnitaryStyle: 'Unitaire flux sortie',
        family: 'Famille',
        family_predefined: 'Styles de l\'application',
        family_user: 'Styles utilisateur'
      }
    }
  },
  es: {
    translation: {
      Noeud: {
        Style: 'Hoja de estilo',
        OrderStyle: 'Orden de estilos asociados',
        multi_style: 'Los nodos seleccionados tienen estilos diferentes',
        editStyle: 'Asignar un estilo',
        AS: 'Restablecer',
        SelectStyle: 'Seleccionar un estilo',
        Reorg: 'Reorganizar flujos de entrada/salida',
        Reorg_title: 'Reorganización',
        Slct: 'Selección',
        SlctOutLink: 'Seleccionar flujos salientes',
        SlctInLink: 'Seleccionar flujos entrantes',
        SlctL: 'Seleccionar los flujos',
        SlctOL: 'Salientes',
        SlctIL: 'Entrantes',
        IB: 'Tooltip',
        IS: 'Info. adicional',
        align_horiz: 'Horizontalmente',
        align_horiz_min: 'Respecto al nodo seleccionado más a la izquierda',
        align_horiz_max: 'Respecto al nodo seleccionado más a la derecha',
        align_vert: 'Verticalmente',
        align_vert_min: 'Respecto al nodo seleccionado más arriba',
        align_vert_max: 'Respecto al nodo seleccionado más abajo',
        align_horiz_left: 'Alinear a su izquierda',
        align_horiz_center: 'Alinear a su centro',
        align_horiz_right: 'Alinear a su derecha',
        align_vert_top: 'Alinear a su parte superior',
        align_vert_bottom: 'Alinear a su parte inferior',
        align: 'Alinear nodos',
        product: 'Producto',
        sector: 'Sector',
        exchange: 'Intercambio',
        size: 'Tamaño',
        position: 'Posición',
        text: 'Texto',
        selector: 'Seleccionar nodos',
        title_desaggreg: 'Desagregación de dimensión',
        title_aggreg: 'Agregación de dimensión',
        text_agreg: 'Se agregará en: ',
        text_desagreg: 'Se desagregará en: ',
        desaggreg: 'Desagregación',
        aggreg: 'Agregación',
        firstPlan: 'Enviar al fondo',
        lastPlan: 'Traer al frente',
        changePlan: 'Cambiar plano de los nodos',
        mask_attr: 'Visualización de elementos',
        tooltips: {
          AS: 'Permite aplicar un estilo predefinido del menú de preferencias a los nodos seleccionados',
          Reorg: 'Permite reorganizar automáticamente los flujos entrantes y salientes (posición arriba/abajo)',
          SlctOutLink: 'Permite seleccionar todos los flujos salientes del/de los nodo(s)',
          SlctInLink: 'Permite seleccionar todos los flujos entrantes al/a los nodo(s)',
          IB: 'Tooltip: texto en formato HTML que se muestra con el tooltip del nodo. Este tooltip aparece en el espacio gráfico con SHIFT + RATÓN sobre el nodo.',
        },
        drawing_area_tooltip: {
          outputs: 'Salidas',
          inputs: 'Entradas',
          dest: 'Salidas',
          val: 'Valores',
          data_value: 'Dato recopilado',
          result_value: 'Dato calculado',
          rat: 'Ratios',
          prov: 'Entradas',
          values_tab: 'Valores',
          tags_tab: 'Otras informaciones'
        },
        tabs: {
          apparence: 'Apariencia',
          infos: 'Info. adicional',
          tags: 'Etiquetas',
          io: 'Flujos E/S',
        },
        apparence: {
          apparence: 'Apariencia',
          shape_visible: 'Forma',
          shape_color: 'Color',
          shape_color_sustainable: 'Color estático',
          shape_type: 'Forma del nodo',
          Geometry: 'Geometría',
          Cercle: 'Arco',
          Rectangle: 'Rectángulo',
          shape_min_width: 'Ancho mínimo',
          shape_min_height: 'Alto mínimo',
          geometry: 'Posicionamiento',
          geometry_absolute: 'Absoluto',
          geometry_parametric: 'Espaciado',
          geometry_relative: 'Desplazamiento',
          position_u: 'Columna',
          column_u: 'Columna (u)',
          position_v: 'Fila',
          row_v: 'Fila (v)',
          position_dx: 'Separación horizontal',
          position_dy: 'Separación vertical',
          anchor_align_vertical: 'Anclas (lados verticales)',
          anchor_align_horizontal: 'Anclas (lados horizontales)',
          asn: 'Aplicar estilo a los nodos',
          override_type_node_shape: 'Desbloquear la forma',
          arrow: 'Flecha',
          display_shape: 'Mostrar el nodo',
          hide_shape: 'Ocultar el nodo',
          display_label: 'Mostrar la etiqueta',
          hide_label: 'Ocultar la etiqueta',
          display_value: 'Mostrar el valor',
          hide_value: 'Ocultar el valor',
          shape_opacity: 'Opacidad',
          tooltips: {
            FormeDisabled: 'Desactivado porque la forma está gestionada por el grupo de etiquetas "Tipo de nodo". Si desea cambiar la forma de los nodos seleccionados, vaya a la pestaña "Etiquetas" y desmarque todas las etiquetas seleccionadas del grupo "Tipo de nodo".',
            shape_anchor_align_vertical: 'Alineación vertical de las anclas de flujo en los lados izquierdo/derecho del nodo (arriba / centro / abajo).',
            shape_anchor_align_horizontal: 'Alineación horizontal de las anclas de flujo en los lados superior/inferior del nodo (izquierda / centro / derecha).',
            geometry: 'Método para calcular la posición del nodo. La posición puede darse en coordenadas absolutas x,y, en coordenadas relativas u,v, o en coordenadas relativas a otro nodo.',
            position_dx: 'Separación horizontal entre el borde derecho del nodo a la izquierda y el borde izquierdo del nodo',
            position_dy: 'Separación vertical entre el borde inferior del nodo superior y el borde superior del nodo',
            shape_position_u_locked: 'Si está bloqueado, el cálculo autosankey conserva el índice de columna (u) de este nodo en lugar de recalcularlo.',
            shape_position_v_locked: 'Si está bloqueado, el cálculo autosankey conserva el orden vertical relativo (v) de este nodo en su columna en lugar de recalcularlo.',
            override_type_node_shape: 'Permite cambiar la forma forzada por defecto en los nodos de tipo producto y sector',
          }
        },
        node_value: {
          anchor: 'Posición del ancla',
          anchor_dx: 'Desplazamiento horizontal',
          anchor_dy: 'Desplazamiento vertical',
          tooltips: {
            anchor: 'El ancla del valor del nodo se puede posicionar de 9 maneras respecto a la forma, combinando horizontalmente borde izquierdo, centro y borde derecho, y verticalmente borde superior, centro y borde inferior',
            anchor_dx: 'Desplazamiento horizontal respecto al ancla del valor del nodo',
            anchor_dy: 'Desplazamiento vertical respecto al ancla del valor del nodo',
          }
        },
        labels: {
          labels: 'Nombre',
          node_value: 'Valor',
          name_label_is_visible: 'Etiqueta',
          lb: 'Etiqueta blanca',
          name_label_background: 'Fondo',
          name_label_background_color: 'Color de fondo',
          pos: 'Posición',
          pos_v: 'Posición del valor',
          tp: 'Tamaño de fuente',
          cl: 'Ancho del área de texto',
          vdv: 'Valor',
          edit_node_label: 'Editar nombre del nodo',
          anchor: 'Posición del ancla',
          name_label_text_source: 'Contenido de la etiqueta',
          name_label_text: 'Etiqueta personalizada',
          name_label_tag_group: 'Grupo de etiquetas',
          name_label_tag: 'Etiqueta',
          name_label_dimension: 'Dimensión',
          name_label_dimension_auto: 'Automática (la primera)',
          text_source: {
            name: 'Nombre del nodo',
            name_container: 'Nombre del elemento',
            custom: 'Texto personalizado',
            tag: 'Nombre largo de una etiqueta',
            ancestor: 'Nombre del nodo ancestro',
          },
          tooltips: {
            name_label_text_source: 'Elegir lo que muestra la etiqueta del nodo: el nombre del nodo, o un texto personalizado independiente (editable sin renombrar el nodo)',
            name_label_is_visible: 'Muestra u oculta la(s) etiqueta(s) asociada(s) al/a los nodo(s) seleccionado(s)',
            lb: 'Muestra el texto de la(s) etiqueta(s) en blanco o negro (útil si la etiqueta está sobre el/los nodo(s))',
            name_label_background: 'Añade un fondo a la etiqueta para mejor visibilidad cuando está delante de un flujo',
            top: 'Muestra la(s) etiqueta(s) encima del/de los nodo(s) seleccionado(s)',
            Milieu_pv: 'Muestra la(s) etiqueta(s) en el centro (verticalmente) del/de los nodo(s) seleccionado(s)',
            Bas: 'Muestra la(s) etiqueta(s) debajo del/de los nodo(s) seleccionado(s)',
            gauche: 'Muestra la(s) etiqueta(s) a la izquierda del/de los nodo(s) seleccionado(s)',
            Milieu_ph: 'Muestra la(s) etiqueta(s) en el centro (horizontalmente) del/de los nodo(s) seleccionado(s)',
            droite: 'Muestra la(s) etiqueta(s) a la derecha del/de los nodo(s) seleccionado(s)',
            cl: 'Ancho del área de texto (en píxeles) para la(s) etiqueta(s) del/de los nodo(s) seleccionado(s)',
            vdv: 'Muestra u oculta el valor asociado al/a los nodo(s) seleccionado(s)',
            anchor: 'El ancla de la etiqueta se puede posicionar de 9 maneras respecto a la forma, combinando horizontalmente borde izquierdo, centro y borde derecho, y verticalmente borde superior, centro y borde inferior',
            haut_val: 'Muestra el valor asociado encima del/de los nodo(s) seleccionado(s)',
            Milieu_pv_val: 'Muestra el valor asociado en el centro (verticalmente) del/de los nodo(s) seleccionado(s)',
            Bas_val: 'Muestra el valor asociado debajo del/de los nodo(s) seleccionado(s)',
            gauche_val: 'Muestra el valor asociado a la izquierda del/de los nodo(s) seleccionado(s)',
            Milieu_ph_val: 'Muestra el valor asociado en el centro (horizontalmente) del/de los nodo(s) seleccionado(s)',
            droite_val: 'Muestra el valor asociado a la derecha del/de los nodo(s) seleccionado(s)',
          }
        },
        tags_node: {
          tags: 'Etiquetas',
          Appartenance: 'Pertenencia'
        },
        agre: {
          Agré: 'Agregación',
          DC: 'Dimensiones del cubo',
          Parent: 'Padre',
          CLE: 'Copiar flujos hijos'
        },
        PF: {
          PF: 'Flujos E/S',
          PFM: 'Organizar flujos E/S',
          FES: 'Tipo de flujo',
          ent: 'Entrada',
          sort: 'Salida',
          FRN: 'Posición relativa / nodo',
          gauche: 'Izquierda',
          droite: 'Derecha',
          ades: 'Encima',
          edes: 'Debajo',
          lti: 'Identificar los flujos de la tabla con sus colores',
          col: 'Aplicar',
          filter_links: 'Flujos a mostrar',
          visible_links: 'Flujos visibles',
          all_links: 'Todos los flujos',
          lock: 'Candado',
          delta: 'Espaciado',
          tooltips: {
            io: 'Elegir los flujos entrantes o salientes del nodo seleccionado',
            side: 'Elegir los flujos de la derecha, izquierda, arriba o abajo del nodo seleccionado',
            lti: 'Mostrar las líneas de la tabla de flujos con sus colores respectivos para identificarlos mejor',
            filter_links: 'Mostrar solo los flujos visibles o todos los flujos incluidos los ocultos',
            lock: 'Bloquea el lado de este anclaje: mover el nodo opuesto ya no lo reposicionará. Se libera con cualquier cálculo automático.',
            delta: 'Espaciado adicional insertado antes de este anclaje, para separar los flujos que llegan al nodo'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Estilo de nodo por defecto',
        LinkStyle: 'Estilo de flujo por defecto',
        ContainerStyle: 'Estilo de contenedor por defecto',
        NodeContainerStyle: 'Marco englobante de nodos',
        NodeLeftExtremityStyle: 'Estilo nodo extremidad izquierda',
        NodeRightExtremityStyle: 'Estilo nodo extremidad derecha',
        NodeProductStyle: 'Estilo etiqueta producto',
        NodeSectorStyle: 'Estilo etiqueta sector',
        NodeImportExportCloseStyle: 'Nodo import-export adjunto',
        NodeImportCloseStyle: 'Nodo import adjunto',
        NodeExportCloseStyle: 'Nodo export adjunto',
        NodeImportExportAboveBelowStyle: 'Nodo import-export arriba/abajo',
        NodeImportAboveStyle: 'Nodo import arriba',
        NodeExportBelowStyle: 'Nodo export abajo',
        LinkImportExportCloseStyle: 'Flujo import-export adjunto',
        LinkImportCloseStyle: 'Flujo import adjunto',
        LinkExportCloseStyle: 'Flujo export adjunto',
        LinkImportExportAboveBelowStyle: 'Flujo import-export arriba/abajo',
        SankeyUnitaryNodeStyle: 'Nodo unitario',
        SankeyUnitaryNodeInputStyle: 'Nodo unitario entrada',
        SankeyUnitaryNodeOutputStyle: 'Nodo unitario salida',
        LinkInUnitaryStyle: 'Flujo unitario entrada',
        LinkOutUnitaryStyle: 'Flujo unitario salida',
        family: 'Familia',
        family_predefined: 'Estilos de la aplicación',
        family_user: 'Estilos de usuario'
      }
    }
  },
  de: {
    translation: {
      Noeud: {
        Style: 'Stilvorlage',
        OrderStyle: 'Reihenfolge der zugeordneten Stile',
        multi_style: 'Ausgewählte Knoten haben unterschiedliche Stile',
        editStyle: 'Stil zuweisen',
        AS: 'Zurücksetzen',
        SelectStyle: 'Stil auswählen',
        Reorg: 'Ein-/Ausgangsflüsse reorganisieren',
        Reorg_title: 'Reorganisation',
        Slct: 'Auswahl',
        SlctOutLink: 'Ausgehende Flüsse auswählen',
        SlctInLink: 'Eingehende Flüsse auswählen',
        SlctL: 'Flüsse auswählen',
        SlctOL: 'Ausgehend',
        SlctIL: 'Eingehend',
        IB: 'Tooltip',
        IS: 'Zusatzinfo',
        align_horiz: 'Horizontal',
        align_horiz_min: 'Relativ zum am weitesten links befindlichen ausgewählten Knoten',
        align_horiz_max: 'Relativ zum am weitesten rechts befindlichen ausgewählten Knoten',
        align_vert: 'Vertikal',
        align_vert_min: 'Relativ zum am weitesten oben befindlichen ausgewählten Knoten',
        align_vert_max: 'Relativ zum am weitesten unten befindlichen ausgewählten Knoten',
        align_horiz_left: 'An seiner linken Seite ausrichten',
        align_horiz_center: 'An seiner Mitte ausrichten',
        align_horiz_right: 'An seiner rechten Seite ausrichten',
        align_vert_top: 'An seiner Oberseite ausrichten',
        align_vert_bottom: 'An seiner Unterseite ausrichten',
        align: 'Knoten ausrichten',
        product: 'Produkt',
        sector: 'Sektor',
        exchange: 'Austausch',
        size: 'Größe',
        position: 'Position',
        text: 'Text',
        selector: 'Knoten auswählen',
        title_desaggreg: 'Dimensionsdisaggregation',
        title_aggreg: 'Dimensionsaggregation',
        text_agreg: 'Wird aggregiert in: ',
        text_desagreg: 'Wird disaggregiert in: ',
        desaggreg: 'Disaggregation',
        aggreg: 'Aggregation',
        firstPlan: 'In den Hintergrund verschieben',
        lastPlan: 'In den Vordergrund verschieben',
        changePlan: 'Ebene der Knoten ändern',
        mask_attr: 'Elementanzeige',
        tooltips: {
          AS: 'Ermöglicht das Anwenden eines vordefinierten Stils aus dem Einstellungsmenü auf die ausgewählten Knoten',
          Reorg: 'Ermöglicht die automatische Reorganisation der ein- und ausgehenden Flüsse (Position oben/unten)',
          SlctOutLink: 'Ermöglicht die Auswahl aller ausgehenden Flüsse des/der Knoten(s)',
          SlctInLink: 'Ermöglicht die Auswahl aller eingehenden Flüsse zum/zu den Knoten',
          IB: 'Tooltip: HTML-formatierter Text, der mit dem Tooltip des Knotens angezeigt wird. Dieser Tooltip erscheint im Grafikbereich mit SHIFT + MAUS auf dem Knoten.',
        },
        drawing_area_tooltip: {
          outputs: 'Ausgänge',
          inputs: 'Eingänge',
          dest: 'Ausgänge',
          val: 'Werte',
          data_value: 'Erhobene Daten',
          result_value: 'Berechnete Daten',
          rat: 'Verhältnisse',
          prov: 'Eingänge',
          values_tab: 'Werte',
          tags_tab: 'Weitere Informationen'
        },
        tabs: {
          apparence: 'Darstellung',
          infos: 'Zusatzinfo',
          tags: 'Tags',
          io: 'E/A-Flüsse',
        },
        apparence: {
          apparence: 'Darstellung',
          shape_visible: 'Form',
          shape_color: 'Farbe',
          shape_color_sustainable: 'Statische Farbe',
          shape_type: 'Knotenform',
          Geometry: 'Geometrie',
          Cercle: 'Bogen',
          Rectangle: 'Rechteck',
          shape_min_width: 'Mindestbreite',
          shape_min_height: 'Mindesthöhe',
          geometry: 'Positionierung',
          geometry_absolute: 'Absolut',
          geometry_parametric: 'Abstand',
          geometry_relative: 'Versatz',
          position_u: 'Spalte',
          column_u: 'Spalte (u)',
          position_v: 'Zeile',
          row_v: 'Zeile (v)',
          position_dx: 'Horizontaler Abstand',
          position_dy: 'Vertikaler Abstand',
          anchor_align_vertical: 'Anker (vertikale Seiten)',
          anchor_align_horizontal: 'Anker (horizontale Seiten)',
          asn: 'Stil auf Knoten anwenden',
          override_type_node_shape: 'Form freischalten',
          arrow: 'Pfeil',
          display_shape: 'Knoten anzeigen',
          hide_shape: 'Knoten ausblenden',
          display_label: 'Beschriftung anzeigen',
          hide_label: 'Beschriftung ausblenden',
          display_value: 'Wert anzeigen',
          hide_value: 'Wert ausblenden',
          shape_opacity: 'Deckkraft',
          tooltips: {
            FormeDisabled: 'Deaktiviert, da die Form von der Tag-Gruppe "Knotentyp" verwaltet wird. Wenn Sie die Form der ausgewählten Knoten ändern möchten, gehen Sie zum Tab "Tags" und deaktivieren Sie alle ausgewählten Tags der Gruppe "Knotentyp".',
            shape_anchor_align_vertical: 'Vertikale Ausrichtung der Flussanker an den linken/rechten Seiten des Knotens (oben / Mitte / unten).',
            shape_anchor_align_horizontal: 'Horizontale Ausrichtung der Flussanker an den oberen/unteren Seiten des Knotens (links / Mitte / rechts).',
            geometry: 'Methode zur Berechnung der Knotenposition. Die Position kann in absoluten Koordinaten x,y, in relativen Koordinaten u,v oder relativ zu einem anderen Knoten angegeben werden.',
            position_dx: 'Horizontaler Abstand zwischen dem rechten Rand des linken Knotens und dem linken Rand des Knotens',
            position_dy: 'Vertikaler Abstand zwischen dem unteren Rand des oberen Knotens und dem oberen Rand des Knotens',
            shape_position_u_locked: 'Wenn gesperrt, behält die Autosankey-Berechnung den Spaltenindex (u) dieses Knotens bei, anstatt ihn neu zu berechnen.',
            shape_position_v_locked: 'Wenn gesperrt, behält die Autosankey-Berechnung die relative vertikale Reihenfolge (v) dieses Knotens in seiner Spalte bei, anstatt sie neu zu berechnen.',
            override_type_node_shape: 'Ermöglicht das Ändern der standardmäßig erzwungenen Form bei Produkt- und Sektorknoten',
          }
        },
        node_value: {
          anchor: 'Ankerposition',
          anchor_dx: 'Horizontaler Versatz',
          anchor_dy: 'Vertikaler Versatz',
          tooltips: {
            anchor: 'Der Anker des Knotenwerts kann auf 9 Arten relativ zur Form positioniert werden, indem horizontal linker Rand, Mitte und rechter Rand und vertikal oberer Rand, Mitte und unterer Rand kombiniert werden',
            anchor_dx: 'Horizontaler Versatz vom Anker des Knotenwerts',
            anchor_dy: 'Vertikaler Versatz vom Anker des Knotenwerts',
          }
        },
        labels: {
          labels: 'Name',
          node_value: 'Wert',
          name_label_is_visible: 'Beschriftung',
          lb: 'Weiße Beschriftung',
          name_label_background: 'Hintergrund',
          name_label_background_color: 'Hintergrundfarbe',
          pos: 'Position',
          pos_v: 'Wertposition',
          tp: 'Schriftgröße',
          cl: 'Textfeldbreite',
          vdv: 'Wert',
          edit_node_label: 'Knotenbezeichnung bearbeiten',
          anchor: 'Ankerposition',
          name_label_text_source: 'Beschriftungsinhalt',
          name_label_text: 'Benutzerdefinierte Beschriftung',
          name_label_tag_group: 'Tag-Gruppe',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimension',
          name_label_dimension_auto: 'Automatisch (erste)',
          text_source: {
            name: 'Knotenname',
            name_container: 'Elementname',
            custom: 'Benutzerdefinierter Text',
            tag: 'Langer Tag-Name',
            ancestor: 'Name des Vorfahrknotens',
          },
          tooltips: {
            name_label_text_source: 'Wählen, was die Knotenbeschriftung anzeigt: den Knotennamen oder einen unabhängigen benutzerdefinierten Text (bearbeitbar, ohne den Knoten umzubenennen)',
            name_label_is_visible: 'Zeigt oder verbirgt die Beschriftung(en) des/der ausgewählten Knoten(s)',
            lb: 'Zeigt den Text der Beschriftung(en) in Weiß oder Schwarz an (nützlich, wenn die Beschriftung auf dem/den Knoten positioniert ist)',
            name_label_background: 'Fügt einen Hintergrund zur Beschriftung hinzu für bessere Sichtbarkeit, wenn sie vor einem Fluss liegt',
            top: 'Zeigt die Beschriftung(en) oberhalb des/der ausgewählten Knoten(s) an',
            Milieu_pv: 'Zeigt die Beschriftung(en) in der Mitte (vertikal) des/der ausgewählten Knoten(s) an',
            Bas: 'Zeigt die Beschriftung(en) unterhalb des/der ausgewählten Knoten(s) an',
            gauche: 'Zeigt die Beschriftung(en) links vom/von den ausgewählten Knoten an',
            Milieu_ph: 'Zeigt die Beschriftung(en) in der Mitte (horizontal) des/der ausgewählten Knoten(s) an',
            droite: 'Zeigt die Beschriftung(en) rechts vom/von den ausgewählten Knoten an',
            cl: 'Breite des Textbereichs (in Pixeln) für die Beschriftung(en) des/der ausgewählten Knoten(s)',
            vdv: 'Zeigt oder verbirgt den zugehörigen Wert des/der ausgewählten Knoten(s)',
            anchor: 'Der Anker der Beschriftung kann auf 9 Arten relativ zur Form positioniert werden, indem horizontal linker Rand, Mitte und rechter Rand und vertikal oberer Rand, Mitte und unterer Rand kombiniert werden',
            haut_val: 'Zeigt den zugehörigen Wert oberhalb des/der ausgewählten Knoten(s) an',
            Milieu_pv_val: 'Zeigt den zugehörigen Wert in der Mitte (vertikal) des/der ausgewählten Knoten(s) an',
            Bas_val: 'Zeigt den zugehörigen Wert unterhalb des/der ausgewählten Knoten(s) an',
            gauche_val: 'Zeigt den zugehörigen Wert links vom/von den ausgewählten Knoten an',
            Milieu_ph_val: 'Zeigt den zugehörigen Wert in der Mitte (horizontal) des/der ausgewählten Knoten(s) an',
            droite_val: 'Zeigt den zugehörigen Wert rechts vom/von den ausgewählten Knoten an',
          }
        },
        tags_node: {
          tags: 'Tags',
          Appartenance: 'Zugehörigkeit'
        },
        agre: {
          Agré: 'Aggregation',
          DC: 'Würfeldimensionen',
          Parent: 'Elternknoten',
          CLE: 'Kindflüsse kopieren'
        },
        PF: {
          PF: 'E/A-Flüsse',
          PFM: 'E/A-Flüsse organisieren',
          FES: 'Flusstyp',
          ent: 'Eingang',
          sort: 'Ausgang',
          FRN: 'Relative Position / Knoten',
          gauche: 'Links',
          droite: 'Rechts',
          ades: 'Darüber',
          edes: 'Darunter',
          lti: 'Flüsse in der Tabelle mit ihren Farben kennzeichnen',
          col: 'Anwenden',
          filter_links: 'Anzuzeigende Flüsse',
          visible_links: 'Sichtbare Flüsse',
          all_links: 'Alle Flüsse',
          lock: 'Schloss',
          delta: 'Abstand',
          tooltips: {
            io: 'Eingehende oder ausgehende Flüsse des ausgewählten Knotens auswählen',
            side: 'Rechte, linke, obere oder untere Flüsse des ausgewählten Knotens auswählen',
            lti: 'Zeigt die Zeilen der Flusstabelle mit ihren jeweiligen Farben an, um sie besser zu identifizieren',
            filter_links: 'Nur sichtbare Flüsse oder alle Flüsse einschließlich der verborgenen anzeigen',
            lock: 'Sperrt die Seite dieses Ankers: Das Verschieben des gegenüberliegenden Knotens positioniert ihn nicht mehr neu. Wird durch jede automatische Berechnung aufgehoben.',
            delta: 'Zusätzlicher Abstand vor diesem Anker, um die am Knoten ankommenden Flüsse zu verteilen'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Standard-Knotenstil',
        LinkStyle: 'Standard-Flussstil',
        ContainerStyle: 'Standard-Containerstil',
        NodeContainerStyle: 'Umschließender Knotenrahmen',
        NodeLeftExtremityStyle: 'Knotenstil linkes Ende',
        NodeRightExtremityStyle: 'Knotenstil rechtes Ende',
        NodeProductStyle: 'Produktbezeichnung-Stil',
        NodeSectorStyle: 'Sektorbezeichnung-Stil',
        NodeImportExportCloseStyle: 'Knoten Import-Export angehängt',
        NodeImportCloseStyle: 'Knoten Import angehängt',
        NodeExportCloseStyle: 'Knoten Export angehängt',
        NodeImportExportAboveBelowStyle: 'Knoten Import-Export oben/unten',
        NodeImportAboveStyle: 'Knoten Import oben',
        NodeExportBelowStyle: 'Knoten Export unten',
        LinkImportExportCloseStyle: 'Fluss Import-Export angehängt',
        LinkImportCloseStyle: 'Fluss Import angehängt',
        LinkExportCloseStyle: 'Fluss Export angehängt',
        LinkImportExportAboveBelowStyle: 'Fluss Import-Export oben/unten',
        SankeyUnitaryNodeStyle: 'Einheitsknoten',
        SankeyUnitaryNodeInputStyle: 'Einheitsknoten Eingang',
        SankeyUnitaryNodeOutputStyle: 'Einheitsknoten Ausgang',
        LinkInUnitaryStyle: 'Einheitsfluss Eingang',
        LinkOutUnitaryStyle: 'Einheitsfluss Ausgang',
        family: 'Familie',
        family_predefined: 'Anwendungsstile',
        family_user: 'Benutzerstile'
      }
    }
  },
  it: {
    translation: {
      Noeud: {
        Style: 'Foglio di stile',
        OrderStyle: 'Ordine degli stili associati',
        multi_style: 'I nodi selezionati hanno stili diversi',
        editStyle: 'Assegnare uno stile',
        AS: 'Ripristina',
        SelectStyle: 'Selezionare uno stile',
        Reorg: 'Riorganizzare i flussi in ingresso/uscita',
        Reorg_title: 'Riorganizzazione',
        Slct: 'Selezione',
        SlctOutLink: 'Selezionare flussi in uscita',
        SlctInLink: 'Selezionare flussi in ingresso',
        SlctL: 'Selezionare i flussi',
        SlctOL: 'In uscita',
        SlctIL: 'In ingresso',
        IB: 'Tooltip',
        IS: 'Info aggiuntive',
        align_horiz: 'Orizzontalmente',
        align_horiz_min: 'Rispetto al nodo selezionato più a sinistra',
        align_horiz_max: 'Rispetto al nodo selezionato più a destra',
        align_vert: 'Verticalmente',
        align_vert_min: 'Rispetto al nodo selezionato più in alto',
        align_vert_max: 'Rispetto al nodo selezionato più in basso',
        align_horiz_left: 'Allinea a sinistra',
        align_horiz_center: 'Allinea al centro',
        align_horiz_right: 'Allinea a destra',
        align_vert_top: 'Allinea in alto',
        align_vert_bottom: 'Allinea in basso',
        align: 'Allinea nodi',
        product: 'Prodotto',
        sector: 'Settore',
        exchange: 'Scambio',
        size: 'Dimensione',
        position: 'Posizione',
        text: 'Testo',
        selector: 'Seleziona nodi',
        title_desaggreg: 'Disaggregazione dimensione',
        title_aggreg: 'Aggregazione dimensione',
        text_agreg: 'Verrà aggregato in: ',
        text_desagreg: 'Verrà disaggregato in: ',
        desaggreg: 'Disaggregazione',
        aggreg: 'Aggregazione',
        firstPlan: 'Porta in secondo piano',
        lastPlan: 'Porta in primo piano',
        changePlan: 'Cambia piano dei nodi',
        mask_attr: 'Visualizzazione elementi',
        tooltips: {
          AS: 'Permette di applicare uno stile predefinito dal menu preferenze ai nodi selezionati',
          Reorg: 'Permette di riorganizzare automaticamente i flussi in ingresso e in uscita (posizione su/giù)',
          SlctOutLink: 'Permette di selezionare tutti i flussi in uscita dal/dai nodo/i',
          SlctInLink: 'Permette di selezionare tutti i flussi in ingresso al/ai nodo/i',
          IB: 'Tooltip: testo formattato in HTML visualizzato con il tooltip del nodo. Questo tooltip appare nello spazio grafico con SHIFT + MOUSE sul nodo.',
        },
        drawing_area_tooltip: {
          outputs: 'Uscite',
          inputs: 'Ingressi',
          dest: 'Uscite',
          val: 'Valori',
          data_value: 'Dato raccolto',
          result_value: 'Dato calcolato',
          rat: 'Rapporti',
          prov: 'Ingressi',
          values_tab: 'Valori',
          tags_tab: 'Altre informazioni'
        },
        tabs: {
          apparence: 'Aspetto',
          infos: 'Info aggiuntive',
          tags: 'Tag',
          io: 'Flussi I/O',
        },
        apparence: {
          apparence: 'Aspetto',
          shape_visible: 'Forma',
          shape_color: 'Colore',
          shape_color_sustainable: 'Colore statico',
          shape_type: 'Forma del nodo',
          Geometry: 'Geometria',
          Cercle: 'Arco',
          Rectangle: 'Rettangolo',
          shape_min_width: 'Larghezza minima',
          shape_min_height: 'Altezza minima',
          geometry: 'Posizionamento',
          geometry_absolute: 'Assoluto',
          geometry_parametric: 'Spaziatura',
          geometry_relative: 'Offset',
          position_u: 'Colonna',
          column_u: 'Colonna (u)',
          position_v: 'Riga',
          row_v: 'Riga (v)',
          position_dx: 'Distanza orizzontale',
          position_dy: 'Distanza verticale',
          anchor_align_vertical: 'Ancore (lati verticali)',
          anchor_align_horizontal: 'Ancore (lati orizzontali)',
          asn: 'Applica stile ai nodi',
          override_type_node_shape: 'Sblocca la forma',
          arrow: 'Freccia',
          display_shape: 'Mostra il nodo',
          hide_shape: 'Nascondi il nodo',
          display_label: 'Mostra l\'etichetta',
          hide_label: 'Nascondi l\'etichetta',
          display_value: 'Mostra il valore',
          hide_value: 'Nascondi il valore',
          shape_opacity: 'Opacità',
          tooltips: {
            FormeDisabled: 'Disattivato perché la forma è gestita dal gruppo di tag "Tipo di nodo". Se si desidera modificare la forma dei nodi selezionati, andare alla scheda "Tag" e deselezionare tutti i tag selezionati del gruppo "Tipo di nodo".',
            shape_anchor_align_vertical: 'Allineamento verticale delle ancore di flusso sui lati sinistro/destro del nodo (alto / centro / basso).',
            shape_anchor_align_horizontal: 'Allineamento orizzontale delle ancore di flusso sui lati superiore/inferiore del nodo (sinistra / centro / destra).',
            geometry: 'Metodo per calcolare la posizione del nodo. La posizione può essere data in coordinate assolute x,y, in coordinate relative u,v, o in coordinate relative a un altro nodo.',
            position_dx: 'Distanza orizzontale tra il bordo destro del nodo a sinistra e il bordo sinistro del nodo',
            position_dy: 'Distanza verticale tra il bordo inferiore del nodo superiore e il bordo superiore del nodo',
            shape_position_u_locked: 'Se bloccato, il calcolo autosankey conserva l\'indice di colonna (u) di questo nodo invece di ricalcolarlo.',
            shape_position_v_locked: 'Se bloccato, il calcolo autosankey conserva l\'ordine verticale relativo (v) di questo nodo nella sua colonna invece di ricalcolarlo.',
            override_type_node_shape: 'Permette di cambiare la forma forzata di default sui nodi di tipo prodotto e settore',
          }
        },
        node_value: {
          anchor: 'Posizione dell\'ancora',
          anchor_dx: 'Spostamento orizzontale',
          anchor_dy: 'Spostamento verticale',
          tooltips: {
            anchor: 'L\'ancora del valore del nodo può essere posizionata in 9 modi rispetto alla forma, combinando orizzontalmente bordo sinistro, centro e bordo destro, e verticalmente bordo superiore, centro e bordo inferiore',
            anchor_dx: 'Spostamento orizzontale dall\'ancora del valore del nodo',
            anchor_dy: 'Spostamento verticale dall\'ancora del valore del nodo',
          }
        },
        labels: {
          labels: 'Nome',
          node_value: 'Valore',
          name_label_is_visible: 'Etichetta',
          lb: 'Etichetta bianca',
          name_label_background: 'Sfondo',
          name_label_background_color: 'Colore sfondo',
          pos: 'Posizione',
          pos_v: 'Posizione del valore',
          tp: 'Dimensione carattere',
          cl: 'Larghezza area testo',
          vdv: 'Valore',
          edit_node_label: 'Modifica nome nodo',
          anchor: 'Posizione dell\'ancora',
          name_label_text_source: 'Contenuto dell\'etichetta',
          name_label_text: 'Etichetta personalizzata',
          name_label_tag_group: 'Gruppo di tag',
          name_label_tag: 'Tag',
          name_label_dimension: 'Dimensione',
          name_label_dimension_auto: 'Automatica (la prima)',
          text_source: {
            name: 'Nome del nodo',
            name_container: 'Nome dell\'elemento',
            custom: 'Testo personalizzato',
            tag: 'Nome lungo di un tag',
            ancestor: 'Nome del nodo antenato',
          },
          tooltips: {
            name_label_text_source: 'Scegli cosa mostra l\'etichetta del nodo: il nome del nodo, o un testo personalizzato indipendente (modificabile senza rinominare il nodo)',
            name_label_is_visible: 'Mostra o nasconde l\'etichetta/e associata/e al/ai nodo/i selezionato/i',
            lb: 'Mostra il testo dell\'etichetta/e in bianco o nero (utile se l\'etichetta è posizionata sul/sui nodo/i)',
            name_label_background: 'Aggiunge uno sfondo all\'etichetta per una migliore visibilità quando è davanti a un flusso',
            top: 'Mostra l\'etichetta/e sopra il/i nodo/i selezionato/i',
            Milieu_pv: 'Mostra l\'etichetta/e al centro (verticalmente) del/dei nodo/i selezionato/i',
            Bas: 'Mostra l\'etichetta/e sotto il/i nodo/i selezionato/i',
            gauche: 'Mostra l\'etichetta/e a sinistra del/dei nodo/i selezionato/i',
            Milieu_ph: 'Mostra l\'etichetta/e al centro (orizzontalmente) del/dei nodo/i selezionato/i',
            droite: 'Mostra l\'etichetta/e a destra del/dei nodo/i selezionato/i',
            cl: 'Larghezza dell\'area di testo (in pixel) per l\'etichetta/e del/dei nodo/i selezionato/i',
            vdv: 'Mostra o nasconde il valore associato al/ai nodo/i selezionato/i',
            anchor: 'L\'ancora dell\'etichetta può essere posizionata in 9 modi rispetto alla forma, combinando orizzontalmente bordo sinistro, centro e bordo destro, e verticalmente bordo superiore, centro e bordo inferiore',
            haut_val: 'Mostra il valore associato sopra il/i nodo/i selezionato/i',
            Milieu_pv_val: 'Mostra il valore associato al centro (verticalmente) del/dei nodo/i selezionato/i',
            Bas_val: 'Mostra il valore associato sotto il/i nodo/i selezionato/i',
            gauche_val: 'Mostra il valore associato a sinistra del/dei nodo/i selezionato/i',
            Milieu_ph_val: 'Mostra il valore associato al centro (orizzontalmente) del/dei nodo/i selezionato/i',
            droite_val: 'Mostra il valore associato a destra del/dei nodo/i selezionato/i',
          }
        },
        tags_node: {
          tags: 'Tag',
          Appartenance: 'Appartenenza'
        },
        agre: {
          Agré: 'Aggregazione',
          DC: 'Dimensioni del cubo',
          Parent: 'Genitore',
          CLE: 'Copia flussi figli'
        },
        PF: {
          PF: 'Flussi I/O',
          PFM: 'Organizza flussi I/O',
          FES: 'Tipo di flusso',
          ent: 'Ingresso',
          sort: 'Uscita',
          FRN: 'Posizione relativa / nodo',
          gauche: 'Sinistra',
          droite: 'Destra',
          ades: 'Sopra',
          edes: 'Sotto',
          lti: 'Identifica i flussi nella tabella con i loro colori',
          col: 'Applica',
          filter_links: 'Flussi da visualizzare',
          visible_links: 'Flussi visibili',
          all_links: 'Tutti i flussi',
          lock: 'Lucchetto',
          delta: 'Spaziatura',
          tooltips: {
            io: 'Scegliere i flussi in ingresso o in uscita del nodo selezionato',
            side: 'Scegliere i flussi a destra, sinistra, sopra o sotto del nodo selezionato',
            lti: 'Mostra le righe della tabella dei flussi con i rispettivi colori per identificarli meglio',
            filter_links: 'Mostra solo i flussi visibili o tutti i flussi compresi quelli nascosti',
            lock: 'Blocca il lato di questa ancora: spostare il nodo opposto non la riposizionerà più. Rilasciato da qualsiasi calcolo automatico.',
            delta: 'Spaziatura aggiuntiva inserita prima di questa ancora, per distanziare i flussi che arrivano sul nodo'
          }
        }
      },
      ElementStyle: {
        NodeStyle: 'Stile nodo predefinito',
        LinkStyle: 'Stile flusso predefinito',
        ContainerStyle: 'Stile contenitore predefinito',
        NodeContainerStyle: 'Cornice englobante di nodi',
        NodeLeftExtremityStyle: 'Stile nodo estremità sinistra',
        NodeRightExtremityStyle: 'Stile nodo estremità destra',
        NodeProductStyle: 'Stile etichetta prodotto',
        NodeSectorStyle: 'Stile etichetta settore',
        NodeImportExportCloseStyle: 'Nodo import-export allegato',
        NodeImportCloseStyle: 'Nodo import allegato',
        NodeExportCloseStyle: 'Nodo export allegato',
        NodeImportExportAboveBelowStyle: 'Nodo import-export sopra/sotto',
        NodeImportAboveStyle: 'Nodo import sopra',
        NodeExportBelowStyle: 'Nodo export sotto',
        LinkImportExportCloseStyle: 'Flusso import-export allegato',
        LinkImportCloseStyle: 'Flusso import allegato',
        LinkExportCloseStyle: 'Flusso export allegato',
        LinkImportExportAboveBelowStyle: 'Flusso import-export sopra/sotto',
        SankeyUnitaryNodeStyle: 'Nodo unitario',
        SankeyUnitaryNodeInputStyle: 'Nodo unitario ingresso',
        SankeyUnitaryNodeOutputStyle: 'Nodo unitario uscita',
        LinkInUnitaryStyle: 'Flusso unitario ingresso',
        LinkOutUnitaryStyle: 'Flusso unitario uscita',
        family: 'Famiglia',
        family_predefined: 'Stili dell\'applicazione',
        family_user: 'Stili utente'
      }
    }
  }
}