export const resources_flux = {
  en: {
    translation: {
      Flux: {
        pg: 'General settings',
        pdl: 'Font',
        pl: 'Parameters per link',
        src: 'Origin',
        trgt: 'Destination',
        value: 'Value',
        calculated_value: 'Comp. Val',
        type: 'Format',
        if: 'Reverse direction',
        dzf: 'Overlaying order',
        style: 'Style',
        as: 'Apply the style to selected link(s)',
        IB: 'ToolTip',
        IS: 'Additional info.',
        ajust_label: 'Adjust labels position',
        FS: 'Link',
        local_scale: 'Local link scale',
        changePlan: 'Change plan of flows',
        mask_attr: 'Change flow\'s attributes',
        tooltips: {
          src: 'Choice of the departure node for the selected link(s)',
          trgt: 'Choice of the arrival node for the selected link(s)',
          if: 'Reverse the start and finish nodes for the selected link(s)',
          up: 'Move up one step to the foreground',
          upup: 'Put the selected stream(s) in the foreground',
          dwn: 'Go down one step to the last plane',
          dwndwn: 'Move the selected stream(s) to the last plane',
          as: 'Allow to apply a predefined style in the preferences menu to the selected link(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the link. This tooltip pops on graphic space with SHIFT + MOUSE on the link.',
          ajust_label: 'Reposition links labels above the links if they\'re taller than link stroke',
          inv: 'Inverse the target and the source'
        },
        data: {
          données: 'Data',
          vpp: 'Value',
          data_type: 'Data type',
          value: 'Value',
          ratio_input: 'Ratio total input',
          ratio_output: 'Ratio total output',
          ratio_source_parent: 'Ratio parent flux(left)',
          ratio_target_parent: 'Ratio parent flux(right)',
          unit_ratio: 'Coeff. units conversion',
          edit_value: 'Edit value',
          value_target: 'Dest. value',
          tab_basic: 'Basic',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Uncertainty',
          affichage: 'Label',
          tooltips: {
            data_type: 'Data type',
            vpp: 'Data associated to the selected link and, if existing, for the selected tag(s)',
            scientificNotation: 'Activate or not the notation in scientific format, for the display of the link\'s data on the Sankey diagram',
            affichage: 'Replacement text for the display of the link\'s data on the Sankey diagram',
            value_target: 'Destination value for tapered links (leave empty for uniform thickness)',
            value: 'Flow value. You can also type "min" or "max": reconciliation then gives the flow the smallest (resp. largest) value compatible with the rest of the model, and the flow comes out determined.',
            data_min: 'Minimum bound for the flow value (used for reconciliation)',
            data_max: 'Maximum bound for the flow value (used for reconciliation)',
            uncertainty: 'Relative uncertainty in % on the flow value (used for reconciliation)',
            tab_basic_disabled: 'Select "Value" as data type in the AFM tab to enable this panel'
          },
          dir: 'Considered flows',
          node_ref: 'Relative to',
          ratio: 'Ratio type',
          value_type: 'Data type'
        },
        apparence: {
          anchor: 'Anchors',
          handle: 'Handles',
          curve_unit: 'Unit',
          apparence: 'Appearance',
          flow: 'Flow',
          fond: 'shape background',
          source: 'Source node',
          target: 'Target node',
          couleur: 'Color',
          color_source: 'Element defining flow color',
          grad: 'Gradient',
          shape_is_dashed: 'Dashed',
          shape_visible_when_zero: 'Show if null',
          of: 'Orientation',
          type: 'Type',
          courbe: 'Curve',
          fleche: 'Arrow',
          opacity: 'Opacity',
          arrow_size: 'Size of arrow',
          shape_arrow_standalone: 'Standalone tip',
          shape_arrow_min_width: 'Min tip width (px)',
          shape_structure_force_min: 'Node/arrow at value height',
          shape_uncertainty_display: 'Show uncertainty',
          display_link_lab: 'Display value',
          hide_link_lab: 'Hide value',
          display_link_name: 'Display name',
          hide_link_name: 'Hide name',
          data_off_scale: 'Scale',
          scale_ref_thickness: 'Max scale thickness (px)',
          bezier_path: 'Simple',
          bezier_outline: 'Outline',
          bezier_outline_exact: 'Exact outline',
          tooltips: {
            color_source: {
              def: 'Choose what rule define flow color :',
              flow: 'Color is defined by flow parameter (default color, flow tag\'s color or data tag\'s color)',
              source: 'Color is defined by source node color',
              target: 'Color is defined by target node color',
              gradient: 'Color is a gradient from source node color to target node color',
              auto: 'Color is determined automatically using this priority:\n1. Common color tag between source and target\n2. Only one side has a color tag → take that side\n3. Both have tags (no common) → prefer the product node\n4. No color tags → prefer the product node\n5. Fallback: source color',
              disabled: 'Rule doesn\'t allow to choose flow color'
            },
            couleur: 'Choose the color for the selected link(s)',
            grad: 'Apply a gradient color effect on the selected link(s). The gradient is done between the color of the start node and the color of the end node',
            shape_is_dashed: 'Applies a hatch effect on the selected link(s)',
            shape_visible_when_zero: 'Always draw this link even when its value is zero (overrides the null-link filter for this link only)',
            of_vv: 'Allows to orient the beginning of the link vertically and the end of the link vertically',
            of_hh: 'Allows to orient the beginning of the link horizontally and the end of the link horizontally',
            of_hv: 'Allows to orient the beginning of the link horizontally and the end of the link vertically',
            of_vh: 'Allows to orient the beginning of the link vertically and the end of the link horizontally',
            courbe: 'Represents the selected link(s) as a Bezier curve',
            fleche: 'Represents the selected link(s) with an arrow tip at the end',
            structure: 'Represents the selected link(s) as if they didn\'t have values no matter their true value',
            starting_curve: 'Allows to refine the position of the starting point of curvature for the selected link(s). This value is a ratio (%) of the link\'s lenght relative to the starting point of the link.',
            ending_curve: 'Allows to refine the position of the ending point of curvature for the selected link(s). This value is a ratio (%) of the link\'s lenght relative to the starting point of the link.',
            starting_tangeant: 'Setting the radius of the starting curvature in case the selected link(s) are represented as Bezier curve(s)',
            ending_tangeant: 'Setting the radius of the ending curvature in case the selected link(s) are represented as Bezier curve(s)',
            arrow_size: 'Change the size of the arrow (from the end of the link to the node)',
            shape_arrow_standalone: 'Draw this link\'s arrow as an independent triangle centered on its real end, instead of sharing the fan of arrows converging at the node side.',
            shape_arrow_min_width: 'Minimum width (px) of the arrow tip base: flows thinner than this get a tip of this width (so they stay visible), thicker flows are unchanged. The tip depth (arrow size) is unchanged. 0 disables it.',
            shape_structure_force_min: 'Checked: in structure mode, this flow keeps its value height on the node and arrow. Unchecked (default): the flow is collapsed to a thin connector and does not enlarge the node or arrow.',
            shape_uncertainty_display: 'Superimpose the flow drawn at its min/mean/max values (thinner = more opaque) to visualize the uncertainty interval.',
            data_off_scale: 'Define a scale for this flow, wich can break the coherence of flow thickness proportionality of value ',
            local_scale: 'Define a local scaling factor that will be multiplied by the multiplier specified for this flow.',
            scale_ref_thickness: 'Maximum thickness (px) for this flow in the current view tag: only when this flow would exceed this thickness, the diagram scale is rescaled so it sits exactly at this value; all other flows and the scale legend follow. Below the threshold, nothing changes. 0 = disabled. One reference flow per view tag.'
          }
        },
        labels: {
          value: 'Value',
          intervals: 'Intervals',
          percent: '%',
          ratio: 'Ratio',
          unit_name: 'Custom unit',
          unit_model: 'Unit from the diagram units',
          unit_ratio: 'Unit ratio',
          unit_tag: 'Native origin unit',
          other_unit_tag: 'Other native units',
          normalized: 'Normalized (ref. flux)',
          '%IS': '% of the source node inflows',
          '%ID': '% of the destination node inflows',
          '%OS': '% of the source node outflows',
          '%OD': '% of the destination node outflows',
          '%PS': '% of the upstream node total (source)',
          '%PD': '% of the downstream node total (destination)',
          '%SS': '% of the source node stock (outflow)',
          '%SD': '% of the destination node stock (inflow)',
          label: 'Label',
          vdb: 'Label value',
          len: 'Black label',
          lb: 'White label',
          lec: 'Colored label',
          pos: 'Position',
          milieu: 'Middle',
          deb: 'Start',
          fin: 'End',
          dessous: 'Above',
          dessus: 'Below',
          pls: 'Manual positioning of the label',
          l_u_v: 'Unit',
          l_u: 'Unit\'s name',
          name_label_text_source: 'Label content',
          name_label_template: 'Template',
          name_label_tag_group: 'Tag group',
          text_source: {
            custom: 'Custom text',
            template: 'Token template',
            none: 'None',
            source: 'Source node',
            target: 'Target node',
            source_target: 'Source → target',
            tag: 'Flux tag',
          },
          tooltips: {
            name_label_text_source: 'Pick what the link label displays: typed text, nothing, source/target node name, or source → target',
            name_label_template: 'Text built from tokens replaced at draw time, e.g. "{EntryName}: {Value} {Unit}"',
            label: 'Display or not the label (data / text) associated to the selected link(s)',
            len: 'Display the label in black, for the selected stream(s)',
            lb: 'Display the label in white, for the selected stream(s)',
            lec: 'Display the label with the same color(s) as the one(s) associated with the selected stream(s)',
            deb: 'For the selected link(s), allows to position the label towards the starting point of the link',
            milieu_h: 'For the selected link(s), allows to position the label between the starting point and the end point of the link',
            end: 'For the selected stream(s), allows to position the label towards the end point of the stream',
            below: 'For the selected stream(s), allows to position the label below the stream',
            milieu_v: 'For the selected link(s), allows to position the label inside the link',
            top: 'For the selected stream(s), allows to position the label above the stream',
            pls: 'Combination Alt/left click move the label of the selected stream(s)',
            l_u_v: 'Display the unit of the links',
            l_u: 'Choose the name of the unit',
            unit_factor: 'Factor of conversion for link unity',
            '%ID': '% of the destination node inflows',
            '%IS': '% of the source node inflows',
            '%OD': '% of the destination node outflows',
            '%OS': '% of the source node outflows',
            '%PD': 'Value displayed as % of the downstream node (destination) total throughput: max(inflows, outflows)',
            '%PS': 'Value displayed as % of the upstream node (source) total throughput: max(inflows, outflows)',
            '%SD': '% of the destination node stock (inflow)',
            '%SS': '% of the source node stock (outflow)',
            dessous: 'For the selected flow(s), place the label text below the flow',
            dessus: 'For the selected flow(s), place the label text above the flow',
            fin: 'For the selected flow(s), place the label text near the end point of the flow',
            value: 'Value'
          },
          NbDigit: 'Maximum number of decimals',
          labels: 'Name',
          name_label_is_visible: 'Label',
          node_value: 'Value',
          pos_v: 'Value position',
          scientificNotation: 'Scientific notation',
          significantDigits: 'Significant digits',
          source: 'Source node',
          target: 'Target node',
          tp: 'Font size',
          unit_factor: 'Unit factor'
        },
        layout: 'Disposition',
        layoutUp: 'Move forward',
        layoutTop: 'Move to the top',
        layoutDown: 'Move backward',
        layoutBottom: 'Move to the bottom',
      }
    }
  },
  fr: {
    translation: {
      Flux: {
        pg: 'Paramètres généraux',
        pdl: 'Police des labels',
        pl: 'Paramètres par flux',
        src: 'Origine',
        trgt: 'Destination',
        value: 'Valeur',
        calculated_value: 'Val. Calc.',
        type: 'Format',
        if: 'Inverser le sens',
        dzf: 'Superposition d\'affichage',
        style: 'Style',
        as: 'Réinitialiser',
        IB: 'Info-bulle',
        IS: 'Info sup.',
        ajust_label: 'Position vertical ajusté',
        local_scale: 'Échelle propre au flux',
        FS: 'Flux',
        changePlan: 'Modifier le plan des flux',
        mask_attr: 'Changer des attributs',
        tooltips: {
          src: 'Choix du noeud de départ pour le/les flux sélectionné(s)',
          trgt: 'Choix du noeud d\'arrivée pour le/les flux sélectionné(s)',
          if: 'Permet d\'inverser les noeuds de départ et d\'arrivée pour le/les flux sélectionné(s)',
          up: 'Monter d\'un cran vers le premier plan',
          upup: 'Mettre le/les flux selectionné(s) au premier plan',
          dwn: 'Descendre d\'un cran vers le dernier plan',
          dwndwn: 'Mettre le/les flux sélectionné(s) au dernier plan',
          as: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) flux selectionné(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du flux. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le flux',
          ajust_label: 'Repositionne les labels de flux au dessus si les labels sont plus grand que l\'épaisseur des flux',
          inv: 'Inverse le sens du flux en inversant sa source et sa cible'
        },
        data: {
          edit_value: 'Éditer la valeur',
          données: 'Données',
          vpp: 'Valeur',
          data_type: 'Type de données',
          value_type: 'Type de données',
          ratio: 'Type de ratio',
          node_ref: 'Relatif à',
          dir: 'Flux pris en compte',
          value: 'Valeur',
          ratio_input: 'Ratio total entrées',
          ratio_output: 'Ratio total sorties',
          ratio_source_parent: 'Ratio flux parent(à gauche)',
          ratio_target_parent: 'Ratio flux parent(à droite)',
          unit_ratio: 'Coeff. conversion unités',
          value_target: 'Valeur dest.',
          tab_basic: 'Basique',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Incertitude',
          affichage: 'Label',
          tooltips: {
            data_type: 'Type de données',
            vpp: 'Valeur associée au flux sélectionné et, si existant(s), pour le/les tag(s) de flux selectionné(s)',
            scientificNotation: 'Activer ou non la notation en format scientifique, pour l\'affichage de la valeur du flux sur le diagramme de Sankey',
            affichage: 'Texte de remplacement de l\'affichage de la valeur du flux sur le diagramme de Sankey',
            value_target: 'Valeur à la destination pour les flux en forme de trapèze (laisser vide pour une épaisseur uniforme)',
            value: 'Valeur du flux. On peut aussi écrire « min » ou « max » : la réconciliation donne alors au flux la plus petite (resp. la plus grande) valeur compatible avec le reste du modèle, et le flux ressort déterminé.',
            data_min: 'Borne inférieure de la valeur du flux (utilisée pour la réconciliation)',
            data_max: 'Borne supérieure de la valeur du flux (utilisée pour la réconciliation)',
            uncertainty: 'Incertitude relative en % sur la valeur du flux (utilisée pour la réconciliation)',
            tab_basic_disabled: 'Sélectionnez "Valeur" comme type de données dans l\'onglet AFM pour activer ce panneau'
          }
        },
        apparence: {
          anchor: 'Ancres',
          handle: 'Poignées',
          curve_unit: 'Unité',
          apparence: 'Apparence',
          fond: 'Fond',
          couleur: 'Couleur',
          grad: 'Gradient',
          flow: 'Flux',
          color_source: 'Élement définissant la couleur du flux',
          source: 'Noeud source',
          target: 'Noeud cible',
          shape_is_dashed: 'Hachuré',
          shape_visible_when_zero: 'Afficher si nul',
          of: 'Orientation',
          type: 'Type',
          courbe: 'Courbe',
          fleche: 'Flèche',
          opacity: 'Opacité',
          arrow_size: 'Taille',
          shape_arrow_standalone: 'Pointe indépendante',
          shape_arrow_min_width: 'Largeur mini de pointe (px)',
          shape_structure_force_min: 'Nœud/flèche à la hauteur de la valeur',
          shape_uncertainty_display: 'Afficher l\'incertitude',
          display_link_lab: 'Afficher la valeur',
          hide_link_lab: 'Masquer la valeur',
          display_link_name: 'Afficher le texte',
          hide_link_name: 'Masquer le texte',
          data_off_scale: 'Échelle',
          scale_ref_thickness: 'Épaisseur max d\'échelle (px)',

          bezier_path: 'Simple',
          bezier_outline: 'Contour',
          bezier_outline_exact: 'Contour exact',
          tooltips: {
            couleur: 'Choisir la couleur pour le/les flux sélectionné(s)',
            color_source: {
              def: 'Choisir la règle qui définit la couleur du flux',
              flow: 'La couleur est définie par les paramètres du flux (couleur par défaut, couleur des étiquettes de flux ou des données)',
              source: 'La couleur est définie par la couleur du nœud source',
              target: 'La couleur est définie par la couleur du nœud cible',
              gradient: 'La couleur est un dégradé de la couleur du nœud source vers la couleur du nœud cible',
              auto: 'La couleur est déterminée automatiquement selon cet ordre de priorité :\n1. Tag couleur commun entre source et cible\n2. Un seul côté a un tag couleur → prendre ce côté\n3. Les deux ont des tags (pas de commun) → préférer le nœud produit\n4. Pas de tags couleur → préférer le nœud produit\n5. Par défaut : couleur source',
              disabled: 'La règle ne permet pas de modifier la couleur du flux'
            },
            grad: 'Applique un effet de gradient de couleur sur le/les flux sélectionné(s). Le gradient est réalisé entre la couleur du noeud de départ et celle du noeud d\'arrivée',
            shape_is_dashed: 'Applique un effet de hachure sur le/les flux sélectionné(s)',
            shape_visible_when_zero: 'Toujours afficher ce flux même si sa valeur est nulle (outrepasse le masquage des flux nuls, pour ce flux uniquement)',
            of_vv: 'Permet d\'orienter le début du flux verticalement et la fin du flux verticalement',
            of_hh: 'Permet d\'orienter le début du flux horizontalement et la fin du flux horizontalement',
            of_hv: 'Permet d\'orienter le début du flux horizontalement et la fin du flux verticalement',
            of_vh: 'Permet d\'orienter le début du flux verticalement et la fin du flux horizontalement',
            courbe: 'Représente le/les flux sélectionné(s) sous forme de courbe(s) de Bezier.',
            fleche: 'Représente le/les flux sélectionné(s) avec une pointe de flèche à la fin.',
            structure: 'Représente le/les flux sélectionné(s) comme si il n\'avait pas de valeur peu importe leur vraie valeur ',
            arrow_size: 'Modifie la taille de la flèche (largeur entre la fin du flux et le noeud',
            shape_arrow_standalone: 'Dessine la pointe de ce flux comme un triangle indépendant centré sur son extrémité réelle, au lieu de partager l\'éventail de pointes convergeant vers le côté du nœud.',
            shape_arrow_min_width: 'Largeur minimale (px) de la base de la pointe : les flux plus fins reçoivent une pointe de cette largeur (pour rester visibles), les flux plus épais ne changent pas. La profondeur de pointe (taille de flèche) est inchangée. 0 = désactivé.',
            shape_structure_force_min: 'Coché : en mode structure, ce flux garde sa hauteur de valeur sur le nœud et la flèche. Décoché (défaut) : le flux est réduit à un connecteur fin et n\'élargit pas le nœud ni la flèche.',
            shape_uncertainty_display: 'Superpose le flux tracé à ses valeurs min/moyenne/max (plus fin = plus opaque) pour visualiser l\'intervalle d\'incertitude.',
            data_off_scale: 'Définie une échelle local pour l\'épaisseur du flux, cela peut casser la cohérence du diagramme au niveau de la proportionalité entre la valeur des flux et leur épaisseur ',
            local_scale: 'Définissez un facteur d\'échelle local qui sera multiplié par le multiplicateur spécifié pour ce flux.',
            scale_ref_thickness: 'Épaisseur maximale (px) de ce flux pour le view tag courant : uniquement quand ce flux dépasserait cette épaisseur, l\'échelle du diagramme est recalculée pour qu\'il s\'y cale exactement ; tous les autres flux et la légende d\'échelle suivent. En dessous du seuil, rien ne change. 0 = désactivé. Un seul flux de référence par view tag.',
            ending_curve: 'Affine la position du point de fin de courbure pour le/les flux sélectionné(s). Cette valeur est un ratio (%) de la longueur du flux par rapport à son point de départ.',
            ending_tangeant: 'Règle le rayon de courbure à l\'arrivée lorsque le/les flux sélectionné(s) sont représentés en courbes de Bézier',
            starting_curve: 'Affine la position du point de départ de courbure pour le/les flux sélectionné(s). Cette valeur est un ratio (%) de la longueur du flux par rapport à son point de départ.',
            starting_tangeant: 'Règle le rayon de courbure au départ lorsque le/les flux sélectionné(s) sont représentés en courbes de Bézier'
          }
        },
        labels: {
          source: 'Noeud source',
          target: 'Noeud destination',
          percent: '%',
          intervals: 'Intervalles',
          ratio: 'Ratio',
          label: 'Label',
          vdb: 'Valeur',
          len: 'Label en noir',
          lec: 'Label en couleur',
          milieu: 'Milieu',
          deb: 'Début',
          fin: 'Fin',
          dessous: 'Dessous',
          dessus: 'Dessus',
          pls: 'Positionnement manuel du label',
          scientificNotation: 'Notation scientifique',
          significantDigits: 'Chiffres significatifs',
          NbDigit: 'Nombre maximum de décimales',
          unit_name: 'Unité personnalisée',
          unit_model: 'Unité du diagramme',
          value: 'Valeur',
          '%IS': '% de flux en entrées du noeud source',
          '%ID': '% de flux en entrées du noeud destination',
          '%OS': '% de flux en sorties du noeud source',
          '%OD': '% de flux en sorties du noeud destination',
          '%PS': '% du total du nœud amont (source)',
          '%PD': '% du total du nœud aval (destination)',
          '%SS': '% du stock du noeud source (en sortie)',
          '%SD': '% du stock du noeud destination (en entrée)',
          unit_ratio: 'Ratio d\'unité',
          unit_tag: 'Unité naturelle d\'origine',
          other_unit_tag: 'Autres unités naturelles',
          normalized: 'Normalisé (flux réf.)',
          unit_factor: 'Facteur d\'unité',
          labels: 'Nom',
          node_value: 'Valeur',
          name_label_is_visible: 'Label',
          name_label_text_source: 'Contenu du label',
          name_label_template: 'Gabarit',
          name_label_tag_group: 'Groupe de tags',
          text_source: {
            custom: 'Texte personnalisé',
            template: 'Gabarit à jetons',
            none: 'Aucun',
            source: 'Nœud source',
            target: 'Nœud destination',
            source_target: 'Source → destination',
            tag: 'Tag de flux',
          },
          lb: 'Blanc',
          pos: 'Position',
          pos_v: 'Position de la valeur',
          tp: 'Taille de police',
          tooltips: {
            name_label_text_source: 'Choisir ce qu\'affiche le label du flux : texte saisi, rien, nom du nœud source/destination, ou source → destination',
            name_label_template: 'Texte construit avec des jetons remplacés au dessin, ex. « {EntryName} : {Value} {Unit} »',
            label: 'Permet d\'afficher ou non le label (donnée / texte) associé au(x) flux sélectionné(s)',
            len: 'Afficher le texte du label en noir, pour le(s) flux sélectionné(s)',
            lb: 'Afficher le texte du label en blanc, pour le(s) flux sélectionné(s)',
            lec: 'Afficher le texte du label avec la/les même(s) couleur(s) que celle(s) associée(s) au(x) flux sélectionné(s)',
            deb: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point de départ du flux',
            milieu_h: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label entre le point de départ et le point d\'arrivée du flux',
            fin: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point d\'arrivée du flux',
            dessous: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label en dessous du flux',
            milieu_v: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label dans le flux',
            dessus: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label au dessus du flux',
            pls: 'La combinaison Alt/click gauche déplace le label du/des flux sélectionné(s)',
            value: 'Valeur',
            '%IS': '% de flux en entrées du noeud source',
            '%ID': '% de flux en entrées du noeud destination',
            '%OS': '% de flux en sorties du noeud source',
            '%OD': '% de flux en sorties du noeud destination',
            '%PS': 'Valeur affichée en % du débit total du nœud amont (source) : max(entrées, sorties)',
            '%PD': 'Valeur affichée en % du débit total du nœud aval (destination) : max(entrées, sorties)',
            '%SS': '% du stock du noeud source (en sortie)',
            '%SD': '% du stock du noeud destination (en entrée)',
            below: 'Pour le/les flux sélectionné(s), positionne le label en dessous du flux',
            end: 'Pour le/les flux sélectionné(s), positionne le label vers le point d\'arrivée du flux',
            l_u: 'Choisir le nom de l\'unité',
            l_u_v: 'Afficher l\'unité des flux',
            top: 'Pour le/les flux sélectionné(s), positionne le label au dessus du flux',
            unit_factor: 'Facteur de conversion pour l\'unité du flux',
          },
          l_u: 'Nom de l\'unité',
          l_u_v: 'Unité'
        },
        layout: 'Organiser',
        layoutUp: 'Avancer',
        layoutTop: 'Premier plan',
        layoutDown: 'Reculer',
        layoutBottom: 'Dernier plan',
      }
    }
  },
  es: {
    translation: {
      Flux: {
        pg: 'Parámetros generales',
        pdl: 'Fuente',
        pl: 'Parámetros por flujo',
        src: 'Origen',
        trgt: 'Destino',
        value: 'Valor',
        calculated_value: 'Val. Calc.',
        type: 'Formato',
        if: 'Invertir dirección',
        dzf: 'Orden de superposición',
        style: 'Estilo',
        as: 'Aplicar el estilo a los flujos seleccionados',
        IB: 'Tooltip',
        IS: 'Info. adicional',
        ajust_label: 'Ajustar posición de etiquetas',
        FS: 'Flujo',
        local_scale: 'Escala local del flujo',
        changePlan: 'Cambiar plano de los flujos',
        mask_attr: 'Cambiar atributos de flujos',
        tooltips: {
          src: 'Elección del nodo de origen para el/los flujo(s) seleccionado(s)',
          trgt: 'Elección del nodo de destino para el/los flujo(s) seleccionado(s)',
          if: 'Invertir los nodos de origen y destino para el/los flujo(s) seleccionado(s)',
          up: 'Subir un nivel hacia el primer plano',
          upup: 'Poner el/los flujo(s) seleccionado(s) en primer plano',
          dwn: 'Bajar un nivel hacia el último plano',
          dwndwn: 'Poner el/los flujo(s) seleccionado(s) en último plano',
          as: 'Permite aplicar un estilo predefinido del menú de preferencias a los flujos seleccionados',
          IB: 'Tooltip: texto formateado en HTML que se muestra con el tooltip del flujo. Este tooltip aparece en el espacio gráfico con SHIFT + RATÓN sobre el flujo.',
          ajust_label: 'Reposiciona las etiquetas de los flujos encima si son más altas que el grosor del flujo',
          inv: 'Invierte la dirección del flujo intercambiando origen y destino'
        },
        data: {
          données: 'Datos',
          vpp: 'Valor',
          data_type: 'Tipo de datos',
          value: 'Valor',
          ratio_input: 'Ratio total entradas',
          ratio_output: 'Ratio total salidas',
          ratio_source_parent: 'Ratio flujo padre (izquierda)',
          ratio_target_parent: 'Ratio flujo padre (derecha)',
          unit_ratio: 'Coef. conversión de unidades',
          edit_value: 'Editar valor',
          value_target: 'Valor dest.',
          tab_basic: 'Básico',
          tab_afm: 'AFM',
          data_min: 'Mín',
          data_max: 'Máx',
          uncertainty: 'Incertidumbre',
          affichage: 'Etiqueta',
          tooltips: {
            data_type: 'Tipo de datos',
            vpp: 'Valor asociado al flujo seleccionado y, si existen, para el/los tag(s) seleccionado(s)',
            scientificNotation: 'Activar o no la notación en formato científico para la visualización del valor del flujo en el diagrama Sankey',
            affichage: 'Texto de sustitución para la visualización del valor del flujo en el diagrama Sankey',
            value_target: 'Valor en el destino para flujos en forma de trapecio (dejar vacío para grosor uniforme)',
            value: 'Valor del flujo. También se puede escribir «min» o «max»: la reconciliación da entonces al flujo el valor más pequeño (resp. el mayor) compatible con el resto del modelo, y el flujo queda determinado.',
            data_min: 'Límite inferior del valor del flujo (usado para reconciliación)',
            data_max: 'Límite superior del valor del flujo (usado para reconciliación)',
            uncertainty: 'Incertidumbre relativa en % sobre el valor del flujo (usada para reconciliación)',
            tab_basic_disabled: 'Seleccione "Valor" como tipo de datos en la pestaña AFM para activar este panel'
          },
          dir: 'Flujos considerados',
          node_ref: 'Relativo a',
          ratio: 'Tipo de ratio',
          value_type: 'Tipo de datos'
        },
        apparence: {
          anchor: 'Anclas',
          handle: 'Tiradores',
          curve_unit: 'Unidad',
          apparence: 'Apariencia',
          flow: 'Flujo',
          fond: 'Fondo de forma',
          source: 'Nodo origen',
          target: 'Nodo destino',
          couleur: 'Color',
          color_source: 'Elemento que define el color del flujo',
          grad: 'Gradiente',
          shape_is_dashed: 'Discontinuo',
          shape_visible_when_zero: 'Mostrar si es nulo',
          of: 'Orientación',
          type: 'Tipo',
          courbe: 'Curva',
          fleche: 'Flecha',
          opacity: 'Opacidad',
          arrow_size: 'Tamaño de la flecha',
          shape_arrow_standalone: 'Punta independiente',
          shape_arrow_min_width: 'Ancho mín. de punta (px)',
          shape_structure_force_min: 'Nodo/flecha a la altura del valor',
          shape_uncertainty_display: 'Mostrar incertidumbre',
          display_link_lab: 'Mostrar valor',
          hide_link_lab: 'Ocultar valor',
          display_link_name: 'Mostrar nombre',
          hide_link_name: 'Ocultar nombre',
          data_off_scale: 'Escala',
          scale_ref_thickness: 'Grosor máx. de escala (px)',
          bezier_path: 'Simple',
          bezier_outline: 'Contorno',
          bezier_outline_exact: 'Contorno exacto',
          tooltips: {
            color_source: {
              def: 'Elegir la regla que define el color del flujo:',
              flow: 'El color se define por los parámetros del flujo (color por defecto, color de etiquetas de flujo o de datos)',
              source: 'El color se define por el color del nodo origen',
              target: 'El color se define por el color del nodo destino',
              gradient: 'El color es un degradado del color del nodo origen al color del nodo destino',
              auto: 'El color se determina automáticamente según esta prioridad:\n1. Tag de color común entre origen y destino\n2. Solo un lado tiene tag de color → tomar ese lado\n3. Ambos tienen tags (sin común) → preferir el nodo producto\n4. Sin tags de color → preferir el nodo producto\n5. Por defecto: color del origen',
              disabled: 'La regla no permite elegir el color del flujo'
            },
            couleur: 'Elegir el color para el/los flujo(s) seleccionado(s)',
            grad: 'Aplica un efecto de gradiente de color en el/los flujo(s) seleccionado(s). El gradiente se realiza entre el color del nodo de inicio y el del nodo de fin',
            shape_is_dashed: 'Aplica un efecto de trazo discontinuo en el/los flujo(s) seleccionado(s)',
            shape_visible_when_zero: 'Mostrar siempre este flujo aunque su valor sea cero (anula el filtrado de flujos nulos solo para este flujo)',
            of_vv: 'Permite orientar el inicio del flujo verticalmente y el final del flujo verticalmente',
            of_hh: 'Permite orientar el inicio del flujo horizontalmente y el final del flujo horizontalmente',
            of_hv: 'Permite orientar el inicio del flujo horizontalmente y el final del flujo verticalmente',
            of_vh: 'Permite orientar el inicio del flujo verticalmente y el final del flujo horizontalmente',
            courbe: 'Representa el/los flujo(s) seleccionado(s) como curva(s) de Bezier',
            fleche: 'Representa el/los flujo(s) seleccionado(s) con una punta de flecha al final',
            structure: 'Representa el/los flujo(s) seleccionado(s) como si no tuvieran valor, sin importar su valor real',
            starting_curve: 'Permite ajustar la posición del punto de inicio de curvatura para el/los flujo(s) seleccionado(s). Este valor es un ratio (%) de la longitud del flujo relativo al punto de inicio.',
            ending_curve: 'Permite ajustar la posición del punto de fin de curvatura para el/los flujo(s) seleccionado(s). Este valor es un ratio (%) de la longitud del flujo relativo al punto de inicio.',
            starting_tangeant: 'Configuración del radio de curvatura inicial en caso de que el/los flujo(s) seleccionado(s) se representen como curva(s) de Bezier',
            ending_tangeant: 'Configuración del radio de curvatura final en caso de que el/los flujo(s) seleccionado(s) se representen como curva(s) de Bezier',
            arrow_size: 'Cambiar el tamaño de la flecha (desde el final del flujo hasta el nodo)',
            shape_arrow_standalone: 'Dibuja la flecha de este flujo como un triángulo independiente centrado en su extremo real, en lugar de compartir el abanico de flechas que convergen en el lado del nodo.',
            shape_arrow_min_width: 'Ancho mínimo (px) de la base de la punta: los flujos más finos reciben una punta de este ancho (para seguir visibles), los más gruesos no cambian. La profundidad de la punta no cambia. 0 = desactivado.',
            shape_structure_force_min: 'Marcado: en modo estructura, este flujo conserva su altura de valor en el nodo y la flecha. Sin marcar (predeterminado): el flujo se reduce a un conector fino y no agranda el nodo ni la flecha.',
            shape_uncertainty_display: 'Superpone el flujo dibujado en sus valores mín/media/máx (más fino = más opaco) para visualizar el intervalo de incertidumbre.',
            data_off_scale: 'Define una escala local para el grosor del flujo, lo que puede romper la coherencia de proporcionalidad entre el valor y el grosor',
            local_scale: 'Define un factor de escala local que se multiplicará por el multiplicador especificado para este flujo.',
            scale_ref_thickness: 'Grosor máximo (px) de este flujo para la etiqueta de vista actual: solo cuando este flujo superaría este grosor, la escala del diagrama se recalcula para ajustarlo exactamente a este valor; los demás flujos y la leyenda de escala se ajustan. Por debajo del umbral, no cambia nada. 0 = desactivado. Un flujo de referencia por etiqueta de vista.'
          }
        },
        labels: {
          value: 'Valor',
          intervals: 'Intervalos',
          percent: '%',
          ratio: 'Ratio',
          label: 'Etiqueta',
          vdb: 'Valor de etiqueta',
          len: 'Etiqueta negra',
          lb: 'Etiqueta blanca',
          lec: 'Etiqueta coloreada',
          pos: 'Posición',
          milieu: 'Centro',
          deb: 'Inicio',
          fin: 'Fin',
          dessous: 'Encima',
          dessus: 'Debajo',
          pls: 'Posicionamiento manual de la etiqueta',
          l_u_v: 'Unidad',
          l_u: 'Nombre de la unidad',
          tooltips: {
            label: 'Mostrar u ocultar la etiqueta (dato / texto) asociada al/a los flujo(s) seleccionado(s)',
            len: 'Mostrar la etiqueta en negro para el/los flujo(s) seleccionado(s)',
            lb: 'Mostrar la etiqueta en blanco para el/los flujo(s) seleccionado(s)',
            lec: 'Mostrar la etiqueta con el/los mismo(s) color(es) que el/los asociado(s) al/a los flujo(s) seleccionado(s)',
            deb: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta hacia el punto de inicio del flujo',
            milieu_h: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta entre el punto de inicio y el punto final del flujo',
            end: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta hacia el punto final del flujo',
            below: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta debajo del flujo',
            milieu_v: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta dentro del flujo',
            top: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta encima del flujo',
            pls: 'La combinación Alt/clic izquierdo mueve la etiqueta del/de los flujo(s) seleccionado(s)',
            l_u_v: 'Mostrar la unidad de los flujos',
            l_u: 'Elegir el nombre de la unidad',
            unit_factor: 'Factor de conversión para la unidad del flujo',
            '%ID': '% de los flujos entrantes del nodo destino',
            '%IS': '% de los flujos entrantes del nodo origen',
            '%OD': '% de los flujos salientes del nodo destino',
            '%OS': '% de los flujos salientes del nodo origen',
            '%PD': 'Valor mostrado como % del caudal total del nodo aguas abajo (destino): max(entradas, salidas)',
            '%PS': 'Valor mostrado como % del caudal total del nodo aguas arriba (origen): max(entradas, salidas)',
            '%SD': '% del stock del nodo destino (entrada)',
            '%SS': '% del stock del nodo origen (salida)',
            dessous: 'Para el/los flujo(s) seleccionado(s), coloca el texto de la etiqueta debajo del flujo',
            dessus: 'Para el/los flujo(s) seleccionado(s), coloca el texto de la etiqueta encima del flujo',
            fin: 'Para el/los flujo(s) seleccionado(s), coloca el texto de la etiqueta cerca del punto de llegada del flujo',
            name_label_text_source: 'Elegir qué muestra la etiqueta del flujo: texto introducido, nada, nombre del nodo origen/destino, u origen → destino',
            name_label_template: 'Texto construido con marcadores sustituidos al dibujar, p. ej. «{EntryName}: {Value} {Unit}»',
            value: 'Valor'
          },
          '%ID': '% de los flujos entrantes del nodo destino',
          '%IS': '% de los flujos entrantes del nodo origen',
          '%OD': '% de los flujos salientes del nodo destino',
          '%OS': '% de los flujos salientes del nodo origen',
          '%PD': '% del total del nodo aguas abajo (destino)',
          '%PS': '% del total del nodo aguas arriba (origen)',
          '%SD': '% del stock del nodo destino (entrada)',
          '%SS': '% del stock del nodo origen (salida)',
          NbDigit: 'Número máximo de decimales',
          labels: 'Nombre',
          name_label_is_visible: 'Etiqueta',
          name_label_tag_group: 'Grupo de etiquetas',
          name_label_text_source: 'Contenido de la etiqueta',
          name_label_template: 'Plantilla',
          node_value: 'Valor',
          normalized: 'Normalizado (flujo ref.)',
          other_unit_tag: 'Otras unidades nativas',
          pos_v: 'Posición del valor',
          scientificNotation: 'Notación científica',
          significantDigits: 'Cifras significativas',
          source: 'Nodo origen',
          target: 'Nodo destino',
          text_source: {
            custom: 'Texto personalizado',
            template: 'Plantilla con marcadores',
            none: 'Ninguno',
            source: 'Nodo origen',
            source_target: 'Origen → destino',
            tag: 'Etiqueta de flujo',
            target: 'Nodo destino'
          },
          tp: 'Tamaño de fuente',
          unit_factor: 'Factor de unidad',
          unit_model: 'Unidad del diagrama',
          unit_name: 'Unidad personalizada',
          unit_ratio: 'Ratio de unidad',
          unit_tag: 'Unidad nativa de origen'
        },
        layout: 'Disposición',
        layoutUp: 'Avanzar',
        layoutTop: 'Primer plano',
        layoutDown: 'Retroceder',
        layoutBottom: 'Último plano',
      }
    }
  },
  de: {
    translation: {
      Flux: {
        pg: 'Allgemeine Einstellungen',
        pdl: 'Schriftart',
        pl: 'Parameter pro Fluss',
        src: 'Ursprung',
        trgt: 'Ziel',
        value: 'Wert',
        calculated_value: 'Ber. Wert',
        type: 'Format',
        if: 'Richtung umkehren',
        dzf: 'Überlagerungsreihenfolge',
        style: 'Stil',
        as: 'Stil auf ausgewählte Flüsse anwenden',
        IB: 'Tooltip',
        IS: 'Zusatzinfo',
        ajust_label: 'Beschriftungspositionen anpassen',
        FS: 'Fluss',
        local_scale: 'Lokale Flussskalierung',
        changePlan: 'Ebene der Flüsse ändern',
        mask_attr: 'Flussattribute ändern',
        tooltips: {
          src: 'Wahl des Ausgangsknotens für den/die ausgewählten Fluss/Flüsse',
          trgt: 'Wahl des Zielknotens für den/die ausgewählten Fluss/Flüsse',
          if: 'Ausgangs- und Zielknoten für den/die ausgewählten Fluss/Flüsse umkehren',
          up: 'Eine Ebene nach vorne bringen',
          upup: 'Ausgewählte(n) Fluss/Flüsse in den Vordergrund bringen',
          dwn: 'Eine Ebene nach hinten bringen',
          dwndwn: 'Ausgewählte(n) Fluss/Flüsse in den Hintergrund bringen',
          as: 'Ermöglicht das Anwenden eines vordefinierten Stils aus dem Einstellungsmenü auf die ausgewählten Flüsse',
          IB: 'Tooltip: HTML-formatierter Text, der mit dem Tooltip des Flusses angezeigt wird. Dieser Tooltip erscheint im Grafikbereich mit SHIFT + MAUS auf dem Fluss.',
          ajust_label: 'Repositioniert die Flussbeschriftungen oberhalb der Flüsse, wenn die Beschriftungen größer als die Flussstärke sind',
          inv: 'Kehrt die Richtung des Flusses um, indem Quelle und Ziel vertauscht werden'
        },
        data: {
          données: 'Daten',
          vpp: 'Wert',
          data_type: 'Datentyp',
          value: 'Wert',
          ratio_input: 'Ratio Gesamteingänge',
          ratio_output: 'Ratio Gesamtausgänge',
          ratio_source_parent: 'Ratio Elternfluss (links)',
          ratio_target_parent: 'Ratio Elternfluss (rechts)',
          unit_ratio: 'Koeff. Einheitenumrechnung',
          edit_value: 'Wert bearbeiten',
          value_target: 'Zielwert',
          tab_basic: 'Basis',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Unsicherheit',
          affichage: 'Beschriftung',
          tooltips: {
            data_type: 'Datentyp',
            vpp: 'Dem ausgewählten Fluss zugeordneter Wert und, falls vorhanden, für den/die ausgewählten Tag(s)',
            scientificNotation: 'Wissenschaftliche Notation für die Anzeige des Flusswerts im Sankey-Diagramm aktivieren oder nicht',
            affichage: 'Ersatztext für die Anzeige des Flusswerts im Sankey-Diagramm',
            value_target: 'Zielwert für trapezförmige Flüsse (leer lassen für gleichmäßige Dicke)',
            value: 'Flusswert. Man kann auch „min“ oder „max“ schreiben: der Abgleich gibt dem Fluss dann den kleinsten (bzw. größten) Wert, der mit dem übrigen Modell vereinbar ist, und der Fluss wird bestimmt.',
            data_min: 'Untergrenze des Flusswerts (für Abgleich verwendet)',
            data_max: 'Obergrenze des Flusswerts (für Abgleich verwendet)',
            uncertainty: 'Relative Unsicherheit in % des Flusswerts (für Abgleich verwendet)',
            tab_basic_disabled: 'Wählen Sie "Wert" als Datentyp im AFM-Tab, um dieses Panel zu aktivieren'
          },
          dir: 'Berücksichtigte Flüsse',
          node_ref: 'Relativ zu',
          ratio: 'Verhältnistyp',
          value_type: 'Datentyp'
        },
        apparence: {
          anchor: 'Anker',
          handle: 'Griffe',
          curve_unit: 'Einheit',
          apparence: 'Darstellung',
          flow: 'Fluss',
          fond: 'Formhintergrund',
          source: 'Quellknoten',
          target: 'Zielknoten',
          couleur: 'Farbe',
          color_source: 'Element, das die Flussfarbe definiert',
          grad: 'Farbverlauf',
          shape_is_dashed: 'Gestrichelt',
          shape_visible_when_zero: 'Anzeigen wenn null',
          of: 'Orientierung',
          type: 'Typ',
          courbe: 'Kurve',
          fleche: 'Pfeil',
          opacity: 'Deckkraft',
          arrow_size: 'Pfeilgröße',
          shape_arrow_standalone: 'Eigenständige Spitze',
          shape_arrow_min_width: 'Mindest-Spitzenbreite (px)',
          shape_structure_force_min: 'Knoten/Pfeil auf Werthöhe',
          shape_uncertainty_display: 'Unsicherheit anzeigen',
          display_link_lab: 'Wert anzeigen',
          hide_link_lab: 'Wert ausblenden',
          display_link_name: 'Name anzeigen',
          hide_link_name: 'Name ausblenden',
          data_off_scale: 'Skalierung',
          scale_ref_thickness: 'Max. Skalendicke (px)',
          bezier_path: 'Einfach',
          bezier_outline: 'Kontur',
          bezier_outline_exact: 'Exakte Kontur',
          tooltips: {
            color_source: {
              def: 'Wählen Sie die Regel, die die Flussfarbe definiert:',
              flow: 'Die Farbe wird durch die Flussparameter definiert (Standardfarbe, Fluss-Tag-Farbe oder Daten-Tag-Farbe)',
              source: 'Die Farbe wird durch die Farbe des Quellknotens definiert',
              target: 'Die Farbe wird durch die Farbe des Zielknotens definiert',
              gradient: 'Die Farbe ist ein Farbverlauf von der Quellknotenfarbe zur Zielknotenfarbe',
              auto: 'Die Farbe wird automatisch nach dieser Priorität bestimmt:\n1. Gemeinsamer Farb-Tag zwischen Quelle und Ziel\n2. Nur eine Seite hat einen Farb-Tag → diese Seite nehmen\n3. Beide haben Tags (kein gemeinsamer) → Produktknoten bevorzugen\n4. Keine Farb-Tags → Produktknoten bevorzugen\n5. Standard: Quellfarbe',
              disabled: 'Die Regel erlaubt keine Auswahl der Flussfarbe'
            },
            couleur: 'Farbe für den/die ausgewählten Fluss/Flüsse wählen',
            grad: 'Wendet einen Farbverlaufseffekt auf den/die ausgewählten Fluss/Flüsse an. Der Verlauf erfolgt zwischen der Farbe des Startknotens und der des Endknotens',
            shape_is_dashed: 'Wendet einen Stricheleffekt auf den/die ausgewählten Fluss/Flüsse an',
            shape_visible_when_zero: 'Diesen Fluss immer anzeigen, auch wenn sein Wert null ist (überschreibt die Nullfluss-Filterung nur für diesen Fluss)',
            of_vv: 'Ermöglicht es, den Anfang des Flusses vertikal und das Ende vertikal auszurichten',
            of_hh: 'Ermöglicht es, den Anfang des Flusses horizontal und das Ende horizontal auszurichten',
            of_hv: 'Ermöglicht es, den Anfang des Flusses horizontal und das Ende vertikal auszurichten',
            of_vh: 'Ermöglicht es, den Anfang des Flusses vertikal und das Ende horizontal auszurichten',
            courbe: 'Stellt den/die ausgewählten Fluss/Flüsse als Bezier-Kurve(n) dar',
            fleche: 'Stellt den/die ausgewählten Fluss/Flüsse mit einer Pfeilspitze am Ende dar',
            structure: 'Stellt den/die ausgewählten Fluss/Flüsse so dar, als hätten sie keinen Wert, unabhängig von ihrem tatsächlichen Wert',
            starting_curve: 'Ermöglicht die Feineinstellung der Position des Krümmungsanfangspunkts für den/die ausgewählten Fluss/Flüsse. Dieser Wert ist ein Verhältnis (%) der Flusslänge relativ zum Startpunkt.',
            ending_curve: 'Ermöglicht die Feineinstellung der Position des Krümmungsendpunkts für den/die ausgewählten Fluss/Flüsse. Dieser Wert ist ein Verhältnis (%) der Flusslänge relativ zum Startpunkt.',
            starting_tangeant: 'Einstellung des Anfangskrümmungsradius, falls der/die ausgewählte(n) Fluss/Flüsse als Bezier-Kurve(n) dargestellt werden',
            ending_tangeant: 'Einstellung des Endkrümmungsradius, falls der/die ausgewählte(n) Fluss/Flüsse als Bezier-Kurve(n) dargestellt werden',
            arrow_size: 'Größe des Pfeils ändern (vom Ende des Flusses zum Knoten)',
            shape_arrow_standalone: 'Zeichnet die Pfeilspitze dieses Flusses als eigenständiges Dreieck, zentriert auf sein echtes Ende, statt den am Knoten zusammenlaufenden Pfeilfächer zu teilen.',
            shape_arrow_min_width: 'Mindestbreite (px) der Pfeilspitzenbasis: dünnere Flüsse erhalten eine Spitze dieser Breite (bleiben sichtbar), dickere Flüsse bleiben unverändert. Die Spitzentiefe bleibt unverändert. 0 = deaktiviert.',
            shape_structure_force_min: 'Angehakt: Im Strukturmodus behält dieser Fluss seine Werthöhe an Knoten und Pfeil. Nicht angehakt (Standard): Der Fluss wird auf einen dünnen Verbinder reduziert und vergrößert Knoten und Pfeil nicht.',
            shape_uncertainty_display: 'Überlagert den Fluss, gezeichnet an seinen Min-/Mittel-/Max-Werten (dünner = undurchsichtiger), um das Unsicherheitsintervall zu visualisieren.',
            data_off_scale: 'Definiert eine lokale Skalierung für die Flussdicke, was die Proportionalitätskohärenz zwischen Wert und Dicke brechen kann',
            local_scale: 'Definieren Sie einen lokalen Skalierungsfaktor, der mit dem für diesen Fluss angegebenen Multiplikator multipliziert wird.',
            scale_ref_thickness: 'Maximale Dicke (px) dieses Flusses für das aktuelle View-Tag: Nur wenn dieser Fluss diese Dicke überschreiten würde, wird der Diagramm-Maßstab so neu berechnet, dass er genau diesen Wert erreicht; alle anderen Flüsse und die Skalenlegende folgen. Unterhalb des Schwellenwerts ändert sich nichts. 0 = deaktiviert. Ein Referenzfluss pro View-Tag.'
          }
        },
        labels: {
          value: 'Wert',
          intervals: 'Intervalle',
          percent: '%',
          ratio: 'Verhältnis',
          label: 'Beschriftung',
          vdb: 'Beschriftungswert',
          len: 'Schwarze Beschriftung',
          lb: 'Weiße Beschriftung',
          lec: 'Farbige Beschriftung',
          pos: 'Position',
          milieu: 'Mitte',
          deb: 'Anfang',
          fin: 'Ende',
          dessous: 'Darüber',
          dessus: 'Darunter',
          pls: 'Manuelle Positionierung der Beschriftung',
          l_u_v: 'Einheit',
          l_u: 'Einheitenname',
          tooltips: {
            label: 'Beschriftung (Daten / Text) des/der ausgewählten Flusses/Flüsse anzeigen oder ausblenden',
            len: 'Beschriftung in Schwarz für den/die ausgewählten Fluss/Flüsse anzeigen',
            lb: 'Beschriftung in Weiß für den/die ausgewählten Fluss/Flüsse anzeigen',
            lec: 'Beschriftung mit der/den gleichen Farbe(n) wie der/die ausgewählte(n) Fluss/Flüsse anzeigen',
            deb: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zum Startpunkt des Flusses positionieren',
            milieu_h: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zwischen Start- und Endpunkt des Flusses positionieren',
            end: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zum Endpunkt des Flusses positionieren',
            below: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung unterhalb des Flusses positionieren',
            milieu_v: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung innerhalb des Flusses positionieren',
            top: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung oberhalb des Flusses positionieren',
            pls: 'Die Kombination Alt/Linksklick verschiebt die Beschriftung des/der ausgewählten Flusses/Flüsse',
            l_u_v: 'Einheit der Flüsse anzeigen',
            l_u: 'Name der Einheit wählen',
            unit_factor: 'Umrechnungsfaktor für die Flusseinheit',
            '%ID': '% der Eingangsflüsse des Zielknotens',
            '%IS': '% der Eingangsflüsse des Quellknotens',
            '%OD': '% der Ausgangsflüsse des Zielknotens',
            '%OS': '% der Ausgangsflüsse des Quellknotens',
            '%PD': 'Wert in % des Gesamtdurchsatzes des nachgelagerten Knotens (Ziel): max(Eingänge, Ausgänge)',
            '%PS': 'Wert in % des Gesamtdurchsatzes des vorgelagerten Knotens (Quelle): max(Eingänge, Ausgänge)',
            '%SD': '% des Bestands des Zielknotens (Eingang)',
            '%SS': '% des Bestands des Quellknotens (Ausgang)',
            dessous: 'Für die ausgewählten Flüsse: Beschriftungstext unterhalb des Flusses platzieren',
            dessus: 'Für die ausgewählten Flüsse: Beschriftungstext oberhalb des Flusses platzieren',
            fin: 'Für die ausgewählten Flüsse: Beschriftungstext am Endpunkt des Flusses platzieren',
            name_label_text_source: 'Wählen, was die Flussbeschriftung anzeigt: eingegebener Text, nichts, Name des Quell-/Zielknotens oder Quelle → Ziel',
            name_label_template: 'Text aus Platzhaltern, die beim Zeichnen ersetzt werden, z. B. „{EntryName}: {Value} {Unit}“',
            value: 'Wert'
          },
          '%ID': '% der Eingangsflüsse des Zielknotens',
          '%IS': '% der Eingangsflüsse des Quellknotens',
          '%OD': '% der Ausgangsflüsse des Zielknotens',
          '%OS': '% der Ausgangsflüsse des Quellknotens',
          '%PD': '% der Gesamtmenge des nachgelagerten Knotens (Ziel)',
          '%PS': '% der Gesamtmenge des vorgelagerten Knotens (Quelle)',
          '%SD': '% des Bestands des Zielknotens (Eingang)',
          '%SS': '% des Bestands des Quellknotens (Ausgang)',
          NbDigit: 'Maximale Anzahl Dezimalstellen',
          labels: 'Name',
          name_label_is_visible: 'Beschriftung',
          name_label_tag_group: 'Tag-Gruppe',
          name_label_text_source: 'Inhalt der Beschriftung',
          name_label_template: 'Vorlage',
          node_value: 'Wert',
          normalized: 'Normiert (Referenzfluss)',
          other_unit_tag: 'Weitere native Einheiten',
          pos_v: 'Position des Werts',
          scientificNotation: 'Wissenschaftliche Notation',
          significantDigits: 'Signifikante Stellen',
          source: 'Quellknoten',
          target: 'Zielknoten',
          text_source: {
            custom: 'Benutzerdefinierter Text',
            template: 'Vorlage mit Platzhaltern',
            none: 'Keine',
            source: 'Quellknoten',
            source_target: 'Quelle → Ziel',
            tag: 'Fluss-Tag',
            target: 'Zielknoten'
          },
          tp: 'Schriftgröße',
          unit_factor: 'Einheitenfaktor',
          unit_model: 'Einheit aus den Diagrammeinheiten',
          unit_name: 'Benutzerdefinierte Einheit',
          unit_ratio: 'Einheitenverhältnis',
          unit_tag: 'Native Ursprungseinheit'
        },
        layout: 'Anordnung',
        layoutUp: 'Vorwärts',
        layoutTop: 'Ganz nach vorne',
        layoutDown: 'Rückwärts',
        layoutBottom: 'Ganz nach hinten',
      }
    }
  },
  it: {
    translation: {
      Flux: {
        pg: 'Impostazioni generali',
        pdl: 'Carattere',
        pl: 'Parametri per flusso',
        src: 'Origine',
        trgt: 'Destinazione',
        value: 'Valore',
        calculated_value: 'Val. Calc.',
        type: 'Formato',
        if: 'Inverti direzione',
        dzf: 'Ordine di sovrapposizione',
        style: 'Stile',
        as: 'Applicare lo stile ai flussi selezionati',
        IB: 'Tooltip',
        IS: 'Info aggiuntive',
        ajust_label: 'Regola posizione etichette',
        FS: 'Flusso',
        local_scale: 'Scala locale del flusso',
        changePlan: 'Cambia piano dei flussi',
        mask_attr: 'Modifica attributi dei flussi',
        tooltips: {
          src: 'Scelta del nodo di partenza per il/i flusso/i selezionato/i',
          trgt: 'Scelta del nodo di arrivo per il/i flusso/i selezionato/i',
          if: 'Inverte i nodi di partenza e di arrivo per il/i flusso/i selezionato/i',
          up: 'Porta avanti di un livello',
          upup: 'Porta il/i flusso/i selezionato/i in primo piano',
          dwn: 'Porta indietro di un livello',
          dwndwn: 'Porta il/i flusso/i selezionato/i in ultimo piano',
          as: 'Permette di applicare uno stile predefinito dal menu preferenze ai flussi selezionati',
          IB: 'Tooltip: testo formattato in HTML visualizzato con il tooltip del flusso. Questo tooltip appare nello spazio grafico con SHIFT + MOUSE sul flusso.',
          ajust_label: 'Riposiziona le etichette dei flussi sopra se le etichette sono più grandi dello spessore del flusso',
          inv: 'Inverte la direzione del flusso scambiando origine e destinazione'
        },
        data: {
          données: 'Dati',
          vpp: 'Valore',
          data_type: 'Tipo di dati',
          value: 'Valore',
          ratio_input: 'Rapporto totale ingressi',
          ratio_output: 'Rapporto totale uscite',
          ratio_source_parent: 'Rapporto flusso padre (sinistra)',
          ratio_target_parent: 'Rapporto flusso padre (destra)',
          unit_ratio: 'Coeff. conversione unità',
          edit_value: 'Modifica valore',
          value_target: 'Valore dest.',
          tab_basic: 'Base',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Incertezza',
          affichage: 'Etichetta',
          tooltips: {
            data_type: 'Tipo di dati',
            vpp: 'Valore associato al flusso selezionato e, se esistenti, per il/i tag selezionato/i',
            scientificNotation: 'Attivare o meno la notazione in formato scientifico per la visualizzazione del valore del flusso nel diagramma Sankey',
            affichage: 'Testo sostitutivo per la visualizzazione del valore del flusso nel diagramma Sankey',
            value_target: 'Valore alla destinazione per flussi a forma di trapezio (lasciare vuoto per spessore uniforme)',
            value: 'Valore del flusso. Si può anche scrivere «min» o «max»: la riconciliazione assegna allora al flusso il valore più piccolo (risp. più grande) compatibile con il resto del modello, e il flusso risulta determinato.',
            data_min: 'Limite inferiore del valore del flusso (usato per la riconciliazione)',
            data_max: 'Limite superiore del valore del flusso (usato per la riconciliazione)',
            uncertainty: 'Incertezza relativa in % sul valore del flusso (usata per la riconciliazione)',
            tab_basic_disabled: 'Selezionare "Valore" come tipo di dati nella scheda AFM per attivare questo pannello'
          },
          dir: 'Flussi considerati',
          node_ref: 'Relativo a',
          ratio: 'Tipo di rapporto',
          value_type: 'Tipo di dati'
        },
        apparence: {
          anchor: 'Ancore',
          handle: 'Maniglie',
          curve_unit: 'Unità',
          apparence: 'Aspetto',
          flow: 'Flusso',
          fond: 'Sfondo forma',
          source: 'Nodo origine',
          target: 'Nodo destinazione',
          couleur: 'Colore',
          color_source: 'Elemento che definisce il colore del flusso',
          grad: 'Gradiente',
          shape_is_dashed: 'Tratteggiato',
          shape_visible_when_zero: 'Mostra se nullo',
          of: 'Orientamento',
          type: 'Tipo',
          courbe: 'Curva',
          fleche: 'Freccia',
          opacity: 'Opacità',
          arrow_size: 'Dimensione freccia',
          shape_arrow_standalone: 'Punta indipendente',
          shape_arrow_min_width: 'Larghezza min. punta (px)',
          shape_structure_force_min: 'Nodo/freccia all\'altezza del valore',
          shape_uncertainty_display: 'Mostra incertezza',
          display_link_lab: 'Mostra valore',
          hide_link_lab: 'Nascondi valore',
          display_link_name: 'Mostra nome',
          hide_link_name: 'Nascondi nome',
          data_off_scale: 'Scala',
          scale_ref_thickness: 'Spessore max scala (px)',
          bezier_path: 'Semplice',
          bezier_outline: 'Contorno',
          bezier_outline_exact: 'Contorno esatto',
          tooltips: {
            color_source: {
              def: 'Scegliere la regola che definisce il colore del flusso:',
              flow: 'Il colore è definito dai parametri del flusso (colore predefinito, colore dei tag di flusso o dei dati)',
              source: 'Il colore è definito dal colore del nodo origine',
              target: 'Il colore è definito dal colore del nodo destinazione',
              gradient: 'Il colore è un gradiente dal colore del nodo origine al colore del nodo destinazione',
              auto: 'Il colore è determinato automaticamente secondo questa priorità:\n1. Tag colore comune tra origine e destinazione\n2. Solo un lato ha un tag colore → prendere quel lato\n3. Entrambi hanno tag (nessuno in comune) → preferire il nodo prodotto\n4. Nessun tag colore → preferire il nodo prodotto\n5. Predefinito: colore origine',
              disabled: 'La regola non permette di scegliere il colore del flusso'
            },
            couleur: 'Scegliere il colore per il/i flusso/i selezionato/i',
            grad: 'Applica un effetto di gradiente di colore sul/sui flusso/i selezionato/i. Il gradiente è realizzato tra il colore del nodo di partenza e quello del nodo di arrivo',
            shape_is_dashed: 'Applica un effetto tratteggiato sul/sui flusso/i selezionato/i',
            shape_visible_when_zero: 'Mostra sempre questo flusso anche se il suo valore è zero (ignora il filtro dei flussi nulli solo per questo flusso)',
            of_vv: 'Permette di orientare l\'inizio del flusso verticalmente e la fine verticalmente',
            of_hh: 'Permette di orientare l\'inizio del flusso orizzontalmente e la fine orizzontalmente',
            of_hv: 'Permette di orientare l\'inizio del flusso orizzontalmente e la fine verticalmente',
            of_vh: 'Permette di orientare l\'inizio del flusso verticalmente e la fine orizzontalmente',
            courbe: 'Rappresenta il/i flusso/i selezionato/i come curva/e di Bezier',
            fleche: 'Rappresenta il/i flusso/i selezionato/i con una punta di freccia alla fine',
            structure: 'Rappresenta il/i flusso/i selezionato/i come se non avessero valore, indipendentemente dal loro valore reale',
            starting_curve: 'Permette di regolare la posizione del punto di inizio curvatura per il/i flusso/i selezionato/i. Questo valore è un rapporto (%) della lunghezza del flusso relativo al punto di partenza.',
            ending_curve: 'Permette di regolare la posizione del punto di fine curvatura per il/i flusso/i selezionato/i. Questo valore è un rapporto (%) della lunghezza del flusso relativo al punto di partenza.',
            starting_tangeant: 'Impostazione del raggio di curvatura iniziale nel caso in cui il/i flusso/i selezionato/i siano rappresentati come curva/e di Bezier',
            ending_tangeant: 'Impostazione del raggio di curvatura finale nel caso in cui il/i flusso/i selezionato/i siano rappresentati come curva/e di Bezier',
            arrow_size: 'Modifica la dimensione della freccia (dalla fine del flusso al nodo)',
            shape_arrow_standalone: 'Disegna la punta di questo flusso come un triangolo indipendente centrato sulla sua estremità reale, invece di condividere il ventaglio di punte che convergono sul lato del nodo.',
            shape_arrow_min_width: 'Larghezza minima (px) della base della punta: i flussi più sottili ricevono una punta di questa larghezza (per restare visibili), quelli più spessi non cambiano. La profondità della punta non cambia. 0 = disattivato.',
            shape_structure_force_min: 'Selezionato: in modalità struttura, questo flusso mantiene la sua altezza di valore sul nodo e sulla freccia. Non selezionato (predefinito): il flusso è ridotto a un connettore sottile e non ingrandisce il nodo né la freccia.',
            shape_uncertainty_display: 'Sovrappone il flusso disegnato ai suoi valori min/media/max (più sottile = più opaco) per visualizzare l\'intervallo di incertezza.',
            data_off_scale: 'Definisce una scala locale per lo spessore del flusso, il che può rompere la coerenza della proporzionalità tra valore e spessore',
            local_scale: 'Definire un fattore di scala locale che sarà moltiplicato per il moltiplicatore specificato per questo flusso.',
            scale_ref_thickness: 'Spessore massimo (px) di questo flusso per il tag vista corrente: solo quando questo flusso supererebbe questo spessore, la scala del diagramma viene ricalcolata affinché si attesti esattamente a questo valore; tutti gli altri flussi e la legenda della scala si adeguano. Sotto la soglia, nulla cambia. 0 = disattivato. Un flusso di riferimento per tag vista.'
          }
        },
        labels: {
          value: 'Valore',
          intervals: 'Intervalli',
          percent: '%',
          ratio: 'Rapporto',
          label: 'Etichetta',
          vdb: 'Valore etichetta',
          len: 'Etichetta nera',
          lb: 'Etichetta bianca',
          lec: 'Etichetta colorata',
          pos: 'Posizione',
          milieu: 'Centro',
          deb: 'Inizio',
          fin: 'Fine',
          dessous: 'Sopra',
          dessus: 'Sotto',
          pls: 'Posizionamento manuale dell\'etichetta',
          l_u_v: 'Unità',
          l_u: 'Nome dell\'unità',
          tooltips: {
            label: 'Mostra o nasconde l\'etichetta (dato / testo) associata al/ai flusso/i selezionato/i',
            len: 'Mostra l\'etichetta in nero per il/i flusso/i selezionato/i',
            lb: 'Mostra l\'etichetta in bianco per il/i flusso/i selezionato/i',
            lec: 'Mostra l\'etichetta con lo/gli stesso/i colore/i associato/i al/ai flusso/i selezionato/i',
            deb: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta verso il punto di partenza del flusso',
            milieu_h: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta tra il punto di partenza e il punto di arrivo del flusso',
            end: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta verso il punto di arrivo del flusso',
            below: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta sotto il flusso',
            milieu_v: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta dentro il flusso',
            top: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta sopra il flusso',
            pls: 'La combinazione Alt/clic sinistro sposta l\'etichetta del/dei flusso/i selezionato/i',
            l_u_v: 'Mostra l\'unità dei flussi',
            l_u: 'Scegliere il nome dell\'unità',
            unit_factor: 'Fattore di conversione per l\'unità del flusso',
            '%ID': '% dei flussi in entrata del nodo destinazione',
            '%IS': '% dei flussi in entrata del nodo sorgente',
            '%OD': '% dei flussi in uscita del nodo destinazione',
            '%OS': '% dei flussi in uscita del nodo sorgente',
            '%PD': 'Valore visualizzato in % della portata totale del nodo a valle (destinazione): max(entrate, uscite)',
            '%PS': 'Valore visualizzato in % della portata totale del nodo a monte (sorgente): max(entrate, uscite)',
            '%SD': '% dello stock del nodo destinazione (in entrata)',
            '%SS': '% dello stock del nodo sorgente (in uscita)',
            dessous: 'Per il/i flussi selezionati, posiziona il testo dell\'etichetta sotto il flusso',
            dessus: 'Per il/i flussi selezionati, posiziona il testo dell\'etichetta sopra il flusso',
            fin: 'Per il/i flussi selezionati, posiziona il testo dell\'etichetta vicino al punto di arrivo del flusso',
            name_label_text_source: 'Scegliere cosa mostra l\'etichetta del flusso: testo digitato, niente, nome del nodo sorgente/destinazione, o sorgente → destinazione',
            name_label_template: 'Testo costruito con segnaposto sostituiti al disegno, es. «{EntryName}: {Value} {Unit}»',
            value: 'Valore'
          },
          '%ID': '% dei flussi in entrata del nodo destinazione',
          '%IS': '% dei flussi in entrata del nodo sorgente',
          '%OD': '% dei flussi in uscita del nodo destinazione',
          '%OS': '% dei flussi in uscita del nodo sorgente',
          '%PD': '% del totale del nodo a valle (destinazione)',
          '%PS': '% del totale del nodo a monte (sorgente)',
          '%SD': '% dello stock del nodo destinazione (in entrata)',
          '%SS': '% dello stock del nodo sorgente (in uscita)',
          NbDigit: 'Numero massimo di decimali',
          labels: 'Nome',
          name_label_is_visible: 'Etichetta',
          name_label_tag_group: 'Gruppo di tag',
          name_label_text_source: 'Contenuto dell\'etichetta',
          name_label_template: 'Modello',
          node_value: 'Valore',
          normalized: 'Normalizzato (flusso rif.)',
          other_unit_tag: 'Altre unità native',
          pos_v: 'Posizione del valore',
          scientificNotation: 'Notazione scientifica',
          significantDigits: 'Cifre significative',
          source: 'Nodo sorgente',
          target: 'Nodo destinazione',
          text_source: {
            custom: 'Testo personalizzato',
            template: 'Modello con segnaposto',
            none: 'Nessuno',
            source: 'Nodo sorgente',
            source_target: 'Sorgente → destinazione',
            tag: 'Tag di flusso',
            target: 'Nodo destinazione'
          },
          tp: 'Dimensione del carattere',
          unit_factor: 'Fattore di unità',
          unit_model: 'Unità del diagramma',
          unit_name: 'Unità personalizzata',
          unit_ratio: 'Rapporto di unità',
          unit_tag: 'Unità nativa di origine'
        },
        layout: 'Disposizione',
        layoutUp: 'Avanzare',
        layoutTop: 'Primo piano',
        layoutDown: 'Arretrare',
        layoutBottom: 'Ultimo piano',
      }
    }
  },
  'zh-CN': {
    translation: {
      Flux: {
        pg: '通用设置',
        pdl: '字体',
        pl: '各流量参数',
        src: '起点',
        trgt: '终点',
        value: '数值',
        calculated_value: '计算值',
        type: '格式',
        if: '反转方向',
        dzf: '叠放顺序',
        style: '样式',
        as: '将该样式应用到所选流量',
        IB: '提示框',
        IS: '附加信息',
        ajust_label: '调整标签位置',
        FS: '流量',
        local_scale: '局部流量比例尺',
        changePlan: '更改流量所在图层',
        mask_attr: '更改流量的属性',
        tooltips: {
          src: '为所选流量选择起始节点',
          trgt: '为所选流量选择到达节点',
          if: '反转所选流量的起点与终点节点',
          up: '向前景方向上移一层',
          upup: '将所选流量置于前景',
          dwn: '向背景方向下移一层',
          dwndwn: '将所选流量移至最底层',
          as: '允许将首选项菜单中预定义的样式应用到所选流量',
          IB: '提示框：以 HTML 编排、随流量提示框一同显示的文本。该提示框在图形区中通过 SHIFT + 鼠标悬停于流量上弹出。',
          ajust_label: '当流量标签高于流量线宽时，将其重新定位到流量上方',
          inv: '交换目标与源'
        },
        data: {
          données: '数据',
          vpp: '数值',
          data_type: '数据类型',
          value: '数值',
          ratio_input: '占总输入的比例',
          ratio_output: '占总输出的比例',
          ratio_source_parent: '占父流量的比例（左）',
          ratio_target_parent: '占父流量的比例（右）',
          unit_ratio: '单位换算系数',
          edit_value: '编辑数值',
          value_target: '终点数值',
          tab_basic: '基础',
          tab_afm: 'AFM',
          data_min: '最小',
          data_max: '最大',
          uncertainty: '不确定性',
          affichage: '标签',
          tooltips: {
            data_type: '数据类型',
            vpp: '与所选流量相关联的数据；若存在，则为所选标签下的数据',
            scientificNotation: '是否在桑基图上以科学计数法显示该流量的数据',
            affichage: '在桑基图上显示该流量数据时使用的替代文本',
            value_target: '渐变粗细流量的终点数值（留空则粗细均匀）',
            value: '流量的数值。也可以填写“min”或“max”：调和将为该流量取与模型其余部分兼容的最小（或最大）值，该流量随之被确定。',
            data_min: '流量数值的下界（用于调和）',
            data_max: '流量数值的上界（用于调和）',
            uncertainty: '流量数值的相对不确定性（%）（用于调和）',
            tab_basic_disabled: '在 AFM 选项卡中将数据类型选为“数值”即可启用此面板'
          },
          dir: '所考虑的流量',
          node_ref: '相对于',
          ratio: '比例类型',
          value_type: '数据类型'
        },
        apparence: {
          anchor: '锚点',
          handle: '控制柄',
          curve_unit: '单位',
          apparence: '外观',
          flow: '流量',
          fond: '形状背景',
          source: '源节点',
          target: '目标节点',
          couleur: '颜色',
          color_source: '决定流量颜色的元素',
          grad: '渐变',
          shape_is_dashed: '虚线',
          shape_visible_when_zero: '为零时仍显示',
          of: '方向',
          type: '类型',
          courbe: '曲线',
          fleche: '箭头',
          opacity: '不透明度',
          arrow_size: '箭头尺寸',
          shape_arrow_standalone: '独立尖端',
          shape_arrow_min_width: '最小箭头底宽（px）',
          shape_structure_force_min: '节点/箭头按数值高度',
          shape_uncertainty_display: '显示不确定性',
          display_link_lab: '显示数值',
          hide_link_lab: '隐藏数值',
          display_link_name: '显示名称',
          hide_link_name: '隐藏名称',
          data_off_scale: '比例尺',
          scale_ref_thickness: '比例尺最大粗细（px）',
          bezier_path: '简单',
          bezier_outline: '轮廓',
          bezier_outline_exact: '精确轮廓',
          tooltips: {
            color_source: {
              def: '选择决定流量颜色的规则：',
              flow: '颜色由流量参数决定（默认颜色、流量标签颜色或数据标签颜色）',
              source: '颜色由源节点的颜色决定',
              target: '颜色由目标节点的颜色决定',
              gradient: '颜色为从源节点颜色到目标节点颜色的渐变',
              auto: '颜色按以下优先级自动确定：\n1. 源与目标共有的颜色标签\n2. 只有一侧有颜色标签 → 取该侧\n3. 两侧都有标签（无共有） → 优先取产品节点\n4. 没有颜色标签 → 优先取产品节点\n5. 兜底：源节点颜色',
              disabled: '该规则不允许选择流量颜色'
            },
            couleur: '为所选流量选择颜色',
            grad: '对所选流量应用渐变色效果。渐变从起点节点的颜色过渡到终点节点的颜色',
            shape_is_dashed: '对所选流量应用剖面线效果',
            shape_visible_when_zero: '即使数值为零也始终绘制该流量（仅对该流量覆盖零值流量筛选）',
            of_vv: '使流量的起点与终点均为垂直方向',
            of_hh: '使流量的起点与终点均为水平方向',
            of_hv: '使流量的起点为水平方向、终点为垂直方向',
            of_vh: '使流量的起点为垂直方向、终点为水平方向',
            courbe: '将所选流量表示为贝塞尔曲线',
            fleche: '在所选流量的末端绘制一个箭头',
            structure: '无论真实数值如何，都将所选流量表示为没有数值',
            starting_curve: '用于微调所选流量曲率起点的位置。该值是相对于流量起点、以流量长度百分比（%）表示的比率。',
            ending_curve: '用于微调所选流量曲率终点的位置。该值是相对于流量起点、以流量长度百分比（%）表示的比率。',
            starting_tangeant: '当所选流量以贝塞尔曲线表示时，设置其起始曲率的半径',
            ending_tangeant: '当所选流量以贝塞尔曲线表示时，设置其结束曲率的半径',
            arrow_size: '更改箭头的尺寸（从流量末端到节点）',
            shape_arrow_standalone: '将该流量的箭头绘制为以其真实末端为中心的独立三角形，而不与汇聚在节点一侧的箭头组共用。',
            shape_arrow_min_width: '箭头底边的最小宽度（px）：比该值更细的流量会获得此宽度的箭头（以保持可见），更粗的流量保持不变。箭头深度（箭头尺寸）不变。0 表示禁用。',
            shape_structure_force_min: '勾选：在结构模式下，该流量在节点与箭头上保留其数值高度。取消勾选（默认）：该流量收缩为细连接线，不会增大节点或箭头。',
            shape_uncertainty_display: '叠加绘制流量的最小值/均值/最大值（越细越不透明），以呈现不确定区间。',
            data_off_scale: '为该流量定义一个比例尺，这可能破坏流量粗细与数值成正比的一致性 ',
            local_scale: '定义一个局部缩放系数，它将与为该流量指定的倍数相乘。',
            scale_ref_thickness: '该流量在当前视图标签下的最大粗细（px）：仅当该流量将超过此粗细时，图表比例尺才会重新缩放，使其恰好等于该值；其他所有流量与比例尺图例随之调整。低于该阈值时不作任何改变。0 = 停用。每个视图标签一条参考流量。'
          }
        },
        labels: {
          value: '数值',
          intervals: '区间',
          percent: '%',
          ratio: '比例',
          unit_name: '自定义单位',
          unit_model: '来自图表单位的单位',
          unit_ratio: '单位比例',
          unit_tag: '原生来源单位',
          other_unit_tag: '其他原生单位',
          normalized: '归一化（参考流量）',
          '%IS': '占源节点进入流量的 %',
          '%ID': '占终点节点进入流量的 %',
          '%OS': '占源节点流出流量的 %',
          '%OD': '占终点节点流出流量的 %',
          '%PS': '占上游节点总量的 %（源）',
          '%PD': '占下游节点总量的 %（终点）',
          '%SS': '占源节点存量的 %（流出）',
          '%SD': '占终点节点存量的 %（进入）',
          label: '标签',
          vdb: '标签数值',
          len: '黑色标签',
          lb: '白色标签',
          lec: '彩色标签',
          pos: '位置',
          milieu: '中间',
          deb: '起点',
          fin: '终点',
          dessous: '上方',
          dessus: '下方',
          pls: '手动定位标签',
          l_u_v: '单位',
          l_u: '单位名称',
          name_label_text_source: '标签内容',
          name_label_template: '模板',
          name_label_tag_group: '标签组',
          text_source: {
            custom: '自定义文本',
            template: '占位符模板',
            none: '无',
            source: '源节点',
            target: '目标节点',
            source_target: '源 → 目标',
            tag: '流量标签',
          },
          tooltips: {
            name_label_text_source: '选择流量标签显示的内容：输入的文本、不显示、源/目标节点名称，或 源 → 目标',
            name_label_template: '由绘制时替换的占位符组成的文本，例如“{EntryName}: {Value} {Unit}”',
            label: '是否显示与所选流量关联的标签（数据 / 文本）',
            len: '以黑色显示所选流量的标签',
            lb: '以白色显示所选流量的标签',
            lec: '以与所选流量相同的颜色显示标签',
            deb: '对于所选流量，将标签定位到流量起点一侧',
            milieu_h: '对于所选流量，将标签定位到流量起点与终点之间',
            end: '对于所选流量，将标签定位到流量终点一侧',
            below: '对于所选流量，将标签定位到流量下方',
            milieu_v: '对于所选流量，将标签定位到流量内部',
            top: '对于所选流量，将标签定位到流量上方',
            pls: 'Alt + 左键组合可移动所选流量的标签',
            l_u_v: '显示流量的单位',
            l_u: '选择单位的名称',
            unit_factor: '流量单位的换算系数',
            '%ID': '占终点节点进入流量的 %',
            '%IS': '占源节点进入流量的 %',
            '%OD': '占终点节点流出流量的 %',
            '%OS': '占源节点流出流量的 %',
            '%PD': '数值以下游节点（终点）总通过量的百分比显示：max(进入, 流出)',
            '%PS': '数值以上游节点（源）总通过量的百分比显示：max(进入, 流出)',
            '%SD': '占终点节点存量的 %（进入）',
            '%SS': '占源节点存量的 %（流出）',
            dessous: '对于所选流量，将标签文本置于流量下方',
            dessus: '对于所选流量，将标签文本置于流量上方',
            fin: '对于所选流量，将标签文本置于流量终点附近',
            value: '数值'
          },
          NbDigit: '最大小数位数',
          labels: '名称',
          name_label_is_visible: '标签',
          node_value: '数值',
          pos_v: '数值位置',
          scientificNotation: '科学计数法',
          significantDigits: '有效数字',
          source: '源节点',
          target: '目标节点',
          tp: '字号',
          unit_factor: '单位系数'
        },
        layout: '排布',
        layoutUp: '上移一层',
        layoutTop: '移至最上层',
        layoutDown: '下移一层',
        layoutBottom: '移至最下层',
      }
    }
  },
  ja: {
    translation: {
      Flux: {
        pg: '全体の設定',
        pdl: 'フォント',
        pl: 'フローごとの設定',
        src: '始点',
        trgt: '終点',
        value: '値',
        calculated_value: '計算値',
        type: '形式',
        if: '向きを反転',
        dzf: '重なり順',
        style: 'スタイル',
        as: '選択したフローにスタイルを適用します',
        IB: 'ツールチップ',
        IS: '補足情報',
        ajust_label: 'ラベル位置を調整',
        FS: 'フロー',
        local_scale: 'フロー個別のスケール',
        changePlan: 'フローのレイヤーを変更',
        mask_attr: 'フローの属性を変更',
        tooltips: {
          src: '選択したフローの始点ノードを選びます',
          trgt: '選択したフローの終点ノードを選びます',
          if: '選択したフローの始点ノードと終点ノードを入れ替えます',
          up: '1 段階前面へ移動します',
          upup: '選択したフローを最前面に置きます',
          dwn: '1 段階背面へ移動します',
          dwndwn: '選択したフローを最背面へ移動します',
          as: '環境設定メニューで定義したスタイルを、選択したフローに適用できるようにします',
          IB: 'ツールチップ：HTML で記述され、フローのツールチップとして表示されるテキストです。描画エリアでフローの上を SHIFT + マウスでポイントすると表示されます。',
          ajust_label: 'フローのラベルがフローの線幅より高い場合、ラベルをフローの上に配置し直します',
          inv: '終点と始点を入れ替えます'
        },
        data: {
          données: 'データ',
          vpp: '値',
          data_type: 'データの種類',
          value: '値',
          ratio_input: '入力合計に対する比率',
          ratio_output: '出力合計に対する比率',
          ratio_source_parent: '親フローに対する比率（左）',
          ratio_target_parent: '親フローに対する比率（右）',
          unit_ratio: '単位換算の係数',
          edit_value: '値を編集',
          value_target: '終点側の値',
          tab_basic: '基本',
          tab_afm: 'AFM',
          data_min: '最小',
          data_max: '最大',
          uncertainty: '不確実性',
          affichage: 'ラベル',
          tooltips: {
            data_type: 'データの種類',
            vpp: '選択したフローに紐づくデータ（該当する場合は選択中のタグのもの）',
            scientificNotation: 'サンキーダイアグラム上でフローのデータを指数表記にするかどうかを設定します',
            affichage: 'サンキーダイアグラム上でフローのデータの代わりに表示するテキスト',
            value_target: '先細りのフローの終点側の値（空欄にすると太さが一定になります）',
            value: 'フローの値。「min」または「max」と書くこともできます：調和はモデルの他の部分と矛盾しない最小（または最大）の値をフローに与え、フローは確定されます。',
            data_min: 'フローの値の下限（調和で使用）',
            data_max: 'フローの値の上限（調和で使用）',
            uncertainty: 'フローの値の相対的な不確実性（%）（調和で使用）',
            tab_basic_disabled: 'このパネルを使うには、AFM タブでデータの種類を「値」にしてください'
          },
          dir: '対象とするフロー',
          node_ref: '基準',
          ratio: '比率の種類',
          value_type: 'データの種類'
        },
        apparence: {
          anchor: 'アンカー',
          handle: 'ハンドル',
          curve_unit: '単位',
          apparence: '外観',
          flow: 'フロー',
          fond: '形状の背景',
          source: '始点ノード',
          target: '終点ノード',
          couleur: '色',
          color_source: 'フローの色を決める要素',
          grad: 'グラデーション',
          shape_is_dashed: '破線',
          shape_visible_when_zero: 'ゼロでも表示',
          of: '向き',
          type: '種類',
          courbe: '曲線',
          fleche: '矢印',
          opacity: '不透明度',
          arrow_size: '矢印の大きさ',
          shape_arrow_standalone: '独立した矢先',
          shape_arrow_min_width: '矢先の最小幅（px）',
          shape_structure_force_min: 'ノード／矢印を値の高さに',
          shape_uncertainty_display: '不確実性を表示',
          display_link_lab: '値を表示',
          hide_link_lab: '値を隠す',
          display_link_name: '名前を表示',
          hide_link_name: '名前を隠す',
          data_off_scale: 'スケール',
          scale_ref_thickness: 'スケールの最大太さ（px）',
          bezier_path: 'シンプル',
          bezier_outline: '輪郭',
          bezier_outline_exact: '厳密な輪郭',
          tooltips: {
            color_source: {
              def: 'フローの色を決めるルールを選択：',
              flow: '色はフローの設定で決まります（既定の色、フロータグの色、データタグの色）',
              source: '色は始点ノードの色で決まります',
              target: '色は終点ノードの色で決まります',
              gradient: '色は始点ノードの色から終点ノードの色へのグラデーションになります',
              auto: '色は次の優先順位で自動的に決まります：\n1. 始点と終点に共通する色タグ\n2. 片側だけに色タグがある → その側を採用\n3. 両側にタグがある（共通なし） → 製品ノードを優先\n4. 色タグがない → 製品ノードを優先\n5. 最後の手段：始点の色',
              disabled: 'このルールではフローの色を選べません'
            },
            couleur: '選択したフローの色を選びます',
            grad: '選択したフローにグラデーションを適用します。グラデーションは始点ノードの色から終点ノードの色へと変化します',
            shape_is_dashed: '選択したフローにハッチングの効果を適用します',
            shape_visible_when_zero: '値がゼロでもこのフローを常に描画します（このフローに限りゼロ値フィルタを無視します）',
            of_vv: 'フローの始点と終点をどちらも垂直方向に向けます',
            of_hh: 'フローの始点と終点をどちらも水平方向に向けます',
            of_hv: 'フローの始点を水平方向、終点を垂直方向に向けます',
            of_vh: 'フローの始点を垂直方向、終点を水平方向に向けます',
            courbe: '選択したフローをベジェ曲線として表現します',
            fleche: '選択したフローの末端に矢印を付けて表現します',
            structure: '実際の値にかかわらず、選択したフローを値を持たないものとして表現します',
            starting_curve: '選択したフローの曲率の始点位置を微調整します。この値はフローの始点を基準とした、フロー長に対する比率（%）です。',
            ending_curve: '選択したフローの曲率の終点位置を微調整します。この値はフローの始点を基準とした、フロー長に対する比率（%）です。',
            starting_tangeant: '選択したフローをベジェ曲線として表現する場合の、開始側の曲率半径を設定します',
            ending_tangeant: '選択したフローをベジェ曲線として表現する場合の、終了側の曲率半径を設定します',
            arrow_size: '矢印の大きさを変更します（フローの端からノードまで）',
            shape_arrow_standalone: 'ノードの辺に集まる矢印の扇形を共有せず、このフローの矢印を実際の終端を中心とする独立した三角形として描画します。',
            shape_arrow_min_width: '矢先の底辺の最小幅（px）：これより細いフローにはこの幅の矢先が付き（見えなくならないように）、太いフローは変わりません。矢先の深さ（矢印サイズ）は変わりません。0 で無効。',
            shape_structure_force_min: 'オン：構造モードでも、このフローはノードと矢印の上で値どおりの高さを保ちます。オフ（既定）：フローは細い連結線に縮められ、ノードや矢印を大きくしません。',
            shape_uncertainty_display: '最小値／平均値／最大値で描いたフローを重ねて表示し（細いほど不透明）、不確実性の幅を可視化します。',
            data_off_scale: 'このフロー専用のスケールを定義します。フローの太さと値の比例関係が崩れることがあります ',
            local_scale: 'このフローに指定された倍率に掛け合わせる、ローカルな拡大率を定義します。',
            scale_ref_thickness: '現在のビュータグにおけるこのフローの最大の太さ（px）：このフローがこの太さを超える場合にのみ、ちょうどこの値になるよう図のスケールが調整され、他のすべてのフローとスケール凡例もそれに従います。しきい値未満では何も変わりません。0 = 無効。ビュータグごとに基準フローは 1 本です。'
          }
        },
        labels: {
          value: '値',
          intervals: '区間',
          percent: '%',
          ratio: '比率',
          unit_name: '任意の単位',
          unit_model: '図の単位から選ぶ',
          unit_ratio: '単位の比率',
          unit_tag: '元データの単位',
          other_unit_tag: 'その他の元単位',
          normalized: '正規化（基準フロー）',
          '%IS': '始点ノードの入力合計に対する %',
          '%ID': '終点ノードの入力合計に対する %',
          '%OS': '始点ノードの出力合計に対する %',
          '%OD': '終点ノードの出力合計に対する %',
          '%PS': '上流ノードの合計に対する %（始点）',
          '%PD': '下流ノードの合計に対する %（終点）',
          '%SS': '始点ノードのストックに対する %（出力）',
          '%SD': '終点ノードのストックに対する %（入力）',
          label: 'ラベル',
          vdb: 'ラベルの値',
          len: '黒いラベル',
          lb: '白いラベル',
          lec: '色付きラベル',
          pos: '位置',
          milieu: '中間',
          deb: '始点',
          fin: '終点',
          dessous: '上',
          dessus: '下',
          pls: 'ラベルを手動で配置します',
          l_u_v: '単位',
          l_u: '単位の名前',
          name_label_text_source: 'ラベルの内容',
          name_label_template: 'テンプレート',
          name_label_tag_group: 'タググループ',
          text_source: {
            custom: '任意テキスト',
            template: 'トークンのテンプレート',
            none: 'なし',
            source: '始点ノード',
            target: '終点ノード',
            source_target: '始点 → 終点',
            tag: 'フロータグ',
          },
          tooltips: {
            name_label_text_source: 'フローのラベルに表示する内容を選択：入力したテキスト、なし、始点／終点ノード名、始点 → 終点',
            name_label_template: '描画時に置き換えられるトークンで組み立てる文字列（例：「{EntryName}: {Value} {Unit}」）',
            label: '選択したフローに紐づくラベル（データ／テキスト）を表示するかどうかを設定します',
            len: '選択したフローのラベルを黒で表示します',
            lb: '選択したフローのラベルを白で表示します',
            lec: '選択したフローに紐づく色と同じ色でラベルを表示します',
            deb: '選択したフローについて、ラベルをフローの始点寄りに配置します',
            milieu_h: '選択したフローについて、ラベルをフローの始点と終点の間に配置します',
            end: '選択したフローについて、ラベルをフローの終点寄りに配置します',
            below: '選択したフローについて、ラベルをフローの下に配置します',
            milieu_v: '選択したフローについて、ラベルをフローの内側に配置します',
            top: '選択したフローについて、ラベルをフローの上に配置します',
            pls: 'Alt + 左クリックの組み合わせで、選択したフローのラベルを移動できます',
            l_u_v: 'フローの単位を表示します',
            l_u: '単位の名前を選びます',
            unit_factor: 'フローの単位の換算係数',
            '%ID': '終点ノードの入力合計に対する %',
            '%IS': '始点ノードの入力合計に対する %',
            '%OD': '終点ノードの出力合計に対する %',
            '%OS': '始点ノードの出力合計に対する %',
            '%PD': '下流ノード（終点）の総通過量に対する % で値を表示します：max(入力, 出力)',
            '%PS': '上流ノード（始点）の総通過量に対する % で値を表示します：max(入力, 出力)',
            '%SD': '終点ノードのストックに対する %（入力）',
            '%SS': '始点ノードのストックに対する %（出力）',
            dessous: '選択したフローについて、ラベルのテキストをフローの下に配置します',
            dessus: '選択したフローについて、ラベルのテキストをフローの上に配置します',
            fin: '選択したフローについて、ラベルのテキストをフローの終点付近に配置します',
            value: '値'
          },
          NbDigit: '小数点以下の最大桁数',
          labels: '名前',
          name_label_is_visible: 'ラベル',
          node_value: '値',
          pos_v: '値の位置',
          scientificNotation: '指数表記',
          significantDigits: '有効数字',
          source: '始点ノード',
          target: '終点ノード',
          tp: '文字サイズ',
          unit_factor: '単位の係数'
        },
        layout: '配置',
        layoutUp: '前面へ',
        layoutTop: '最前面へ',
        layoutDown: '背面へ',
        layoutBottom: '最背面へ',
      }
    }
  }
}