// ==================================================================================================
// The MIT License (MIT) - Copyright (c) 2025 TerriFlux
// ==================================================================================================
// Traductions du tableur Univer (grande zone « Tableur ») : barre d'outils, sélecteurs, modale
// « Ajouter une contrainte », panneau de documentation, noms d'onglets et en-têtes de colonnes du
// classeur. Clé racine i18next : `Spreadsheet`.
// Le classeur (UniverSankeyData) lit ces clés via i18next.t ; les composants React via useTranslation.
// ==================================================================================================

export const resources_spreadsheet = {
  //=======================================================
  // EN
  //=======================================================
  en: {
    translation: {
      Spreadsheet: {
        // --- Onglets (noms de feuilles) ---
        sheet: {
          flux: 'Flows',
          analysis: 'Results analysis',
          nodes: 'Nodes',
          nodes_agg: 'Nodes by aggregation',
          tags: 'Tags',
          stock: 'Stocks',
          ratio: 'Flow ratio',
          ratio_stock: 'Stock-flow ratio',
          stock_chaining: 'Stock chaining',
          products: 'Products',
          sectors: 'Sectors',
          exchanges: 'Exchanges',
          tes: 'IOT (IO matrix)',
          ter: 'SUT (supply-use)'
        },
        // --- En-têtes de colonnes ---
        header: {
          level: 'Level',
          level_n: 'Level {{n}}',
          name: 'Name',
          balance: 'Balance',
          balance_io: 'Input-output balance',
          color: 'Color',
          definitions: 'Definitions',
          column_u: 'Column u',
          row_v: 'Row v',
          origin: 'Origin',
          destination: 'Destination',
          value: 'Value',
          min: 'Min',
          max: 'Max',
          computed_value: 'Computed value',
          dest_value: 'Destination value',
          natural_quantity: 'Natural quantity',
          uncertainty_pct: 'Uncertainty %',
          source: 'Source',
          hypothesis: 'Hypothesis',
          computed_min: 'Computed min',
          computed_max: 'Computed max',
          delta_recon: 'Reconciled - unreconciled delta',
          gap_sigma: 'Reconciled gap (σ count)',
          variable_type: 'Variable type',
          node: 'Node',
          stock: 'Stock',
          computed_stock: 'Computed stock',
          delta_stock: 'Δ Stock',
          computed_delta: 'Computed Δ',
          coef: 'Coef',
          origin_ref: 'Origin ref',
          dest_ref: 'Destination ref',
          tag: 'Tag',
          tag_ref: 'Tag ref',
          translation: 'Translation',
          delta_stock_plain: 'Delta stock',
          dimension: 'Dimension',
          tags: 'Tags',
          tag_group_name: 'Tag group name',
          tag_type: 'Tag type',
          colors: 'Colors',
          // En-têtes de matrice
          origin_dest: 'Origin ╲ Destination',
          resources: 'Resources',
          uses: 'Uses'
        },
        // --- Types d'étiquette (colonne Type de l'onglet Etiquettes) ---
        tagtype: {
          node: 'Node',
          level: 'Level',
          flux: 'Flow',
          data: 'Data'
        },
        // --- Classification du type de variable (onglet Analyse) ---
        classif: {
          measured: 'Measured',
          free_interval: 'Free (interval)',
          determined: 'Determined'
        },
        // --- Barre d'outils ---
        toolbar: {
          add_constraint: '+ Constraint',
          add_constraint_tip: 'Create a constraint (flow, stock, node total…) via a guided form',
          parser: 'Parse',
          parser_tip: 'Builds the aggregation hierarchy from the Level column',
          filter: 'Filter',
          filter_tip: 'Toggles column filters (Excel-style) on this sheet',
          columns: 'Columns',
          columns_count: 'Columns ({{shown}}/{{total}})',
          sheets: 'Sheets',
          sheets_count: 'Sheets ({{shown}}/{{total}})',
          search: 'Search',
          select_all: '(Select all)',
          show_all: 'Show all',
          only_visible: 'Visible only',
          display_filter_tip: 'Row display filter for the spreadsheet',
          placement_auto: 'Placement: auto',
          placement_none: 'Placement: none',
          placement_increment: 'Placement: incremental',
          placement_tip: 'How to position a node created by adding a flow: auto (full layout), none (default position), incremental (guesses the spot without moving others)',
          matrix_cross: 'Matrix: cross',
          matrix_value: 'Matrix: value',
          matrix_tip: 'Matrix cell content: cross (the flow exists) or flow value for the selected data_type'
        },
        // --- Modale « Ajouter une contrainte » ---
        constraint: {
          title: 'Add a constraint',
          term1: 'Term 1',
          term2_ref: 'Term 2 (reference)',
          type_flux: 'Flow',
          type_node_total: 'Node (total)',
          type_stock: 'Stock',
          type_delta_stock: 'Δ stock',
          in: 'inbound',
          out: 'outbound',
          node: 'Node',
          origin: 'Origin',
          destination: 'Destination',
          search: 'Search…',
          no_node: 'No node',
          coef: 'coef',
          translation_label: 'Translation (auto, editable)',
          translation_ph: 'Natural language description',
          regenerate: 'regenerate',
          invalid_combo: 'Invalid term combination.',
          cancel: 'Cancel',
          add: 'Add',
          desc_flux: 'flow {{orig}}→{{dest}}',
          desc_node_in: 'total inbound of {{node}}',
          desc_node_out: 'total outbound of {{node}}',
          desc_stock: 'stock of {{node}}',
          desc_delta: 'Δ stock of {{node}}'
        },
        // --- Panneau de documentation ---
        doc: {
          title: 'Documentation',
          window_title: 'OpenSankey — Documentation',
          pos_sheet_right: 'Right of the spreadsheet',
          pos_sheet_left: 'Left of the spreadsheet',
          pos_sheet_top: 'Above the spreadsheet',
          pos_sheet_bottom: 'Below the spreadsheet',
          pos_diagram_bottom: 'Below the diagram',
          pos_window_bottom: 'Bottom bar',
          pos_right: 'Right',
          pos_left: 'Left',
          pos_top: 'Above',
          pos_bottom: 'Below',
          with_sheet: 'With the spreadsheet',
          under_diagram: 'Below the diagram',
          window_bottom_full: 'Bottom bar (full width)',
          insert: 'Insert',
          insert_image: 'An image…',
          insert_views_outline: 'Title + link for each view',
          insert_view_link: 'Link to a view',
          mode_edit: 'Edit',
          mode_split: 'Side by side',
          mode_preview: 'Preview',
          reattach: 'Reattach the documentation into the main window',
          detach: 'Detach the documentation into a separate window',
          editor_placeholder: 'Write this diagram\'s documentation in markdown…\n\n# Title\n\n- point 1\n- point 2'
        },
        // --- Boutons bascule de la grande zone (MenuTop) ---
        zone: {
          diagram: 'Diagram',
          spreadsheet: 'Spreadsheet',
          doc: 'Doc',
          documentation: 'Documentation',
          unitary: 'Unitary Sankey',
          unit: 'Unit.'
        }
      }
    }
  },
  //=======================================================
  // FR
  //=======================================================
  fr: {
    translation: {
      Spreadsheet: {
        sheet: {
          flux: 'Flux',
          analysis: 'Analyse des résultats',
          nodes: 'Noeuds',
          nodes_agg: 'Noeuds par agrégation',
          tags: 'Etiquettes',
          stock: 'Stocks',
          ratio: 'Ratio flux',
          ratio_stock: 'Ratio stock flux',
          stock_chaining: 'Chaînage stock',
          products: 'Produits',
          sectors: 'Secteurs',
          exchanges: 'Echanges',
          tes: 'TES (matrice IO)',
          ter: 'TER (emplois-ressources)'
        },
        header: {
          level: 'Niveau',
          level_n: 'Niveau {{n}}',
          name: 'Nom',
          balance: 'Equilibre',
          balance_io: 'Equilibre entrée-sortie',
          color: 'Couleur',
          definitions: 'Définitions',
          column_u: 'Colonne u',
          row_v: 'Ligne v',
          origin: 'Origine',
          destination: 'Destination',
          value: 'Valeur',
          min: 'Min',
          max: 'Max',
          computed_value: 'Valeur calculée',
          dest_value: 'Valeur destination',
          natural_quantity: 'Quantité naturelle',
          uncertainty_pct: 'Incertitude %',
          source: 'Source',
          hypothesis: 'Hypothèse',
          computed_min: 'Min calculée',
          computed_max: 'Max calculée',
          delta_recon: 'Delta réconcilié - non-réconcilié',
          gap_sigma: 'Écart réconcilié (nb σ)',
          variable_type: 'Type de variable',
          node: 'Nœud',
          stock: 'Stock',
          computed_stock: 'Stock calculé',
          delta_stock: 'Δ Stock',
          computed_delta: 'Δ calculée',
          coef: 'Coef',
          origin_ref: 'Origine réf',
          dest_ref: 'Destination réf',
          tag: 'Étiquette',
          tag_ref: 'Étiquette réf',
          translation: 'Traduction',
          delta_stock_plain: 'Delta stock',
          dimension: 'Dimension',
          tags: 'Etiquettes',
          tag_group_name: 'Nom du groupe d\'étiquette',
          tag_type: 'Type d\'étiquette',
          colors: 'Couleurs',
          origin_dest: 'Origine ╲ Destination',
          resources: 'Ressources',
          uses: 'Emplois'
        },
        tagtype: {
          node: 'Noeud',
          level: 'Niveau',
          flux: 'Flux',
          data: 'Donnée'
        },
        classif: {
          measured: 'Mesurée',
          free_interval: 'Libre (intervalle)',
          determined: 'Déterminée'
        },
        toolbar: {
          add_constraint: '+ Contrainte',
          add_constraint_tip: 'Créer une contrainte (flux, stock, total de nœud…) via un formulaire guidé',
          parser: 'Parser',
          parser_tip: 'Construit la hiérarchie d\'agrégation depuis la colonne Niveau',
          filter: 'Filtrer',
          filter_tip: 'Active/désactive les filtres de colonne (style Excel) sur cet onglet',
          columns: 'Colonnes',
          columns_count: 'Colonnes ({{shown}}/{{total}})',
          sheets: 'Onglets',
          sheets_count: 'Onglets ({{shown}}/{{total}})',
          search: 'Rechercher',
          select_all: '(Tout sélectionner)',
          show_all: 'Tout afficher',
          only_visible: 'Visibles uniquement',
          display_filter_tip: 'Filtre d\'affichage des lignes du tableur',
          placement_auto: 'Placement : auto',
          placement_none: 'Placement : aucun',
          placement_increment: 'Placement : incrémental',
          placement_tip: 'Comment positionner un nœud créé en ajoutant un flux : auto (disposition complète), aucun (position par défaut), incrémental (devine la place sans bouger les autres)',
          matrix_cross: 'Matrice : croix',
          matrix_value: 'Matrice : valeur',
          matrix_tip: 'Contenu des cellules de la matrice : croix (le flux existe) ou valeur du flux pour le data_type sélectionné'
        },
        constraint: {
          title: 'Ajouter une contrainte',
          term1: 'Terme 1',
          term2_ref: 'Terme 2 (référence)',
          type_flux: 'Flux',
          type_node_total: 'Nœud (total)',
          type_stock: 'Stock',
          type_delta_stock: 'Δ stock',
          in: 'entrants',
          out: 'sortants',
          node: 'Nœud',
          origin: 'Origine',
          destination: 'Destination',
          search: 'Rechercher…',
          no_node: 'Aucun nœud',
          coef: 'coef',
          translation_label: 'Traduction (auto, modifiable)',
          translation_ph: 'Description en langage naturel',
          regenerate: 'régénérer',
          invalid_combo: 'Combinaison de termes non valide.',
          cancel: 'Annuler',
          add: 'Ajouter',
          desc_flux: 'flux {{orig}}→{{dest}}',
          desc_node_in: 'total des entrants de {{node}}',
          desc_node_out: 'total des sortants de {{node}}',
          desc_stock: 'stock de {{node}}',
          desc_delta: 'Δ stock de {{node}}'
        },
        doc: {
          title: 'Documentation',
          window_title: 'OpenSankey — Documentation',
          pos_sheet_right: 'À droite du tableur',
          pos_sheet_left: 'À gauche du tableur',
          pos_sheet_top: 'Au-dessus du tableur',
          pos_sheet_bottom: 'En-dessous du tableur',
          pos_diagram_bottom: 'Sous le diagramme',
          pos_window_bottom: 'Bandeau bas',
          pos_right: 'À droite',
          pos_left: 'À gauche',
          pos_top: 'Au-dessus',
          pos_bottom: 'En-dessous',
          with_sheet: 'Avec le tableur',
          under_diagram: 'Sous le diagramme',
          window_bottom_full: 'Bandeau bas (pleine largeur)',
          insert: 'Insérer',
          insert_image: 'Une image…',
          insert_views_outline: 'Titre + lien pour chaque vue',
          insert_view_link: 'Lien vers une vue',
          mode_edit: 'Édition',
          mode_split: 'Côte à côte',
          mode_preview: 'Aperçu',
          reattach: 'Ré-attacher la documentation dans la fenêtre principale',
          detach: 'Détacher la documentation dans une fenêtre séparée',
          editor_placeholder: 'Rédigez la documentation de ce diagramme en markdown…\n\n# Titre\n\n- point 1\n- point 2'
        },
        zone: {
          diagram: 'Diagramme',
          spreadsheet: 'Tableur',
          doc: 'Doc',
          documentation: 'Documentation',
          unitary: 'Sankey unitaire',
          unit: 'Unit.'
        }
      }
    }
  },
  //=======================================================
  // ES
  //=======================================================
  es: {
    translation: {
      Spreadsheet: {
        sheet: {
          flux: 'Flujos',
          analysis: 'Análisis de resultados',
          nodes: 'Nodos',
          nodes_agg: 'Nodos por agregación',
          tags: 'Etiquetas',
          stock: 'Existencias',
          ratio: 'Ratio de flujo',
          ratio_stock: 'Ratio existencia-flujo',
          stock_chaining: 'Encadenamiento de existencias',
          products: 'Productos',
          sectors: 'Sectores',
          exchanges: 'Intercambios',
          tes: 'TIO (matriz IO)',
          ter: 'TOR (empleos-recursos)'
        },
        header: {
          level: 'Nivel',
          level_n: 'Nivel {{n}}',
          name: 'Nombre',
          balance: 'Equilibrio',
          balance_io: 'Equilibrio entrada-salida',
          color: 'Color',
          definitions: 'Definiciones',
          column_u: 'Columna u',
          row_v: 'Fila v',
          origin: 'Origen',
          destination: 'Destino',
          value: 'Valor',
          min: 'Mín',
          max: 'Máx',
          computed_value: 'Valor calculado',
          dest_value: 'Valor destino',
          natural_quantity: 'Cantidad natural',
          uncertainty_pct: 'Incertidumbre %',
          source: 'Fuente',
          hypothesis: 'Hipótesis',
          computed_min: 'Mín calculado',
          computed_max: 'Máx calculado',
          delta_recon: 'Delta reconciliado - no reconciliado',
          gap_sigma: 'Desviación reconciliada (nº σ)',
          variable_type: 'Tipo de variable',
          node: 'Nodo',
          stock: 'Existencia',
          computed_stock: 'Existencia calculada',
          delta_stock: 'Δ Existencia',
          computed_delta: 'Δ calculada',
          coef: 'Coef',
          origin_ref: 'Origen ref',
          dest_ref: 'Destino ref',
          tag: 'Etiqueta',
          tag_ref: 'Etiqueta ref',
          translation: 'Traducción',
          delta_stock_plain: 'Delta existencia',
          dimension: 'Dimensión',
          tags: 'Etiquetas',
          tag_group_name: 'Nombre del grupo de etiquetas',
          tag_type: 'Tipo de etiqueta',
          colors: 'Colores',
          origin_dest: 'Origen ╲ Destino',
          resources: 'Recursos',
          uses: 'Empleos'
        },
        tagtype: {
          node: 'Nodo',
          level: 'Nivel',
          flux: 'Flujo',
          data: 'Dato'
        },
        classif: {
          measured: 'Medida',
          free_interval: 'Libre (intervalo)',
          determined: 'Determinada'
        },
        toolbar: {
          add_constraint: '+ Restricción',
          add_constraint_tip: 'Crear una restricción (flujo, existencia, total de nodo…) mediante un formulario guiado',
          parser: 'Analizar',
          parser_tip: 'Construye la jerarquía de agregación a partir de la columna Nivel',
          filter: 'Filtrar',
          filter_tip: 'Activa/desactiva los filtros de columna (estilo Excel) en esta pestaña',
          columns: 'Columnas',
          columns_count: 'Columnas ({{shown}}/{{total}})',
          sheets: 'Pestañas',
          sheets_count: 'Pestañas ({{shown}}/{{total}})',
          search: 'Buscar',
          select_all: '(Seleccionar todo)',
          show_all: 'Mostrar todo',
          only_visible: 'Solo visibles',
          display_filter_tip: 'Filtro de visualización de las filas de la hoja',
          placement_auto: 'Colocación: auto',
          placement_none: 'Colocación: ninguna',
          placement_increment: 'Colocación: incremental',
          placement_tip: 'Cómo colocar un nodo creado al añadir un flujo: auto (disposición completa), ninguna (posición por defecto), incremental (adivina el sitio sin mover los demás)',
          matrix_cross: 'Matriz: cruz',
          matrix_value: 'Matriz: valor',
          matrix_tip: 'Contenido de las celdas de la matriz: cruz (el flujo existe) o valor del flujo para el data_type seleccionado'
        },
        constraint: {
          title: 'Añadir una restricción',
          term1: 'Término 1',
          term2_ref: 'Término 2 (referencia)',
          type_flux: 'Flujo',
          type_node_total: 'Nodo (total)',
          type_stock: 'Existencia',
          type_delta_stock: 'Δ existencia',
          in: 'entrantes',
          out: 'salientes',
          node: 'Nodo',
          origin: 'Origen',
          destination: 'Destino',
          search: 'Buscar…',
          no_node: 'Ningún nodo',
          coef: 'coef',
          translation_label: 'Traducción (auto, editable)',
          translation_ph: 'Descripción en lenguaje natural',
          regenerate: 'regenerar',
          invalid_combo: 'Combinación de términos no válida.',
          cancel: 'Cancelar',
          add: 'Añadir',
          desc_flux: 'flujo {{orig}}→{{dest}}',
          desc_node_in: 'total de entrantes de {{node}}',
          desc_node_out: 'total de salientes de {{node}}',
          desc_stock: 'existencia de {{node}}',
          desc_delta: 'Δ existencia de {{node}}'
        },
        doc: {
          title: 'Documentación',
          window_title: 'OpenSankey — Documentación',
          pos_sheet_right: 'A la derecha de la hoja',
          pos_sheet_left: 'A la izquierda de la hoja',
          pos_sheet_top: 'Encima de la hoja',
          pos_sheet_bottom: 'Debajo de la hoja',
          pos_diagram_bottom: 'Debajo del diagrama',
          pos_window_bottom: 'Banda inferior',
          pos_right: 'A la derecha',
          pos_left: 'A la izquierda',
          pos_top: 'Encima',
          pos_bottom: 'Debajo',
          with_sheet: 'Con la hoja',
          under_diagram: 'Debajo del diagrama',
          window_bottom_full: 'Banda inferior (ancho completo)',
          insert: 'Insertar',
          insert_image: 'Una imagen…',
          insert_views_outline: 'Título + enlace por cada vista',
          insert_view_link: 'Enlace a una vista',
          mode_edit: 'Edición',
          mode_split: 'Lado a lado',
          mode_preview: 'Vista previa',
          reattach: 'Volver a anclar la documentación en la ventana principal',
          detach: 'Separar la documentación en una ventana aparte',
          editor_placeholder: 'Redacte la documentación de este diagrama en markdown…\n\n# Título\n\n- punto 1\n- punto 2'
        },
        zone: {
          diagram: 'Diagrama',
          spreadsheet: 'Hoja de cálculo',
          doc: 'Doc',
          documentation: 'Documentación',
          unitary: 'Sankey unitario',
          unit: 'Unit.'
        }
      }
    }
  },
  //=======================================================
  // DE
  //=======================================================
  de: {
    translation: {
      Spreadsheet: {
        sheet: {
          flux: 'Flüsse',
          analysis: 'Ergebnisanalyse',
          nodes: 'Knoten',
          nodes_agg: 'Knoten nach Aggregation',
          tags: 'Etiketten',
          stock: 'Bestände',
          ratio: 'Flussverhältnis',
          ratio_stock: 'Bestand-Fluss-Verhältnis',
          stock_chaining: 'Bestandsverkettung',
          products: 'Produkte',
          sectors: 'Sektoren',
          exchanges: 'Austausch',
          tes: 'IOT (IO-Matrix)',
          ter: 'AVT (Aufkommen-Verwendung)'
        },
        header: {
          level: 'Ebene',
          level_n: 'Ebene {{n}}',
          name: 'Name',
          balance: 'Gleichgewicht',
          balance_io: 'Eingang-Ausgang-Gleichgewicht',
          color: 'Farbe',
          definitions: 'Definitionen',
          column_u: 'Spalte u',
          row_v: 'Zeile v',
          origin: 'Quelle',
          destination: 'Ziel',
          value: 'Wert',
          min: 'Min',
          max: 'Max',
          computed_value: 'Berechneter Wert',
          dest_value: 'Zielwert',
          natural_quantity: 'Natürliche Menge',
          uncertainty_pct: 'Unsicherheit %',
          source: 'Quelle',
          hypothesis: 'Hypothese',
          computed_min: 'Berechnetes Min',
          computed_max: 'Berechnetes Max',
          delta_recon: 'Abgeglichenes - nicht abgeglichenes Delta',
          gap_sigma: 'Abgeglichene Abweichung (Anz. σ)',
          variable_type: 'Variablentyp',
          node: 'Knoten',
          stock: 'Bestand',
          computed_stock: 'Berechneter Bestand',
          delta_stock: 'Δ Bestand',
          computed_delta: 'Berechnetes Δ',
          coef: 'Koeff.',
          origin_ref: 'Quelle Ref',
          dest_ref: 'Ziel Ref',
          tag: 'Etikett',
          tag_ref: 'Etikett Ref',
          translation: 'Übersetzung',
          delta_stock_plain: 'Delta Bestand',
          dimension: 'Dimension',
          tags: 'Etiketten',
          tag_group_name: 'Name der Etikettengruppe',
          tag_type: 'Etikettentyp',
          colors: 'Farben',
          origin_dest: 'Quelle ╲ Ziel',
          resources: 'Ressourcen',
          uses: 'Verwendungen'
        },
        tagtype: {
          node: 'Knoten',
          level: 'Ebene',
          flux: 'Fluss',
          data: 'Daten'
        },
        classif: {
          measured: 'Gemessen',
          free_interval: 'Frei (Intervall)',
          determined: 'Bestimmt'
        },
        toolbar: {
          add_constraint: '+ Bedingung',
          add_constraint_tip: 'Eine Bedingung (Fluss, Bestand, Knotensumme…) über ein geführtes Formular erstellen',
          parser: 'Parsen',
          parser_tip: 'Erstellt die Aggregationshierarchie aus der Spalte Ebene',
          filter: 'Filtern',
          filter_tip: 'Aktiviert/deaktiviert die Spaltenfilter (Excel-Stil) auf diesem Blatt',
          columns: 'Spalten',
          columns_count: 'Spalten ({{shown}}/{{total}})',
          sheets: 'Blätter',
          sheets_count: 'Blätter ({{shown}}/{{total}})',
          search: 'Suchen',
          select_all: '(Alle auswählen)',
          show_all: 'Alle anzeigen',
          only_visible: 'Nur sichtbare',
          display_filter_tip: 'Anzeigefilter für die Zeilen der Tabelle',
          placement_auto: 'Platzierung: auto',
          placement_none: 'Platzierung: keine',
          placement_increment: 'Platzierung: inkrementell',
          placement_tip: 'Wie ein durch Hinzufügen eines Flusses erstellter Knoten positioniert wird: auto (vollständige Anordnung), keine (Standardposition), inkrementell (errät den Platz, ohne die anderen zu verschieben)',
          matrix_cross: 'Matrix: Kreuz',
          matrix_value: 'Matrix: Wert',
          matrix_tip: 'Inhalt der Matrixzellen: Kreuz (der Fluss existiert) oder Flusswert für den ausgewählten data_type'
        },
        constraint: {
          title: 'Eine Bedingung hinzufügen',
          term1: 'Term 1',
          term2_ref: 'Term 2 (Referenz)',
          type_flux: 'Fluss',
          type_node_total: 'Knoten (Summe)',
          type_stock: 'Bestand',
          type_delta_stock: 'Δ Bestand',
          in: 'eingehend',
          out: 'ausgehend',
          node: 'Knoten',
          origin: 'Quelle',
          destination: 'Ziel',
          search: 'Suchen…',
          no_node: 'Kein Knoten',
          coef: 'Koeff.',
          translation_label: 'Übersetzung (auto, bearbeitbar)',
          translation_ph: 'Beschreibung in natürlicher Sprache',
          regenerate: 'neu erzeugen',
          invalid_combo: 'Ungültige Termkombination.',
          cancel: 'Abbrechen',
          add: 'Hinzufügen',
          desc_flux: 'Fluss {{orig}}→{{dest}}',
          desc_node_in: 'Summe eingehend von {{node}}',
          desc_node_out: 'Summe ausgehend von {{node}}',
          desc_stock: 'Bestand von {{node}}',
          desc_delta: 'Δ Bestand von {{node}}'
        },
        doc: {
          title: 'Dokumentation',
          window_title: 'OpenSankey — Dokumentation',
          pos_sheet_right: 'Rechts von der Tabelle',
          pos_sheet_left: 'Links von der Tabelle',
          pos_sheet_top: 'Über der Tabelle',
          pos_sheet_bottom: 'Unter der Tabelle',
          pos_diagram_bottom: 'Unter dem Diagramm',
          pos_window_bottom: 'Untere Leiste',
          pos_right: 'Rechts',
          pos_left: 'Links',
          pos_top: 'Oben',
          pos_bottom: 'Unten',
          with_sheet: 'Mit der Tabelle',
          under_diagram: 'Unter dem Diagramm',
          window_bottom_full: 'Untere Leiste (volle Breite)',
          insert: 'Einfügen',
          insert_image: 'Ein Bild…',
          insert_views_outline: 'Titel + Link für jede Ansicht',
          insert_view_link: 'Link zu einer Ansicht',
          mode_edit: 'Bearbeiten',
          mode_split: 'Nebeneinander',
          mode_preview: 'Vorschau',
          reattach: 'Dokumentation wieder im Hauptfenster andocken',
          detach: 'Dokumentation in einem separaten Fenster lösen',
          editor_placeholder: 'Verfassen Sie die Dokumentation dieses Diagramms in Markdown…\n\n# Titel\n\n- Punkt 1\n- Punkt 2'
        },
        zone: {
          diagram: 'Diagramm',
          spreadsheet: 'Tabelle',
          doc: 'Doc',
          documentation: 'Dokumentation',
          unitary: 'Unitäres Sankey',
          unit: 'Einh.'
        }
      }
    }
  },
  //=======================================================
  // IT
  //=======================================================
  it: {
    translation: {
      Spreadsheet: {
        sheet: {
          flux: 'Flussi',
          analysis: 'Analisi dei risultati',
          nodes: 'Nodi',
          nodes_agg: 'Nodi per aggregazione',
          tags: 'Etichette',
          stock: 'Scorte',
          ratio: 'Rapporto flusso',
          ratio_stock: 'Rapporto scorta-flusso',
          stock_chaining: 'Concatenamento scorte',
          products: 'Prodotti',
          sectors: 'Settori',
          exchanges: 'Scambi',
          tes: 'TIO (matrice IO)',
          ter: 'TOR (impieghi-risorse)'
        },
        header: {
          level: 'Livello',
          level_n: 'Livello {{n}}',
          name: 'Nome',
          balance: 'Equilibrio',
          balance_io: 'Equilibrio entrata-uscita',
          color: 'Colore',
          definitions: 'Definizioni',
          column_u: 'Colonna u',
          row_v: 'Riga v',
          origin: 'Origine',
          destination: 'Destinazione',
          value: 'Valore',
          min: 'Min',
          max: 'Max',
          computed_value: 'Valore calcolato',
          dest_value: 'Valore destinazione',
          natural_quantity: 'Quantità naturale',
          uncertainty_pct: 'Incertezza %',
          source: 'Fonte',
          hypothesis: 'Ipotesi',
          computed_min: 'Min calcolato',
          computed_max: 'Max calcolato',
          delta_recon: 'Delta riconciliato - non riconciliato',
          gap_sigma: 'Scarto riconciliato (n. σ)',
          variable_type: 'Tipo di variabile',
          node: 'Nodo',
          stock: 'Scorta',
          computed_stock: 'Scorta calcolata',
          delta_stock: 'Δ Scorta',
          computed_delta: 'Δ calcolata',
          coef: 'Coef',
          origin_ref: 'Origine rif',
          dest_ref: 'Destinazione rif',
          tag: 'Etichetta',
          tag_ref: 'Etichetta rif',
          translation: 'Traduzione',
          delta_stock_plain: 'Delta scorta',
          dimension: 'Dimensione',
          tags: 'Etichette',
          tag_group_name: 'Nome del gruppo di etichette',
          tag_type: 'Tipo di etichetta',
          colors: 'Colori',
          origin_dest: 'Origine ╲ Destinazione',
          resources: 'Risorse',
          uses: 'Impieghi'
        },
        tagtype: {
          node: 'Nodo',
          level: 'Livello',
          flux: 'Flusso',
          data: 'Dato'
        },
        classif: {
          measured: 'Misurata',
          free_interval: 'Libera (intervallo)',
          determined: 'Determinata'
        },
        toolbar: {
          add_constraint: '+ Vincolo',
          add_constraint_tip: 'Creare un vincolo (flusso, scorta, totale di nodo…) tramite un modulo guidato',
          parser: 'Analizza',
          parser_tip: 'Costruisce la gerarchia di aggregazione dalla colonna Livello',
          filter: 'Filtra',
          filter_tip: 'Attiva/disattiva i filtri di colonna (stile Excel) su questo foglio',
          columns: 'Colonne',
          columns_count: 'Colonne ({{shown}}/{{total}})',
          sheets: 'Fogli',
          sheets_count: 'Fogli ({{shown}}/{{total}})',
          search: 'Cerca',
          select_all: '(Seleziona tutto)',
          show_all: 'Mostra tutto',
          only_visible: 'Solo visibili',
          display_filter_tip: 'Filtro di visualizzazione delle righe del foglio',
          placement_auto: 'Posizionamento: auto',
          placement_none: 'Posizionamento: nessuno',
          placement_increment: 'Posizionamento: incrementale',
          placement_tip: 'Come posizionare un nodo creato aggiungendo un flusso: auto (disposizione completa), nessuno (posizione predefinita), incrementale (indovina il posto senza spostare gli altri)',
          matrix_cross: 'Matrice: croce',
          matrix_value: 'Matrice: valore',
          matrix_tip: 'Contenuto delle celle della matrice: croce (il flusso esiste) o valore del flusso per il data_type selezionato'
        },
        constraint: {
          title: 'Aggiungere un vincolo',
          term1: 'Termine 1',
          term2_ref: 'Termine 2 (riferimento)',
          type_flux: 'Flusso',
          type_node_total: 'Nodo (totale)',
          type_stock: 'Scorta',
          type_delta_stock: 'Δ scorta',
          in: 'entranti',
          out: 'uscenti',
          node: 'Nodo',
          origin: 'Origine',
          destination: 'Destinazione',
          search: 'Cerca…',
          no_node: 'Nessun nodo',
          coef: 'coef',
          translation_label: 'Traduzione (auto, modificabile)',
          translation_ph: 'Descrizione in linguaggio naturale',
          regenerate: 'rigenera',
          invalid_combo: 'Combinazione di termini non valida.',
          cancel: 'Annulla',
          add: 'Aggiungi',
          desc_flux: 'flusso {{orig}}→{{dest}}',
          desc_node_in: 'totale entranti di {{node}}',
          desc_node_out: 'totale uscenti di {{node}}',
          desc_stock: 'scorta di {{node}}',
          desc_delta: 'Δ scorta di {{node}}'
        },
        doc: {
          title: 'Documentazione',
          window_title: 'OpenSankey — Documentazione',
          pos_sheet_right: 'A destra del foglio',
          pos_sheet_left: 'A sinistra del foglio',
          pos_sheet_top: 'Sopra il foglio',
          pos_sheet_bottom: 'Sotto il foglio',
          pos_diagram_bottom: 'Sotto il diagramma',
          pos_window_bottom: 'Banda inferiore',
          pos_right: 'A destra',
          pos_left: 'A sinistra',
          pos_top: 'Sopra',
          pos_bottom: 'Sotto',
          with_sheet: 'Con il foglio',
          under_diagram: 'Sotto il diagramma',
          window_bottom_full: 'Banda inferiore (larghezza piena)',
          insert: 'Inserisci',
          insert_image: 'Un\'immagine…',
          insert_views_outline: 'Titolo + link per ogni vista',
          insert_view_link: 'Link a una vista',
          mode_edit: 'Modifica',
          mode_split: 'Affiancato',
          mode_preview: 'Anteprima',
          reattach: 'Riancorare la documentazione nella finestra principale',
          detach: 'Staccare la documentazione in una finestra separata',
          editor_placeholder: 'Redigi la documentazione di questo diagramma in markdown…\n\n# Titolo\n\n- punto 1\n- punto 2'
        },
        zone: {
          diagram: 'Diagramma',
          spreadsheet: 'Foglio di calcolo',
          doc: 'Doc',
          documentation: 'Documentazione',
          unitary: 'Sankey unitario',
          unit: 'Unit.'
        }
      }
    }
  }
}
