import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
// the translations
// (tip move them in a JSON file and import them,
// or even better, manage them separated from your code: https://react.i18next.com/guides/multiple-translation-files)
const resources = {
  en: {
    translation: {
      Menu:{
        'confSankey': 'Sankey\'s configuration',
        'MEP':'Global layout',
        'Noeuds':'Nodes',
        'EN':'Nodes\' tags',
        'EdN':'Editing nodes',
        'flux':'Links',
        'EF':'Links\' tags',
        'EdF':'Editing links',
        'ED':'Data\'s tags',
        'LL':'Free labels',
        'Leg':'Legends',
        'LegX':'Horizontal position',
        'LegY':'Vertical position',
        'LegWidth':'Width',
        'Fichiers':'Files',
        'Edition':'Edition',
        'Formations':'Tutorials',
        'Exemples':'Demos',
        'Aide':'Help',
        'ouvrir':'Open',
        'enregistrer':'Save',
        'exporter':'Export',
        'preference':'Preferences',
        'reinit':'Reset',
        'pub':'Publish',
        'amp':'Import a layout',
        'esn':'Edit nodes style',
        'esf':'Edit links style',
        'rc':'Keyboard Shortcuts',
        'as':'Additional Help',
        'doc': 'Documentation',
        'ca':'Path',
        'annuler':'Cancel',
        'pdd':'Publish/Update diagram',
        'fmep':'Layout file',
        'ad':'Apply the layout',
        'ns':'Style name',
        'BgC':'Sankey background color',
        'dns':'Display only visible nodes in the nodes selector',
        'dls':'Display only visible links in the links selector',
        'textDisposition':'Apply the modifications on :',
        'PosNoeud':'Nodes\' positions',
        'attrNode':'Nodes\' attributes',
        'attrFlux':'Links\' attributes',
        'tagNode':'Nodes\' tags',
        'tagFlux':'Links\' tags',
        'attrGeneral':'Generals attributes',
        'SaveJSON':'Save as JSON',
        'SaveValue':'Save with links\' values',
        'templates':'Templates',
        'warningLimitNode':'Warning : Limit of node reach for unconnected user',
        tooltips:{
          noeud:{
            slct: 'Choose one / some / all nodes to select via a drop-down list',
            plus: 'Add a node, which will be automatically selected.',
            rm: 'Allow to delete all currently selected nodes',
            dns: 'Display in the node selection list, only the node(s) that is/are currently visible in the graphic space'
          },
          flux:{
            slct: 'Choose one / some / all link(s) to select via a drop-down list',
            plus: 'Add a new link. This one will be automatically selected.',
            rm: 'Allow to delete currently selected link(s)',
            dls: 'Display in the list of selection of link(s), only the link(s) that is/are currently visible on the graphic space',
          },
          LegX: 'Horizontal distance (in px) between the upper left corner of the legend and the upper left corner of the window',
          LegY: 'Vertical distance (in px) between the upper left corner of the legend and the upper left corner of the window',
          LegWidth: 'Width (in px) for the legend space',
          BgC: 'Change the background color of the interactive graphic space',
        }
      },
      MEP:{
        'Echelle':'Scale of diagram',
        'MaxFlux':'Maximal value for links (px)',
        'vp100':'value for 100px',
        'TCG':'Background grid',
        'AN':'Arrange the nodes on the grid',
        'Horizontal':'Horizontal spacing between nodes',
        'Vertical':'Vertical spacing between nodes',
        'PA':'Automatic positioning of nodes and links',
        tooltips: {
          Echelle: 'Change the scale of the links and nodes',
          MaxFlux: 'Change the maximum size (in pixels) for the display of the links',
          TCG: 'Size of the background grid tiles (in pixels)',
          GV: 'Enable or disable the display of the background grid',
          AN: 'Automatically arrange nodes: ie come and paste the upper left corner of the nodes on the nearest grid corner',
          EEN_h: 'Default horizontal distance (in pixel) between nodes for automatic positioning',
          EEN_v: 'Default vertical distance (in pixel) between nodes for automatic positioning',
          PA: 'Perform an automatic positioning of the nodes according to the specified default distances'
        }
      },
      Tags:{
        'Nom':'Name',
        'Leg':'Legend',
        'tags':'Tags',
        'Bannière':'Banner',
        'Position':'Position',
        'Aucun':'None',
        'Unique':'Unique',
        'Multiple':'Multiple',
        'Niveau' : 'Level',
        'Visible':'Visible',
        'Couleur':'Color',
        'Forme':'Shape',
        'GE':'Tags\' Group',
        'selct':'Selected',
        tooltips: {
          pal: 'Apply a random color palette for the tags of the selected group',
          pal_shuffle: 'Change the order of the colors applied to the tags of the selected group',
          pal_std: 'Choose a standard color palette for the tags of the selected group',
          add: 'Add a tag to the selected group',
          add_grp: 'Add a tag group',
          rm: 'Delete the tag',
          rm_grp: 'Delete this tag group',
          nom: 'Rename the current tag',
          nom_grp: 'Rename this tag group',
          leg_grp: 'Activate or not the legend on the filtering of this group of tags and therefore the colors associated with the tags of this group',
          visible: 'Choose to make visible or not the nodes associated with this tag',
          couleur: 'Change the color of the current tag',
          forme: 'Choose the shape of the nodes associated with this tag',
          banner: 'Choose the type of dropdown menu on the filtering of this tag group (None / Single / Multiple / LevelTags)',
          up: 'Move the tag group up in the node filtering menu',
          down: 'Move the tag group down in the node filter menu'
        }
      },
      Noeud:{
        'Nom':'Name',
        'Style':'Style',
        'AS':'Apply the style',
        'TS':'Select all',
        'NS':'No node selected',
        'Reorg':'Reorganize incoming/outgoing links',
        'SlctOutLink':'Select outgoing links',
        'SlctInLink':'Select incoming links',
        'IB':'Tooltip',
        tooltips:{
          Nom: 'Change the name of the selected node. If several nodes are selected, this field is disabled',
          AS: 'Allow to apply a predefined style in the preference menu to the selected node(s)',
          Reorg:'Allows automatic reorganization of incoming and outgoing flows (up/down position)',
          SlctOutLink:'Allow to select all outgoing flows from the node(s)',
          SlctInLink:'Allow to select all incoming flows to the node(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the node. This tooltip pops on graphic space with SHIFT + MOUSE on the node.'
        },
        apparence:{
          'apparence':'Appearence',
          'Visibilité':'Visibility',
          'Couleur':'Color',
          'CouleurPérenne':'Static color',
          'Forme':'Shape',
          'Cercle':'Circle',
          'Rectangle':'Rectangle',
          'TML':'Minimum width',
          'TMH': 'Minimum height',
          'HideAlone':'Hide if node is intermediate',
          'asn':'Apply style to nodes',
          'toScale':'Node out of scale',
          'Orientation':'Orientation : ',
          'toScaleBottom':'to the bottom',
          'toScaleTop':'to the top',
          'toScaleLeft':'to the left',
          'toScaleRight':'to the right',
          tooltips: {
            Visibilité: 'Makes the selected node(s) visible or invisible',
            Couleur: 'Choose the color of the selected node(s)',
            CouleurPérenne: 'Keep the color of the node(s) if any flux or data filter is activated, otherwise node turns grey (default color)',
            Forme: 'Choose a shape between rectangle or circle for the selected node(s)',
            TML: 'Minimum width in pixels of the selected node(s)',
            TMH: 'Minimum height in pixels of the selected node(s)'
          }
        },
        labels:{
          'labels':'Labels',
          'vdb':'Label visibility',
          'lb':'White label',
          'pv':'Vertical position',
          'haut':'Top',
          'Milieu':'Middle',
          'Bas':'Bottom',
          'ph':'Horizontal position',
          'gauche':'Left',
          'droite':'Right',
          'tp':'Font size',
          'police':'Font type',
          'gras':'Bold',
          'maj':'Uppercase',
          'ita':'Italic',
          'cl':'Text box width',
          'vdv':'Set value visibility',
          tooltips: {
            vdb: 'Displays or not the label(s) attached to the selected node(s)',
            lb: 'Displays the text of the label(s) in white or black (useful if label is positioned on node(s))',
            top: 'Displays the label(s) above the selected node(s)',
            Milieu_pv: 'Displays the label(s) in the middle (vertically) of the selected node(s)',
            Bas: 'Displays the label(s) below the selected node(s)',
            gauche: 'Displays the label(s) to the left of the selected node(s)',
            Milieu_ph: 'Displays the label(s) in the middle (horizontally) of the selected node(s)',
            droite: 'Displays the label(s) to the right of the selected node(s)',
            cl: 'Width of the text area (in pixels) for the label(s) of the selected node(s)',
            vdv: 'Displays or not the associated value with the selected node(s)',
            haut_val: 'Displays the associated value above the selected node(s)',
            Milieu_pv_val: 'Displays the associated value in the middle (vertically) of the selected node(s)',
            Bas_val: 'Displays the associated value below the selected node(s)',
            gauche_val: 'Displays the associated value to the left of the selected node(s)',
            Milieu_ph_val: 'Displays the associated value in the middle (horizontally) of the selected node(s)',
            droite_val: 'Displays the associated value to the right of the selected node(s)',
          }
        },
        icon:{
          'icon':'Icon',
          'si':'Select icon',
          'couleur':'Color',
          'rIN':'Size ratio icon/node',
          'Aucun':'None'
        },
        tags_node:{
          'tags':'Tags',
          'Appartenance':'Affiliations'
        },
        agre:{
          'Agré':'Aggregation',
          'DC':'Cube\'s dimensions',
          'Parent':'Parent',
          'CLE':'Copy childs\' links'
        },
        PF:{
          'PF':'I/O links positions',
          'FES':'Links type',
          'ent':'Input',
          'sort':'Output',
          'FRN':'Relative position to the node',
          'gauche':'Left',
          'droite':'Right',
          'ades':'Above',
          'edes':'Below',
          'lti':'Identify the links in the table with their colors',
          'col':'Apply',
          tooltips:{
            ent: 'Display in the table below, the incoming links of the selected node(s)',
            sort: 'Display in the table below, the outgoing links of the selected node(s)',
            droite: 'Display in the table below, the links on the right of the selected node(s)',
            gauche: 'Display in the table below, the links on the left of the selected node(s)',
            ades: 'Display in the table below, the feeds above the selected node(s)',
            edes: 'Display in the table below, the feeds below the selected node(s)',
            lti: 'Display the lines of the links table with their respective colors to better identify them'
          }
        }
      },
      Flux:{
        'pg': 'General settings',
        'pdl':'Font',
        'pl': 'Parameters per link',
        'src':'Source',
        'trgt':'Target',
        'if':'Reverse direction',
        'dzf':'Relative overlay on display',
        'style':'Style',
        'as':'Apply the style to selected link(s)',
        'IB':'ToolTip',
        tooltips: {
          src: 'Choice of the departure node for the selected link(s)',
          trgt: 'Choice of the arrival node for the selected link(s)',
          if: 'Reverse the start and finish nodes for the selected link(s)',
          up: 'Move up one step to the foreground',
          upup: 'Put the selected stream(s) in the foreground',
          dwn: 'Go down one step to the last plane',
          dwndwn: 'Move the selected stream(s) to the last plane',
          as: 'Allow to apply a predefined style in the preference menu to the selected link(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the link. This tooltip pops on graphic space with SHIFT + MOUSE on the link.'
        },
        data:{
          'données':'Data',
          'vpp':'Value for given parameters',
          'affichage':'Display',
          'toPrecision':'Display the value in scientific notation',
          tooltips: {
            vpp: 'Data associated to the selected link and, if existing, for the selected tag(s)',
            toPrecision: 'Activate or not the notation in scientific format, for the display of the link\'s data on the Sankey diagram',
            affichage: 'Replacement text for the display of the link\'s data on the Sankey diagram'
          }
        },
        apparence:{
          'apparence':'Appearance',
          'couleur':'Color',
          'grad':'Gradient',
          'hach':'Dashed',
          'of':'Orientation',
          'pdc':'Position of the center point (%)',
          'eep':'Position of the centers of curvature (%)',
          'type':'Type',
          'courbe':'Curve',
          'fleche':'Arrow',
          'recy':'Recycling',
          'courbure':'Curvature',
          tooltips: {
            couleur: 'Choose the color for the selected link(s)',
            grad: 'Apply a gradient color effect on the selected link(s). The gradient is done between the color of the start node and the color of the end node',
            hach: 'Applies a hatch effect on the selected link(s)',
            of_vv: 'Allows to orient the beginning of the link vertically and the end of the link vertically',
            of_hh: 'Allows to orient the beginning of the link horizontally and the end of the link horizontally',
            of_hv: 'Allows to orient the beginning of the link horizontally and the end of the link vertically',
            of_vh: 'Allows to orient the beginning of the link vertically and the end of the link horizontally',
            pdc: 'Allows to refine the position of the center of the selected link(s). This value is a ratio (%) relative to the starting point of the link',
            eep: 'Allows to refine the positions of the centers of curvature of the selected link(s). This value is a ratio (%) relative to the center point of the link. These centers of curvature are mirrored with respect to the center of the link(s)',
            courbe: 'Represents the selected link(s) as a Bezier curve',
            fleche: 'Represents the selected link(s) with an arrow tip at the end',
            recy: 'Represents the selected link(s) as a recycle, i.e. with a backward turn',
            courbure: 'Setting the radius of curvature in case the selected link(s) are represented as Bezier curve(s)'
          }
        },
        label:{
          'label':'Label',
          'vdb':'Label visibility',
          'len':'Black label',
          'lb':'White label',
          'lec':'Colored label',
          'acf':'Orient along the link axis',
          'pl':'Lateral position',
          'po':'Orthogonal position',
          'milieu': 'Middle',
          'deb':'Start',
          'fin':'End',
          'dessous':'Above',
          'dessus':'Below',
          'pls':'Position the label with the mouse',
          tooltips: {
            label: 'Display or not the label (data / text) associated to the selected link(s)',
            len: 'Display the label in black, for the selected stream(s)',
            lb: 'Display the label in white, for the selected stream(s)',
            lec: 'Display the label with the same color(s) as the one(s) associated with the selected stream(s)',
            acf: 'For the selected stream(s), allows to orient the label following the shape of the associated stream',
            deb: 'For the selected link(s), allows to position the label towards the starting point of the link',
            milieu_h: 'For the selected link(s), allows to position the label between the starting point and the end point of the link',
            end: 'For the selected stream(s), allows to position the label towards the end point of the stream',
            below: 'For the selected stream(s), allows to position the label below the stream',
            milieu_v: 'For the selected link(s), allows to position the label inside the link',
            top: 'For the selected stream(s), allows to position the label above the stream',
            pls: 'Activates the possibility to move the label of the selected stream(s) with the mouse'
          }
        }
      },
      LL:{
        'hl':'Label Height',
        'll':'Label Width',
        'ft':'Background opacity',
        'cfl':'Background Color',
        'bt':'Transparent border',
        'cbl':'Border Color',
        'pvt':'Vertical position',
        'at':'Texte alignment',
        'labels':'Labels',
        'gras':'Bold',
        'maj':'Uppercase',
        'ita':'Italic',
        'centre':'Centre',
        'textAsHTML':'foreignObject label',
        'editorRaw':'Editeur brut'

      },
      Banner:{
        'data':'Data',
        'filter':'Filter',
        'fdf':'Link filtering',
        'fdn':'Node Filtering',
        'ndd':'Levels of detail',
        'ndd_lst':'Tags groups',
        'ndd_chk':'Apply the groups\' colors',
        'sdr':'Diagram type',
        'sdd':'Data selection',
        'tl':'Download',
        'rslt': 'Download results',
        'ff':'Links visual filtering',
        'filtre':'Threshold value for links dislay',
        'fl':'Threshold value for labels display',
        'fn':'Null Link',
        'visible':'Visible',
        'hlp':'Help',
        'hlp_1':'Sankey diagram',
        'hlp_1_txt_1':'The thickness of an arrow is proportional to the value of the flux it represents.',
        'hlp_1_txt_2':'The diagram can be viewed with different levels of aggregation using the Level of Detail> selector',
        'hlp_1_txt_3':'Filters can be used to display only parts of the diagram. To do this use the selectors',
        'hlp_1_txt_4':'Different color palettes can be used to color nodes and flows using the Color Palette selector',
        'hlp_1_txt_5':'The diagram structure (without link thickness) can be displayed by checking Diagram structure',
        'hlp_1_txt_6':'The diagram can be adjusted on screen by checking Adjust on screen',
        'hlp_1_txt_7':'To get information about each link, press shift and move the mouse over the link',
        'hlp_1_txt_8':'To hide link/link\'s label when their value is under a threshold.',
        'hlp_1_txt_9':'Dropdown to filter node/link/data according to their group tag or to choose to display the diagram with color palette from a tag group.',
        'tooltipAdjust':'Readjust the drawing area to the screen size',
        'tooltipStructure':'Allows to display the structure of the diagram without proportion of the flows according to their value',
        'tooltipData':'Allows to display the data of the diagram',
        'tooltipSelection':'Allows to drag the nodes',
        'tooltipHelp':'Show the help dialog',
        'tooltipAjoutNode':'Adds a node to the mouse click',
        'tooltipLiason':'Allows to create links between two existing nodes, from an existing node or to an existing node'
      },
      welcome:{
        'welcome':'Welcome to OpenSankey web application',
        'exemple1':'Exemple of a sankey diagram with gradient links (functionality from Opensankey+) ',
        'exemple2':'Exemple of a sankey diagram realised with Opensankey',

        'introduction':'Introduction to OpenSankey web application',
        1:'Bouton de sélection du mode de la souris, il existe 2 modes : un mode permettant de sélectionner les noeuds et flux pour pouvoir les déplacer, puis un mode permettant de créer des liens et noeuds aux cliques de la souris',
        2:'Boutons permettant de filtrer la visibilité ou couleurs des noeuds et flux en fonction des groupes auxquels ils sont associés',
        3:'Bouton permettant de filtrer les noeuds en fonction de leur niveau d\'agrégation',
        4:'Bouton permettant de filtrer la visibilité des flux en fonction de leurs valeurs, ce bouton permet aussi de modifier l\'échelle du diagramme (l\'épaisseur des flux)',
        5:'Bouton permettant de réajuster la taille de la zone de dessin pour que tous les éléments soient visibles',
        6:'Bouton permettant d\'afficher le diagramme sans prendre en compte la valeur des flux',
        7:'Bouton permettant d`\'afficher de l\'aide supplémentaire',
        8:'Menu de navigation permettant d\'ouvrir, enregistrer, éditer des sankeys ',
        9:'Bouton permettant de se connecter avec un compte opensankey et activer des modules supplémentaires',
        10:'Bouton permettant d\'ouvrir le menu de configuration qui permet d\'éditer les éléments du diagramme de sankey',
      },
      'DisplayWelcome':'Display Bienvenue',
      'dontSeeAgain':'Don\'t show again',
      'scale':'Scale'

    }
  },
  //=======================================================
  //FR
  //=======================================================
  fr: {
    translation: {
      Menu:{
        'confSankey': 'Configuration du Sankey',
        'MEP':'Mise en page',
        'Noeuds':'Noeuds',
        'EN':'Étiquettes des noeuds',
        'EdN':'Édition des noeuds',
        'flux':'Flux',
        'EF':'Étiquettes des flux',
        'EdF':'Édition des flux',
        'ED':'Étiquettes des données',
        'LL':'Label libres',
        'Leg':'Legendes',
        'LegX':'Position horizontale',
        'LegY':'Position verticale',
        'LegWidth':'Largeur',
        'Fichiers':'Fichiers',
        'Edition':'Édition',
        'Formations':'Tutoriels',
        'Exemples':'Démos',
        'Aide':'Aide',
        'ouvrir':'Ouvrir',
        'enregistrer':'Enregistrer',
        'exporter':'Exporter',
        'preference':'Préférences',
        'reinit':'Réinitialiser',
        'pub':'Publier',
        'amp':'Importer une mise en page',
        'esn':'Editer le style des noeuds',
        'esf':'Editer le style des flux',
        'rc':'Raccourcis clavier',
        'as':'Aide Supplémentaire',
        'doc': 'Documentation',
        'ca':'Chemin d\'accés',
        'annuler':'Annuler',
        'pdd':'Publier/Mettre à jour le diagramme',
        'fmep':'Fichier de mise en page',
        'ad':'Appliquer la mise en page',
        'ns':'Nom du Style',
        'BgC':'Couleur du fond de page',
        'dns':'N\'affiche que les noeuds visibles dans le sélecteur de noeuds',
        'dls':'N\'affiche que les flux visibles dans le sélecteur de flux',
        'textDisposition':'Appliquer les modifications sur :',
        'PosNoeud':'Positions des noeuds',
        'attrNode':'Attributs des noeuds',
        'attrFlux':'Attributs des flux',
        'tagNode':'Etiquettes des noeuds',
        'tagFlux':'Etiquettes des flux',
        'attrGeneral':'Attributs généraux',
        'SaveJSON':'Enregistrer JSON',
        'SaveValue':'Enregistrer avec les valeurs des flux',
        'templates':'Modèles',
        'warningLimitNode':'Attention :Nombre de noeuds limite atteint pour les utilisateurs non connecté',
        tooltips:{
          noeud:{
            slct: 'Choisir un / des / tous les noeud(s) à sélectionner via une liste déroulante',
            plus: 'Ajouter un noeud. Celui-ci sera automatiquement selectionné.',
            rm: 'Permettre de supprimer tous les noeud(s) actuellement sélectionné(s)',
            dns: 'Afficher dans la liste de selection des noeuds, uniquement ceux actuellement visibles sur l\'espace graphique'
          },
          flux:{
            slct: 'Choisir un / des / tous les flux à sélectionner via une liste déroulante',
            plus: 'Ajouter un flux. Celui-ci sera automatiquement selectionné.',
            rm: 'Permettre de supprimer tous les flux actuellement sélectionné(s)',
            dls: 'Afficher dans la liste de selection des flux, uniquement ceux actuellement visibles sur l\'espace graphique',
          },
          LegX: 'Ecart horizontal (en px) entre le coin supérieur gauche de la légende par rapport au coin supérieur gauche de la fenêtre',
          LegY: 'Ecart vertical (en px) entre le coin supérieur gauche de la légende par rapport au coin supérieur gauche de la fenêtre',
          LegWidth: 'Largeur (en px) de l\'espace de la légende',
          BgC: 'Changer la couleur fond de l\'espace graphique interactif',
        }
      },
      MEP:{
        'Echelle': 'Echelle du diagramme',
        'MaxFlux': 'Taille maximale des flux (px)',
        'vp100':'valeur pour 100px',
        'TCG':'Quadrillage en fond',
        'AN':'Arranger les noeuds sur le quadrillage',
        'Horizontal':'Ecartement horizontal des noeuds',
        'Vertical':'Ecartement vertical des noeuds',
        'PA':'Positionnement automatique des noeuds et flux',
        tooltips: {
          Echelle: 'Modifier l\'échelle des flux et noeuds',
          MaxFlux: 'Modifier la taille maximale (en pixel) pour l\'affichage des flux',
          TCG: 'Taille des carreaux de la grille de fond (en pixel)',
          GV: 'Activer ou désactiver l\'affichage de la grille de fond',
          AN: 'Arrangement automatiquement les noeuds : ie venir coller le coin supérieur gauche des noeuds sur le coin de grille le plus proche',
          EEN_h: 'Ecart horizontal par défaut (en pixel) entre les noeuds pour un positionnement automatique',
          EEN_v: 'Ecart vertical par défaut (en pixel) entre les noeuds pour un positionnement automatique',
          PA: 'Réaliser un positionnement automatique des noeuds en fonction des écarts par défaut spécifiés'
        }
      },
      Tags:{
        'Nom':'Nom',
        'Leg':'Légende',
        'tags':'Étiquette',
        'Bannière':'Bannière',
        'Position':'Position',
        'Aucun':'Aucun',
        'Unique':'Unique',
        'Multiple':'Multiple',
        'Niveau': 'Niveau',
        'Visible':'Visible',
        'Couleur':'Couleur',
        'Forme':'Forme',
        'GE':'Groupe d\'étiquettes',
        'selct':'Sélectionné',
        tooltips: {
          pal: 'Appliquer une palette de couleurs aléatoires pour les étiquettes du groupe sélectionné',
          pal_shuffle: 'Changer l\'ordre des couleur appliquées aux étiquettes du groupe sélectionné',
          pal_std: 'Choisir une palette de couleurs standard pour les étiquettes du groupe sélectionné',
          add: 'Ajouter une étiquette au groupe sélectionné',
          add_grp: 'Ajouter un groupe d\'étiquette',
          rm: 'Supprimer l\'étiquette',
          rm_grp: 'Supprimer ce groupe d\'étiquette',
          nom: 'Renommer l\'étiquette courante',
          nom_grp: 'Renommer ce groupe d\'étiquette',
          leg_grp: ' Active ou non la légende sur le filtrage de ce groupe d\'étiquettes et donc les couleurs associées aux étiquettes de ce groupe',
          visible: 'Choisir de rendre visible ou non les noeuds associés à cette étiquette',
          couleur: 'Changer la couleur de l\'étiquette courante',
          forme: 'Choisir la forme des noeuds associés à cette étiquette',
          banner: 'Choisir le type de menu déroulant sur le filtrage de ce groupe d\'étiquettes (Aucun / Unique / multiple / LevelTags)',
          up: 'Monter le groupe d\'étiquettes dans le menu de filtrage des noeuds',
          down: 'Descendre le groupe d\'étiquettes dans le menu de filtrage des noeuds'
        }
      },
      Noeud:{
        'Nom':'Nom',
        'Style':'Style',
        'AS':'Appliquer le style',
        'TS':'Tout sélectionner',
        'NS':'Aucun noeud sélectionné',
        'Reorg':'Réorganiser flux',
        'SlctOutLink':'Sélectionner flux sortants',
        'SlctInLink':'Sélectionner flux entrants',
        'IB':'Info-bulle',
        tooltips:{
          Nom: 'Changer le nom du noeud sélectionné. Si plusieurs noeuds sont sélectionnés, ce champ est désactivé',
          AS: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) noeud(s) selectionné(s)',
          Reorg: 'Permet de réorganiser automatiquement les flux entrant et sortant (position haut / bas)',
          SlctOutLink: 'Permettre de sélectionner tous les flux sortants du/des noeud(s)',
          SlctInLink: 'Permettre de sélectionner tous les flux entrants vers le/les noeud(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du noeud. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le noeud'
        },
        apparence:{
          'apparence':'Apparence',
          'Visibilité':'Visibilité',
          'Couleur':'Couleur',
          'CouleurPérenne':'Couleur fixe',
          'Forme':'Forme',
          'Cercle':'Cercle',
          'Rectangle':'Rectangle',
          'TML':'Largeur minimale',
          'TMH':'Hauteur minimale',
          'HideAlone':'Cacher si noeud est intermédiaire',
          'asn':'Appliquer le style aux noeuds',
          'toScale':'Noeud hors échelle',
          'Orientation':'Orientation : ',
          'toScaleBottom':'Vers le bas',
          'toScaleTop':'Vers le haut',
          'toScaleLeft':'Vers la gauche',
          'toScaleRight':'Vers la droite',
          tooltips: {
            Visibilité: 'Rend le/les noeud(s) selectionné(s) visible(s) ou invisible(s)',
            Couleur: 'Choisir la couleur du/des noeud(s) selectionné(s)',
            CouleurPérenne: 'Garder la couleur du/des noeud(s) en cas de filtrage des flux ou données. Sinon le noeud reste en gris (couleur par defaut).',
            Forme: 'Choisir une Forme entre rectangle ou cercle pour le/les noeud(s) selectionné(s)',
            TML: 'Largeur minimale en pixel du/des noeud(s) selectionné(s)',
            TMH: 'Hauteur minimale en pixel du/des noeud(s) selectionné(s)'
          }
        },
        labels:{
          'labels':'Labels',
          'vdb':'Visibilité du label',
          'lb':'Label blanc',
          'pv':'Position verticale',
          'haut':'Haut',
          'Milieu':'Milieu',
          'Bas':'Bas',
          'ph':'Position horizontale',
          'gauche':'Gauche',
          'droite':'Droite',
          'tp':'Taille de police',
          'police':'Style de police',
          'gras':'Gras',
          'maj':'Majuscule',
          'ita':'Italique',
          'cl':'Largeur zone de texte',
          'vdv':'Afficher la valeur',
          tooltips: {
            vdb: 'Permet d\'afficher ou non le label accolé au(x) noeud(s) sélectionné(s)',
            lb: 'Permet d\'afficher le texte du label en blanc ou en noir (utile si label positionné sur noeud(s))',
            haut: 'Positionner le label au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv: 'Positionner le label au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas: 'Positionner le label en dessous du/des noeud(s) sélectionné(s)',
            gauche: 'Positionner le label à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph: 'Positionner le label au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite: 'Positionner le label à droite du/des noeud(s) sélectionné(s)',
            cl: 'Largeur de la zone de texte (en pixel) pour le label du/des noeud(s) sélectionné(s)',
            vdv: 'Active l\'affichage de la valeur associée au(x) noeud(s) sélectionné(s)',
            haut_val: 'Positionner l\'affichage de la valeur associée au dessus du/des noeud(s) sélectionné(s)',
            Milieu_pv_val: 'Positionner l\'affichage de la valeur associée au milieu (verticalement) du/des noeud(s) sélectionné(s)',
            Bas_val: 'Positionner l\'affichage de la valeur associée en dessous du/des noeud(s) sélectionné(s)',
            gauche_val: 'Positionner l\'affichage de la valeur associée à gauche du/des noeud(s) sélectionné(s)',
            Milieu_ph_val: 'Positionner l\'affichage de la valeur associée au milieu (horizontalement) du/des noeud(s) sélectionné(s)',
            droite_val: 'Positionner l\'affichage de la valeur associée à droite du/des noeud(s) sélectionné(s)',
          }
        },
        icon:{
          'icon':'Icône',
          'si':'Sélectionner l\'icône',
          'couleur':'Couleur',
          'rIN':'Ratio taille icône/noeud',
          'Aucun':'Aucun'
        },
        tags_node:{
          'tags':'Étiquettes',
          'Appartenance':'Appartenance'
        },
        agre:{
          'Agré':'Agrégations',
          'DC':'Dimension du cube',
          'Parent':'Parent',
          'CLE':'Copier liens enfants'
        },
        PF:{
          'PF':'Flux E/S',
          'FES':'Type de flux',
          'ent':'Entrant',
          'sort':'Sortant',
          'FRN':'Position relative au noeud',
          'gauche':'Gauche',
          'droite':'Droite',
          'ades':'Au-dessus',
          'edes':'En-dessous',
          'lti':'Identifier les flux du tableau avec leurs couleurs',
          'col':'Appliquer',
          tooltips:{
            ent: 'Afficher les flux entrants du/des noeud(s) selectionné(s)',
            sort: 'Afficher les flux sortant du/des noeud(s) selectionné(s)',
            droite: 'Afficher les flux se situant à droite du/des noeud(s) selectionné(s)',
            gauche: 'Afficher les flux se situant à gauche du/des noeud(s) selectionné(s)',
            ades: 'Afficher les flux se situant au dessus du/des noeud(s) selectionné(s)',
            edes: 'Afficher les flux se situant en dessous du/des noeud(s) selectionné(s)',
            lti: 'Affiche les lignes du tableau des flux avec leur couleurs respectives pour mieux les identifier'
          }
        }
      },
      Flux:{
        'pg': 'Paramètres généraux',
        'pdl':'Police des labels',
        'pl': 'Paramètres par flux',
        'src':'Source',
        'trgt':'Cible',
        'if':'Inverser la direction',
        'dzf':'Superposition à l\'affichage',
        'style':'Style',
        'as':'Appliquer le style au(x) flux selectionné(s)',
        'IB':'Info-bulle',
        tooltips: {
          src: 'Choix du noeud de départ pour le/les flux sélectionné(s)',
          trgt: 'Choix du noeud d\'arrivée pour le/les flux sélectionné(s)',
          if: 'Permet d\'inverser les noeuds de départ et d\'arrivée pour le/les flux sélectionné(s)',
          up: 'Monter d\'un cran vers le premier plan',
          upup: 'Mettre le/les flux selectionné(s) au premier plan',
          dwn: 'Descendre d\'un cran vers le dernier plan',
          dwndwn: 'Mettre le/les flux sélectionné(s) au dernier plan',
          as: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) flux selectionné(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du flux. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le flux'
        },
        data:{
          'données':'Données',
          'vpp':'Valeur pour ces paramètres',
          'affichage':'Affichage',
          'toPrecision':'Afficher la valeur en notation scientifique',
          tooltips: {
            vpp: 'Valeur associée au flux sélectionné et, si existant(s), pour le/les tag(s) de flux selectionné(s)',
            toPrecision: 'Activer ou non la notation en format scientifique, pour l\'affichage de la valeur du flux sur le diagramme de Sankey',
            affichage: 'Texte de remplacement de l\'affichage de la valeur du flux sur le diagramme de Sankey'
          }
        },
        apparence:{
          'apparence':'Apparence',
          'couleur':'Couleur',
          'grad':'Gradient',
          'hach':'Hachuré',
          'of':'Orientation',
          'pdc':'Position du point central (%)',
          'eep':'Position des centres de courbure (%)',
          'type':'Type',
          'courbe':'Courbe',
          'fleche':'Flèche',
          'recy':'Recyclage',
          'courbure':'Courbure',
          tooltips: {
            couleur: 'Choisir la couleur pour le/les flux sélectionné(s)',
            grad: 'Applique un effet de gradient de couleur sur le/les flux sélectionné(s). Le gradient est réalisé entre la couleur du noeud de départ et celle du noeud d\'arrivée',
            hach: 'Applique un effet de hachure sur le/les flux sélectionné(s)',
            of_vv: 'Permet d\'orienter le début du flux verticalement et la fin du flux verticalement',
            of_hh: 'Permet d\'orienter le début du flux horizontalement et la fin du flux horizontalement',
            of_hv: 'Permet d\'orienter le début du flux horizontalement et la fin du flux verticalement',
            of_vh: 'Permet d\'orienter le début du flux verticalement et la fin du flux horizontalement',
            pdc: 'Permet d\'affiner la position du centre du/des flux sélectionné(s). Cette valeur est un ratio (%) relatif au au point de départ du flux.',
            eep: 'Permet d\'affiner les positions des centres de courbure du/des flux sélectionné(s). Cette valeur est un ratio (%) relatif au point central du flux. Ces centres de courbure se positionnent en miroir par rapport au centre du/des flux',
            courbe: 'Représente le/les flux sélectionné(s) sous forme de courbe(s) de Bezier.',
            fleche: 'Représente le/les flux sélectionné(s) avec une pointe de flèche à la fin.',
            recy: 'Représente le/les flux sélectionné(s) sous forme de recyclage, ie. avec un retour vers l\'arrière.',
            courbure: 'Paramétrage du rayon de courbure dans le cas ou le/les flux sélectionné(s) sont sous forme de courbe(s) de Bezier'
          }
        },
        label:{
          'label':'Label',
          'vdb':'Visibilité du label',
          'len':'Label en noir',
          'lb':'Label en blanc',
          'lec':'Label en couleur',
          'acf':'Orienter suivant l\'axe du flux',
          'pl':'Positionnement Lateral',
          'po':'Positionnement Orthogonal',
          'milieu': 'Milieu',
          'deb':'Début',
          'fin':'Fin',
          'dessous':'Dessous',
          'dessus':'Dessus',
          'pls':'Positionner le label à la souris',
          tooltips: {
            label: 'Permet d\'afficher ou non le label (donnée / texte) associé au(x) flux sélectionné(s)',
            len: 'Afficher le texte du label en noir, pour le(s) flux sélectionné(s)',
            lb:'Afficher le texte du label en blanc, pour le(s) flux sélectionné(s)',
            lec: 'Afficher le texte du label avec la/les même(s) couleur(s) que celle(s) associée(s) au(x) flux sélectionné(s)',
            acf: 'Pour le/les flux sélectionné(s), permet d\'orienter le texte du label en suivant la forme du flux associé',
            deb: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point de départ du flux',
            milieu_h: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label entre le point de départ et le point d\'arrivée du flux',
            fin: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point d\'arrivée du flux',
            dessous: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label en dessous du flux',
            milieu_v: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label dans le flux',
            dessus: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label au dessus du flux',
            pls: 'Active la possibilité de déplacer avec la souris le label du/des flux sélectionné(s)'
          }
        }
      },
      LL:{
        'hl':'Hauteur label',
        'll':'Largeur label',
        'ft':'Opacité du fond',
        'cfl':'Couleur fond label',
        'bt':'Bordure transparent',
        'cbl':'Couleur bordure label',
        'pvt':'Position verticale texte',
        'at':'Alignement texte',
        'labels':'Labels',
        'gras':'Gras',
        'maj':'Majuscule',
        'ita':'Italique',
        'centre':'Centre',
        'textAsHTML':'Label foreignObject',
        'editorRaw':'Editeur brut'

      },
      Banner:{
        'data':'Données',
        'filter':'Filtres',
        'fdf':'Filtrage des flux',
        'fdn':'Filtrage des noeuds',
        'ndd':'Niveaux de détail',
        'ndd_lst':'Groupes d\'étiquettes',
        'ndd_chk':'Appliquer les couleurs associées',
        'sdr':'Type de diagramme',
        'sdd':'Sélection des données',
        'tl':'Téléchargements',
        'rslt':'Téléchargement résultats',
        'ff':'Filtrage visuel des flux',
        'filtre':'Valeur seuil pour l\'affichage des flux',
        'fl':'Valeur seuil pour l\'affichage des labels',
        'fn':'Flux nuls',
        'visible':'Visible',
        'hlp':'Aide',
        'hlp_1':'Les diagrammes de Sankey',
        'hlp_1_txt_1':'L\'épaisseur d\'une flèche est proportionnelle à la valeur du flux qu\'elle représente.',
        'hlp_1_txt_2':'Le diagramme peut être visualisé avec différents niveaux d\'agrégations en utilisant le sélecteur Niveau de détail',
        'hlp_1_txt_3':'Des filtres peuvent être utilisés pour n\'afficher que des parties du diagramme. Pour cela utiliser les selecteurs',
        'hlp_1_txt_4':'Différents palettes de couleurs peuvent être utiliser pour colorer les noeuds et les flux en utilisant le sélecteur Palette de Couleurs',
        'hlp_1_txt_5':'La structure du diagramme (sans épaisseur de flux) peut être affiché en cochant Structure du diagramme',
        'hlp_1_txt_6':'Le diagramme peut être ajusté à l\'écran en cochant Ajuster à l\'écran',
        'hlp_1_txt_7':'Pour obtenir des informations sur chaque flux, appuyer sur shift et passer la souris sur le flux.',
        'hlp_1_txt_8':'Pour masquer les flux/label de flux  qui sont en dessous d\'un seuil.',
        'hlp_1_txt_9':'Menu déroulant pour filtrer les noeuds/flux/données selon leur groupe d\'étiquette associée ou bien pour appliquer des couleurs au diagramme avec la palette de couleurs du groupe d\'étiquette.',
        'tooltipAdjust':'Permet de réajuster la zone de dessin à la taille de l\'écran',
        'tooltipStructure':'Permet d\'afficher la structure du diagramme sans proportion des flux selon leur valeur',
        'tooltipData':'Permet d\'afficher les données du diagramme',
        'tooltipSelection':'Permet de sélectionner ou de déplacer les noeuds',
        'tooltipHelp':'Affiche le dialogue d\'aide',
        'tooltipLiason':'Permet de créer des flux entre deux noeuds existants, depuis un noeud existant ou vers un noeud existant'
      },
      welcome:{
        'welcome':'Bienvenue sur l\'applicaion web OpenSankey',
        'exemple1':'Exemple d\'un diagramme de sankey comme des dégradés comme couleur de flux  (fonctionnalité d\'Opensankey+) ',
        'exemple2':'Exemple d\'un diagramme de sankey pouvant être réaliser avec Opensankey',
        'introduction':'Introduction à l\'application web OpenSankey',
        1:'Bouton de sélection du mode de la souris, il existe 2 modes : un mode permettant des sélectionner les noeuds et flux pour pouvoir les déplacer, puis un mode permettant de créer des liens et noeuds au clique de la souris',
        2:'Boutons permettant de filtrer la visibilité ou couleurs des noeuds et flux en fonction des groupes auxquels ils sont associés',
        3:'Boutons permettant de filtrer les noeuds en fonction de leur niveau d\'aggrégation',
        4:'Boutons permettant de filtrer la visibilité des flux en fonction de leurs valeurs, ce boutons permet aussi de modifier l\'échelle du diagramme (l\'épaisseur des flux)',
        5:'Boutons permettant de réajuster la taille de la zone de dessin pour que tous les éléments soit visible',
        6:'Boutons permettant d\'afficher le diagramme sans prendre en compte la valeur des flux',
        7:'Boutons permettant d`\'afficher de l\'aide supplémentaire',
        8:'Menu de navigation permettant d\'ouvrir,enregistrer, éditer des sankeys ',
        9:'Boutons permetttant de ce connecter avec un compte opensankey et activer des modules supplémentaires',
        10:'Boutons permetttant d\'ouvrir le menu de configuration qui permet d\'éditer les éléments du diagramme de sankey',
      },
      'DisplayWelcome':'Afficher Bienvenue',
      'dontSeeAgain':'Ne plus montrer',
      
      'scale':'Échelle'



    }
  }
}

i18next
  .use(LanguageDetector)
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    // lng: 'en', // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option

    interpolation: {
      escapeValue: false // react already safes from xss
    }
  })

export default i18next