stages:
    #- install_dependencies
    # - build
    #- test
    - deploy
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

# install_dependencies:
#   stage: install_dependencies
#   tags:
#     - dev, test, prod
#   cache: 
#     key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
#     paths:
#       - opensankey/client/node_modules/
#   script:
#     - cd opensankey/client
#     - echo $CI_COMMIT_REF_SLUG
#     - echo $CI_PROJECT_DIR
#     - npm install
#   only:
#     changes:
#       - opensankey/client/package.json

# build:
#   stage: build
#   tags:
#     - dev, test, prod
#   cache: 
#     key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
#     paths:
#       - opensankey/client/node_modules/
#     policy: pull
#   script:
#     - source /home/gitlab-runner/gitlab/bin/activate
#     - echo $CI_PROJECT_DIR
#     - cd opensankey/client
#     - CI= npm run build
#     - mv node_modules ../../..
#     - cd ../..
#     - pip install .
#     - mv ../node_modules opensankey/client

#test:
#  stage: test
#  tags:
#    - dev, test, prod
#  cache: 
#    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
#    paths:
#      - opensankey/client/node_modules/
#    policy: pull

#  variables:
#    GIT_STRATEGY: none
#  script:
#    - cd opensankey/client
#    - npm install
#    - npm link mfa-data
#   - npm run test
#  artifacts:
#    when: always
#    reports:
#      junit:
#        - junit.xml

deploy_opensankey:
  stage: deploy
  tags:
    - dev
  environment:
    name: dev
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - $folder/opensankey/opensankey/client/node_modules/
    policy: pull
  before_script:
    - sudo systemctl stop dev_opensankey || true
  after_script:
    - cd "$folder"
    - bash restart_site.sh
  variables:
    NODE_ENV: "production"
  script:
    - cd "$folder"
    - source dev_opensankey/bin/activate
    - bash update_build_opensankey.sh

