import React from 'react'
import { Box, Checkbox, Input, Text } from '@chakra-ui/react'
import {
  FormatType,
  INPUT_ATTRIBUTES_CONFIG,
  InputAttributeKey,
  OUTPUT_ATTRIBUTES_CONFIG,
  OutputAttributeKey,
  OutputOptionTypes,
  InputOptionTypes,
  FormatAttributeConfig
} from './PersistenceProcessDialogConfigs'
import { OSTooltip } from '../configmenus/MenuCommon'

interface FormatCheckboxProps<F extends FormatType> {
  format: F
  propertyName: OutputAttributeKey<F> | InputAttributeKey<F>
  value: boolean
  onChange: (checked: boolean) => void
  lang: 'en' | 'fr'
  config: typeof OUTPUT_ATTRIBUTES_CONFIG | typeof INPUT_ATTRIBUTES_CONFIG
}

export const FormatCheckbox = <F extends FormatType>({
  format,
  propertyName,
  value,
  onChange,
  lang,
  config
}: FormatCheckboxProps<F>) => {
  const formatConfig = config[format]
  
  // @ts-expect-error Type inference limitation
  const attr = formatConfig[propertyName] as FormatAttributeConfig<boolean>
  
  return (
    <Checkbox
      variant='menuconfigpanel_option_checkbox'
      isChecked={value}
      onChange={(e) => onChange(e.target.checked)}
    >
      <OSTooltip label={attr.tooltips[lang]}>
        {attr.labels[lang]}
      </OSTooltip>
    </Checkbox>
  )
}

interface AutoGeneratedOptionsProps<F extends FormatType> {
  format: F
  config: typeof OUTPUT_ATTRIBUTES_CONFIG | typeof INPUT_ATTRIBUTES_CONFIG
  options: Record<string, unknown>
  setOptions: (options: OutputOptionTypes<F> | InputOptionTypes<F>) => void
  lang: 'en' | 'fr'
}

export const AutoGeneratedOptions = <F extends FormatType>({
  format,
  config,
  options,
  setOptions,
  lang
}: AutoGeneratedOptionsProps<F>) => {
  const formatConfig = config[format]
  
  // Fonction pour vérifier si un attribut doit être affiché
  const shouldShowAttribute = (attr: unknown): boolean => {
    const typedAttr = attr as { 
      conditional?: { 
        dependsOn: string
        showWhen: boolean | number | string 
      } 
    }
    if (!typedAttr.conditional) return true
    
    const parentValue = (options as Record<string, unknown>)[typedAttr.conditional.dependsOn]
    return parentValue === typedAttr.conditional.showWhen
  }
  
  return (
    <>
      {Object.entries(formatConfig).map(([key, attrValue]) => {
        const attr = attrValue as FormatAttributeConfig<boolean | number | string>
        const typedKey = key as OutputAttributeKey<F> | InputAttributeKey<F>
        
        // Vérifier si l'attribut doit être affiché
        if (!shouldShowAttribute(attr)) return null
        
        // Déterminer l'indentation selon la condition
        const isConditional = attr.conditional !== undefined
        
        // Pour les boolean
        if (typeof attr.default === 'boolean') {
          return (
            <Box key={key} ml={isConditional ? 4 : 0}>
              <FormatCheckbox
                format={format}
                propertyName={typedKey}
                value={(options as Record<string, unknown>)[key] as boolean}
                onChange={(checked) => {
                  setOptions({
                    ...options,
                    [key]: checked
                  } as OutputOptionTypes<F> | InputOptionTypes<F>)
                }}
                lang={lang}
                config={config}
              />
            </Box>
          )
        }
        
        // Pour les numbers
        if (typeof attr.default === 'number') {
          return (
            <Box key={key} ml={isConditional ? 4 : 0} layerStyle='menuconfigpanel_row_2cols'>
              <Text>{attr.labels[lang]}</Text>
              <OSTooltip label={attr.tooltips[lang]}>
                <Input
                  type="number"
                  value={(options as Record<string, unknown>)[key] as number}
                  onChange={(e) => {
                    setOptions({
                      ...options,
                      [key]: parseInt(e.target.value)
                    } as OutputOptionTypes<F> | InputOptionTypes<F>)
                  }}
                  size='sm'
                  width='100px'
                />
              </OSTooltip>
            </Box>
          )
        }
        
        return null
      })}
    </>
  )
}