import React from 'react'
import { Box, Checkbox, Input, Text } from '@chakra-ui/react'
import {
  FormatType,
  INPUT_ATTRIBUTES_CONFIG,
  OUTPUT_ATTRIBUTES_CONFIG,
  FormatAttributeConfig,
  OptionGroup,
  OptionDirection,
  OPTION_GROUP_ORDER,
  OPTION_GROUP_LABELS
} from './PersistenceProcessDialogConfigs'
import { OSTooltip } from '../configmenus/MenuCommon'
import { MenuCondition, MenuConditionEvaluator } from './SankeyMenuContext'
import { Class_ApplicationData } from '../../types/ApplicationData'

export interface OptionBucket {
  format: FormatType
  options: Record<string, unknown>
  setOptions: (options: Record<string, unknown>) => void
}

interface AutoGeneratedOptionsProps {
  app_data: Class_ApplicationData
  config: typeof OUTPUT_ATTRIBUTES_CONFIG | typeof INPUT_ATTRIBUTES_CONFIG
  buckets: OptionBucket[]
  direction: OptionDirection
  lang: 'en' | 'fr'
}

export const AutoGeneratedOptions = ({
  app_data,
  config,
  buckets,
  direction,
  lang
}: AutoGeneratedOptionsProps) => {
  // Merge lecture seule pour l'évaluation des conditions de visibilité cross-bucket.
  const mergedOptions: Record<string, unknown> = {}
  buckets.forEach(b => Object.assign(mergedOptions, b.options))

  // Agrégation des entrées dans l'ordre des buckets (base d'abord par convention du caller).
  // On route setOptions vers le bon bucket via keyToBucket.
  const keyToBucket = new Map<string, OptionBucket>()
  const allEntries: Array<[string, FormatAttributeConfig<boolean | number | string>]> = []
  buckets.forEach(bucket => {
    const cfg = config[bucket.format] as Record<string, unknown>
    Object.entries(cfg).forEach(([key, attrValue]) => {
      // Ignorer les placeholders vides (ex: example_excel: {} hérités par spread)
      if (typeof attrValue !== 'object' || attrValue === null) return
      if (!('default' in (attrValue as object))) return
      if (keyToBucket.has(key)) return
      keyToBucket.set(key, bucket)
      allEntries.push([key, attrValue as FormatAttributeConfig<boolean | number | string>])
    })
  })

  const attrByKey = new Map<string, FormatAttributeConfig<boolean | number | string>>(allEntries)

  const shouldShowAttribute = (attr: unknown): boolean => {
    const typedAttr = attr as { visibilityConditions?: MenuCondition[] }
    if (!typedAttr.visibilityConditions) return true
    return MenuConditionEvaluator.evaluateAll(
      typedAttr.visibilityConditions,
      app_data,
      mergedOptions
    )
  }

  // Détection des unités parent-enfant via visibilityConditions (logique inchangée).
  const processed = new Set<string>()
  const units: Array<{ parent: string; children: string[] }> = []
  allEntries.forEach(([key]) => {
    if (processed.has(key)) return
    const children: string[] = []
    allEntries.forEach(([childKey, childAttr]) => {
      if (childKey === key) return
      if (!childAttr.visibilityConditions) return
      const dependsOnKey = childAttr.visibilityConditions.some(
        c => c.type === 'optionProperty' && c.property === key
      )
      if (dependsOnKey) {
        children.push(childKey)
        processed.add(childKey)
      }
    })
    units.push({ parent: key, children })
    processed.add(key)
  })

  const renderAttribute = (key: string, attr: FormatAttributeConfig<boolean | number | string>) => {
    const bucket = keyToBucket.get(key)
    if (!bucket) return null

    if (typeof attr.default === 'boolean') {
      return (
        <Checkbox
          variant='menuconfigpanel_option_checkbox'
          isChecked={bucket.options[key] as boolean}
          onChange={(e) => bucket.setOptions({ ...bucket.options, [key]: e.target.checked })}
        >
          <OSTooltip label={attr.tooltips[lang]}>
            {attr.labels[lang]}
          </OSTooltip>
        </Checkbox>
      )
    }

    if (typeof attr.default === 'number') {
      return (
        <Box layerStyle='menuconfigpanel_row_2cols'>
          <Text>{attr.labels[lang]}</Text>
          <OSTooltip label={attr.tooltips[lang]}>
            <Input
              type="number"
              value={bucket.options[key] as number}
              onChange={(e) => bucket.setOptions({ ...bucket.options, [key]: parseInt(e.target.value) })}
              size='sm'
              width='100px'
            />
          </OSTooltip>
        </Box>
      )
    }

    return null
  }

  const renderUnit = (unit: { parent: string; children: string[] }) => {
    const parentAttr = attrByKey.get(unit.parent)
    if (!parentAttr || !shouldShowAttribute(parentAttr)) return null

    const visibleChildren = unit.children.filter(childKey => {
      const childAttr = attrByKey.get(childKey)
      return childAttr ? shouldShowAttribute(childAttr) : false
    })

    if (visibleChildren.length === 0) {
      return (
        <Box key={unit.parent}>
          {renderAttribute(unit.parent, parentAttr)}
        </Box>
      )
    }

    return (
      <Box
        key={unit.parent}
        display='grid'
        gridTemplateColumns={`repeat(${visibleChildren.length + 1}, auto)`}
        columnGap='12px'
        alignItems='center'
      >
        {renderAttribute(unit.parent, parentAttr)}
        {visibleChildren.map(childKey => {
          const childAttr = attrByKey.get(childKey)!
          return renderAttribute(childKey, childAttr)
        })}
      </Box>
    )
  }

  const isUnitVisible = (unit: { parent: string; children: string[] }) => {
    const parentAttr = attrByKey.get(unit.parent)
    return parentAttr ? shouldShowAttribute(parentAttr) : false
  }

  // Bucketing par groupe sémantique (tiré du `group` du parent de l'unité).
  const UNGROUPED = '__ungrouped__'
  const unitsByGroup = new Map<string, typeof units>()
  units.forEach(unit => {
    const parentAttr = attrByKey.get(unit.parent)
    const groupKey: string = parentAttr?.group ?? UNGROUPED
    if (!unitsByGroup.has(groupKey)) unitsByGroup.set(groupKey, [])
    unitsByGroup.get(groupKey)!.push(unit)
  })

  const orderedGroups: Array<[string, typeof units]> = []
  OPTION_GROUP_ORDER.forEach(g => {
    const groupUnits = unitsByGroup.get(g)
    if (groupUnits && groupUnits.length > 0) orderedGroups.push([g, groupUnits])
  })
  const ungrouped = unitsByGroup.get(UNGROUPED)
  if (ungrouped && ungrouped.length > 0) orderedGroups.push([UNGROUPED, ungrouped])

  return (
    <>
      {orderedGroups.map(([groupKey, groupUnits]) => {
        const visibleUnits = groupUnits.filter(isUnitVisible)
        if (visibleUnits.length === 0) return null

        const showHeader = groupKey !== UNGROUPED
        const headerLabel = showHeader
          ? OPTION_GROUP_LABELS[groupKey as OptionGroup][direction][lang]
          : null

        return (
          <Box key={groupKey} mt={showHeader ? '8px' : '0'}>
            {headerLabel && (
              <Text fontSize='sm' fontWeight='semibold' color='gray.600' mb='4px'>
                {headerLabel}
              </Text>
            )}
            <Box
              display='flex'
              flexDirection='row'
              flexWrap='wrap'
              rowGap='4px'
              columnGap='16px'
              alignItems='center'
            >
              {visibleUnits.map(unit => renderUnit(unit))}
            </Box>
          </Box>
        )
      })}
    </>
  )
}
