import React, { useMemo, useState } from 'react'
import {
  Box, Button, Checkbox, Divider, Input, Popover, PopoverArrow, PopoverBody,
  PopoverContent, PopoverTrigger, Portal, Select, Text, VStack
} from '@chakra-ui/react'
import { ChevronDownIcon } from '@chakra-ui/icons'
import {
  FormatType,
  INPUT_ATTRIBUTES_CONFIG,
  OUTPUT_ATTRIBUTES_CONFIG,
  FormatAttributeConfig,
  OptionGroup,
  OptionDirection,
  OPTION_GROUP_ORDER,
  OPTION_GROUP_LABELS
} from './PersistenceProcessDialogConfigs'
import { OSTooltip } from '../configmenus/MenuCommon'
import { MenuCondition, MenuConditionEvaluator } from './SankeyMenuContext'
import { Class_ApplicationData } from '../../types/ApplicationData'

export interface OptionBucket {
  format: FormatType
  options: Record<string, unknown>
  setOptions: (options: Record<string, unknown>) => void
}

interface AutoGeneratedOptionsProps {
  app_data: Class_ApplicationData
  config: typeof OUTPUT_ATTRIBUTES_CONFIG | typeof INPUT_ATTRIBUTES_CONFIG
  buckets: OptionBucket[]
  direction: OptionDirection
  lang: 'en' | 'fr'
  // Format context for cross-cutting visibility conditions
  // (e.g. show option only when input_format == 'blob').
  input_format?: FormatType
  output_format?: FormatType
  // True when the active converter targets the MFA reconciliation solver.
  // Surfaced as the synthetic ``_solver_options_enabled`` key in mergedOptions
  // so solver-group attributes can gate their visibility on it.
  solver_options_enabled?: boolean
  // Optional whitelist of OptionGroup keys to render. When set, only attributes
  // whose group is in this list are rendered. Used to split rendering across
  // multiple panels (e.g. dedicated "Solveur" tab containing only solver-group
  // options).
  groups_only?: OptionGroup[]
  // Optional blacklist of OptionGroup keys to skip. Useful as the complement
  // of groups_only on the same-source panel (e.g. output panel renders all
  // groups except 'solver' which lives in its own tab).
  groups_exclude?: OptionGroup[]
}

export const AutoGeneratedOptions = ({
  app_data,
  config,
  buckets,
  direction,
  lang,
  input_format,
  output_format,
  solver_options_enabled,
  groups_only,
  groups_exclude
}: AutoGeneratedOptionsProps) => {
  // Merge lecture seule pour l'évaluation des conditions de visibilité cross-bucket.
  // Synthetic ``_input_format`` / ``_output_format`` keys are injected so the
  // declarative ``visibilityConditions`` (type: optionProperty) can branch on
  // the dialog's format selectors without growing a new condition type.
  const mergedOptions: Record<string, unknown> = {}
  buckets.forEach(b => Object.assign(mergedOptions, b.options))
  if (input_format !== undefined) mergedOptions['_input_format'] = input_format
  if (output_format !== undefined) mergedOptions['_output_format'] = output_format
  if (solver_options_enabled !== undefined) mergedOptions['_solver_options_enabled'] = solver_options_enabled

  // Agrégation des entrées dans l'ordre des buckets (base d'abord par convention du caller).
  // On route setOptions vers le bon bucket via keyToBucket.
  const keyToBucket = new Map<string, OptionBucket>()
  const allEntries: Array<[string, FormatAttributeConfig<boolean | number | string>]> = []
  buckets.forEach(bucket => {
    const cfg = config[bucket.format] as Record<string, unknown>
    Object.entries(cfg).forEach(([key, attrValue]) => {
      // Ignorer les placeholders vides (ex: example_excel: {} hérités par spread)
      if (typeof attrValue !== 'object' || attrValue === null) return
      if (!('default' in (attrValue as object))) return
      if (keyToBucket.has(key)) return
      keyToBucket.set(key, bucket)
      allEntries.push([key, attrValue as FormatAttributeConfig<boolean | number | string>])
    })
  })

  const attrByKey = new Map<string, FormatAttributeConfig<boolean | number | string>>(allEntries)

  const shouldShowAttribute = (attr: unknown): boolean => {
    const typedAttr = attr as { visibilityConditions?: MenuCondition[] }
    if (!typedAttr.visibilityConditions) return true
    return MenuConditionEvaluator.evaluateAll(
      typedAttr.visibilityConditions,
      app_data,
      mergedOptions
    )
  }

  // [SA #136] An option is rendered disabled (and the dialog parent enforces
  // its forcedValueWhenDisabled via useEffect) when its disabledConditions
  // evaluate true on the merged options. Used for the activate_flux_matrix
  // → activate_data_table + data_table_with_all_flux lock.
  const isAttributeDisabled = (attr: unknown): boolean => {
    const typedAttr = attr as { disabledConditions?: MenuCondition[] }
    if (!typedAttr.disabledConditions || typedAttr.disabledConditions.length === 0) return false
    return MenuConditionEvaluator.evaluateAll(
      typedAttr.disabledConditions,
      app_data,
      mergedOptions
    )
  }

  // Détection des unités parent-enfant via visibilityConditions (logique inchangée).
  const processed = new Set<string>()
  const units: Array<{ parent: string; children: string[] }> = []
  allEntries.forEach(([key]) => {
    if (processed.has(key)) return
    const children: string[] = []
    allEntries.forEach(([childKey, childAttr]) => {
      if (childKey === key) return
      if (!childAttr.visibilityConditions) return
      const dependsOnKey = childAttr.visibilityConditions.some(
        c => c.type === 'optionProperty' && c.property === key
      )
      if (dependsOnKey) {
        children.push(childKey)
        processed.add(childKey)
      }
    })
    units.push({ parent: key, children })
    processed.add(key)
  })

  const renderAttribute = (key: string, attr: FormatAttributeConfig<boolean | number | string>) => {
    const bucket = keyToBucket.get(key)
    if (!bucket) return null

    const disabled = isAttributeDisabled(attr)
    const tooltip = (disabled && attr.disabledTooltip ? attr.disabledTooltip : attr.tooltips)[lang]

    if (typeof attr.default === 'boolean') {
      return (
        <Checkbox
          variant='menuconfigpanel_option_checkbox'
          isChecked={bucket.options[key] as boolean}
          isDisabled={disabled}
          onChange={(e) => bucket.setOptions({ ...bucket.options, [key]: e.target.checked })}
        >
          <OSTooltip label={tooltip}>
            {attr.labels[lang]}
          </OSTooltip>
        </Checkbox>
      )
    }

    if (typeof attr.default === 'number') {
      return (
        <Box layerStyle='menuconfigpanel_row_2cols'>
          <Text>{attr.labels[lang]}</Text>
          <OSTooltip label={tooltip}>
            <Input
              type="number"
              value={bucket.options[key] as number}
              onChange={(e) => bucket.setOptions({ ...bucket.options, [key]: parseInt(e.target.value) })}
              size='sm'
              width='100px'
              isDisabled={disabled}
            />
          </OSTooltip>
        </Box>
      )
    }

    if (typeof attr.default === 'string' && attr.selectOptions) {
      return (
        <Box display='flex' flexDirection='row' alignItems='center' columnGap='6px'>
          <Text fontWeight='semibold'>{attr.labels[lang]}</Text>
          <OSTooltip label={tooltip}>
            <Select
              value={bucket.options[key] as string}
              onChange={(e) => bucket.setOptions({ ...bucket.options, [key]: e.target.value })}
              size='sm'
              width='240px'
              isDisabled={disabled}
            >
              {attr.selectOptions.map(opt => (
                <option key={opt.value} value={opt.value}>
                  {opt.labels[lang]}
                </option>
              ))}
            </Select>
          </OSTooltip>
        </Box>
      )
    }

    return null
  }

  const renderUnit = (unit: { parent: string; children: string[] }) => {
    const parentAttr = attrByKey.get(unit.parent)
    if (!parentAttr || !shouldShowAttribute(parentAttr)) return null

    const visibleChildren = unit.children.filter(childKey => {
      const childAttr = attrByKey.get(childKey)
      return childAttr ? shouldShowAttribute(childAttr) : false
    })

    if (visibleChildren.length === 0) {
      return (
        <Box key={unit.parent}>
          {renderAttribute(unit.parent, parentAttr)}
        </Box>
      )
    }

    return (
      <Box
        key={unit.parent}
        display='grid'
        gridTemplateColumns={`repeat(${visibleChildren.length + 1}, auto)`}
        columnGap='12px'
        alignItems='center'
      >
        {renderAttribute(unit.parent, parentAttr)}
        {visibleChildren.map(childKey => {
          const childAttr = attrByKey.get(childKey)!
          return renderAttribute(childKey, childAttr)
        })}
      </Box>
    )
  }

  const isUnitVisible = (unit: { parent: string; children: string[] }) => {
    const parentAttr = attrByKey.get(unit.parent)
    return parentAttr ? shouldShowAttribute(parentAttr) : false
  }

  // Bucketing par groupe sémantique (tiré du `group` du parent de l'unité).
  const UNGROUPED = '__ungrouped__'
  const unitsByGroup = new Map<string, typeof units>()
  units.forEach(unit => {
    const parentAttr = attrByKey.get(unit.parent)
    const groupKey: string = parentAttr?.group ?? UNGROUPED
    if (!unitsByGroup.has(groupKey)) unitsByGroup.set(groupKey, [])
    unitsByGroup.get(groupKey)!.push(unit)
  })

  // Ungrouped attributes render first (above all named sections), without a
  // header. Used for top-level options that should sit alone — e.g.
  // ``save_only_visible_elements`` above the "Onglets écrits" group.
  const onlySet = groups_only ? new Set<string>(groups_only) : null
  const excludeSet = groups_exclude ? new Set<string>(groups_exclude) : null
  const isGroupAllowed = (g: string) => {
    if (onlySet && !onlySet.has(g)) return false
    if (excludeSet && excludeSet.has(g)) return false
    return true
  }
  const orderedGroups: Array<[string, typeof units]> = []
  const ungrouped = unitsByGroup.get(UNGROUPED)
  // Untagged attributes only belong to the "default" panel — exclude them when
  // the caller asked for a specific group whitelist.
  if (ungrouped && ungrouped.length > 0 && !onlySet) orderedGroups.push([UNGROUPED, ungrouped])
  OPTION_GROUP_ORDER.forEach(g => {
    if (!isGroupAllowed(g)) return
    const groupUnits = unitsByGroup.get(g)
    if (groupUnits && groupUnits.length > 0) orderedGroups.push([g, groupUnits])
  })

  // [SA #145] Groups rendered as a single Excel-style filter dropdown
  // (button trigger → popover with search, "(Tout sélectionner)" tri-state,
  // per-option checkboxes, OK/Annuler). Used for the ``autocorrection``
  // group where 8 inline checkboxes were noisy and tedious to click.
  const CHECKLIST_GROUPS: ReadonlyArray<OptionGroup> = ['autocorrection']
  const checklistLabels: Record<'en' | 'fr', {
    triggerNone: string; triggerAll: string; triggerCount: (n: number, t: number) => string
    selectAll: string; search: string
  }> = {
    en: {
      triggerNone: 'None',
      triggerAll: 'All',
      triggerCount: (n, t) => `${n} / ${t} selected`,
      selectAll: '(Select all)',
      search: 'Search',
    },
    fr: {
      triggerNone: 'Aucune',
      triggerAll: 'Toutes',
      triggerCount: (n, t) => `${n} / ${t} sélectionnée(s)`,
      selectAll: '(Tout sélectionner)',
      search: 'Rechercher',
    },
  }
  const collectBooleanParents = (groupUnits: typeof units) => {
    const out: Array<{ key: string; attr: FormatAttributeConfig<boolean | number | string>; bucket: OptionBucket }> = []
    groupUnits.forEach(unit => {
      const attr = attrByKey.get(unit.parent)
      if (!attr || typeof attr.default !== 'boolean') return
      if (!shouldShowAttribute(attr)) return
      const bucket = keyToBucket.get(unit.parent)
      if (!bucket) return
      out.push({ key: unit.parent, attr, bucket })
    })
    return out
  }
  const writeBackBuckets = (
    booleanParents: Array<{ key: string; bucket: OptionBucket }>,
    draft: Record<string, boolean>,
  ) => {
    // Coalesce by bucket: one setOptions call per bucket carries every
    // toggled key, so a single render re-applies the full state instead
    // of N partial states racing through React's batching.
    const pending = new Map<OptionBucket, Record<string, unknown>>()
    booleanParents.forEach(({ key, bucket }) => {
      const base = pending.get(bucket) ?? { ...bucket.options }
      base[key] = !!draft[key]
      pending.set(bucket, base)
    })
    pending.forEach((next, bucket) => bucket.setOptions(next))
  }

  return (
    <>
      {orderedGroups.map(([groupKey, groupUnits]) => {
        const visibleUnits = groupUnits.filter(isUnitVisible)
        if (visibleUnits.length === 0) return null

        const showHeader = groupKey !== UNGROUPED
        const headerLabel = showHeader
          ? OPTION_GROUP_LABELS[groupKey as OptionGroup][direction][lang]
          : null

        const isChecklist = (
          showHeader
          && CHECKLIST_GROUPS.includes(groupKey as OptionGroup)
        )
        if (isChecklist) {
          const booleanParents = collectBooleanParents(groupUnits)
          if (booleanParents.length === 0) return null
          return (
            <Box key={groupKey} mt='8px'>
              {headerLabel && (
                <Text fontSize='sm' fontWeight='semibold' color='gray.600' mb='4px'>
                  {headerLabel}
                </Text>
              )}
              <ChecklistDropdown
                booleanParents={booleanParents}
                isAttributeDisabled={isAttributeDisabled}
                lang={lang}
                labels={checklistLabels[lang]}
                onCommit={(draft) => writeBackBuckets(booleanParents, draft)}
              />
            </Box>
          )
        }

        return (
          <Box key={groupKey} mt={showHeader ? '8px' : '0'}>
            {headerLabel && (
              <Text fontSize='sm' fontWeight='semibold' color='gray.600' mb='4px'>
                {headerLabel}
              </Text>
            )}
            <Box
              display='flex'
              flexDirection='row'
              flexWrap='wrap'
              rowGap='4px'
              columnGap='16px'
              alignItems='center'
            >
              {visibleUnits.map((unit, idx) => {
                const parentAttr = attrByKey.get(unit.parent)
                // Force a row break before this unit (skip on the very first
                // unit — a leading break would just add empty space).
                const breakBefore = idx > 0 && parentAttr?.breakBefore === true
                return (
                  <React.Fragment key={unit.parent}>
                    {breakBefore && <Box flexBasis='100%' height='0' />}
                    {renderUnit(unit)}
                  </React.Fragment>
                )
              })}
            </Box>
          </Box>
        )
      })}
    </>
  )
}

// [SA #145] Excel-style filter dropdown for a group of independent boolean
// options. Edits apply immediately (no OK/Annuler) : every toggle writes back
// to the buckets at once. Inspired by Excel's column filter: search field +
// "(Sélectionner tout)" tri-state at the top + per-item checkboxes.
interface ChecklistDropdownProps {
  booleanParents: Array<{
    key: string
    attr: FormatAttributeConfig<boolean | number | string>
    bucket: OptionBucket
  }>
  isAttributeDisabled: (attr: unknown) => boolean
  lang: 'en' | 'fr'
  labels: {
    triggerNone: string
    triggerAll: string
    triggerCount: (n: number, t: number) => string
    selectAll: string
    search: string
  }
  onCommit: (draft: Record<string, boolean>) => void
}

const ChecklistDropdown: React.FC<ChecklistDropdownProps> = ({
  booleanParents, isAttributeDisabled, lang, labels, onCommit,
}) => {
  // Current committed state — recomputed from bucket.options at every render
  // so external changes (e.g. another control flipping a flag) are reflected
  // when the popover re-opens.
  const committed = useMemo(() => {
    const m: Record<string, boolean> = {}
    booleanParents.forEach(({ key, bucket }) => {
      m[key] = !!bucket.options[key]
    })
    return m
  }, [booleanParents])

  const [isOpen, setIsOpen] = useState(false)
  const [draft, setDraft] = useState<Record<string, boolean>>(committed)
  const [search, setSearch] = useState('')

  // Sync draft from the committed state + clear the search every time the
  // popover opens, so external changes to the flags are reflected.
  const openPopover = () => {
    setDraft({ ...committed })
    setSearch('')
    setIsOpen(true)
  }
  const closePopover = () => setIsOpen(false)
  // Apply immediately on every edit: update the local draft (instant visual
  // feedback while the popover is open) and write back to the buckets at once.
  const applyDraft = (next: Record<string, boolean>) => {
    setDraft(next)
    onCommit(next)
  }

  const total = booleanParents.length
  const checkedCount = booleanParents.reduce(
    (n, { key }) => n + (committed[key] ? 1 : 0), 0,
  )
  const triggerLabel = (() => {
    if (checkedCount === 0) return labels.triggerNone
    if (checkedCount === total) return labels.triggerAll
    return labels.triggerCount(checkedCount, total)
  })()

  // Filter visible rows by search term (matched on the displayed label).
  const search_lc = search.trim().toLowerCase()
  const visibleRows = booleanParents.filter(({ attr }) => {
    if (!search_lc) return true
    return attr.labels[lang].toLowerCase().includes(search_lc)
  })

  const visibleCheckedCount = visibleRows.reduce(
    (n, { key }) => n + (draft[key] ? 1 : 0), 0,
  )
  const masterAllChecked = visibleRows.length > 0 && visibleCheckedCount === visibleRows.length
  const masterNoneChecked = visibleCheckedCount === 0
  const toggleAllVisible = (next: boolean) => {
    const out = { ...draft }
    visibleRows.forEach(({ key }) => { out[key] = next })
    applyDraft(out)
  }

  return (
    <Popover isOpen={isOpen} onClose={closePopover} placement='bottom-start' isLazy>
      <PopoverTrigger>
        <Button
          size='xs'
          variant='outline'
          rightIcon={<ChevronDownIcon />}
          onClick={openPopover}
          width='auto'
          minW='180px'
          maxW='320px'
          justifyContent='space-between'
          fontWeight='normal'
        >
          {triggerLabel}
        </Button>
      </PopoverTrigger>
      {/* Portal so the popover escapes the modal's overflow:hidden clipping
          and floats above it (z-index handled by Chakra's Popover layer). */}
      <Portal>
        <PopoverContent minW='360px' maxW='480px' zIndex='popover'>
          <PopoverArrow />
          <PopoverBody p='6px'>
            <Input
              size='xs'
              placeholder={labels.search}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              mb='6px'
            />
            <Checkbox
              size='sm'
              isChecked={masterAllChecked}
              isIndeterminate={!masterAllChecked && !masterNoneChecked}
              onChange={(e) => toggleAllVisible(e.target.checked)}
            >
              <Text fontSize='xs' fontStyle='italic'>{labels.selectAll}</Text>
            </Checkbox>
            <Divider my='4px' />
            <VStack align='stretch' spacing='2px' maxH='220px' overflowY='auto'>
              {visibleRows.map(({ key, attr }) => {
                const disabled = isAttributeDisabled(attr)
                const tooltip = (disabled && attr.disabledTooltip
                  ? attr.disabledTooltip
                  : attr.tooltips)[lang]
                return (
                  <Checkbox
                    key={key}
                    size='sm'
                    isChecked={!!draft[key]}
                    isDisabled={disabled}
                    onChange={(e) => applyDraft({ ...draft, [key]: e.target.checked })}
                  >
                    <OSTooltip label={tooltip}>
                      <Text fontSize='xs'>{attr.labels[lang]}</Text>
                    </OSTooltip>
                  </Checkbox>
                )
              })}
              {visibleRows.length === 0 && (
                <Text fontSize='xs' color='gray.500' fontStyle='italic'>—</Text>
              )}
            </VStack>
          </PopoverBody>
        </PopoverContent>
      </Portal>
    </Popover>
  )
}
