// ==================================================================================================
// The MIT License (MIT)
// ==================================================================================================
// Copyright (c) 2025 TerriFlux
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// ==================================================================================================
// Author        : Vincent LE DOZE & Vincent CLAVEL & Julien Alapetite for TerriFlux
// ==================================================================================================

import React, { ChangeEvent, useState } from 'react'
import { Checkbox, Box, Button, Input, Select, Text, Divider, Alert, AlertIcon } from '@chakra-ui/react'
import { MenuDraggable } from '../topmenus/SankeyMenus'
import { Class_ApplicationData } from '../../types/ApplicationData'
import { actions_type, default_actions_type, FType_ProcessFunctions } from '../../Modules'
import FileSaver from 'file-saver'
import { decompressUploadedFileUniversal } from '../../Persistence/UniversalJSONCompression'
import { Type_JSON } from '../../types/Utils'
import { ProcessTerminal } from './PersistenceProcessDialogTerminal'
import {
  CONVERTER_CONFIGS, ConverterConfig, ConverterConfigKey, FormatType, getDefaultInputOptions, getDefaultOutputOptions,
  getInitialFormat, hasOptionsFormat, INPUT_ATTRIBUTES_CONFIG, OUTPUT_ATTRIBUTES_CONFIG
} from './PersistenceProcessDialogConfigs'
import { OSTooltip, WrapperBoxSubSectionMenu } from '../configmenus/MenuCommon'
import { AutoGeneratedOptions } from './PersistenceProcessDialogOptions'
import { applyRandomColors } from '../../Algorithms/Colors'
import { Class_DataTagGroup } from '../../types/TagGroup'
/**
 * Types de formats supportés
 */
type FileFormat = 'excel' | 'json' | 'blob'

/**
 * Configuration pour chaque format
 */
const FORMAT_CONFIG: Record<FileFormat, {
  extension: string
  accept: string
  label: string
  icon: string
}> = {
  excel: {
    extension: '.xlsx',
    accept: '.xlsx',
    label: 'Fichier Excel',
    icon: '📊'
  },
  json: {
    extension: '.json',
    accept: '.json,.json.gz',
    label: 'Fichier JSON',
    icon: '📄'
  },
  blob: {
    extension: '.json',
    accept: '.json,.json.gz',
    label: 'Sankey courant',
    icon: '📄'
  }
}

interface FileFormatSectionProps {
  // Config
  section_type: 'input' | 'output'
  app_data: Class_ApplicationData
  lang: 'en' | 'fr'

  // Format config
  format_config: {
    fixed?: FormatType
    options?: FormatType[]
  }
  required: boolean

  // États
  current_format: FormatType
  set_current_format: (format: FormatType) => void

  set_file?: (file: Blob | undefined) => void

  // Options
  options_excel: Record<string, unknown>
  set_options_excel: (opts: Record<string, unknown>) => void
  options_json: Record<string, unknown>
  set_options_json: (opts: Record<string, unknown>) => void
}

export const FileFormatSection = ({
  section_type,
  app_data,
  lang,
  format_config,
  required,
  current_format,
  set_current_format,
  set_file,
  options_excel,
  set_options_excel,
  options_json,
  set_options_json,
}: FileFormatSectionProps) => {
  const { t } = app_data

  const is_input = section_type === 'input'
  const config_to_use = is_input ? INPUT_ATTRIBUTES_CONFIG : OUTPUT_ATTRIBUTES_CONFIG
  const gridTemplateColumns = hasOptionsFormat(format_config) && format_config.options.length > 1 ? '1fr 2fr 3fr' : '1fr'
  if (!required) return <></>
  return (
    <Box>
      <Box
        as='span'
        layerStyle='menu_sub_section_title'
        textStyle='title_sub_section'
      >
        {is_input
          ? t('ProcessDialog.input_parameters')
          : t('ProcessDialog.output_parameters')
        }
        {/* </Box> */}
      </Box>

      {/* <Collapse in={isOpen} animateOpacity> */}
      <Box layerStyle='menuconfigpanel_grid'>
        {/* Sélecteur de format - seulement si multiple choix */}
        <Box display={'grid'} gridTemplateColumns={gridTemplateColumns}>
          {hasOptionsFormat(format_config) && format_config.options.length > 1 && (<>
            <Text fontWeight='bold' mb={2}>
              {is_input
                ? t('ProcessDialog.input_format')
                : t('ProcessDialog.output_format')
              }
            </Text>
            <Select
              value={current_format}
              onChange={(e: { target: { value: string } }) => set_current_format(e.target.value as FormatType)}
            >
              {format_config.options.map((fmt: FormatType) => (
                <option key={fmt} value={fmt}>
                  {FORMAT_CONFIG[fmt].icon} {FORMAT_CONFIG[fmt].label}
                </option>
              ))}
            </Select></>
          )}

          {/* Input file - seulement pour section input */}
          {current_format != 'blob' && is_input && (hasOptionsFormat(format_config)) && set_file && (
            <Input
              type="file"
              accept={FORMAT_CONFIG[current_format].accept}
              onChange={(evt: ChangeEvent<HTMLInputElement>) => {
                const files = (evt.target as HTMLInputElement).files
                set_file(files?.[0])
              }}
            />
          )}
        </Box>

        {/* Options de format */}
        {hasOptionsFormat(format_config) && (
          <WrapperBoxSubSectionMenu
            new_data={app_data}
            title={is_input
              ? t('ProcessDialog.input_options')
              : t('ProcessDialog.output_options')
            }
            with_border={false}
            is_open={false}
          ><>
              {current_format === 'excel' && (
                <AutoGeneratedOptions
                  format='excel'
                  config={config_to_use}
                  options={options_excel}
                  setOptions={set_options_excel}
                  lang={lang}
                />
              )}
              {current_format === 'json' && (
                <AutoGeneratedOptions
                  format='json'
                  config={config_to_use}
                  options={options_json}
                  setOptions={set_options_json}
                  lang={lang}
                />
              )}</>
          </WrapperBoxSubSectionMenu>
        )}
      </Box>
      {/* </Collapse> */}
    </Box>
  )
}

/**
 * Reset Drawing area with extracted json data from an excel file
 *
 * @param {*} applicationData
 * @param {string} text
 */
export const retrieveJSONResults = (
  app_data: Class_ApplicationData,
  text: string,
  apply_layout_current_sankey: ConstrainBoolean,
  kwargs: Type_JSON
) => {
  // Failsafe
  if (text === '{}')
    return
  // Extract JSON struct
  const data_as_json = JSON.parse(text) as Type_JSON
  data_as_json['version'] = app_data.version // Avoid converter process
  const current_json = app_data.toJSON()
  // Extract sankey datas from JSON
  app_data.fromJSON(data_as_json, kwargs, false)
  app_data.sendWaitingToast(
    () => {
      app_data.drawing_area.sankey.nodes_list.forEach(n => {
        const tagg = app_data.drawing_area.sankey.node_taggs_dict['type de noeud']
        if (!tagg) {
          return
        }
        const product_tag = tagg.tags_dict['produit']
        const sector_tag = tagg.tags_dict['secteur']
        //const echange_tag = tagg.tags_dict['echange']
        if (n.hasGivenTag(product_tag) && n.style.some(s => s.id === 'default')) {
          n.style = [app_data.drawing_area.sankey.node_styles_dict['NodeProductStyle']]
        } else if (n.hasGivenTag(sector_tag) && n.style.some(s => s.id === 'default')) {
          n.style = [app_data.drawing_area.sankey.node_styles_dict['NodeSectorStyle']]
        }
      })
      app_data.drawing_area.legend.masked = false
      if (app_data.drawing_area.sankey.flux_taggs_list.length > 0) {
        app_data.drawing_area.sankey.flux_taggs_list[0].use_colors = true
      } else if (app_data.drawing_area.sankey.node_taggs_list.filter(tagg => tagg.id != 'type de noeud').length == 0) {
        applyRandomColors(app_data, app_data.drawing_area.sankey.links_list)
      }
      const unit_taggs = app_data.drawing_area.sankey.getTagGroupsAsList('data_taggs').filter(tagg => tagg.is_unit) as Class_DataTagGroup[]
      if (unit_taggs.length > 0) {
        app_data.drawing_area.sankey.link_styles_dict['default'].value_label_unit_type = 'unit_tag'
        app_data.drawing_area.sankey.link_styles_dict['default'].value_label_unit_visible = true
      }

      // Case 1 : Apply extracted layout if present -> contains positions
      if (apply_layout_current_sankey) {
        app_data.drawing_area.nodePositioning.computeScale()
        app_data.updateFromJSON(current_json)
      } else if (data_as_json['layout']) {
        app_data.drawing_area.nodePositioning.computeScale()
        app_data.updateFromJSON(data_as_json)
      } else {
        app_data.drawing_area.nodePositioning.computeAutoSankeyWithToast(true, true)
      }
    })
}

/**
 * Composant de conversion universelle de formats
 */
export const UniversalFileConverter = ({
  app_data,
  processFunctions,
  config_key,
  dialog_name
}: {
  app_data: Class_ApplicationData,
  processFunctions: FType_ProcessFunctions,
  config_key: ConverterConfigKey,
  dialog_name: string
}) => {
  const config = CONVERTER_CONFIGS[config_key] as ConverterConfig
  const { t, url_prefix } = app_data
  const lang = (app_data.i18n?.language === 'fr' ? 'fr' : 'en') as 'en' | 'fr'
  //const [layout_open, setLayoutOpen] = useState(false)
  const [auto_layout, setAutoLayout] = useState(false)
  const [auto_load, setAutoLoad] = useState(!config.output.required && !config.input.format.options!.includes('blob'))


  // États de base - utiliser les helpers
  const [input_file, set_input_file] = useState<Blob | undefined>(undefined)

  const [input_format, set_input_format] = useState<FormatType>(
    getInitialFormat(config.input.format, 'excel')
  )

  const [output_format, set_output_format] = useState<FormatType>(
    getInitialFormat(config.output.format, 'json')
  )

  // Options pour chaque format de sortie
  const [output_options_excel, set_output_options_excel] = useState(getDefaultOutputOptions('excel'))
  const [output_options_json, set_output_options_json] = useState(getDefaultOutputOptions('json'))
  // Options pour chaque format d'entrée (réservé pour plus tard)
  const [input_options_excel, set_input_options_excel] = useState(getDefaultInputOptions('excel'))
  const [input_options_json, set_input_options_json] = useState(getDefaultInputOptions('json'))
  //const [input_options_blob, set_input_options_blob] = useState(getDefaultInputOptions('blob'))

  const [show_terminal, set_show_terminal] = useState(false)

  const [update, setUpdate] = useState(0)

  const launch = (cur_path: string, actions: actions_type) => {
    processFunctions.path.current = cur_path
    processFunctions.failure.current = true
    processFunctions.ref_processing.current = true
    processFunctions.not_started.current = false
    processFunctions.ref_result.current('')
    processFunctions.actions.current = actions
  }

  const getCurrentOutputOptions = () => {
    switch (output_format) {
    case 'excel': return output_options_excel
    case 'json': return output_options_json
    }
  }

  const getCurrentInputOptions = () => {
    switch (input_format) {
    case 'excel': return input_options_excel
    case 'json': return input_options_json
    case 'blob': return {}
    }
  }

    const reset = () => {
      // const form_data = new FormData()
      // fetch(window.location.origin + url_prefix + '/upload/clean', {
      //   method: 'POST',
      //   body: form_data
      // })
      processFunctions.ref_processing.current = false
      processFunctions.failure.current = false
      //set_is_computing(false)
      setAutoLoad(!config.output.required && !config.input.format.options!.includes('blob'))
      processFunctions.not_started.current = true
      set_show_terminal(false)
      setUpdate(a => a + 1)
    }

  const handleFinish = async () => {
    if (!auto_load) {
      console.log('🔄 Conversion terminée - en attente d\'action utilisateur')
      processFunctions.ref_processing.current = false
      processFunctions.failure.current = false
      processFunctions.not_started.current = true
      setUpdate((a: number) => a + 1)
      return
    }

    // ========== MODE CHARGEMENT CLASSIQUE ==========
    const path = window.location.origin
    const url = path + url_prefix + 'upload/retrieve_result'
    const form_data = new FormData()

    const fetchData = {
      method: 'POST',
      body: form_data
    }

    try {
      const response = await fetch(url, fetchData)
      if (response.ok) {
        const text = await response.text()
        retrieveJSONResults(app_data, text, auto_layout, output_options_json)
        setAutoLoad(false)
      }
    } catch (error) {
      console.error('Erreur chargement JSON:', error)
    }
    processFunctions.ref_processing.current = false
    processFunctions.failure.current = false
    processFunctions.not_started.current = true
    setUpdate((a: number) => a + 1)
  }

  const downloadFileResult = () => {
    const path = window.location.origin
    const url = path + url_prefix + 'upload/retrieve_result'
    const form_data = new FormData()
    form_data.append('input_format', input_format)
    form_data.append('output_format', output_format)
    const output_options = getCurrentOutputOptions()
    form_data.append('output_options', JSON.stringify(output_options))
    const input_options = getCurrentInputOptions()
    form_data.append('input_options', JSON.stringify(input_options))
    const fetchData = {
      method: 'POST',
      body: form_data
    }

    fetch(url, fetchData)
      .then(response => {
        if (!response.ok) {
          throw new Error('File not found')
        }
        return response.blob()
      })
      .then(blob => {
        // Déterminer le nom selon le format de sortie
        const output_format = processFunctions.actions.current.output_format || 'converted'
        const extensions: Record<string, string> = {
          excel: '.xlsx',
          json: '.json'
        }
        const root_filename = (input_file as File).name.split('.')[0]
        const filename = `${root_filename}${extensions[output_format] || ''}`

        FileSaver.saveAs(blob, filename)
        console.log(`✅ Fichier téléchargé: ${filename}`)
      })
      .catch(error => {
        console.error('❌ Erreur téléchargement:', error)
        alert('Impossible de télécharger le fichier converti')
      })
  }
  const loadFileResult = () => {
    setAutoLoad(true)
    launch('', default_actions_type)
    const form_data = new FormData()
    form_data.append('input_format', input_format)
    form_data.append('output_format', output_format)
    const output_options = getCurrentOutputOptions()
    form_data.append('output_options', JSON.stringify(output_options))
    const input_options = getCurrentInputOptions()
    form_data.append('input_options', JSON.stringify(input_options))
    fetch(window.location.origin + url_prefix + '/upload/retrieve_json', {
      method: 'POST',
      body: form_data
    })
  }
  /**
   * Gère le clic sur le bouton Convertir
   */
  const process = () => {
    if (input_format != 'blob' && !input_file) {
      alert(t('ProcessDialog.select_file') || 'Veuillez sélectionner un fichier')
      return
    }
    const the_actions_type: actions_type = {
      input_format: input_format,
      output_format: output_format
    }
    launch(''/*(input_file as unknown as { [name: string]: string }).name*/, the_actions_type)
    // Préparer la requête
    const form_data = new FormData()
    const output_options = getCurrentOutputOptions()
    form_data.append('output_options', JSON.stringify(output_options))
    const input_options = getCurrentInputOptions()
    form_data.append('input_options', JSON.stringify(input_options))
    if (input_format == 'blob') {
      form_data.append('data', JSON.stringify(app_data.toJSON(output_options)))
    } else {
      form_data.append('file', input_file as Blob)
    }
    form_data.append('input_format', input_format)
    form_data.append('output_format', output_format)

    if (input_format == 'blob' && output_format == 'json') {
      app_data.saveToJSON(output_options)
      processFunctions.ref_processing.current = false
      processFunctions.failure.current = false
      processFunctions.not_started.current = true
      return
    } else if (input_format == 'json' && output_format == 'blob') {
      decompressUploadedFileUniversal(input_file as File).then(JSON_data => {
        app_data.fromJSON(JSON_data as Type_JSON, input_options)
      })
      processFunctions.ref_processing.current = false
      processFunctions.failure.current = false
      processFunctions.not_started.current = true
      return
    }
    const url = window.location.origin + config.server_endpoint

    console.log(`🔄 Lancement conversion ${input_format} → ${output_format}`)
    console.log('Options entrée:', input_options)
    console.log('Options sortie:', output_options)

    set_show_terminal(true)
    fetch(url, { method: 'POST', body: form_data })
      .then(response => {
        if (!response.ok) {
          console.error('❌ Erreur lancement conversion:')

          // Mettre à jour les états pour indiquer l'échec
          processFunctions.not_started.current = true
          processFunctions.ref_processing.current = false
          processFunctions.failure.current = true
          processFunctions.ref_result.current('❌ Erreur lancement conversion:')
          setUpdate(a => a + 1)
        }
        return response.json()
      })
      .then(data => {
        console.log('✅ Conversion lancée avec succès:', data)
      })
      .catch(error => {
        console.error('❌ Erreur lancement conversion:', error)

        // Mettre à jour les états pour indiquer l'échec
        processFunctions.not_started.current = true
        processFunctions.ref_processing.current = false
        processFunctions.failure.current = true
        processFunctions.ref_result.current('❌ Erreur lancement conversion:')
        setUpdate((a: number) => a + 1)
      })
  }

  const content = (
    <Box layerStyle='menuconfigpanel_grid'>
      {/* Section Input */}
      <FileFormatSection
        section_type='input'
        app_data={app_data}
        lang={lang}
        format_config={config.input.format}
        required={config.input.required}
        current_format={input_format}
        set_current_format={set_input_format}
        set_file={set_input_file}
        options_excel={input_options_excel as Record<string, unknown>}
        set_options_excel={(opts) => set_input_options_excel(opts as typeof input_options_excel)}
        options_json={input_options_json as Record<string, unknown>}
        set_options_json={(opts) => set_input_options_json(opts as typeof input_options_json)}
      />
      {config.input.required && config.output.required ? <Divider borderBottomWidth='2px' opacity='1' borderColor='primaire.2' /> : <></>}
      {/* Section Output */}
      <FileFormatSection
        section_type='output'
        app_data={app_data}
        lang={lang}
        format_config={config.output.format}
        required={config.output.required}
        current_format={output_format}
        set_current_format={set_output_format}
        options_excel={output_options_excel as Record<string, unknown>}
        set_options_excel={(opts) => set_output_options_excel(opts as typeof output_options_excel)}
        options_json={output_options_json as Record<string, unknown>}
        set_options_json={(opts) => set_output_options_json(opts as typeof output_options_json)}
      />
      {config.output.required && output_format == 'blob' ? <><Divider borderBottomWidth='2px' opacity='1' borderColor='primaire.2' />
        <WrapperBoxSubSectionMenu
          new_data={app_data}
          is_open={false}
          with_border={false}
          title={'Mise en page'}
        >
          <Checkbox
            variant='menuconfigpanel_option_checkbox'
            isChecked={auto_layout}
            onChange={(e: { target: { checked: boolean } }) => setAutoLayout(e.target.checked)}
          >
            <OSTooltip label={' A partir du sankey affiché'}>
              A partir du sankey affiché
            </OSTooltip>
          </Checkbox>

        </WrapperBoxSubSectionMenu></>
        : <></>}
      <Divider borderBottomWidth='2px' opacity='1' borderColor='primaire.2' />
      {/* Bouton de lancement */}
      <Box layerStyle='menuconfigpanel_row_3cols'>
        <Box />
        <Box />
        <Button
          variant="menuconfigpanel_option_button_secondary"
          isActive
          size='sizeButtonDialog'
          isDisabled={input_format !== 'blob' && config.input.required && !input_file}
          onClick={process}
        >
          {t(config.launch_button_label)}
        </Button>
      </Box>
      {config.input.required && !input_file ? <Alert status='warning'>
        <AlertIcon />
        {t('ProcessDialog.waiting_file')}
      </Alert> : <></>}
      {!processFunctions.not_started && !processFunctions.ref_processing.current && !processFunctions.failure.current ? (
        <Alert status='success'>
          <AlertIcon />
          {t('ProcessDialog.success')}
        </Alert>
      ) : (<></>)}
      {/* Terminal inline si configuré */}
      {show_terminal && (
        <>
          <Divider borderBottomWidth='2px' opacity='1' borderColor='primaire.2' />
          <Box
            as='span'
            layerStyle='menuconfigpanel_part_title_1'>
            Terminal
          </Box>
          <ProcessTerminal
            processFunctions={processFunctions}
            url_prefix={app_data.url_prefix}
            app_data={app_data}
            reset={reset}
            handleFinish={handleFinish}
            downloadFileResult={downloadFileResult}
            loadFileResult={loadFileResult}
            auto_load={auto_load}
          />
        </>
      )}
    </Box>
  )

  return (
    <MenuDraggable
      dict_hook_ref_setter_show_dialog_components={app_data.menu_configuration.dict_setter_show_dialog}
      //@ts-expect-error xxx
      dialog_name={dialog_name}
      content={content}
      title={t(config.title)}
      minW={'25vw'}
      maxW={'50vw'}
    />
  )
}
