import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
// the translations
// (tip move them in a JSON file and import them,
// or even better, manage them separated from your code: https://react.i18next.com/guides/multiple-translation-files)
const resources = {
  en: {
    translation: {
      Menu:{
        'confSankey': 'Sankey\'s configuration',
        'MEP':'Global layout',
        'Noeuds':'Nodes',
        'EN':'Nodes\' tags',
        'EdN':'Editing nodes',
        'flux':'Links',
        'EF':'Links\' tags',
        'EdF':'Editing links',
        'ED':'Data\'s tags',
        'LL':'Free labels',
        'Leg':'Legends',
        'LegX':'Horizontal position',
        'LegY':'Vertical position',
        'LegWidth':'Width',
        'Fichiers':'Files',
        'Edition':'Edition',
        'Formations':'Tutorials',
        'Exemples':'Demos',
        'Aide':'Help',

        'ouvrir':'Open',
        'enregistrer':'Save',
        'exporter':'Export',
        'preference':'Preferences',
        'reinit':'Reset',
        'pub':'Publish',
        'amp':'Import a layout',
        'esn':'Edit nodes style',
        'esf':'Edit links style',
        'rc':'Keyboard Shortcuts',
        'as':'Additional Help',
        'doc': 'Documentation',
        'ca':'Path',
        'annuler':'Cancel',
        'pdd':'Publish/Update diagram',
        'fmep':'Layout file',
        'ad':'Apply the layout',
        'ns':'Style name',

        'BgC':'Sankey background color',
        'dns':'Display only visible nodes in the nodes selector',
        'dls':'Display only visible links in the links selector',

        'textDisposition':'Apply the modifications on :',
        'PosNoeud':'Nodes\' positions',
        'attrNode':'Nodes\' attributes',
        'attrFlux':'Links\' attributes',
        'tagNode':'Nodes\' tags',
        'tagFlux':'Links\' tags',
        'attrGeneral':'Generals attributes',
        'SaveJSON':'Save as JSON',
        'SaveValue':'Save with links\' values',
        'templates':'Templates'
      },
      MEP:{
        'Echelle':'Scale of diagram',
        'MaxFlux':'Maximal value for links (px)',
        'vp100':'value for 100px',
        'TCG':'Grid size (px)',
        'GV':'Show grid',
        'AN':'Arrange the nodes on the grid',
        'EEN':'Spacing between nodes on the grid (px)',
        'Horizontal':'Horizontal',
        'Vertical':'Vertical',
        'PA':'Automatic positioning of nodes and links',
      },
      Tags:{
        'Nom':'Name',
        'Leg':'Legend',
        'tags':'Tags',
        'Bannière':'Banner',
        'Position':'Position',
        'Aucun':'None',
        'Unique':'Unique',
        'Multiple':'Multiple',
        'Niveau' : 'Level',
        'Visible':'Visible',
        'Couleur':'Color',
        'Forme':'Shape',
        'GE':'Tags\' Group',
        'selct':'Selected'
      },
      Noeud:{
        'Nom':'Name',
        'Style':'Style',
        'AS':'Apply the style to selected node(s)',
        'TS':'Select all',
        'NS':'No node selected',
        apparence:{
          'apparence':'Appearence',
          'Visibilité':'Visibility',
          'Couleur':'Color',
          'CouleurPérenne':'Static color',
          'Forme':'Shape',
          'Cercle':'Circle',
          'Rectangle':'Rectangle',
          'TML':'Minimum width',
          'TMH': 'Minimum height',
          'HideAlone':'Hide if node is intermediate',
          'asn':'Apply style to nodes',
          'toScale':'Node out of scale',
          'Orientation':'Orientation : ',
          'toScaleBottom':'to the bottom',
          'toScaleTop':'to the top',
          'toScaleLeft':'to the left',
          'toScaleRight':'to the right'
        },
        labels:{
          'labels':'Labels',
          'vdb':'Label visibility',
          'lb':'White label',
          'pv':'Vertical position',
          'haut':'Top',
          'Milieu':'Middle',
          'Bas':'Bottom',
          'ph':'Horizontal position',
          'gauche':'Left',
          'droite':'Right',
          'tp':'Font size',
          'police':'Font type',
          'gras':'Bold',
          'maj':'Uppercase',
          'ita':'Italic',
          'cl':'Text box width',
          'vdv':'Set value visibility'
        },
        icon:{
          'icon':'Icon',
          'si':'Select icon',
          'couleur':'Color',
          'rIN':'Size ratio icon/node',
          'Aucun':'None'
        },
        tags_node:{
          'tags':'Tags',
          'Appartenance':'Affiliations'
        },
        'IB':'Tooltip',
        agre:{
          'Agré':'Aggregation',
          'DC':'Cube\'s dimensions',
          'Parent':'Parent',
          'CLE':'Copy childs\' links'
        },
        PF:{
          'PF':'I/O links positions',
          'FES':'Links type',
          'ent':'Input',
          'sort':'Output',
          'FRN':'Relative position to the node',
          'g':'Left',
          'd':'Right',
          'ades':'Above',
          'edes':'Below',
          'lti':'Identify the links in the table with their colors',
          'col':'Appliquer'
        }
      },
      Flux:{
        'pdl':'Font',
        'src':'Source',
        'trgt':'Target',
        'if':'Reverse direction',
        'dzf':'Relative overlay on display',
        'style':'Style',
        'as':'Apply the style to selected link(s)',
        data:{
          'données':'Data',
          'vpp':'Value for given parameters',
          'affichage':'Display',
          'toPrecision':'Display the value in scientific notation'
        },
        apparence:{
          'apparence':'Appearance',
          'couleur':'Color',
          'grad':'Gradient',
          'hach':'Dashed',
          'of':'Orientation',
          'pdc':'Relative position of the center (%)',
          'eep':'Relative distance from handles to center (%)',
          'type':'Type',
          'courbe':'Curve',
          'fleche':'Arrow',
          'recy':'Recycling',
          'courbure':'Curvature'
        },
        label:{
          'label':'Label',
          'len':'Black label',
          'lb':'White label',
          'lec':'Colored label',
          'acf':'Orient along the link axis',
          'pl':'Lateral position',
          'po':'Orthogonal position',
          'deb':'Start',
          'fin':'End',
          'dessous':'Above',
          'dessus':'Below',
          'pls':'Position the label with the mouse'
        }
      },
      LL:{
        'hl':'Label Height',
        'll':'Label Width',
        'ft':'Transparent Background',
        'cfl':'Background Color',
        'bt':'Transparent border',
        'cbl':'Border Color',
        'pvt':'Vertical position',
        'at':'Texte alignment',
        'labels':'Labels',
        'gras':'Bold',
        'maj':'Uppercase',
        'ita':'Italic',
        'centre':'Centre',
        'textAsHTML':'foreignObject label'
      },
      Banner:{
        'fdf':'Link filtering',
        'fdn':'Node Filtering',
        'ndd':'Levels of detail',
        'ndd_lst':'Tags groups',
        'ndd_chk':'Apply the groups\' colors',
        'sdr':'Diagram type',
        'sdd':'Data selection',
        'tl':'Download',
        'rslt':'Results',
        'ff':'Links visual filtering',
        'filtre':'Threshold value for links dislay',
        'fl':'Threshold value for labels display',
        'fn':'Null Link',
        'visible':'Visible',
        'hlp':'Help',
        'hlp_1':'Sankey diagram',
        'hlp_1_txt_1':'The thickness of an arrow is proportional to the value of the flux it represents.',
        'hlp_1_txt_2':'The diagram can be viewed with different levels of aggregation using the Level of Detail> selector',
        'hlp_1_txt_3':'Filters can be used to display only parts of the diagram. To do this use the selectors',
        'hlp_1_txt_4':'Different color palettes can be used to color nodes and flows using the Color Palette selector',
        'hlp_1_txt_5':'The diagram structure (without flow thickness) can be displayed by checking Diagram structure',
        'hlp_1_txt_6':'The diagram can be adjusted on screen by checking Adjust on screen',
        'hlp_1_txt_7':'To get information about each flow, press shift and move the mouse over the flow',
        'tooltipAdjust':'Readjust the drawing area to the screen size',
        'tooltipStructure':'Allows to display the structure of the diagram without proportion of the flows according to their value',
        'tooltipData':'Allows to display the data of the diagram',
        'tooltipSelection':'Allows to drag the nodes',
        'tooltipHelp':'Additional informations about Sankey diagrams',
        'tooltipAjoutNode':'Adds a node to the mouse click',
        'tooltipLiason':'Allows to create links between two existing nodes, from an existing node or to an existing node'
      }
    }
  },
  //=======================================================
  //FR
  //=======================================================
  fr: {
    translation: {
      Menu:{
        'confSankey': 'Configuration du Sankey',
        'MEP':'Mise en page',
        'Noeuds':'Noeuds',
        'EN':'Étiquettes des noeuds',
        'EdN':'Édition des noeuds',
        'flux':'Flux',
        'EF':'Étiquettes des flux',
        'EdF':'Édition des flux',
        'ED':'Étiquettes des données',
        'LL':'Label libres',
        'Leg':'Legendes',
        'LegX':'Position horizontale',
        'LegY':'Position verticale',
        'LegWidth':'Largeur',
        'Fichiers':'Fichiers',
        'Edition':'Édition',
        'Formations':'Tutoriels',
        'Exemples':'Démos',
        'Aide':'Aide',

        'ouvrir':'Ouvrir',
        'enregistrer':'Enregistrer',
        'exporter':'Exporter',
        'preference':'Préférences',
        'reinit':'Réinitialiser',
        'pub':'Publier',
        'amp':'Importer une mise en page',
        'esn':'Editer le style des Noeuds',
        'esf':'Editer le style des Flux',
        'rc':'Raccourcis Clavier',
        'as':'Aide Supplémentaire',
        'doc': 'Documentation',
        'ca':'Chemin d\'accés',
        'annuler':'Annuler',
        'pdd':'Publication/Mise à jour du diagramme',
        'fmep':'Fichier de mise en page',
        'ad':'Appliquer la mise en page',

        'ns':'Nom du Style',

        'BgC':'Couleur du fond de page',
        'dns':'N\'affiche que les noeuds visibles dans le sélecteur de noeuds',
        'dls':'N\'affiche que les flux visibles dans le sélecteur de flux',

        'textDisposition':'Appliquer les modifications sur :',
        'PosNoeud':'Positions des Noeuds',
        'attrNode':'Attributs des Noeuds',
        'attrFlux':'Attributs des Flux',
        'tagNode':'Etiquettes des Noeuds',
        'tagFlux':'Etiquettes des Flux',
        'attrGeneral':'Attributs généraux',
        'SaveJSON':'Enregistrer JSON',
        'SaveValue':'Enregistrer avec les valeurs des flux'
      },
      MEP:{
        'Echelle': 'Echelle du diagramme',
        'MaxFlux': 'Taille maximale des flux (px)',
        'vp100':'valeur pour 100px',
        'TCG':'Taille du quadrillage (px)',
        'GV':'Afficher le quadrillage',
        'AN':'Arranger les noeuds sur le quadrillage',
        'EEN':'Ecart entre les noeuds sur le quadrillage (px)',
        'Horizontal':'Horizontal',
        'Vertical':'Vertical',
        'PA':'Positionnement automatique des noeuds et flux'
      },
      Tags:{
        'Nom':'Nom',
        'Leg':'Légende',
        'tags':'Étiquette',
        'Bannière':'Bannière',
        'Position':'Position',
        'Aucun':'Aucun',
        'Unique':'Unique',
        'Multiple':'Multiple',
        'Visible':'Visible',
        'Couleur':'Couleur',
        'Forme':'Forme',
        'GE':'Groupe d\'étiquettes',
        'selct':'Sélectionné'
      },
      Noeud:{
        'Nom':'Nom',
        'Style':'Style',
        'AS':'Appliquer le style au(x) noeud(s) selectionné(s)',
        'TS':'Tout sélectionner',
        'NS':'Aucun noeud sélectionné',
        apparence:{
          'apparence':'Apparence',
          'Visibilité':'Visibilité',
          'Couleur':'Couleur',
          'CouleurPérenne':'Couleur fixe',
          'Forme':'Forme',
          'Cercle':'Cercle',
          'Rectangle':'Rectangle',
          'TML':'Largeur minimale',
          'TMH':'Hauteur minimale',
          'HideAlone':'Cacher si noeud est intermédiaire',
          'asn':'Appliquer le style aux noeuds',
          'toScale':'Noeud hors échelle',
          'Orientation':'Orientation : ',
          'toScaleBottom':'Vers le bas',
          'toScaleTop':'Vers le haut',
          'toScaleLeft':'Vers la gauche',
          'toScaleRight':'Vers la droite'
        },
        labels:{
          'labels':'Labels',
          'vdb':'Visibilité du label',
          'lb':'Label blanc',
          'pv':'Position verticale',
          'haut':'Haut',
          'Milieu':'Milieu',
          'Bas':'Bas',
          'ph':'Position horizontale',
          'gauche':'Gauche',
          'droite':'Droite',
          'tp':'Taille de police',
          'police':'Style de police',
          'gras':'Gras',
          'maj':'Majuscule',
          'ita':'Italique',
          'cl':'Largeur zone de texte',
          'vdv':'Afficher la valeur'
        },
        icon:{
          'icon':'Icône',
          'si':'Sélectionner l\'icône',
          'couleur':'Couleur',
          'rIN':'Ratio taille icône/noeud',
          'Aucun':'Aucun'
        },
        tags_node:{
          'tags':'Étiquettes',
          'Appartenance':'Appartenance'
        },
        'IB':'Info-bulle',
        agre:{
          'Agré':'Agrégations',
          'DC':'Dimension du cube',
          'Parent':'Parent',
          'CLE':'Copier liens enfants'
        },
        PF:{
          'PF':'Position flux e/s',
          'FES':'Type de flux',
          'ent':'Entrant',
          'sort':'Sortant',
          'FRN':'Position relative au noeud',
          'ades':'Au-dessus',
          'edes':'En-dessous',
          'lti':'Identifier les flux du tableau avec leurs couleurs',
          'col':'Appliquer'
        }
      },
      Flux:{
        'pdl':'Police des labels',
        'src':'Source',
        'trgt':'Cible',
        'if':'Inverser la direction',
        'dzf':'Superposition à l\'affichage',
        'style':'Style',
        'as':'Appliquer le style au(x) flux selectionné(s)',
        data:{
          'données':'Données',
          'vpp':'Valeur pour ces paramètres',
          'affichage':'Affichage',
          'toPrecision':'Afficher la valeur en notation scientifique'
        },
        apparence:{
          'apparence':'Apparence',
          'couleur':'Couleur',
          'grad':'Gradient',
          'hach':'Hachuré',
          'of':'Orientation',
          'pdc':'Position relative du centre (%)',
          'eep':'Distance relative des poignées au centre (%)',
          'type':'Type',
          'courbe':'Courbe',
          'fleche':'Flèche',
          'recy':'Recyclage',
          'courbure':'Courbure'
        },
        label:{
          'label':'Label',
          'len':'Label en noir',
          'lb':'Label en blanc',
          'lec':'Label en couleur',
          'acf':'Orienter suivant l\'axe du flux',
          'pl':'Positionnement Lateral',
          'po':'Positionnement Orthogonal',
          'deb':'Début',
          'fin':'Fin',
          'dessous':'Dessous',
          'dessus':'Dessus',
          'pls':'Positionner le label à la souris'
        }
      },
      LL:{
        'hl':'Hauteur label',
        'll':'Largeur label',
        'ft':'Fond transparent',
        'cfl':'Couleur fond label',
        'bt':'Bordure transparent',
        'cbl':'Couleur bordure label',
        'pvt':'Position verticale texte',
        'at':'Alignement texte',
        'labels':'Labels',
        'gras':'Gras',
        'maj':'Majuscule',
        'ita':'Italique',
        'centre':'Centre',
        'textAsHTML':'Label foreignObject'
      },
      Banner:{
        'fdf':'Filtrage des flux',
        'fdn':'Filtrage des noeuds',
        'ndd':'Niveaux de détail',
        'ndd_lst':'Groupes d\'étiquettes',
        'ndd_chk':'Appliquer les couleurs associées',
        'sdr':'Type de diagramme',
        'sdd':'Sélection des données',
        'tl':'Téléchargements',
        'rslt':'Résultats',
        'ff':'Filtrage visuel des flux',
        'filtre':'Valeur seuil pour l\'affichage des flux',
        'fl':'Valeur seuil pour l\'affichage des labels',
        'fn':'Flux non-renseignés',
        'visible':'Visible',
        'hlp':'Aide',
        'hlp_1':'Les diagrammes de Sankey',
        'hlp_1_txt_1':'L\'épaisseur d\'une flèche est proportionnelle à la valeur du flux qu\'elle représente.',
        'hlp_1_txt_2':'Le diagramme peut être visualisé avec différents niveaux d\'agrégations en utilisant le sélecteur Niveau de détail',
        'hlp_1_txt_3':'Des filtres peuvent être utilisés pour n\'afficher que des parties du diagramme. Pour cela utiliser les selecteurs',
        'hlp_1_txt_4':'Différents palettes de couleurs peuvent être utiliser pour colorer les noeuds et les flux en utilisant le sélecteur Palette de Couleurs',
        'hlp_1_txt_5':'La structure du diagramme (sans épaisseur de flux) peut être affiché en cochant Structure du diagramme',
        'hlp_1_txt_6':'Le diagramme peut être ajusté à l\'écran en cochant Ajuster à l\'écran',
        'hlp_1_txt_7':'Pour obtenir des informations sur chaque flux, appuyer sur shift et passer la souris sur le flux.',
        'tooltipAdjust':'Permet de réajuster la zone de dessin à la taille de l\'écran',
        'tooltipStructure':'Permet d\'afficher la structure du diagramme sans proportion des flux selon leur valeur',
        'tooltipData':'Permet d\'afficher les données du diagramme',
        'tooltipSelection':'Permet de sélectionner ou de déplacer les noeuds',
        'tooltipHelp':'Informations supplémentaires sur la représentation avec les diagrammes de Sankey',
        'tooltipLiason':'Permet de créer des flux entre deux noeuds existants, depuis un noeud existant ou vers un noeud existant'
      }
    }
  }
}

i18next
  .use(LanguageDetector)
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    // lng: 'en', // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option

    interpolation: {
      escapeValue: false // react already safes from xss
    }
  })

export default i18next