import * as OpensankeyUtils from 'open-sankey/dist/src/lib/SankeyUtils'
import * as OpenSankeyDrawFunc from 'open-sankey/dist/src/lib/SankeyDrawFunction'
import * as OpensankeyDragFunc from 'open-sankey/dist/src/lib/SankeyDrag'
import * as OpensankeyConvert from 'open-sankey/dist/src/lib/SankeyConvert'
import * as FunctionTypes from 'open-sankey/types/FunctionTypes'
import { drag_legend_g_element} from 'open-sankey/dist/src/lib/SankeyDrawLegend'


export const ReturnValueLink=OpensankeyUtils.ReturnValueLink as FunctionTypes.ReturnValueLinkFuncType

export const ReturnValueNode=OpensankeyUtils.ReturnValueNode as FunctionTypes.ReturnValueNodeFuncType

export const IsAllLinkAttrSameValue=OpensankeyUtils.IsAllLinkAttrSameValue as FunctionTypes.IsAllLinkAttrSameValueFuncType

export const IsLinkDiplayingValueLocal =OpensankeyUtils.IsLinkDiplayingValueLocal as FunctionTypes.IsLinkDisplayingValueLocalFuncType

export const NodeColor = OpensankeyUtils.NodeColor as FunctionTypes.NodeColorFuncType

export const LinkStrokeOSTyped = OpenSankeyDrawFunc.LinkStroke as FunctionTypes.LinkStrokeFuncType

export const DrawArrows = OpenSankeyDrawFunc.DrawArrows as FunctionTypes.drawArrowsType

export const DrawGrid = OpenSankeyDrawFunc.DrawGrid as FunctionTypes.DrawGridFuncType

export const GetSankeyMinWidthAndHeight = OpenSankeyDrawFunc.GetSankeyMinWidthAndHeight as FunctionTypes.GetSankeyMinWidthAndHeightFuncType

export const NodeVisibleOnsSvg = OpenSankeyDrawFunc.NodeVisibleOnsSvg as FunctionTypes.NodeVisibleOnsSvgFuncType

export const LinkVisibleOnSvg = OpenSankeyDrawFunc.LinkVisibleOnSvg as FunctionTypes.LinkVisibleOnsSvgFuncType

export const DeselectVisualyNodes = OpenSankeyDrawFunc.DeselectVisualyNodes as FunctionTypes.DeselectVisualyNodesFuncType

export const RemoveAnimate = OpenSankeyDrawFunc.RemoveAnimate as FunctionTypes.RemoveAnimateFuncType

export const SvgDragMiddleMouseStart = OpenSankeyDrawFunc.SvgDragMiddleMouseStart as FunctionTypes.SvgDragMiddleMouseStartFuncType

export const SvgDragMiddleMouseMove = OpenSankeyDrawFunc.SvgDragMiddleMouseMove as FunctionTypes.SvgDragMiddleMouseMoveFuncType

export const SimpleGNodeClick = OpenSankeyDrawFunc.SimpleGNodeClick as FunctionTypes.SimpleGNodeClickFuncType

export const IsNodeDisplayingValueLocal = OpensankeyUtils.IsNodeDisplayingValueLocal as FunctionTypes.IsNodeDisplayingValueLocalFuncType

export const IsAllNodeAttrSameValue = OpensankeyUtils.IsAllNodeAttrSameValue as FunctionTypes.IsAllNodeAttrSameValueFuncType

export const AssignNodeValueToCorrectVar:FunctionTypes.AssignNodeValueToCorrectVarFuncType = OpensankeyUtils.AssignNodeValueToCorrectVar

export const opposing_drag_elements:FunctionTypes.opposing_drag_elementsFuncType = OpensankeyDragFunc.opposing_drag_elements

export const drag_elements:FunctionTypes.drag_elementsFuncType = OpensankeyDragFunc.drag_elements

export const drag_node_text:FunctionTypes.drag_node_textFuncType = OpensankeyDragFunc.drag_node_text

export const return_out_of_bound_element:FunctionTypes.return_out_of_bound_elementFuncType =OpensankeyDragFunc.return_out_of_bound_element

export const drag_legend_g_elementOSTyped:FunctionTypes.drag_legend_g_elementFuncType = drag_legend_g_element

export const LinkColor:FunctionTypes.LinkColorFuncType=OpensankeyUtils.LinkColor

export const AssignLinkValueToCorrectVar:FunctionTypes.AssignLinkValueToCorrectVarFuncType = OpensankeyUtils.AssignLinkValueToCorrectVar

export const DefaultLinkStyle:FunctionTypes.DefaultLinkStyleFuncType = OpensankeyUtils.DefaultLinkStyle

export const DefaultLink:FunctionTypes.DefaultLinkFuncType = OpensankeyUtils.DefaultLink

export const DefaultNode:FunctionTypes.DefaultNodeFuncType = OpensankeyUtils.DefaultNode

export const updateLayoutOSTyped:FunctionTypes.updateLayoutFuncType = OpensankeyUtils.updateLayout

export const AdjustSankeyZone:FunctionTypes.AdjustSankeyZoneFuncType= OpensankeyUtils.AdjustSankeyZone

export const synchronizeNodesandLinksIdOSTyped:FunctionTypes.synchronizeNodesandLinksIdFuncType = OpensankeyUtils.synchronizeNodesandLinksId

export const complete_sankey_data:FunctionTypes.complete_sankey_dataFunctType = OpensankeyConvert.complete_sankey_data

export const convert_data:FunctionTypes.ConvertDataFuncType = OpensankeyConvert.convert_data

export const convert_nodes:FunctionTypes.convert_nodesFuncType = OpensankeyConvert.convert_nodes

export const convert_links:FunctionTypes.convert_linksFuncType = OpensankeyConvert.convert_links

export const convert_tags:FunctionTypes.convert_tagsFuncType = OpensankeyConvert.convert_tags

export const NodeDisplayed:FunctionTypes.NodeDisplayedFuncType = OpensankeyUtils.NodeDisplayed

export const reorganize_node_outputLinksIdOSTyped:FunctionTypes.reorganize_node_outputLinksIdFuncType = OpensankeyUtils.reorganize_node_outputLinksId

export const reorganize_node_inputLinksIdOSTyped:FunctionTypes.reorganize_node_inputLinksIdFuncType = OpensankeyUtils.reorganize_node_inputLinksId