export const rcc_shortcuts = {

  en: {
    translation: {
      Menu: {
        rcc_titre_princ: 'OpenSankey Application Shortcuts',
        rcc_titre_select: 'With the mouse in selection mode',
        rcc_cn_bold: 'Click (element)',
        rcc_cn: 'Select the clicked element and open its configuration',
        rcc_ctrl_cn_bold: 'CTRL + Click (element) / CMD + Click on Mac',
        rcc_ctrl_cn: 'Add or remove the clicked element from the selection',
        rcc_cs_bold: 'Click (drawing area)',
        rcc_cs: 'Deselects all selected elements',
        rcc_click_and_drag_bold: 'Click & drag (drawing area)',
        rcc_click_and_drag: 'Create a selection zone that selects elements included inside',
        rcc_dn_bold: 'Drag (nodes)',
        rcc_dn: 'Move the selected nodes (all selected nodes move together)',
        rcc_shift_dn_bold: 'Shift + Drag (nodes)',
        rcc_shift_dn: 'Lock the movement to a single axis (horizontal or vertical), chosen from the initial motion — release Shift to resume free movement',
        rcc_cdn_bold: 'Right click (element, drawing area)',
        rcc_cdn: 'Open a contextual menu to apply quick changes or open some modals',
        rcc_ad_bold: 'Alt + Drag (labels, values, icons)',
        rcc_ad: 'Repositions the label, value or icon of any element (node, link, free label)',
        rcc_handle_bold: 'Drag (link handles)',
        rcc_handle: 'Adjusts the shape of the link (starting/ending curve, tangents, recycling middle point)',
        rcc_shift_hover_bold: 'Shift + Hover (element)',
        rcc_shift_hover: 'Displays a tooltip for the element',
        rcc_titre_edi: 'With the mouse in edit mode',
        rcc_e_cn_bold: 'Click (drawing area)',
        rcc_e_cn: 'Adds a node where clicked',
        rcc_e_ds_bold: 'Drag (from drawing area)',
        rcc_e_ds: 'Creates a node at the drag start point and then creates a link from the node created to: either a node already existing if you drop on it, or a node that you create at the place where you drop on the drawing area',
        rcc_e_dn_bold: 'Drag (from a node)',
        rcc_e_dn: 'Create a link from the drag start node: either a node already existing if you drop on it, or a node that you create where you drop on the drawing area',
        rcc_titre_toolbar: 'Toolbar',
        rcc_tb_select_bold: 'Selection mode',
        rcc_tb_select: 'Move and select elements',
        rcc_tb_edition_bold: 'Edition mode',
        rcc_tb_edition: 'Create nodes and links by clicking or dragging',
        rcc_tb_style_bold: 'Style paint',
        rcc_tb_style: 'Apply the style of the selected element to others by clicking on them',
        rcc_tb_param_bold: 'Parametric / Absolute',
        rcc_tb_param: 'Switch between parametric (hierarchical) and absolute positioning for nodes',
        rcc_tb_fit_bold: 'Auto-fit',
        rcc_tb_fit: 'Auto-fit the drawing area horizontally or vertically',
        rcc_tb_fullscreen_bold: 'Fullscreen',
        rcc_tb_fullscreen: 'Toggle fullscreen mode',
        rcc_titre_autre: 'Keyboard shortcuts',
        rcc_a_s_bold: 'Delete / Backspace on Mac',
        rcc_a_s: 'Removes selected elements',
        rcc_a_fc_bold: 'Keyboard arrows',
        rcc_a_fc: 'Move the selected nodes according to the mesh',
        rcc_a_dbm_bold: 'Drag (middle mouse button)',
        rcc_a_dbm: 'Pan the drawing area',
        rcc_a_ech_bold: 'Esc',
        rcc_a_ech: 'Closes the menu and resets the mouse mode to selection',
        rcc_titre_OSP: 'Views',
        rcc_osp_cs_bold: 'CTRL+X / CMD+X on Mac',
        rcc_osp_cs: 'Creates a view which can then be modified. To keep the modifications applied to the view, save it with Ctrl+S (CMD+S on Mac).',
        rcc_F7_bold: 'F7 (Fn+F7 on Mac)',
        rcc_F7: 'Switch to master data',
        rcc_F8_bold: 'F8 (Fn+F8 on Mac)',
        rcc_F8: 'Switch to previous view',
        rcc_F9_bold: 'F9 (Fn+F9 on Mac)',
        rcc_F9: 'Switch to next view',
        rcc_ctrl_a_bold: 'CTRL+A / CMD+A on Mac',
        rcc_ctrl_a: 'Select all visible elements',
        rcc_ctrl_c_bold: 'CTRL+C / CMD+C on Mac',
        rcc_ctrl_c: 'Copy selected nodes',
        rcc_ctrl_v_bold: 'CTRL+V / CMD+V on Mac',
        rcc_ctrl_v: 'Paste copied nodes',
        rcc_ctrl_s_bold: 'CTRL+S / CMD+S on Mac',
        rcc_ctrl_s: 'Save to cache',
        rcc_ctrl_shift_s_bold: 'CTRL+SHIFT+S / CMD+SHIFT+S on Mac',
        rcc_ctrl_shift_s: 'Download as JSON',
        rcc_ctrl_alt_s_bold: 'CTRL+ALT+S / CMD+ALT+S on Mac',
        rcc_ctrl_alt_s: 'Download as Excel',
        rcc_ctrl_scrll_bold: 'CTRL+scroll / CMD+scroll on Mac',
        rcc_ctrl_scrll: 'Zoom/Unzoom in the drawing area',
        rcc_ctrl_z_bold: 'CTRL+Z / CMD+Z on Mac',
        rcc_ctrl_z: 'Undo last modification',
        rcc_ctrl_y_bold: 'CTRL+Y / CMD+Y on Mac',
        rcc_ctrl_y: 'Redo canceled modification'
      }
    }
  },
  fr: {
    translation: {
      Menu: {
        rcc_titre_princ: 'Navigation',
        rcc_titre_select: 'Avec la souris en mode sélection',
        rcc_cn_bold: 'Click (élément)',
        rcc_cn: 'Sélectionne l\'élément cliqué et ouvre sa configuration',
        rcc_ctrl_cn_bold: 'CTRL + Click (élément) / CMD + Click sur Mac',
        rcc_ctrl_cn: 'Ajoute ou retire l\'élément cliqué de la sélection',
        rcc_cs_bold: 'Click (zone de dessin)',
        rcc_cs: 'Désélectionne tous les éléments sélectionnés',
        rcc_click_and_drag_bold: 'Click & drag (zone de dessin)',
        rcc_click_and_drag: 'Crée une zone de sélection qui sélectionne les éléments compris à l\'intérieur une fois qu\'on relâche la souris',
        rcc_dn_bold: 'Drag (noeuds)',
        rcc_dn: 'Déplace les noeuds sélectionnés (tous les noeuds sélectionnés se déplacent ensemble)',
        rcc_shift_dn_bold: 'Shift + Drag (noeuds)',
        rcc_shift_dn: 'Verrouille le déplacement sur un seul axe (horizontal ou vertical), choisi selon le mouvement initial — relâcher Shift pour reprendre un déplacement libre',
        rcc_cdn_bold: 'Click droit (élément, zone de dessin)',
        rcc_cdn: 'Ouvre un menu contextuel permettant de faire des modifications rapides ou d\'ouvrir des modales',
        rcc_ad_bold: 'Alt + Drag (labels, valeurs, icônes)',
        rcc_ad: 'Repositionne le label, la valeur ou l\'icône de n\'importe quel élément (noeud, flux, zone de texte)',
        rcc_handle_bold: 'Drag (poignées de flux)',
        rcc_handle: 'Ajuste la forme du flux (courbure début/fin, tangentes, point milieu de recyclage)',
        rcc_shift_hover_bold: 'Shift + Survol (élément)',
        rcc_shift_hover: 'Affiche une infobulle pour l\'élément',
        rcc_titre_edi: 'Avec la souris en mode édition',
        rcc_e_cn_bold: 'Click (zone de dessin)',
        rcc_e_cn: 'Ajoute un noeud à l\'endroit cliqué',
        rcc_e_ds_bold: 'Drag (à partir de la zone de dessin)',
        rcc_e_ds: 'Crée un noeud au point de départ du drag puis crée un flux à partir du noeud crée vers : soit un noeud déjà existant si l\'on drop dessus, soit un noeud que l\'on crée à l\'endroit où l\'on drop sur la zone de dessin',
        rcc_e_dn_bold: 'Drag (à partir d\'un noeud)',
        rcc_e_dn: 'Créer un flux à partir du noeud de départ du drag vers : soit un noeud déjà existant si l\'on drop dessus, soit un noeud que l\'on crée à l\'endroit où l\'on drop sur la zone de dessin',
        rcc_titre_toolbar: 'Barre d\'outils',
        rcc_tb_select_bold: 'Mode sélection',
        rcc_tb_select: 'Déplacer et sélectionner les éléments',
        rcc_tb_edition_bold: 'Mode édition',
        rcc_tb_edition: 'Créer des noeuds et des flux en cliquant ou en glissant',
        rcc_tb_style_bold: 'Pinceau de style',
        rcc_tb_style: 'Applique le style de l\'élément sélectionné aux autres en cliquant dessus',
        rcc_tb_param_bold: 'Paramétrique / Absolu',
        rcc_tb_param: 'Bascule entre le positionnement paramétrique (hiérarchique) et absolu des noeuds',
        rcc_tb_fit_bold: 'Auto-ajustement',
        rcc_tb_fit: 'Ajuste automatiquement la zone de dessin horizontalement ou verticalement',
        rcc_tb_fullscreen_bold: 'Plein écran',
        rcc_tb_fullscreen: 'Active ou désactive le mode plein écran',
        rcc_titre_autre: 'Raccourcis clavier',
        rcc_a_s_bold: 'Suppr / Backspace sur Mac',
        rcc_a_s: 'Supprime les éléments sélectionnés',
        rcc_a_fc_bold: 'Flèches du clavier',
        rcc_a_fc: 'Déplace les noeuds sélectionnés en fonction du grillage',
        rcc_a_dbm_bold: 'Drag (bouton du milieu de la souris)',
        rcc_a_dbm: 'Déplace la zone de dessin',
        rcc_a_ech_bold: 'Echap',
        rcc_a_ech: 'Ferme le menu et remet la souris en mode sélection',
        rcc_titre_OSP: 'Vues',
        rcc_osp_cs_bold: 'CTRL+X / CMD+X sur Mac',
        rcc_osp_cs: 'Crée une vue qui peut être ensuite modifiée, pour conserver les modifications il faut l\'enregistrer avec Ctrl+S (CMD+S sur Mac)',
        rcc_F7_bold: 'F7 (Fn+F7 sur Mac)',
        rcc_F7: 'Retourne aux données maîtres',
        rcc_F8_bold: 'F8 (Fn+F8 sur Mac)',
        rcc_F8: 'Passe à la vue précédente',
        rcc_F9_bold: 'F9 (Fn+F9 sur Mac)',
        rcc_F9: 'Passe à la vue suivante',
        rcc_ctrl_a_bold: 'CTRL+A / CMD+A sur Mac',
        rcc_ctrl_a: 'Sélectionne tous les éléments visibles',
        rcc_ctrl_c_bold: 'CTRL+C / CMD+C sur Mac',
        rcc_ctrl_c: 'Copie les noeuds sélectionnés',
        rcc_ctrl_v_bold: 'CTRL+V / CMD+V sur Mac',
        rcc_ctrl_v: 'Colle les noeuds copiés',
        rcc_ctrl_s_bold: 'CTRL+S / CMD+S sur Mac',
        rcc_ctrl_s: 'Sauvegarde en cache',
        rcc_ctrl_shift_s_bold: 'CTRL+SHIFT+S / CMD+SHIFT+S sur Mac',
        rcc_ctrl_shift_s: 'Télécharge en JSON',
        rcc_ctrl_alt_s_bold: 'CTRL+ALT+S / CMD+ALT+S sur Mac',
        rcc_ctrl_alt_s: 'Télécharge en Excel',
        rcc_ctrl_scrll_bold: 'CTRL+scroll / CMD+scroll sur Mac',
        rcc_ctrl_scrll: 'Zoomer/dézoomer sur la zone de dessin',
        rcc_ctrl_z_bold: 'CTRL+Z / CMD+Z sur Mac',
        rcc_ctrl_z: 'Annule la dernière modification',
        rcc_ctrl_y_bold: 'CTRL+Y / CMD+Y sur Mac',
        rcc_ctrl_y: 'Refait la modification précédemment annulée'
      }
    }
  },
  es: {
    translation: {
      Menu: {
        rcc_titre_princ: 'Atajos de la aplicación OpenSankey',
        rcc_titre_select: 'Con el ratón en modo selección',
        rcc_cn_bold: 'Clic (elemento)',
        rcc_cn: 'Selecciona el elemento clicado y abre su configuración',
        rcc_ctrl_cn_bold: 'CTRL + Clic (elemento) / CMD + Clic en Mac',
        rcc_ctrl_cn: 'Añade o elimina el elemento clicado de la selección',
        rcc_cs_bold: 'Clic (área de dibujo)',
        rcc_cs: 'Deselecciona todos los elementos seleccionados',
        rcc_click_and_drag_bold: 'Clic y arrastrar (área de dibujo)',
        rcc_click_and_drag: 'Crea una zona de selección que selecciona los elementos incluidos dentro al soltar el ratón',
        rcc_dn_bold: 'Arrastrar (nodos)',
        rcc_dn: 'Mueve los nodos seleccionados (todos los nodos seleccionados se mueven juntos)',
        rcc_shift_dn_bold: 'Shift + Arrastrar (nodos)',
        rcc_shift_dn: 'Bloquea el movimiento en un solo eje (horizontal o vertical), elegido según el movimiento inicial — soltar Shift para reanudar el movimiento libre',
        rcc_cdn_bold: 'Clic derecho (elemento, área de dibujo)',
        rcc_cdn: 'Abre un menú contextual para aplicar cambios rápidos o abrir ventanas modales',
        rcc_ad_bold: 'Alt + Arrastrar (etiquetas, valores, iconos)',
        rcc_ad: 'Reposiciona la etiqueta, el valor o el icono de cualquier elemento (nodo, flujo, etiqueta libre)',
        rcc_handle_bold: 'Arrastrar (tiradores de flujo)',
        rcc_handle: 'Ajusta la forma del flujo (curvatura de inicio/fin, tangentes, punto medio de reciclaje)',
        rcc_shift_hover_bold: 'Shift + Pasar el ratón (elemento)',
        rcc_shift_hover: 'Muestra una información emergente del elemento',
        rcc_titre_edi: 'Con el ratón en modo edición',
        rcc_e_cn_bold: 'Clic (área de dibujo)',
        rcc_e_cn: 'Añade un nodo donde se hace clic',
        rcc_e_ds_bold: 'Arrastrar (desde el área de dibujo)',
        rcc_e_ds: 'Crea un nodo en el punto de inicio del arrastre y luego crea un flujo desde el nodo creado hacia: un nodo ya existente si se suelta sobre él, o un nodo que se crea en el lugar donde se suelta en el área de dibujo',
        rcc_e_dn_bold: 'Arrastrar (desde un nodo)',
        rcc_e_dn: 'Crea un flujo desde el nodo de inicio del arrastre hacia: un nodo ya existente si se suelta sobre él, o un nodo que se crea donde se suelta en el área de dibujo',
        rcc_titre_toolbar: 'Barra de herramientas',
        rcc_tb_select_bold: 'Modo selección',
        rcc_tb_select: 'Mover y seleccionar elementos',
        rcc_tb_edition_bold: 'Modo edición',
        rcc_tb_edition: 'Crear nodos y flujos haciendo clic o arrastrando',
        rcc_tb_style_bold: 'Pincel de estilo',
        rcc_tb_style: 'Aplica el estilo del elemento seleccionado a otros al hacer clic sobre ellos',
        rcc_tb_param_bold: 'Paramétrico / Absoluto',
        rcc_tb_param: 'Alterna entre posicionamiento paramétrico (jerárquico) y absoluto para los nodos',
        rcc_tb_fit_bold: 'Autoajuste',
        rcc_tb_fit: 'Ajusta automáticamente el área de dibujo horizontal o verticalmente',
        rcc_tb_fullscreen_bold: 'Pantalla completa',
        rcc_tb_fullscreen: 'Activa o desactiva el modo de pantalla completa',
        rcc_titre_autre: 'Atajos de teclado',
        rcc_a_s_bold: 'Supr / Backspace en Mac',
        rcc_a_s: 'Elimina los elementos seleccionados',
        rcc_a_fc_bold: 'Flechas del teclado',
        rcc_a_fc: 'Mueve los nodos seleccionados según la cuadrícula',
        rcc_a_dbm_bold: 'Arrastrar (botón central del ratón)',
        rcc_a_dbm: 'Desplaza el área de dibujo',
        rcc_a_ech_bold: 'Esc',
        rcc_a_ech: 'Cierra el menú y restablece el ratón al modo selección',
        rcc_titre_OSP: 'Vistas',
        rcc_osp_cs_bold: 'CTRL+X / CMD+X en Mac',
        rcc_osp_cs: 'Crea una vista que luego puede modificarse. Para conservar las modificaciones, guárdela con CTRL+S (CMD+S en Mac).',
        rcc_F7_bold: 'F7 (Fn+F7 en Mac)',
        rcc_F7: 'Volver a los datos maestros',
        rcc_F8_bold: 'F8 (Fn+F8 en Mac)',
        rcc_F8: 'Cambiar a la vista anterior',
        rcc_F9_bold: 'F9 (Fn+F9 en Mac)',
        rcc_F9: 'Cambiar a la vista siguiente',
        rcc_ctrl_a_bold: 'CTRL+A / CMD+A en Mac',
        rcc_ctrl_a: 'Seleccionar todos los elementos visibles',
        rcc_ctrl_c_bold: 'CTRL+C / CMD+C en Mac',
        rcc_ctrl_c: 'Copiar los nodos seleccionados',
        rcc_ctrl_v_bold: 'CTRL+V / CMD+V en Mac',
        rcc_ctrl_v: 'Pegar los nodos copiados',
        rcc_ctrl_s_bold: 'CTRL+S / CMD+S en Mac',
        rcc_ctrl_s: 'Guardar en caché',
        rcc_ctrl_shift_s_bold: 'CTRL+SHIFT+S / CMD+SHIFT+S en Mac',
        rcc_ctrl_shift_s: 'Descargar como JSON',
        rcc_ctrl_alt_s_bold: 'CTRL+ALT+S / CMD+ALT+S en Mac',
        rcc_ctrl_alt_s: 'Descargar como Excel',
        rcc_ctrl_scrll_bold: 'CTRL+scroll / CMD+scroll en Mac',
        rcc_ctrl_scrll: 'Acercar/alejar en el área de dibujo',
        rcc_ctrl_z_bold: 'CTRL+Z / CMD+Z en Mac',
        rcc_ctrl_z: 'Deshacer la última modificación',
        rcc_ctrl_y_bold: 'CTRL+Y / CMD+Y en Mac',
        rcc_ctrl_y: 'Rehacer la modificación cancelada'
      }
    }
  },
  de: {
    translation: {
      Menu: {
        rcc_titre_princ: 'OpenSankey-Anwendungskürzel',
        rcc_titre_select: 'Mit der Maus im Auswahlmodus',
        rcc_cn_bold: 'Klick (Element)',
        rcc_cn: 'Wählt das angeklickte Element aus und öffnet seine Konfiguration',
        rcc_ctrl_cn_bold: 'CTRL + Klick (Element) / CMD + Klick auf Mac',
        rcc_ctrl_cn: 'Fügt das angeklickte Element zur Auswahl hinzu oder entfernt es',
        rcc_cs_bold: 'Klick (Zeichenfläche)',
        rcc_cs: 'Hebt die Auswahl aller ausgewählten Elemente auf',
        rcc_click_and_drag_bold: 'Klick & Ziehen (Zeichenfläche)',
        rcc_click_and_drag: 'Erstellt einen Auswahlbereich, der die darin enthaltenen Elemente beim Loslassen der Maus auswählt',
        rcc_dn_bold: 'Ziehen (Knoten)',
        rcc_dn: 'Verschiebt die ausgewählten Knoten (alle ausgewählten Knoten bewegen sich gemeinsam)',
        rcc_shift_dn_bold: 'Shift + Ziehen (Knoten)',
        rcc_shift_dn: 'Sperrt die Bewegung auf eine einzelne Achse (horizontal oder vertikal), bestimmt durch die anfängliche Bewegung — Shift loslassen für freie Bewegung',
        rcc_cdn_bold: 'Rechtsklick (Element, Zeichenfläche)',
        rcc_cdn: 'Öffnet ein Kontextmenü für schnelle Änderungen oder zum Öffnen von Dialogfenstern',
        rcc_ad_bold: 'Alt + Ziehen (Beschriftungen, Werte, Symbole)',
        rcc_ad: 'Positioniert die Beschriftung, den Wert oder das Symbol eines Elements neu (Knoten, Fluss, freie Beschriftung)',
        rcc_handle_bold: 'Ziehen (Flussgriffe)',
        rcc_handle: 'Passt die Form des Flusses an (Anfangs-/Endkrümmung, Tangenten, Recycling-Mittelpunkt)',
        rcc_shift_hover_bold: 'Shift + Überfahren (Element)',
        rcc_shift_hover: 'Zeigt einen Tooltip für das Element an',
        rcc_titre_edi: 'Mit der Maus im Bearbeitungsmodus',
        rcc_e_cn_bold: 'Klick (Zeichenfläche)',
        rcc_e_cn: 'Fügt einen Knoten an der angeklickten Stelle hinzu',
        rcc_e_ds_bold: 'Ziehen (von der Zeichenfläche)',
        rcc_e_ds: 'Erstellt einen Knoten am Startpunkt des Ziehens und dann einen Fluss vom erstellten Knoten zu: entweder einem bereits vorhandenen Knoten, wenn darauf losgelassen wird, oder einem neuen Knoten an der Stelle, an der auf der Zeichenfläche losgelassen wird',
        rcc_e_dn_bold: 'Ziehen (von einem Knoten)',
        rcc_e_dn: 'Erstellt einen Fluss vom Startknoten des Ziehens zu: entweder einem bereits vorhandenen Knoten, wenn darauf losgelassen wird, oder einem neuen Knoten an der Stelle, an der auf der Zeichenfläche losgelassen wird',
        rcc_titre_toolbar: 'Symbolleiste',
        rcc_tb_select_bold: 'Auswahlmodus',
        rcc_tb_select: 'Elemente verschieben und auswählen',
        rcc_tb_edition_bold: 'Bearbeitungsmodus',
        rcc_tb_edition: 'Knoten und Flüsse durch Klicken oder Ziehen erstellen',
        rcc_tb_style_bold: 'Stilpinsel',
        rcc_tb_style: 'Wendet den Stil des ausgewählten Elements auf andere an, indem man darauf klickt',
        rcc_tb_param_bold: 'Parametrisch / Absolut',
        rcc_tb_param: 'Wechselt zwischen parametrischer (hierarchischer) und absoluter Positionierung der Knoten',
        rcc_tb_fit_bold: 'Automatische Anpassung',
        rcc_tb_fit: 'Passt die Zeichenfläche automatisch horizontal oder vertikal an',
        rcc_tb_fullscreen_bold: 'Vollbild',
        rcc_tb_fullscreen: 'Vollbildmodus ein- oder ausschalten',
        rcc_titre_autre: 'Tastenkürzel',
        rcc_a_s_bold: 'Entf / Backspace auf Mac',
        rcc_a_s: 'Löscht die ausgewählten Elemente',
        rcc_a_fc_bold: 'Pfeiltasten',
        rcc_a_fc: 'Verschiebt die ausgewählten Knoten gemäß dem Raster',
        rcc_a_dbm_bold: 'Ziehen (mittlere Maustaste)',
        rcc_a_dbm: 'Verschiebt die Zeichenfläche',
        rcc_a_ech_bold: 'Esc',
        rcc_a_ech: 'Schließt das Menü und setzt die Maus in den Auswahlmodus zurück',
        rcc_titre_OSP: 'Ansichten',
        rcc_osp_cs_bold: 'CTRL+X / CMD+X auf Mac',
        rcc_osp_cs: 'Erstellt eine Ansicht, die anschließend geändert werden kann. Um die Änderungen zu speichern, verwenden Sie CTRL+S (CMD+S auf Mac).',
        rcc_F7_bold: 'F7 (Fn+F7 auf Mac)',
        rcc_F7: 'Zu den Stammdaten wechseln',
        rcc_F8_bold: 'F8 (Fn+F8 auf Mac)',
        rcc_F8: 'Zur vorherigen Ansicht wechseln',
        rcc_F9_bold: 'F9 (Fn+F9 auf Mac)',
        rcc_F9: 'Zur nächsten Ansicht wechseln',
        rcc_ctrl_a_bold: 'CTRL+A / CMD+A auf Mac',
        rcc_ctrl_a: 'Alle sichtbaren Elemente auswählen',
        rcc_ctrl_c_bold: 'CTRL+C / CMD+C auf Mac',
        rcc_ctrl_c: 'Ausgewählte Knoten kopieren',
        rcc_ctrl_v_bold: 'CTRL+V / CMD+V auf Mac',
        rcc_ctrl_v: 'Kopierte Knoten einfügen',
        rcc_ctrl_s_bold: 'CTRL+S / CMD+S auf Mac',
        rcc_ctrl_s: 'Im Cache speichern',
        rcc_ctrl_shift_s_bold: 'CTRL+SHIFT+S / CMD+SHIFT+S auf Mac',
        rcc_ctrl_shift_s: 'Als JSON herunterladen',
        rcc_ctrl_alt_s_bold: 'CTRL+ALT+S / CMD+ALT+S auf Mac',
        rcc_ctrl_alt_s: 'Als Excel herunterladen',
        rcc_ctrl_scrll_bold: 'CTRL+Scrollen / CMD+Scrollen auf Mac',
        rcc_ctrl_scrll: 'In der Zeichenfläche hinein-/herauszoomen',
        rcc_ctrl_z_bold: 'CTRL+Z / CMD+Z auf Mac',
        rcc_ctrl_z: 'Letzte Änderung rückgängig machen',
        rcc_ctrl_y_bold: 'CTRL+Y / CMD+Y auf Mac',
        rcc_ctrl_y: 'Rückgängig gemachte Änderung wiederherstellen'
      }
    }
  },
  it: {
    translation: {
      Menu: {
        rcc_titre_princ: 'Scorciatoie dell\'applicazione OpenSankey',
        rcc_titre_select: 'Con il mouse in modalità selezione',
        rcc_cn_bold: 'Clic (elemento)',
        rcc_cn: 'Seleziona l\'elemento cliccato e apre la sua configurazione',
        rcc_ctrl_cn_bold: 'CTRL + Clic (elemento) / CMD + Clic su Mac',
        rcc_ctrl_cn: 'Aggiunge o rimuove l\'elemento cliccato dalla selezione',
        rcc_cs_bold: 'Clic (area di disegno)',
        rcc_cs: 'Deseleziona tutti gli elementi selezionati',
        rcc_click_and_drag_bold: 'Clic e trascinamento (area di disegno)',
        rcc_click_and_drag: 'Crea una zona di selezione che seleziona gli elementi inclusi al rilascio del mouse',
        rcc_dn_bold: 'Trascinamento (nodi)',
        rcc_dn: 'Sposta i nodi selezionati (tutti i nodi selezionati si muovono insieme)',
        rcc_shift_dn_bold: 'Shift + Trascinamento (nodi)',
        rcc_shift_dn: 'Blocca il movimento su un singolo asse (orizzontale o verticale), scelto in base al movimento iniziale — rilasciare Shift per riprendere il movimento libero',
        rcc_cdn_bold: 'Clic destro (elemento, area di disegno)',
        rcc_cdn: 'Apre un menu contestuale per applicare modifiche rapide o aprire finestre modali',
        rcc_ad_bold: 'Alt + Trascinamento (etichette, valori, icone)',
        rcc_ad: 'Riposiziona l\'etichetta, il valore o l\'icona di qualsiasi elemento (nodo, flusso, etichetta libera)',
        rcc_handle_bold: 'Trascinamento (maniglie di flusso)',
        rcc_handle: 'Regola la forma del flusso (curvatura iniziale/finale, tangenti, punto medio di riciclo)',
        rcc_shift_hover_bold: 'Shift + Passaggio del mouse (elemento)',
        rcc_shift_hover: 'Mostra un suggerimento per l\'elemento',
        rcc_titre_edi: 'Con il mouse in modalità modifica',
        rcc_e_cn_bold: 'Clic (area di disegno)',
        rcc_e_cn: 'Aggiunge un nodo nel punto cliccato',
        rcc_e_ds_bold: 'Trascinamento (dall\'area di disegno)',
        rcc_e_ds: 'Crea un nodo nel punto di partenza del trascinamento e poi crea un flusso dal nodo creato verso: un nodo già esistente se si rilascia su di esso, oppure un nodo che si crea nel punto in cui si rilascia sull\'area di disegno',
        rcc_e_dn_bold: 'Trascinamento (da un nodo)',
        rcc_e_dn: 'Crea un flusso dal nodo di partenza del trascinamento verso: un nodo già esistente se si rilascia su di esso, oppure un nodo che si crea nel punto in cui si rilascia sull\'area di disegno',
        rcc_titre_toolbar: 'Barra degli strumenti',
        rcc_tb_select_bold: 'Modalità selezione',
        rcc_tb_select: 'Spostare e selezionare gli elementi',
        rcc_tb_edition_bold: 'Modalità modifica',
        rcc_tb_edition: 'Creare nodi e flussi cliccando o trascinando',
        rcc_tb_style_bold: 'Pennello di stile',
        rcc_tb_style: 'Applica lo stile dell\'elemento selezionato agli altri cliccandoci sopra',
        rcc_tb_param_bold: 'Parametrico / Assoluto',
        rcc_tb_param: 'Alterna tra posizionamento parametrico (gerarchico) e assoluto per i nodi',
        rcc_tb_fit_bold: 'Adattamento automatico',
        rcc_tb_fit: 'Adatta automaticamente l\'area di disegno orizzontalmente o verticalmente',
        rcc_tb_fullscreen_bold: 'Schermo intero',
        rcc_tb_fullscreen: 'Attiva o disattiva la modalità schermo intero',
        rcc_titre_autre: 'Scorciatoie da tastiera',
        rcc_a_s_bold: 'Canc / Backspace su Mac',
        rcc_a_s: 'Elimina gli elementi selezionati',
        rcc_a_fc_bold: 'Frecce della tastiera',
        rcc_a_fc: 'Sposta i nodi selezionati secondo la griglia',
        rcc_a_dbm_bold: 'Trascinamento (pulsante centrale del mouse)',
        rcc_a_dbm: 'Sposta l\'area di disegno',
        rcc_a_ech_bold: 'Esc',
        rcc_a_ech: 'Chiude il menu e ripristina il mouse in modalità selezione',
        rcc_titre_OSP: 'Viste',
        rcc_osp_cs_bold: 'CTRL+X / CMD+X su Mac',
        rcc_osp_cs: 'Crea una vista che può essere successivamente modificata. Per conservare le modifiche, salvarla con CTRL+S (CMD+S su Mac).',
        rcc_F7_bold: 'F7 (Fn+F7 su Mac)',
        rcc_F7: 'Tornare ai dati principali',
        rcc_F8_bold: 'F8 (Fn+F8 su Mac)',
        rcc_F8: 'Passare alla vista precedente',
        rcc_F9_bold: 'F9 (Fn+F9 su Mac)',
        rcc_F9: 'Passare alla vista successiva',
        rcc_ctrl_a_bold: 'CTRL+A / CMD+A su Mac',
        rcc_ctrl_a: 'Selezionare tutti gli elementi visibili',
        rcc_ctrl_c_bold: 'CTRL+C / CMD+C su Mac',
        rcc_ctrl_c: 'Copiare i nodi selezionati',
        rcc_ctrl_v_bold: 'CTRL+V / CMD+V su Mac',
        rcc_ctrl_v: 'Incollare i nodi copiati',
        rcc_ctrl_s_bold: 'CTRL+S / CMD+S su Mac',
        rcc_ctrl_s: 'Salvare nella cache',
        rcc_ctrl_shift_s_bold: 'CTRL+SHIFT+S / CMD+SHIFT+S su Mac',
        rcc_ctrl_shift_s: 'Scaricare come JSON',
        rcc_ctrl_alt_s_bold: 'CTRL+ALT+S / CMD+ALT+S su Mac',
        rcc_ctrl_alt_s: 'Scaricare come Excel',
        rcc_ctrl_scrll_bold: 'CTRL+scroll / CMD+scroll su Mac',
        rcc_ctrl_scrll: 'Ingrandire/ridurre nell\'area di disegno',
        rcc_ctrl_z_bold: 'CTRL+Z / CMD+Z su Mac',
        rcc_ctrl_z: 'Annullare l\'ultima modifica',
        rcc_ctrl_y_bold: 'CTRL+Y / CMD+Y su Mac',
        rcc_ctrl_y: 'Ripristinare la modifica precedentemente annullata'
      }
    }
  }
}
