export const resources_flux = {
  en: {
    translation: {
      Flux: {
        pg: 'General settings',
        pdl: 'Font',
        pl: 'Parameters per link',
        src: 'Origin',
        trgt: 'Destination',
        value: 'Value',
        calculated_value: 'Comp. Val',
        type: 'Format',
        if: 'Reverse direction',
        dzf: 'Overlaying order',
        style: 'Style',
        as: 'Apply the style to selected link(s)',
        IB: 'ToolTip',
        IS: 'Additional info.',
        ajust_label: 'Adjust labels position',
        FS: 'Link',
        local_scale: 'Local link scale',
        changePlan: 'Change plan of flows',
        mask_attr: 'Change flow\'s attributes',
        tooltips: {
          src: 'Choice of the departure node for the selected link(s)',
          trgt: 'Choice of the arrival node for the selected link(s)',
          if: 'Reverse the start and finish nodes for the selected link(s)',
          up: 'Move up one step to the foreground',
          upup: 'Put the selected stream(s) in the foreground',
          dwn: 'Go down one step to the last plane',
          dwndwn: 'Move the selected stream(s) to the last plane',
          as: 'Allow to apply a predefined style in the preferences menu to the selected link(s)',
          IB: 'Tooltip : text formatted in HTML and displayed with the tooltip of the link. This tooltip pops on graphic space with SHIFT + MOUSE on the link.',
          ajust_label: 'Reposition links labels above the links if they\'re taller than link stroke',
          inv: 'Inverse the target and the source'
        },
        data: {
          données: 'Data',
          vpp: 'Value',
          data_type: 'Data type',
          value: 'Value',
          ratio_input: 'Ratio total input',
          ratio_output: 'Ratio total output',
          ratio_source_parent: 'Ratio parent flux(left)',
          ratio_target_parent: 'Ratio parent flux(right)',
          unit_ratio: 'Coeff. units conversion',
          edit_value: 'Edit value',
          value_target: 'Dest. value',
          tab_basic: 'Basic',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Uncertainty',
          affichage: 'Label',
          tooltips: {
            data_type: 'Data type',
            vpp: 'Data associated to the selected link and, if existing, for the selected tag(s)',
            scientificNotation: 'Activate or not the notation in scientific format, for the display of the link\'s data on the Sankey diagram',
            affichage: 'Replacement text for the display of the link\'s data on the Sankey diagram',
            value_target: 'Destination value for tapered links (leave empty for uniform thickness)',
            data_min: 'Minimum bound for the flow value (used for reconciliation)',
            data_max: 'Maximum bound for the flow value (used for reconciliation)',
            uncertainty: 'Relative uncertainty in % on the flow value (used for reconciliation)',
            tab_basic_disabled: 'Select "Value" as data type in the AFM tab to enable this panel'
          }
        },
        apparence: {
          anchor: 'Anchors',
          handle: 'Handles',
          apparence: 'Appearance',
          flow: 'Flow',
          fond: 'shape background',
          source: 'Source node',
          target: 'Target node',
          couleur: 'Color',
          color_source: 'Element defining flow color',
          grad: 'Gradient',
          shape_is_dashed: 'Dashed',
          of: 'Orientation',
          type: 'Type',
          courbe: 'Curve',
          fleche: 'Arrow',
          opacity: 'Opacity',
          arrow_size: 'Size of arrow',
          display_link_lab: 'Display value',
          hide_link_lab: 'Hide value',
          display_link_name: 'Display name',
          hide_link_name: 'Hide name',
          data_off_scale: 'Scale',
          tooltips: {
            color_source: {
              def: 'Choose what rule define flow color :',
              flow: 'Color is defined by flow parameter (default color, flow tag\'s color or data tag\'s color)',
              source: 'Color is defined by source node color',
              target: 'Color is defined by target node color',
              gradient: 'Color is a gradient from source node color to target node color',
              auto: 'Color is determined automatically using this priority:\n1. Common color tag between source and target\n2. Only one side has a color tag → take that side\n3. Both have tags (no common) → prefer the product node\n4. No color tags → prefer the product node\n5. Fallback: source color',
              disabled: 'Rule doesn\'t allow to choose flow color'
            },
            couleur: 'Choose the color for the selected link(s)',
            grad: 'Apply a gradient color effect on the selected link(s). The gradient is done between the color of the start node and the color of the end node',
            shape_is_dashed: 'Applies a hatch effect on the selected link(s)',
            of_vv: 'Allows to orient the beginning of the link vertically and the end of the link vertically',
            of_hh: 'Allows to orient the beginning of the link horizontally and the end of the link horizontally',
            of_hv: 'Allows to orient the beginning of the link horizontally and the end of the link vertically',
            of_vh: 'Allows to orient the beginning of the link vertically and the end of the link horizontally',
            courbe: 'Represents the selected link(s) as a Bezier curve',
            fleche: 'Represents the selected link(s) with an arrow tip at the end',
            structure: 'Represents the selected link(s) as if they didn\'t have values no matter their true value',
            starting_curve: 'Allows to refine the position of the starting point of curvature for the selected link(s). This value is a ratio (%) of the link\'s lenght relative to the starting point of the link.',
            ending_curve: 'Allows to refine the position of the ending point of curvature for the selected link(s). This value is a ratio (%) of the link\'s lenght relative to the starting point of the link.',
            starting_tangeant: 'Setting the radius of the starting curvature in case the selected link(s) are represented as Bezier curve(s)',
            ending_tangeant: 'Setting the radius of the ending curvature in case the selected link(s) are represented as Bezier curve(s)',
            arrow_size: 'Change the size of the arrow (from the end of the link to the node)',
            data_off_scale: 'Define a scale for this flow, wich can break the coherence of flow thickness proportionality of value ',
            local_scale: 'Define a local scaling factor that will be multiplied by the multiplier specified for this flow.'
          }
        },
        labels: {
          value: 'Value',
          intervals: 'Intervals',
          percent: '%',
          ratio: 'Ratio',
          label: 'Label',
          vdb: 'Label value',
          len: 'Black label',
          lb: 'White label',
          lec: 'Colored label',
          pos: 'Position',
          milieu: 'Middle',
          deb: 'Start',
          fin: 'End',
          dessous: 'Above',
          dessus: 'Below',
          pls: 'Manual positioning of the label',
          l_u_v: 'Unit',
          l_u: 'Unit\'s name',
          name_label_text_source: 'Label content',
          text_source: {
            custom: 'Custom text',
            none: 'None',
            source: 'Source node',
            target: 'Target node',
            source_target: 'Source → target',
          },
          tooltips: {
            name_label_text_source: 'Pick what the link label displays: typed text, nothing, source/target node name, or source → target',
            label: 'Display or not the label (data / text) associated to the selected link(s)',
            len: 'Display the label in black, for the selected stream(s)',
            lb: 'Display the label in white, for the selected stream(s)',
            lec: 'Display the label with the same color(s) as the one(s) associated with the selected stream(s)',
            deb: 'For the selected link(s), allows to position the label towards the starting point of the link',
            milieu_h: 'For the selected link(s), allows to position the label between the starting point and the end point of the link',
            end: 'For the selected stream(s), allows to position the label towards the end point of the stream',
            below: 'For the selected stream(s), allows to position the label below the stream',
            milieu_v: 'For the selected link(s), allows to position the label inside the link',
            top: 'For the selected stream(s), allows to position the label above the stream',
            pls: 'Combination Alt/left click move the label of the selected stream(s)',
            l_u_v: 'Display the unit of the links',
            l_u: 'Choose the name of the unit',
            unit_factor: 'Factor of conversion for link unity'
          }
        },
        layout: 'Disposition',
        layoutUp: 'Move forward',
        layoutTop: 'Move to the top',
        layoutDown: 'Move backward',
        layoutBottom: 'Move to the bottom',
      }
    }
  },
  fr: {
    translation: {
      Flux: {
        pg: 'Paramètres généraux',
        pdl: 'Police des labels',
        pl: 'Paramètres par flux',
        src: 'Origine',
        trgt: 'Destination',
        value: 'Valeur',
        calculated_value: 'Val. Calc.',
        type: 'Format',
        if: 'Inverser le sens',
        dzf: 'Superposition d\'affichage',
        style: 'Style',
        as: 'Réinitialiser',
        IB: 'Info-bulle',
        IS: 'Info sup.',
        ajust_label: 'Position vertical ajusté',
        local_scale: 'Échelle propre au flux',
        FS: 'Flux',
        changePlan: 'Modifier le plan des flux',
        mask_attr: 'Changer des attributs',
        tooltips: {
          src: 'Choix du noeud de départ pour le/les flux sélectionné(s)',
          trgt: 'Choix du noeud d\'arrivée pour le/les flux sélectionné(s)',
          if: 'Permet d\'inverser les noeuds de départ et d\'arrivée pour le/les flux sélectionné(s)',
          up: 'Monter d\'un cran vers le premier plan',
          upup: 'Mettre le/les flux selectionné(s) au premier plan',
          dwn: 'Descendre d\'un cran vers le dernier plan',
          dwndwn: 'Mettre le/les flux sélectionné(s) au dernier plan',
          as: 'Permettre d\'appliquer un style prédéfini dans le menu préférence au(x) flux selectionné(s)',
          IB: 'Info bulle : texte formaté en HTML et affiché avec l\'info-bulle du flux. Cet info-bulle apparait sur espace graphique avec SHIFT + SOURIS sur le flux',
          ajust_label: 'Repositionne les labels de flux au dessus si les labels sont plus grand que l\'épaisseur des flux',
          inv: 'Inverse le sens du flux en inversant sa source et sa cible'
        },
        data: {
          edit_value: 'Éditer la valeur',
          données: 'Données',
          vpp: 'Valeur',
          data_type: 'Type de données',
          value_type: 'Type de données',
          ratio: 'Type de ratio',
          node_ref: 'Relatif à',
          dir: 'Flux pris en compte',
          value: 'Valeur',
          ratio_input: 'Ratio total entrées',
          ratio_output: 'Ratio total sorties',
          ratio_source_parent: 'Ratio flux parent(à gauche)',
          ratio_target_parent: 'Ratio flux parent(à droite)',
          unit_ratio: 'Coeff. conversion unités',
          value_target: 'Valeur dest.',
          tab_basic: 'Basique',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Incertitude',
          affichage: 'Label',
          tooltips: {
            data_type: 'Type de données',
            vpp: 'Valeur associée au flux sélectionné et, si existant(s), pour le/les tag(s) de flux selectionné(s)',
            scientificNotation: 'Activer ou non la notation en format scientifique, pour l\'affichage de la valeur du flux sur le diagramme de Sankey',
            affichage: 'Texte de remplacement de l\'affichage de la valeur du flux sur le diagramme de Sankey',
            value_target: 'Valeur à la destination pour les flux en forme de trapèze (laisser vide pour une épaisseur uniforme)',
            data_min: 'Borne inférieure de la valeur du flux (utilisée pour la réconciliation)',
            data_max: 'Borne supérieure de la valeur du flux (utilisée pour la réconciliation)',
            uncertainty: 'Incertitude relative en % sur la valeur du flux (utilisée pour la réconciliation)',
            tab_basic_disabled: 'Sélectionnez "Valeur" comme type de données dans l\'onglet AFM pour activer ce panneau'
          }
        },
        apparence: {
          anchor: 'Ancres',
          handle: 'Poignées',
          apparence: 'Apparence',
          fond: 'Fond',
          couleur: 'Couleur',
          grad: 'Gradient',
          flow: 'Flux',
          color_source: 'Élement définissant la couleur du flux',
          source: 'Noeud source',
          target: 'Noeud cible',
          shape_is_dashed: 'Hachuré',
          of: 'Orientation',
          type: 'Type',
          courbe: 'Courbe',
          fleche: 'Flèche',
          opacity: 'Opacité',
          arrow_size: 'Taille',
          display_link_lab: 'Afficher la valeur',
          hide_link_lab: 'Masquer la valeur',
          display_link_name: 'Afficher le texte',
          hide_link_name: 'Masquer le texte',
          data_off_scale: 'Échelle',

          bezier_path: 'Chemin Bezier',
          bezier_outline: 'Contour Bezier',
          tooltips: {
            couleur: 'Choisir la couleur pour le/les flux sélectionné(s)',
            color_source: {
              def: 'Choisir la règle qui définit la couleur du flux',
              flow: 'La couleur est définie par les paramètres du flux (couleur par défaut, couleur des étiquettes de flux ou des données)',
              source: 'La couleur est définie par la couleur du nœud source',
              target: 'La couleur est définie par la couleur du nœud cible',
              gradient: 'La couleur est un dégradé de la couleur du nœud source vers la couleur du nœud cible',
              auto: 'La couleur est déterminée automatiquement selon cet ordre de priorité :\n1. Tag couleur commun entre source et cible\n2. Un seul côté a un tag couleur → prendre ce côté\n3. Les deux ont des tags (pas de commun) → préférer le nœud produit\n4. Pas de tags couleur → préférer le nœud produit\n5. Par défaut : couleur source',
              disabled: 'La règle ne permet pas de modifier la couleur du flux'
            },
            grad: 'Applique un effet de gradient de couleur sur le/les flux sélectionné(s). Le gradient est réalisé entre la couleur du noeud de départ et celle du noeud d\'arrivée',
            shape_is_dashed: 'Applique un effet de hachure sur le/les flux sélectionné(s)',
            of_vv: 'Permet d\'orienter le début du flux verticalement et la fin du flux verticalement',
            of_hh: 'Permet d\'orienter le début du flux horizontalement et la fin du flux horizontalement',
            of_hv: 'Permet d\'orienter le début du flux horizontalement et la fin du flux verticalement',
            of_vh: 'Permet d\'orienter le début du flux verticalement et la fin du flux horizontalement',
            courbe: 'Représente le/les flux sélectionné(s) sous forme de courbe(s) de Bezier.',
            fleche: 'Représente le/les flux sélectionné(s) avec une pointe de flèche à la fin.',
            structure: 'Représente le/les flux sélectionné(s) comme si il n\'avait pas de valeur peu importe leur vraie valeur ',
            arrow_size: 'Modifie la taille de la flèche (largeur entre la fin du flux et le noeud',
            data_off_scale: 'Définie une échelle local pour l\'épaisseur du flux, cela peut casser la cohérence du diagramme au niveau de la proportionalité entre la valeur des flux et leur épaisseur ',
            local_scale: 'Définissez un facteur d\'échelle local qui sera multiplié par le multiplicateur spécifié pour ce flux.'
          }
        },
        labels: {
          source: 'Noeud source',
          target: 'Noeud destination',
          percent: '%',
          intervals: 'Intervalles',
          ratio: 'Ratio',
          label: 'Label',
          vdb: 'Valeur',
          len: 'Label en noir',
          lec: 'Label en couleur',
          milieu: 'Milieu',
          deb: 'Début',
          fin: 'Fin',
          dessous: 'Dessous',
          dessus: 'Dessus',
          pls: 'Positionnement manuel du label',
          scientificNotation: 'Notation scientifique',
          significantDigits: 'Chiffres significatifs',
          NbDigit: 'Nombre maximum de décimales',
          unit_name: 'Unité personnalisée',
          value: 'Valeur',
          '%IS': 'Flux en entrées du noeud source',
          '%ID': 'Flux en entrées du noeud destination',
          '%OS': 'Flux en sorties du noeud source',
          '%OD': 'Flux en sorties du noeud destination',
          '%PS': 'Flux parent du noeud source',
          '%PD': 'Flux parent du noeud destination',
          unit_ratio: 'Ratio d\'unité',
          unit_tag: 'Unité naturelle d\'origine',
          other_unit_tag: 'Autres unités naturelles',
          normalized: 'Normalisé (flux réf.)',
          unit_factor: 'Facteur d\'unité',
          labels: 'Nom',
          node_value: 'Valeur',
          name_label_is_visible: 'Label',
          name_label_text_source: 'Contenu du label',
          text_source: {
            custom: 'Texte personnalisé',
            none: 'Aucun',
            source: 'Nœud source',
            target: 'Nœud destination',
            source_target: 'Source → destination',
          },
          lb: 'Blanc',
          pos: 'Position',
          pos_v: 'Position de la valeur',
          tp: 'Taille de police',
          tooltips: {
            name_label_text_source: 'Choisir ce qu\'affiche le label du flux : texte saisi, rien, nom du nœud source/destination, ou source → destination',
            label: 'Permet d\'afficher ou non le label (donnée / texte) associé au(x) flux sélectionné(s)',
            len: 'Afficher le texte du label en noir, pour le(s) flux sélectionné(s)',
            lb: 'Afficher le texte du label en blanc, pour le(s) flux sélectionné(s)',
            lec: 'Afficher le texte du label avec la/les même(s) couleur(s) que celle(s) associée(s) au(x) flux sélectionné(s)',
            deb: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point de départ du flux',
            milieu_h: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label entre le point de départ et le point d\'arrivée du flux',
            fin: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label vers le point d\'arrivée du flux',
            dessous: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label en dessous du flux',
            milieu_v: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label dans le flux',
            dessus: 'Pour le/les flux sélectionné(s), permet de positionner le texte du label au dessus du flux',
            pls: 'La combinaison Alt/click gauche déplace le label du/des flux sélectionné(s)',
            value: 'Valeur',
            '%IS': 'Flux en entrées du noeud source',
            '%ID': 'Flux en entrées du noeud destination',
            '%OS': 'Flux en sorties du noeud source',
            '%OD': 'Flux en sorties du noeud destination',
            '%PS': 'Flux parent du noeud source',
            '%PD': 'Flux parent du noeud destination',
          }
        },
        layout: 'Organiser',
        layoutUp: 'Avancer',
        layoutTop: 'Premier plan',
        layoutDown: 'Reculer',
        layoutBottom: 'Dernier plan',
      }
    }
  },
  es: {
    translation: {
      Flux: {
        pg: 'Parámetros generales',
        pdl: 'Fuente',
        pl: 'Parámetros por flujo',
        src: 'Origen',
        trgt: 'Destino',
        value: 'Valor',
        calculated_value: 'Val. Calc.',
        type: 'Formato',
        if: 'Invertir dirección',
        dzf: 'Orden de superposición',
        style: 'Estilo',
        as: 'Aplicar el estilo a los flujos seleccionados',
        IB: 'Tooltip',
        IS: 'Info. adicional',
        ajust_label: 'Ajustar posición de etiquetas',
        FS: 'Flujo',
        local_scale: 'Escala local del flujo',
        changePlan: 'Cambiar plano de los flujos',
        mask_attr: 'Cambiar atributos de flujos',
        tooltips: {
          src: 'Elección del nodo de origen para el/los flujo(s) seleccionado(s)',
          trgt: 'Elección del nodo de destino para el/los flujo(s) seleccionado(s)',
          if: 'Invertir los nodos de origen y destino para el/los flujo(s) seleccionado(s)',
          up: 'Subir un nivel hacia el primer plano',
          upup: 'Poner el/los flujo(s) seleccionado(s) en primer plano',
          dwn: 'Bajar un nivel hacia el último plano',
          dwndwn: 'Poner el/los flujo(s) seleccionado(s) en último plano',
          as: 'Permite aplicar un estilo predefinido del menú de preferencias a los flujos seleccionados',
          IB: 'Tooltip: texto formateado en HTML que se muestra con el tooltip del flujo. Este tooltip aparece en el espacio gráfico con SHIFT + RATÓN sobre el flujo.',
          ajust_label: 'Reposiciona las etiquetas de los flujos encima si son más altas que el grosor del flujo',
          inv: 'Invierte la dirección del flujo intercambiando origen y destino'
        },
        data: {
          données: 'Datos',
          vpp: 'Valor',
          data_type: 'Tipo de datos',
          value: 'Valor',
          ratio_input: 'Ratio total entradas',
          ratio_output: 'Ratio total salidas',
          ratio_source_parent: 'Ratio flujo padre (izquierda)',
          ratio_target_parent: 'Ratio flujo padre (derecha)',
          unit_ratio: 'Coef. conversión de unidades',
          edit_value: 'Editar valor',
          value_target: 'Valor dest.',
          tab_basic: 'Básico',
          tab_afm: 'AFM',
          data_min: 'Mín',
          data_max: 'Máx',
          uncertainty: 'Incertidumbre',
          affichage: 'Etiqueta',
          tooltips: {
            data_type: 'Tipo de datos',
            vpp: 'Valor asociado al flujo seleccionado y, si existen, para el/los tag(s) seleccionado(s)',
            scientificNotation: 'Activar o no la notación en formato científico para la visualización del valor del flujo en el diagrama Sankey',
            affichage: 'Texto de sustitución para la visualización del valor del flujo en el diagrama Sankey',
            value_target: 'Valor en el destino para flujos en forma de trapecio (dejar vacío para grosor uniforme)',
            data_min: 'Límite inferior del valor del flujo (usado para reconciliación)',
            data_max: 'Límite superior del valor del flujo (usado para reconciliación)',
            uncertainty: 'Incertidumbre relativa en % sobre el valor del flujo (usada para reconciliación)',
            tab_basic_disabled: 'Seleccione "Valor" como tipo de datos en la pestaña AFM para activar este panel'
          }
        },
        apparence: {
          anchor: 'Anclas',
          handle: 'Tiradores',
          apparence: 'Apariencia',
          flow: 'Flujo',
          fond: 'Fondo de forma',
          source: 'Nodo origen',
          target: 'Nodo destino',
          couleur: 'Color',
          color_source: 'Elemento que define el color del flujo',
          grad: 'Gradiente',
          shape_is_dashed: 'Discontinuo',
          of: 'Orientación',
          type: 'Tipo',
          courbe: 'Curva',
          fleche: 'Flecha',
          opacity: 'Opacidad',
          arrow_size: 'Tamaño de la flecha',
          display_link_lab: 'Mostrar valor',
          hide_link_lab: 'Ocultar valor',
          display_link_name: 'Mostrar nombre',
          hide_link_name: 'Ocultar nombre',
          data_off_scale: 'Escala',
          tooltips: {
            color_source: {
              def: 'Elegir la regla que define el color del flujo:',
              flow: 'El color se define por los parámetros del flujo (color por defecto, color de etiquetas de flujo o de datos)',
              source: 'El color se define por el color del nodo origen',
              target: 'El color se define por el color del nodo destino',
              gradient: 'El color es un degradado del color del nodo origen al color del nodo destino',
              auto: 'El color se determina automáticamente según esta prioridad:\n1. Tag de color común entre origen y destino\n2. Solo un lado tiene tag de color → tomar ese lado\n3. Ambos tienen tags (sin común) → preferir el nodo producto\n4. Sin tags de color → preferir el nodo producto\n5. Por defecto: color del origen',
              disabled: 'La regla no permite elegir el color del flujo'
            },
            couleur: 'Elegir el color para el/los flujo(s) seleccionado(s)',
            grad: 'Aplica un efecto de gradiente de color en el/los flujo(s) seleccionado(s). El gradiente se realiza entre el color del nodo de inicio y el del nodo de fin',
            shape_is_dashed: 'Aplica un efecto de trazo discontinuo en el/los flujo(s) seleccionado(s)',
            of_vv: 'Permite orientar el inicio del flujo verticalmente y el final del flujo verticalmente',
            of_hh: 'Permite orientar el inicio del flujo horizontalmente y el final del flujo horizontalmente',
            of_hv: 'Permite orientar el inicio del flujo horizontalmente y el final del flujo verticalmente',
            of_vh: 'Permite orientar el inicio del flujo verticalmente y el final del flujo horizontalmente',
            courbe: 'Representa el/los flujo(s) seleccionado(s) como curva(s) de Bezier',
            fleche: 'Representa el/los flujo(s) seleccionado(s) con una punta de flecha al final',
            structure: 'Representa el/los flujo(s) seleccionado(s) como si no tuvieran valor, sin importar su valor real',
            starting_curve: 'Permite ajustar la posición del punto de inicio de curvatura para el/los flujo(s) seleccionado(s). Este valor es un ratio (%) de la longitud del flujo relativo al punto de inicio.',
            ending_curve: 'Permite ajustar la posición del punto de fin de curvatura para el/los flujo(s) seleccionado(s). Este valor es un ratio (%) de la longitud del flujo relativo al punto de inicio.',
            starting_tangeant: 'Configuración del radio de curvatura inicial en caso de que el/los flujo(s) seleccionado(s) se representen como curva(s) de Bezier',
            ending_tangeant: 'Configuración del radio de curvatura final en caso de que el/los flujo(s) seleccionado(s) se representen como curva(s) de Bezier',
            arrow_size: 'Cambiar el tamaño de la flecha (desde el final del flujo hasta el nodo)',
            data_off_scale: 'Define una escala local para el grosor del flujo, lo que puede romper la coherencia de proporcionalidad entre el valor y el grosor',
            local_scale: 'Define un factor de escala local que se multiplicará por el multiplicador especificado para este flujo.'
          }
        },
        labels: {
          value: 'Valor',
          intervals: 'Intervalos',
          percent: '%',
          ratio: 'Ratio',
          label: 'Etiqueta',
          vdb: 'Valor de etiqueta',
          len: 'Etiqueta negra',
          lb: 'Etiqueta blanca',
          lec: 'Etiqueta coloreada',
          pos: 'Posición',
          milieu: 'Centro',
          deb: 'Inicio',
          fin: 'Fin',
          dessous: 'Encima',
          dessus: 'Debajo',
          pls: 'Posicionamiento manual de la etiqueta',
          l_u_v: 'Unidad',
          l_u: 'Nombre de la unidad',
          tooltips: {
            label: 'Mostrar u ocultar la etiqueta (dato / texto) asociada al/a los flujo(s) seleccionado(s)',
            len: 'Mostrar la etiqueta en negro para el/los flujo(s) seleccionado(s)',
            lb: 'Mostrar la etiqueta en blanco para el/los flujo(s) seleccionado(s)',
            lec: 'Mostrar la etiqueta con el/los mismo(s) color(es) que el/los asociado(s) al/a los flujo(s) seleccionado(s)',
            deb: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta hacia el punto de inicio del flujo',
            milieu_h: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta entre el punto de inicio y el punto final del flujo',
            end: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta hacia el punto final del flujo',
            below: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta debajo del flujo',
            milieu_v: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta dentro del flujo',
            top: 'Para el/los flujo(s) seleccionado(s), posicionar la etiqueta encima del flujo',
            pls: 'La combinación Alt/clic izquierdo mueve la etiqueta del/de los flujo(s) seleccionado(s)',
            l_u_v: 'Mostrar la unidad de los flujos',
            l_u: 'Elegir el nombre de la unidad',
            unit_factor: 'Factor de conversión para la unidad del flujo'
          }
        },
        layout: 'Disposición',
        layoutUp: 'Avanzar',
        layoutTop: 'Primer plano',
        layoutDown: 'Retroceder',
        layoutBottom: 'Último plano',
      }
    }
  },
  de: {
    translation: {
      Flux: {
        pg: 'Allgemeine Einstellungen',
        pdl: 'Schriftart',
        pl: 'Parameter pro Fluss',
        src: 'Ursprung',
        trgt: 'Ziel',
        value: 'Wert',
        calculated_value: 'Ber. Wert',
        type: 'Format',
        if: 'Richtung umkehren',
        dzf: 'Überlagerungsreihenfolge',
        style: 'Stil',
        as: 'Stil auf ausgewählte Flüsse anwenden',
        IB: 'Tooltip',
        IS: 'Zusatzinfo',
        ajust_label: 'Beschriftungspositionen anpassen',
        FS: 'Fluss',
        local_scale: 'Lokale Flussskalierung',
        changePlan: 'Ebene der Flüsse ändern',
        mask_attr: 'Flussattribute ändern',
        tooltips: {
          src: 'Wahl des Ausgangsknotens für den/die ausgewählten Fluss/Flüsse',
          trgt: 'Wahl des Zielknotens für den/die ausgewählten Fluss/Flüsse',
          if: 'Ausgangs- und Zielknoten für den/die ausgewählten Fluss/Flüsse umkehren',
          up: 'Eine Ebene nach vorne bringen',
          upup: 'Ausgewählte(n) Fluss/Flüsse in den Vordergrund bringen',
          dwn: 'Eine Ebene nach hinten bringen',
          dwndwn: 'Ausgewählte(n) Fluss/Flüsse in den Hintergrund bringen',
          as: 'Ermöglicht das Anwenden eines vordefinierten Stils aus dem Einstellungsmenü auf die ausgewählten Flüsse',
          IB: 'Tooltip: HTML-formatierter Text, der mit dem Tooltip des Flusses angezeigt wird. Dieser Tooltip erscheint im Grafikbereich mit SHIFT + MAUS auf dem Fluss.',
          ajust_label: 'Repositioniert die Flussbeschriftungen oberhalb der Flüsse, wenn die Beschriftungen größer als die Flussstärke sind',
          inv: 'Kehrt die Richtung des Flusses um, indem Quelle und Ziel vertauscht werden'
        },
        data: {
          données: 'Daten',
          vpp: 'Wert',
          data_type: 'Datentyp',
          value: 'Wert',
          ratio_input: 'Ratio Gesamteingänge',
          ratio_output: 'Ratio Gesamtausgänge',
          ratio_source_parent: 'Ratio Elternfluss (links)',
          ratio_target_parent: 'Ratio Elternfluss (rechts)',
          unit_ratio: 'Koeff. Einheitenumrechnung',
          edit_value: 'Wert bearbeiten',
          value_target: 'Zielwert',
          tab_basic: 'Basis',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Unsicherheit',
          affichage: 'Beschriftung',
          tooltips: {
            data_type: 'Datentyp',
            vpp: 'Dem ausgewählten Fluss zugeordneter Wert und, falls vorhanden, für den/die ausgewählten Tag(s)',
            scientificNotation: 'Wissenschaftliche Notation für die Anzeige des Flusswerts im Sankey-Diagramm aktivieren oder nicht',
            affichage: 'Ersatztext für die Anzeige des Flusswerts im Sankey-Diagramm',
            value_target: 'Zielwert für trapezförmige Flüsse (leer lassen für gleichmäßige Dicke)',
            data_min: 'Untergrenze des Flusswerts (für Abgleich verwendet)',
            data_max: 'Obergrenze des Flusswerts (für Abgleich verwendet)',
            uncertainty: 'Relative Unsicherheit in % des Flusswerts (für Abgleich verwendet)',
            tab_basic_disabled: 'Wählen Sie "Wert" als Datentyp im AFM-Tab, um dieses Panel zu aktivieren'
          }
        },
        apparence: {
          anchor: 'Anker',
          handle: 'Griffe',
          apparence: 'Darstellung',
          flow: 'Fluss',
          fond: 'Formhintergrund',
          source: 'Quellknoten',
          target: 'Zielknoten',
          couleur: 'Farbe',
          color_source: 'Element, das die Flussfarbe definiert',
          grad: 'Farbverlauf',
          shape_is_dashed: 'Gestrichelt',
          of: 'Orientierung',
          type: 'Typ',
          courbe: 'Kurve',
          fleche: 'Pfeil',
          opacity: 'Deckkraft',
          arrow_size: 'Pfeilgröße',
          display_link_lab: 'Wert anzeigen',
          hide_link_lab: 'Wert ausblenden',
          display_link_name: 'Name anzeigen',
          hide_link_name: 'Name ausblenden',
          data_off_scale: 'Skalierung',
          tooltips: {
            color_source: {
              def: 'Wählen Sie die Regel, die die Flussfarbe definiert:',
              flow: 'Die Farbe wird durch die Flussparameter definiert (Standardfarbe, Fluss-Tag-Farbe oder Daten-Tag-Farbe)',
              source: 'Die Farbe wird durch die Farbe des Quellknotens definiert',
              target: 'Die Farbe wird durch die Farbe des Zielknotens definiert',
              gradient: 'Die Farbe ist ein Farbverlauf von der Quellknotenfarbe zur Zielknotenfarbe',
              auto: 'Die Farbe wird automatisch nach dieser Priorität bestimmt:\n1. Gemeinsamer Farb-Tag zwischen Quelle und Ziel\n2. Nur eine Seite hat einen Farb-Tag → diese Seite nehmen\n3. Beide haben Tags (kein gemeinsamer) → Produktknoten bevorzugen\n4. Keine Farb-Tags → Produktknoten bevorzugen\n5. Standard: Quellfarbe',
              disabled: 'Die Regel erlaubt keine Auswahl der Flussfarbe'
            },
            couleur: 'Farbe für den/die ausgewählten Fluss/Flüsse wählen',
            grad: 'Wendet einen Farbverlaufseffekt auf den/die ausgewählten Fluss/Flüsse an. Der Verlauf erfolgt zwischen der Farbe des Startknotens und der des Endknotens',
            shape_is_dashed: 'Wendet einen Stricheleffekt auf den/die ausgewählten Fluss/Flüsse an',
            of_vv: 'Ermöglicht es, den Anfang des Flusses vertikal und das Ende vertikal auszurichten',
            of_hh: 'Ermöglicht es, den Anfang des Flusses horizontal und das Ende horizontal auszurichten',
            of_hv: 'Ermöglicht es, den Anfang des Flusses horizontal und das Ende vertikal auszurichten',
            of_vh: 'Ermöglicht es, den Anfang des Flusses vertikal und das Ende horizontal auszurichten',
            courbe: 'Stellt den/die ausgewählten Fluss/Flüsse als Bezier-Kurve(n) dar',
            fleche: 'Stellt den/die ausgewählten Fluss/Flüsse mit einer Pfeilspitze am Ende dar',
            structure: 'Stellt den/die ausgewählten Fluss/Flüsse so dar, als hätten sie keinen Wert, unabhängig von ihrem tatsächlichen Wert',
            starting_curve: 'Ermöglicht die Feineinstellung der Position des Krümmungsanfangspunkts für den/die ausgewählten Fluss/Flüsse. Dieser Wert ist ein Verhältnis (%) der Flusslänge relativ zum Startpunkt.',
            ending_curve: 'Ermöglicht die Feineinstellung der Position des Krümmungsendpunkts für den/die ausgewählten Fluss/Flüsse. Dieser Wert ist ein Verhältnis (%) der Flusslänge relativ zum Startpunkt.',
            starting_tangeant: 'Einstellung des Anfangskrümmungsradius, falls der/die ausgewählte(n) Fluss/Flüsse als Bezier-Kurve(n) dargestellt werden',
            ending_tangeant: 'Einstellung des Endkrümmungsradius, falls der/die ausgewählte(n) Fluss/Flüsse als Bezier-Kurve(n) dargestellt werden',
            arrow_size: 'Größe des Pfeils ändern (vom Ende des Flusses zum Knoten)',
            data_off_scale: 'Definiert eine lokale Skalierung für die Flussdicke, was die Proportionalitätskohärenz zwischen Wert und Dicke brechen kann',
            local_scale: 'Definieren Sie einen lokalen Skalierungsfaktor, der mit dem für diesen Fluss angegebenen Multiplikator multipliziert wird.'
          }
        },
        labels: {
          value: 'Wert',
          intervals: 'Intervalle',
          percent: '%',
          ratio: 'Verhältnis',
          label: 'Beschriftung',
          vdb: 'Beschriftungswert',
          len: 'Schwarze Beschriftung',
          lb: 'Weiße Beschriftung',
          lec: 'Farbige Beschriftung',
          pos: 'Position',
          milieu: 'Mitte',
          deb: 'Anfang',
          fin: 'Ende',
          dessous: 'Darüber',
          dessus: 'Darunter',
          pls: 'Manuelle Positionierung der Beschriftung',
          l_u_v: 'Einheit',
          l_u: 'Einheitenname',
          tooltips: {
            label: 'Beschriftung (Daten / Text) des/der ausgewählten Flusses/Flüsse anzeigen oder ausblenden',
            len: 'Beschriftung in Schwarz für den/die ausgewählten Fluss/Flüsse anzeigen',
            lb: 'Beschriftung in Weiß für den/die ausgewählten Fluss/Flüsse anzeigen',
            lec: 'Beschriftung mit der/den gleichen Farbe(n) wie der/die ausgewählte(n) Fluss/Flüsse anzeigen',
            deb: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zum Startpunkt des Flusses positionieren',
            milieu_h: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zwischen Start- und Endpunkt des Flusses positionieren',
            end: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung zum Endpunkt des Flusses positionieren',
            below: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung unterhalb des Flusses positionieren',
            milieu_v: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung innerhalb des Flusses positionieren',
            top: 'Für den/die ausgewählten Fluss/Flüsse die Beschriftung oberhalb des Flusses positionieren',
            pls: 'Die Kombination Alt/Linksklick verschiebt die Beschriftung des/der ausgewählten Flusses/Flüsse',
            l_u_v: 'Einheit der Flüsse anzeigen',
            l_u: 'Name der Einheit wählen',
            unit_factor: 'Umrechnungsfaktor für die Flusseinheit'
          }
        },
        layout: 'Anordnung',
        layoutUp: 'Vorwärts',
        layoutTop: 'Ganz nach vorne',
        layoutDown: 'Rückwärts',
        layoutBottom: 'Ganz nach hinten',
      }
    }
  },
  it: {
    translation: {
      Flux: {
        pg: 'Impostazioni generali',
        pdl: 'Carattere',
        pl: 'Parametri per flusso',
        src: 'Origine',
        trgt: 'Destinazione',
        value: 'Valore',
        calculated_value: 'Val. Calc.',
        type: 'Formato',
        if: 'Inverti direzione',
        dzf: 'Ordine di sovrapposizione',
        style: 'Stile',
        as: 'Applicare lo stile ai flussi selezionati',
        IB: 'Tooltip',
        IS: 'Info aggiuntive',
        ajust_label: 'Regola posizione etichette',
        FS: 'Flusso',
        local_scale: 'Scala locale del flusso',
        changePlan: 'Cambia piano dei flussi',
        mask_attr: 'Modifica attributi dei flussi',
        tooltips: {
          src: 'Scelta del nodo di partenza per il/i flusso/i selezionato/i',
          trgt: 'Scelta del nodo di arrivo per il/i flusso/i selezionato/i',
          if: 'Inverte i nodi di partenza e di arrivo per il/i flusso/i selezionato/i',
          up: 'Porta avanti di un livello',
          upup: 'Porta il/i flusso/i selezionato/i in primo piano',
          dwn: 'Porta indietro di un livello',
          dwndwn: 'Porta il/i flusso/i selezionato/i in ultimo piano',
          as: 'Permette di applicare uno stile predefinito dal menu preferenze ai flussi selezionati',
          IB: 'Tooltip: testo formattato in HTML visualizzato con il tooltip del flusso. Questo tooltip appare nello spazio grafico con SHIFT + MOUSE sul flusso.',
          ajust_label: 'Riposiziona le etichette dei flussi sopra se le etichette sono più grandi dello spessore del flusso',
          inv: 'Inverte la direzione del flusso scambiando origine e destinazione'
        },
        data: {
          données: 'Dati',
          vpp: 'Valore',
          data_type: 'Tipo di dati',
          value: 'Valore',
          ratio_input: 'Rapporto totale ingressi',
          ratio_output: 'Rapporto totale uscite',
          ratio_source_parent: 'Rapporto flusso padre (sinistra)',
          ratio_target_parent: 'Rapporto flusso padre (destra)',
          unit_ratio: 'Coeff. conversione unità',
          edit_value: 'Modifica valore',
          value_target: 'Valore dest.',
          tab_basic: 'Base',
          tab_afm: 'AFM',
          data_min: 'Min',
          data_max: 'Max',
          uncertainty: 'Incertezza',
          affichage: 'Etichetta',
          tooltips: {
            data_type: 'Tipo di dati',
            vpp: 'Valore associato al flusso selezionato e, se esistenti, per il/i tag selezionato/i',
            scientificNotation: 'Attivare o meno la notazione in formato scientifico per la visualizzazione del valore del flusso nel diagramma Sankey',
            affichage: 'Testo sostitutivo per la visualizzazione del valore del flusso nel diagramma Sankey',
            value_target: 'Valore alla destinazione per flussi a forma di trapezio (lasciare vuoto per spessore uniforme)',
            data_min: 'Limite inferiore del valore del flusso (usato per la riconciliazione)',
            data_max: 'Limite superiore del valore del flusso (usato per la riconciliazione)',
            uncertainty: 'Incertezza relativa in % sul valore del flusso (usata per la riconciliazione)',
            tab_basic_disabled: 'Selezionare "Valore" come tipo di dati nella scheda AFM per attivare questo pannello'
          }
        },
        apparence: {
          anchor: 'Ancore',
          handle: 'Maniglie',
          apparence: 'Aspetto',
          flow: 'Flusso',
          fond: 'Sfondo forma',
          source: 'Nodo origine',
          target: 'Nodo destinazione',
          couleur: 'Colore',
          color_source: 'Elemento che definisce il colore del flusso',
          grad: 'Gradiente',
          shape_is_dashed: 'Tratteggiato',
          of: 'Orientamento',
          type: 'Tipo',
          courbe: 'Curva',
          fleche: 'Freccia',
          opacity: 'Opacità',
          arrow_size: 'Dimensione freccia',
          display_link_lab: 'Mostra valore',
          hide_link_lab: 'Nascondi valore',
          display_link_name: 'Mostra nome',
          hide_link_name: 'Nascondi nome',
          data_off_scale: 'Scala',
          tooltips: {
            color_source: {
              def: 'Scegliere la regola che definisce il colore del flusso:',
              flow: 'Il colore è definito dai parametri del flusso (colore predefinito, colore dei tag di flusso o dei dati)',
              source: 'Il colore è definito dal colore del nodo origine',
              target: 'Il colore è definito dal colore del nodo destinazione',
              gradient: 'Il colore è un gradiente dal colore del nodo origine al colore del nodo destinazione',
              auto: 'Il colore è determinato automaticamente secondo questa priorità:\n1. Tag colore comune tra origine e destinazione\n2. Solo un lato ha un tag colore → prendere quel lato\n3. Entrambi hanno tag (nessuno in comune) → preferire il nodo prodotto\n4. Nessun tag colore → preferire il nodo prodotto\n5. Predefinito: colore origine',
              disabled: 'La regola non permette di scegliere il colore del flusso'
            },
            couleur: 'Scegliere il colore per il/i flusso/i selezionato/i',
            grad: 'Applica un effetto di gradiente di colore sul/sui flusso/i selezionato/i. Il gradiente è realizzato tra il colore del nodo di partenza e quello del nodo di arrivo',
            shape_is_dashed: 'Applica un effetto tratteggiato sul/sui flusso/i selezionato/i',
            of_vv: 'Permette di orientare l\'inizio del flusso verticalmente e la fine verticalmente',
            of_hh: 'Permette di orientare l\'inizio del flusso orizzontalmente e la fine orizzontalmente',
            of_hv: 'Permette di orientare l\'inizio del flusso orizzontalmente e la fine verticalmente',
            of_vh: 'Permette di orientare l\'inizio del flusso verticalmente e la fine orizzontalmente',
            courbe: 'Rappresenta il/i flusso/i selezionato/i come curva/e di Bezier',
            fleche: 'Rappresenta il/i flusso/i selezionato/i con una punta di freccia alla fine',
            structure: 'Rappresenta il/i flusso/i selezionato/i come se non avessero valore, indipendentemente dal loro valore reale',
            starting_curve: 'Permette di regolare la posizione del punto di inizio curvatura per il/i flusso/i selezionato/i. Questo valore è un rapporto (%) della lunghezza del flusso relativo al punto di partenza.',
            ending_curve: 'Permette di regolare la posizione del punto di fine curvatura per il/i flusso/i selezionato/i. Questo valore è un rapporto (%) della lunghezza del flusso relativo al punto di partenza.',
            starting_tangeant: 'Impostazione del raggio di curvatura iniziale nel caso in cui il/i flusso/i selezionato/i siano rappresentati come curva/e di Bezier',
            ending_tangeant: 'Impostazione del raggio di curvatura finale nel caso in cui il/i flusso/i selezionato/i siano rappresentati come curva/e di Bezier',
            arrow_size: 'Modifica la dimensione della freccia (dalla fine del flusso al nodo)',
            data_off_scale: 'Definisce una scala locale per lo spessore del flusso, il che può rompere la coerenza della proporzionalità tra valore e spessore',
            local_scale: 'Definire un fattore di scala locale che sarà moltiplicato per il moltiplicatore specificato per questo flusso.'
          }
        },
        labels: {
          value: 'Valore',
          intervals: 'Intervalli',
          percent: '%',
          ratio: 'Rapporto',
          label: 'Etichetta',
          vdb: 'Valore etichetta',
          len: 'Etichetta nera',
          lb: 'Etichetta bianca',
          lec: 'Etichetta colorata',
          pos: 'Posizione',
          milieu: 'Centro',
          deb: 'Inizio',
          fin: 'Fine',
          dessous: 'Sopra',
          dessus: 'Sotto',
          pls: 'Posizionamento manuale dell\'etichetta',
          l_u_v: 'Unità',
          l_u: 'Nome dell\'unità',
          tooltips: {
            label: 'Mostra o nasconde l\'etichetta (dato / testo) associata al/ai flusso/i selezionato/i',
            len: 'Mostra l\'etichetta in nero per il/i flusso/i selezionato/i',
            lb: 'Mostra l\'etichetta in bianco per il/i flusso/i selezionato/i',
            lec: 'Mostra l\'etichetta con lo/gli stesso/i colore/i associato/i al/ai flusso/i selezionato/i',
            deb: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta verso il punto di partenza del flusso',
            milieu_h: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta tra il punto di partenza e il punto di arrivo del flusso',
            end: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta verso il punto di arrivo del flusso',
            below: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta sotto il flusso',
            milieu_v: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta dentro il flusso',
            top: 'Per il/i flusso/i selezionato/i, posiziona l\'etichetta sopra il flusso',
            pls: 'La combinazione Alt/clic sinistro sposta l\'etichetta del/dei flusso/i selezionato/i',
            l_u_v: 'Mostra l\'unità dei flussi',
            l_u: 'Scegliere il nome dell\'unità',
            unit_factor: 'Fattore di conversione per l\'unità del flusso'
          }
        },
        layout: 'Disposizione',
        layoutUp: 'Avanzare',
        layoutTop: 'Primo piano',
        layoutDown: 'Arretrare',
        layoutBottom: 'Ultimo piano',
      }
    }
  }
}