export const rcc_shortcuts = {

  en: {
    translation: {
      Menu: {
        rcc_titre_princ: 'OpenSankey Application Shortcuts',
        rcc_titre_select: 'With the mouse in selection mode',
        rcc_cn_bold: 'Click (nodes)',
        rcc_cn: 'Select uniquely the clicked node',
        rcc_shift_cn_bold: 'CTRL + dblClick (nodes)',
        rcc_shift_cn: 'Select the clicked node and open the "Nodes" tab of the menu',
        rcc_ctrl_cn_bold: 'CTRL + Click (nodes)',
        rcc_ctrl_cn: 'Add clicked node to list of selected nodes',
        rcc_cf_bold: 'Click (link)',
        rcc_cf: 'Selects the clicked link',
        rcc_shift_cf_bold: 'CTRL + dblClick (link)',
        rcc_shift_cf: 'Selects the clicked link and opens the "Link" tab of the menu',
        rcc_ctrl_cf_bold: 'CTRL + Click (link)',
        rcc_ctrl_cf: 'Add clicked link to list of selected links',
        rcc_cs_bold: 'Click (outside of a node/link)',
        rcc_cs: 'Deselects the selected nodes and links',
        rcc_click_and_drag_bold: 'Click & drag  (drawing area)',
        rcc_click_and_drag: 'Create a selection zone that select nodes included inside',
        rcc_cdn_bold: 'Right click (nodes,links,drawing area)',
        rcc_cdn: 'Open a contextual menu to apply quick changement tot the elements or open some modals',
        rcc_ad_bold: 'Alt Drag (label nodes)',
        rcc_ad: 'Moves the label',
        rcc_titre_edi: 'With the mouse in edit mode',
        rcc_e_cn_bold: 'Click (drawing area)',
        rcc_e_cn: 'Adds a node where clicked',
        rcc_e_ds_bold: 'Drag (from drawing area)',
        rcc_e_ds: 'Creates a node at the drag start point and then creates a link from the node created to: either a node already existing if you drop on it, or a node that you create at the place where you drop on the drawing area',
        rcc_e_dn_bold: 'Drag (from a node)',
        rcc_e_dn: 'Create a link from the drag start node: either a node already existing if you drop on it, or a node that you create where you drop on the drawing area',
        rcc_titre_autre: 'Other shortcuts',
        rcc_a_s_bold: 'Delete',
        rcc_a_s: 'Removes selected nodes and links',
        rcc_a_fc_bold: 'Keyboard arrow',
        rcc_a_fc: 'Move the selected nodes according to the mesh',
        rcc_a_dbm_bold: 'Drag (middle mouse button and outside a node/link)',
        rcc_a_dbm: 'Moves the full sankey',
        rcc_a_ech_bold: 'Esc:',
        rcc_a_ech: 'Closes the Menu when it is open and resets the mouse modeto selection',
        rcc_titre_OSP: 'OpenSankey+ module Shortcuts',
        rcc_osp_cs_bold: 'CTRL+X',
        rcc_osp_cs: 'Creates a view which can then be modified. To keep the modifications applied to the view, save it with Ctrl+S.',
        rcc_osp_ctrl_czdt_bold: 'CTRL+Click (Text Box)',
        rcc_osp_ctrl_czdt: 'Selects the clicked area and opens the text box edit menu',
        rcc_F7_bold: 'F7',
        rcc_F7: 'Switche to master data',
        rcc_F8_bold: 'F8',
        rcc_F8: 'Switche to previous view',
        rcc_F9_bold: 'F9',
        rcc_F9: 'Switch to next view',
        rcc_ctrl_scrll_bold: 'CTRL+scroll (sankey draw zone)',
        rcc_ctrl_scrll: 'Zoom/Unzoom in the sankey zone',
        rcc_ctrl_z_bold: 'CTRL+Z',
        rcc_ctrl_z: 'Cancel last modifiaction done to the sankey',
        rcc_ctrl_y_bold: 'CTRL+Y',
        rcc_ctrl_y: 'Redo canceled modification to sankey'
      }
    }
  },
  fr: {
    translation: {
      Menu: {
        rcc_titre_princ: 'Navigation',
        rcc_titre_select: 'Avec la souris en mode sélection',
        rcc_cn_bold: 'Click (noeuds)',
        rcc_cn: 'Sélectionne uniquement le noeud cliqué',
        rcc_shift_cn_bold: 'CTRL + dblClick (noeuds)',
        rcc_shift_cn: 'Sélectionne le noeud cliqué et ouvre l\'onglet "Noeuds" du menu',
        rcc_ctrl_cn_bold: 'CTRL + Click (noeuds)',
        rcc_ctrl_cn: 'Ajoute le noeud cliqué à la liste des noeuds sélectionnés',
        rcc_cf_bold: 'Click (flux)',
        rcc_cf: 'Sélectionne le flux cliqué',
        rcc_shift_cf_bold: 'CTRL + dblClick (flux)',
        rcc_shift_cf: 'Sélectionne le flux cliqué et ouvre l\'onglet "Flux" du menu',
        rcc_ctrl_cf_bold: 'CTRL + Click (flux)',
        rcc_ctrl_cf: 'Ajoute le flux cliqué à la liste des flux sélectionnés',
        rcc_cs_bold: 'Click (en dehors d\'un noeud/flux)',
        rcc_cs: 'Désélectionne les noeuds et flux sélectionnés',
        rcc_click_and_drag_bold: 'Click & drag  (zone de dessin)',
        rcc_click_and_drag: 'Crée une zone de sélection qui permet de sélectionner les noeuds compris dans cette zone une fois que le relâche la souris',
        rcc_cdn_bold: 'Click droit (noeuds, flux, zone de dessin)',
        rcc_cdn: 'Ouvre un menu contextuel permettant de faire des modifications rapides des éléments',
        rcc_ad_bold: 'Alt Drag (label noeuds)',
        rcc_ad: 'Déplace le label',
        rcc_titre_edi: 'Avec la souris en mode édition',
        rcc_e_cn_bold: 'Click (zone de dessin)',
        rcc_e_cn: 'Ajoute un noeud à l\'endroit cliqué',
        rcc_e_ds_bold: 'Drag (à partir de la zone de dessin)',
        rcc_e_ds: 'Crée un noeud au point de départ du drag puis crée un flux à partir du noeud crée vers : soit un noeud déjà existant si l\'on drop dessus, soit un noeud que l\'on crée à l\'endroit où l\'on drop sur la zone de dessin',
        rcc_e_dn_bold: 'Drag (à partir d\'un noeud)',
        rcc_e_dn: 'Créer un flux à partir du noeud de départ du drag vers : soit un noeud déjà existant si l\'on drop dessus, soit un noeud que l\'on crée à l\'endroit où l\'on drop sur la zone de dessin',
        rcc_titre_autre: 'Autres raccourcis',
        rcc_a_s_bold: 'Suppr',
        rcc_a_s: 'Supprime les noeuds et flux sélectionnés',
        rcc_a_fc_bold: 'Flèche du clavier',
        rcc_a_fc: 'Permet de déplacer les noeuds sélectionnés en fonction du grillage',
        rcc_a_dbm_bold: 'Drag (bouton du milieu de la souris et en dehors d\'un noeud/flux):',
        rcc_a_dbm: ' Permet de déplacer le sankey complet',
        rcc_a_ech_bold: 'Echap',
        rcc_a_ech: 'Ferme le Menu quand il est ouvert et remet la fonction de la souris en tant que sélecteur',
        rcc_titre_OSP: 'Raccourcis du module OpenSankey+',
        rcc_osp_cs_bold: 'CTRL+X',
        rcc_osp_cs: 'Crée une vue qui peut être ensuite modifiée, pour conserver les modifications appliquées à la vue il faut l\'enregistrer avec Ctrl+S',
        rcc_osp_ctrl_czdt_bold: 'CTRL+Click (Zone Texte) :',
        rcc_osp_ctrl_czdt: 'Sélectionne la zone clické et ouvre le menu d\'édition de zone de texte',
        rcc_F7_bold: 'F7',
        rcc_F7: 'Retourne aux données maîtres',
        rcc_F8_bold: 'F8',
        rcc_F8: 'Passe à la vue précédente',
        rcc_F9_bold: 'F9',
        rcc_F9: 'Passe à la vue suivante',
        rcc_ctrl_scrll_bold: 'CTRL+scroll (zone de dessin)',
        rcc_ctrl_scrll: 'Permet de zoomer/dezomer sur la zone de dessin',
        rcc_ctrl_z_bold: 'CTRL+Z',
        rcc_ctrl_z: 'Permet d\'annuler la dernière modification apportée au sankey',
        rcc_ctrl_y_bold: 'CTRL+Y',
        rcc_ctrl_y: 'Permet de refaire la modification de sankey précédemment annulée'
      }
    }
  }
}